modin-project/modin

- README.rst
- setup.py
Adding `pandas` to the requirements. Also adding the start of a README.
> Making work with PyPI

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
These templates are largely based on those from Ray.
> Adding contribution templates

- modin/pandas/utils.py
This reverts commit ac621b0d5eb77503583ecbc557eb868d27ba52dc.
> Revert "Performance boost in _blocks_to_col by np.concatenate (#19)"

- setup.py
> Bumping version and updating dependencies

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
Improves the performance or `__repr__` and `__str__` and adds a test to verify correctness
I rewrote the majority of the implementation. It is a bit more complicated now, so I added some documentation to make it (hopefully) easier to follow.
#40
> Improve __repr__ performance

- modin/pandas/io.py
- modin/pandas/utils.py
I was finally able to reproduce the issue in #38, and found that we are not using best practices for Ray. I refactored the code to follow the best practices.
Resolves #38
> Fixing the order to follow best practices

- modin/pandas/__init__.py
> Automatically determining number of partitions based on cores

- modin/__init__.py
- setup.py
Changelog
- Fix repr, equals
- __git_revision__
- Fix iloc (#43) and DataFrameView
- Bump ray version to 0.5.2
> Bump version to v0.1.2

- modin/pandas/io.py
- modin/pandas/test/test_dataframe.py
Update the codebase with the most recent release of the black formatter.
Resolves #89
> Updating formatting from black update

- README.md
Adding a badge to the readme for pandas API coverage
> Adding pandas api coverage badge

- modin/data_management/data_manager.py
- modin/data_management/factories.py
- modin/data_management/partitioning/partition_collections.py
- modin/pandas/concat.py
- modin/pandas/dataframe.py
- modin/pandas/datetimes.py
- modin/pandas/groupby.py
- modin/pandas/indexing.py
- modin/pandas/io.py
- modin/pandas/reshape.py
- modin/pandas/utils.py
We have a decent amount of vertical whitespace that is unnecessary. Removing to clean up the codebase.
Also stops using `PendingDeprecationWarning` for defaulting to Pandas. We should be using `UserWarning` instead.
> Removing unneeded newlines

- modin/pandas/__init__.py
How do you all feel about this? If Modin releases again before Ray, then this could be reverted for the release. However, I think xray is stable enough that this should be ok.
> Use xray by default in Modin.

- modin/pandas/concat.py
- modin/pandas/dataframe.py
- modin/pandas/io.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_groupby.py
- requirements.txt
Modin now compatible with pandas 0.23 API/functionality changes. Mirrors pandas functionality including when FutureWarnings are thrown.
> Adding pandas 0.23 compatibility

- setup.py
> update pandas version in setup.py

- modin/data_management/data_manager.py
Matches pandas 0.23.4 empty series return values
Resolves #120
> Fixed empty series return value

- modin/data_management/data_manager.py
When full reduce functions try to return an empty dataframe, modin errors out. This fixes it.
Resolves #122
> Fixed returning empty series

- modin/data_management/data_manager.py
- modin/pandas/dataframe.py
Fixes numeric functions to have consistent behavior as pandas.
resolves #132
> Fix numeric functions

- modin/data_management/data_manager.py
- modin/data_management/partitioning/partition_collections.py
Also fixes issue with printing Empty DataFrames with just an index or column, as well as assigning dtypes to empty DataFrames
> Fixing Head and Tail Functions

- modin/data_management/data_manager.py
This PR addresses bugs in Describe primarily related to DateTime and TimeDelta columns. Fixes https://github.com/modin-project/modin/issues/143
> Fixes Bugs in Describe

- modin/data_management/data_manager.py
> spelling error

- modin/data_management/data_manager.py
- modin/pandas/dataframe.py
Fixes bugs in `df.clip()` function. Fixes https://github.com/modin-project/modin/issues/144
> Fixed Clip

- modin/data_management/partitioning/partition_collections.py
Alters the way we build a pandas DataFrame from a Modin DataFrame. This builds the columns first.
> Changing the way we convert to pandas

- modin/data_management/partitioning/partition_collections.py
Reverts modin-project/modin#152
> Revert "Changing the way we convert to pandas"

- modin/data_management/data_manager.py
- modin/pandas/dataframe.py
Fix column mismatch when pandas backend automatically drops non-bool columns.
Resolves #124
> Fix `bool_only` argument functions

- modin/data_management/data_manager.py
- modin/data_management/partitioning/partition_collections.py
This change will fix `to_pandas` from returning a series out of order.
Resolves #155
> Fixed to_pandas for series

- modin/pandas/dataframe.py
Fixes `sort_values` to properly update in place if `update_inplace = True` and fixes `na_position` argument so that it is actually used
Resolves #156
> Fixes sort_values

- modin/pandas/dataframe.py
> fix nunique

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
> Default to pandas for multilevel index and edge cases

- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> Adding functionality for defaulting to pandas in groupby

- modin/pandas/dataframe.py
Has `plot` return the plot object to have access to the `plot`'s attributes.
> Fixed plot to work with plot's attributes

- docs/requirements-doc.txt
Fixes memory issue with docs builds
> Adding doc requirements file

- modin/__init__.py
- setup.py
> Bumping version, fixing setup

- modin/pandas/__init__.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/test/test_dataframe.py
We weren't supporting certain general pandas functions (`pd.func()`). This PR adds support for somet of those.
> General pandas functions support

- modin/data_management/data_manager.py
- modin/pandas/dataframe.py
- modin/pandas/indexing.py
> Fixing loc and sub issues

- modin/data_management/data_manager.py
- modin/pandas/dataframe.py
> moved dtype validation for min and max to dataframe.py

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
Do dtype checking for `inter_df_operations` such as `add` and `lt` and other related fixes
Resolves #195
> Fixes inter_df_operations

- README.md
- modin/__init__.py
- modin/pandas/__init__.py
- setup.py
> Bump version to 0.2.1

- modin/data_management/partitioning/partition_collections/base_block_partitions.py
> Removing debug code

- README.md
- modin/__init__.py
- setup.py
> Bumping version

- .jenkins/build-tests/Dockerfile
- .jenkins/performance-tests/Dockerfile
> missing dep in Dockerfiles

- .jenkins/performance-tests/run_perf_test.sh
> Writing Perf Results to AWS

- modin/pandas/dataframe.py
Fixes column attribute errors in `sample`
Resolves #248
> Fixed sample

- modin/data_management/query_compiler/pandas_query_compiler.py
Fixes all and any to be able to work on python backend when `bool_only=True`
> fix all and any to work for python backend

- modin/pandas/dataframe.py
> Fix minor edge case in repr

- modin/pandas/dataframe.py
Making use of the `_create_dataframe_from_compiler` and reducing code footprint.
Also making more consistent naming.
> Refactor dataframe

- README.md
- modin/__init__.py
- modin/pandas/__init__.py
- setup.py
> Bump version 0.2.3

- .travis/install-dependencies.sh
- requirements.txt
- setup.py
> Pin redis until Ray release

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
Adding `squeeze()` functionality for modin. Basic test with several cases also included in `test_dataframe.py`. Currently returns `pandas.Series` where necessary because no Series implementation in modin yet.
> Squeeze functionality

- README.md
- modin/__init__.py
- setup.py
> Bump version

- modin/pandas/io.py
Use Ray to parallelize `read_hdf` similar to what is done in `read_parquet`
#204
> Use ray to parallelize read hdf 204

- modin/data_management/partitioning/partition_collections/base_block_partitions.py
Refactors block partitions file to use __constructor__ instead of type(self) in each method
N/A
> Refactor block partitions 

- modin/data_management/factories.py
- modin/data_management/partitioning/axis_partition/__init__.py
- modin/data_management/partitioning/axis_partition/dask.py
- modin/data_management/partitioning/partition_collections/__init__.py
- modin/data_management/partitioning/partition_collections/dask.py
- modin/data_management/partitioning/remote_partition/__init__.py
- modin/data_management/partitioning/remote_partition/dask.py
- modin/pandas/__init__.py
Adds an empty skeleton for implementing Dask as a runtime for Modin. 
N/A
> Dask skeleton

- modin/data_management/partitioning/axis_partition/pandas_on_ray.py
- modin/pandas/__init__.py
- modin/pandas/io.py
- requirements.txt
- setup.py
Update Ray to 0.6
Resolves #282
> Update ray and make changes to be compatible with API changes

- README.md
- modin/__init__.py
- setup.py
> Bump version 0.2.5

- modin/data_management/query_compiler/pandas_query_compiler.py
Removes `try_scale` so it will properly assign index in a python backend
> Fixed apply for python backend

- modin/engines/base/block_partitions.py
- modin/engines/ray/pandas_on_ray/block_partitions.py
This makes `__repr__` about 4x faster on the first time around. Merge #299 First.
N/A
> Using numpy arrays instead of python lists for metadata

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/engines/base/block_partitions.py
- modin/engines/base/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/error_message.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
Lint
Adding internal checks
In an effort to get more bug reports, I am adding a single check to test how it will look. Feedback welcome!
In the future, I want to setup an email that is separate from the dev mailing list for issues/bugs. For now, we don't have another one.
> Adding internal checks and email address

- modin/error_message.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
* Added a non-verified udf warning to ErrorMessages
* Changed all of the warnings for defaulting to pandas in DataFrame
* Standardized _default_to_pandas
* Renamed _default_to_pandas_func to _default_to_pandas
N/A
> Removing dead code and removing explicit warnings

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Added a case for MultiIndex
* Added a test for this case
Resolves #303
> Fix reset_index with a MultiIndex resulted in a single column

- modin/engines/python/pandas_on_python/axis_partition.py
Fixes the python backend to return values that are matched properly
Fixes #309
> Fixes python backend returning mismatched results 

- modin/data_management/query_compiler/pandas_query_compiler.py
Partially rewrites `mode` to work efficiently with the new backend
Fixes #312
> Fixes mode to work with the new backend that filters out empty dataframes

- modin/pandas/indexing.py
* Minor refactor of code for readability
* Add condition for items that have an index/columns
* Add extra checking for when the passed item is invalid
* Allow setting from items that contain a superset of the index/columns
Resolves #318
> Allow Modin to use the larger than target item for __setitem__

- modin/pandas/dataframe.py
* This allows subclasses of the QueryCompiler object to be operated on inplace
Resolves #322
> Adding additional check to inplace operations

- modin/pandas/__init__.py
- modin/pandas/reshape.py
> Adding modin.pandas.melt for pandas concordance

- modin/data_management/query_compiler/pandas_query_compiler.py
Adds a `try...except` to the remote function for `groupby` + `agg` operations.
Resolves #327
> Fixing issue where non-numeric partitions threw errors on numeric ops

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/__init__.py
- modin/pandas/dataframe.py
- modin/pandas/indexing.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
* Now `df['column1'].fillna(0, inplace=True)` will work correctly
* Wraps all Series objects that are returned from getitem
* Minor fix to an issue in setitem where some Series objects were
incorrectly set based on their index
> Adding SeriesView object that allows inplace operations

- modin/pandas/series.py
* This handles the case for `loc` and others
* Essentially checking this case for all properties, which should resolve other issues as well
Resolves #330
> Adding extra check to SeriesView if method on parent class is callable as well

- README.md
Adds link to discourse on README
N/A
> Adding badge to README for link to discourse

- modin/engines/base/block_partitions.py
> Ensuring ordered retrieval of columns/rows when operating on a subset

- modin/pandas/dataframe.py
> Adding check for lists of columns with a column not in the index

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
Adds `rmod` to `PandasQueryCompiler`
Fixes #343
> Fixes rmod

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
Adds `rfloordiv` to `PandasQueryCompiler`
Fixes #341
> Fix rfloordiv error

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
Rewrote `sort_index` to avoid the `RayGetError` and to properly sort the index/column
Resolves #159
> Fixed sort_index

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
> Setting min_count default to 0 to match pandas

- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
* This will make sure that all things that are callable are evaluated
Resolves #353
> Change the way we test whether something is callable in SeriesView

- .jenkins/build-tests/run_ci.sh
- .jenkins/build-tests/run_test.sh
- .travis.yml
- .travis/install-dependencies.sh
- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/test/test_concat.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
This PR aims to refactor the testing suite to simplify the addition of new tests and to increase the code coverage of our current tests.
> Refactor testing suite

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
>  Filtering default exclude values in describe based on the include passed in

- modin/engines/base/block_partitions.py
- modin/engines/dask/pandas_on_dask_delayed/axis_partition.py
- modin/engines/python/pandas_on_python/axis_partition.py
- modin/engines/ray/pandas_on_ray/axis_partition.py
* Adds a new parameter to apply for axis_partitions
* Allows partitioning to be either recomputed and rebalanced or
maintained between runs
Resolves #360
> Fixing partitioning issue when doing a reindex/concat

- modin/pandas/__init__.py
- modin/pandas/reshape.py
Adds crosstab to modin.pandas
Resolves #366
> Adding crosstab that defaults to pandas to modin.pandas

- modin/pandas/dataframe.py
* Resolves #382
* Prevents errors from DataFrames with 2 rows
Resolves #382
> Checking for type before we check the length to avoid spurious errors.

- modin/pandas/dataframe.py
> Removing data from DataFrame.hist parameter requirements

- modin/pandas/__init__.py
- modin/pandas/plotting.py
* Resolves #388
* For now, we have a class that overrides all function calls and
converts the arguments to pandas.
* The class created is a metaclass with the sole purpose of converting
the arguments to pandas compatible args.
* This approach allows us to avoid copying a bunch of code and
hard-coding the entire module.
> Adding plotting module.

- modin/data_management/query_compiler/pandas_query_compiler.py
* Resolves #145
* Performs a `reindex` on the `dtypes_cache` if there is already
something there.
* Adds a `dtype` property to `PandasQueryCompilerView` objects to be
handled differently than parent.
> Correcting dtypes after iloc issue

- modin/pandas/series.py
This is useful for things like:
```python
s = df.col1
s.<tab>
```
N/A
> Add tab completion to SeriesView to be identical to Series

- modin/pandas/__init__.py
- modin/pandas/general.py
* Resolves #394
* Aliasing isnull to isna, which was already implemented.
> Adding isnull to modin.pandas

- modin/pandas/test/test_io.py
- requirements.txt
- setup.py
> Bump Ray version to 0.6.1

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/data_management/utils.py
- modin/engines/base/axis_partition.py
- modin/engines/base/block_partitions.py
- modin/engines/python/pandas_on_python/axis_partition.py
- modin/engines/ray/pandas_on_ray/axis_partition.py
* Adds a minimum partition size of 4kb
* Adds some improved shuffling methods
* Improves small DataFrame performance by up to 10x
> Making Modin more efficient at small DataFrames

- modin/pandas/test/test_dataframe.py
- modin/pandas/test/utils.py
Tests empty dataframes and larger test dataframes
> Modify test dataframes

- modin/engines/base/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/error_message.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/reshape.py
* No longer print every time to request implementation - only first
* Add the API that is defaulting to pandas to the message every time
* Add correct email addresses for reporting/requesting
* Changing prints to warnings
(Above)
N/A
> Improving our error messages

- README.md
- modin/__init__.py
- setup.py
> Bump version to 0.3.0

- modin/engines/dask/pandas_on_dask_delayed/axis_partition.py
- modin/engines/dask/pandas_on_dask_delayed/remote_partition.py
Fix issue where some users have to install Dask  to run Modin
N/A
> Fix issue where some users have to install Dask  to run Modin

- modin/pandas/dataframe.py
* Defaulting to pandas
* Reported in #65
> Fix issue with MultiIndex in reindex

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
Fix flake8 errors exposed by update of flake8
Resolves #441
> Fix flake8 errors exposed by update of flake8

- README.md
Add binderhub badge and rearrange badges
N/A
> Add binderhub badges and rearrange badges

- README.md
- docs/installation.rst
- docs/out_of_core.rst
- docs/using_modin.rst
A bit of documentation cleanup
N/A
> Cleaning up docs a bit

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #458
* Resolves #460 
* Only gets the unique values of the index
* Add test to validate changes
> Fixing issue with duplicated rows when looping through groupby object

- setup.py
Adds typing to dependencies per this blog post: https://pythondata.com/quick-tip-speed-up-pandas-using-modin/
N/A
> Add typing to dependencies

- README.md
- modin/__init__.py
- setup.py
> Bump version to 0.3.1

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves #464
* No longer rely directly on index values
* Corrects issue introduced in #433
* Add tests
> Correct support for `drop_duplicates`

- modin/pandas/__init__.py
* Resolves #471
* Updates in the commit remove keyword arguments from the `ray.init` call
- [] tests added and passing
> Remove arguments causing errors with Ray 0.7.0

- modin/data_management/query_compiler/base_query_compiler.py
- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/engines/ray/pandas_on_ray/io.py
Creates a `BaseQueryCompiler` abstract class that will be the parent of all the other `QueryCompiler` classes to facilitate the adding of other `QueryCompilers`
> Create Base Query Compiler object for query compilers

- modin/data_management/query_compiler/base_query_compiler.py
- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
Fixes an inheritance issue introduced when adding `BaseQueryCompiler`s
Fixes #477
> Fix inheritance of __constructor__ for PandasQueryCompilerView

- README.md
- modin/__init__.py
- setup.py
> Bump version to 0.4.0rc1

- docker/Dockerfile
Issue: #485 
Image on dockerhub: https://hub.docker.com/r/aglove2189/modin
> add dockerfile and docker image

- README.md
- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_groupby.py
* Minor bugfixes for `quantile`, `idxmax`, and `idxmin`
* Add tests for some non-covered paths
* Improve test cases for warnings and error messages
> Improve test coverage for release 0.4

- modin/data_management/query_compiler/pandas_query_compiler.py
> Remove dead code for 0.4 release

- README.md
- modin/__init__.py
- setup.py
> Bump Version 0.4.0

- .travis.yml
- modin/experimental/engines/pyarrow_on_ray/frame/partition.py
- modin/experimental/engines/pyarrow_on_ray/io.py
- modin/pandas/test/test_io.py
> Integrate pyarrow's CSV reader into modin

- ci/benchmarks/arithmetic_benchmark.py
- ci/benchmarks/df_op_benchmark.py
- ci/benchmarks/groupby_benchmark.py
- ci/benchmarks/io_benchmark.py
- ci/benchmarks/join_merge_benchmark.py
- ci/benchmarks/pandas/arithmetic_benchmark.py
- ci/benchmarks/pandas/df_op_benchmark.py
- ci/benchmarks/pandas/groupby_benchmark.py
- ci/benchmarks/pandas/io_benchmark.py
- ci/benchmarks/pandas/join_merge_benchmark.py
- ci/benchmarks/pandas/run_pandas_benchmark.py
- ci/benchmarks/run_benchmark.py
- ci/travis/strip-type-hints.py
- setup.py
> Formatting with black

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
Updates `describe` to follow how pandas excludes columns from describe
Fixes #520
> Change how describe excludes columns

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
Reverts modin-project/modin#549
> Revert "Fix `groupby` with `by=pandas.Grouper` object"

- modin/engines/base/frame/partition_manager.py
- modin/pandas/indexing.py
- requirements.txt
- setup.py
* Resolves #540
* Remove type hints that relied on the typing
> Remove typing dependency

- modin/backends/pandas/query_compiler.py
The qc._dtype_cache should now be consistent with the columns metadata now.
> Dtype cleanup 

- requirements.txt
- setup.py
> Update Ray version to 0.6.6

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
* Resolves #577
* Drops non-numeric columns before computation
> Fix numeric_only parameter

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Convert to pandas Series if it is a list of Series
* Convert values to pandas if Series in value of dictionary
> Fix regression in constructor for lists/dicts of Series

- modin/__init__.py
- setup.py
> Update master version to 0.6.0.dev.0

- modin/pandas/dataframe.py
> Add fastrack for slices when `step=None`

- modin/pandas/base.py
- modin/pandas/dataframe.py
* Combine codepaths for `DataFrame` and `Series`
> Fix Series.__getitem__ with a slice

- requirements.txt
- setup.py
> Update ray version to 0.7

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
* Resolves #514
* Adds a `_sibling` list that tracks what other objects share a `_query_compiler`
* Update the constructor and `_update_inplace`
* Add tests
> Fix shallow copy

- modin/engines/ray/generic/io.py
- modin/pandas/test/test_io.py
* Resolves #637
* Checks functionality with correct kwargs
> Fix hdf error checking

- modin/engines/ray/generic/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/pandas/test/test_io.py
Adds special case for partitioned parquet files
Fixes #624 and #633
> Read partitioned parquet files

- README.md
- modin/__init__.py
- setup.py
> Bump version to 0.5.1

- modin/__init__.py
- setup.py
> Bump dev version

- README.md
- modin/__init__.py
- setup.py
> Bump to 0.5.2

- docs/index.rst
> Fix Table of Contents in Docs

- docs/index.rst
> Fix Table of contents

- docs/UsingPandasonRay/index.rst
> Update Table of Contents

- docs/UsingPandasonRay/utilities_supported.rst
> Update utilities documentation for pandas on ray

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/axis_partition.py
- modin/engines/base/frame/partition_manager.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
Fixes bug that arises when entire rows/columns are empty in doing full_axis_reductions
Fixes #646
> Fixes full axis reduce functions with empty row and/or column partitions

- modin/backends/pandas/query_compiler.py
- modin/pandas/series.py
* Resolves #677
* Also add logic to handle update_inplace with transposed QueryCompiler
* Resolves #678
> Fix issue with `sort_values` after transpose

- modin/pandas/series.py
> Default to pandas when trying to get slice from Series

- README.md
- modin/__init__.py
- setup.py
> Bump to 0.5.3

- modin/pandas/__init__.py
- requirements.txt
- setup.py
> Update ray version to 0.7.1

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/backends/pyarrow/query_compiler.py
- modin/pandas/iterator.py
Changes `DataManager` references to `QueryCompiler`
> Change datamanager to querycompiler

- examples/cluster/aws_example.yaml
…extraneous environment varialbes
Update autoscaler script to install released version of modin and remove extraneous environment variables
> Update aws example

- modin/backends/pandas/query_compiler.py
Moves the functions around in the `PandasQueryCompiler` to go where they are supposed to go
> Code quality/reorganize query compiler

- modin/engines/ray/generic/io.py
- modin/pandas/test/test_io.py
* Resolves #711
* Adds logic to convert the SQLAlchemy objects that are not pickleable to the string URL
* The workers will establish a connection independently.
> Fix case where SQLAlchemy connections are passed in to read_sql

- modin/backends/pandas/query_compiler.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
Adds support for text manipulation operations
> Add support for text manipulation operations

- modin/data_management/utils.py
- modin/engines/ray/generic/io.py
- modin/experimental/engines/pyarrow_on_ray/frame/partition.py
> Add a way to compute pre-compute metadata on read_csv

- modin/engines/ray/generic/io.py
> Add metadata to object when reading from parquet

- modin/backends/pandas/query_compiler.py
- modin/data_management/utils.py
- modin/engines/base/frame/axis_partition.py
- modin/engines/base/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
Adds support for both `df.dot` and `series.dot`
> Add support for `dot`

- modin/engines/ray/generic/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/experimental/engines/pyarrow_on_ray/io.py
> Improve performance of dtypes computation by collecting at data ingest

- modin/engines/ray/generic/io.py
updates the partition with calculation for small files to avoid having negative numbers.
> Update partition width calculation for read csv with a ray engine

- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
Adds support for indexing with a boolean list using `loc`
Fixes #720
> Fixes indexing with boolean list in loc

- README.md
- modin/__init__.py
- setup.py
> Release 0.5.4

- modin/engines/ray/generic/frame/partition_manager.py
Ray has quirks we need to address to actually speed up bumpy
> Fix reshape so that it succeeds on larger tables as well

- requirements.txt
- setup.py
> Bump Ray version

- modin/pandas/dataframe.py
This fixes issue modin-project#756
> Apply groupby function to every elements (modin-project#756)

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
Allows count() with multiple levels in index and columns. Can specify level with col/index name.
> count with level

- .travis.yml
- modin/pandas/test/performance-tests/test_performance.py
- modin/pandas/test/test_api.py
- modin/pandas/test/utils.py
- modin/sql/connection.py
* No longer should we merge PRs that contain debugging prints
* Cleans up several test files where prints were left
* Add a test `grep`ing for print statements
> Remove debugging prints and add a test for prints

- .travis.yml
- modin/pandas/test/performance-tests/test_performance.py
- modin/pandas/test/test_api.py
- modin/pandas/test/utils.py
- modin/sql/connection.py
Reverts modin-project/modin#766
> Revert "Remove debugging prints and add a test for prints"

- modin/__init__.py
- setup.py
> Bump version to 0.6.0

- README.md
- modin/__init__.py
- setup.py
> Version bump/0.6.0

- modin/__init__.py
- modin/engines/dask/pandas_on_dask_futures/frame/axis_partition.py
- modin/engines/dask/pandas_on_dask_futures/frame/data.py
- modin/engines/dask/pandas_on_dask_futures/frame/partition.py
- modin/engines/dask/pandas_on_dask_futures/frame/partition_manager.py
- modin/engines/ray/generic/frame/partition_manager.py
- modin/engines/ray/generic/io.py
- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
- modin/engines/ray/pandas_on_ray/frame/data.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
- modin/experimental/engines/pyarrow_on_ray/frame/data.py
- modin/experimental/engines/pyarrow_on_ray/frame/partition.py
- modin/pandas/__init__.py
- setup.py
* Change setup.py to have only required pandas
* add modin[ray] and keep modin[dask] targets for pip install
* Prepare for conda forge submission
> Support Windows with the proper requirements

- modin/pandas/groupby.py
Resolves #801 
Updates the DataFrameGroupBy class's `any` function to accept **kwargs
> Fix `any()` in groupby.py to accept arguments

- modin/backends/pandas/query_compiler.py
- modin/data_management/utils.py
- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/engines/python/pandas_on_python/frame/partition.py
- modin/engines/ray/generic/io.py
- modin/error_message.py
* Resolves #791
* Add a validation for the widths passed in against the index
* Correct `index` computation for `_apply_full_axis`
> Improve and correct metadata management internally

- modin/backends/pyarrow/query_compiler.py
> Fix Pyarrow import

- README.md
- modin/__init__.py
- setup.py
> Bump version to 0.6.1

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/__init__.py
- modin/data_management/functions/mapreducefunction.py
- modin/data_management/functions/reductionfunction.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
* Turn QueryCompilers into one line definitions
* Helps keep code clean and will help with new contributors
> Add MapReduce to the functions and register

- modin/backends/pandas/query_compiler.py
* Also relocate `dot` to a more appropriate location
> Add mean to the Reductions list

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/__init__.py
- modin/data_management/functions/foldfunction.py
- modin/data_management/functions/function.py
- modin/data_management/functions/mapfunction.py
- modin/data_management/functions/mapreducefunction.py
- modin/data_management/functions/reductionfunction.py
* Add cumulatives and diff to that implementation
* Include a refactor of functions to factor out common code
> Initial addition of Fold Function in Pandas Query Compiler

- README.md
- modin/__init__.py
- setup.py
> Bump version to 0.6.2

- modin/pandas/__init__.py
- requirements.txt
- setup.py
> Update to latest pandas version 0.25.2

- .github/workflows/ci.yml
- README.md
> Update actions name and create badge on README

- .github/workflows/ci.yml
> Add CODECOV_SECRET to the environment variable to upload Codecov report

- modin/engines/ray/generic/io.py
> Fix psycopg2 connection functionality

- README.md
- modin/__init__.py
- setup.py
> Bump version to 0.6.3

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
Allows merging named Series like DataFrames, see #877
#877
> Allow merging of named Series (#877)

- setup.py
> Enforce only Python3+ on future releases

- .github/workflows/push.yml
> Fix Master Build

- .github/workflows/push.yml
- pytest.ini
> Fix test artifact upload

- .github/workflows/push.yml
> Fix experimental test suite for master build

- modin/engines/base/io/text/csv_reader.py
* Resolves #904
* Removes hard dependency on `py`
> Remove top of file import for `py`

- .github/workflows/ci.yml
- modin/engines/base/io/text/csv_reader.py
- modin/pandas/test/test_io.py
* Resolves #904
* Remove hard requirement of `py`
> Remove top level import of `py`

- .github/workflows/push.yml
> Upload artifacts from Master build to be used by PRs

- .github/workflows/push.yml
> Correct Directory for artifact upload

- .github/workflows/push.yml
> Fix artifact upload credentials for Master build

- modin/__init__.py
- modin/pandas/__init__.py
- requirements.txt
- setup.py
> Update Ray version to latest

- modin/pandas/test/test_io.py
> Fix Windows Remove file test error

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
* Resolves #913
* Adds fastpath for setting from an existing column
* Add logic to set from an existing row as well
* Currently takes ~5ms to set the column down from multiple seconds
* Row takes ~100-200ms to set.
* Add tests to verify new fastpath logic is correct
> Improve performance of setting a column from an existing Series

- run-tests.sh
* Resolves #947
* Simplify new/existing developer experience
> Add test script for simple execution of all unit tests

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
> Fix inplace updates on partitions

- .github/workflows/ci.yml
- .github/workflows/push.yml
> Fix environment variables for CI and Master test suite

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/engines/dask/pandas_on_dask_futures/frame/axis_partition.py
- modin/engines/dask/pandas_on_dask_futures/frame/partition.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_series.py
- run-tests.sh
* Resolves #956
* Add Dask tests to CI and master test suite, progress toward #853
* Update run-tests.sh to run all Dask tests
> Set `pure=False` for Dask `Client.submit` and `hash=False` for `Client.scatter`

- .github/workflows/ci.yml
- .github/workflows/push.yml
* Progress toward #853
* Adds caching to each build
> Cache pip depdendencies between builds to speed up process

- .github/workflows/ci.yml
- .github/workflows/push.yml
- df_test_requires.txt
> Fix master CI workflow order and simplify workflow names

- .github/workflows/push.yml
> Update master build to allow coverage to be run

- .github/workflows/ci.yml
- .github/workflows/push.yml
- df_test_requires.txt
- pytest.ini
> Optimize CI with minimal pip installs

- README.md
* Progress toward #973
* Also update badge for master build
* Make more clear certain parts of the documentation
> Update README to have a more accurate API coverage section

- README.md
> Move API Coverage section in README to a more appropriate place

- README.md
> Update README to add advanced usage

- modin/pandas/base.py
* Resolves #1001
* Correct the logic for handling the `numeric_only` arg
> Fix `count` when `numeric_only=False`

- README.md
> Bump version to 0.7.0

- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
* Resolves #1032
* Special case the boolean mask
* Add test cases
> Fix loc when column mask is boolean and no rows are masked

- run-tests.sh
> Re-enable testmon force selection

- .coveragerc
- .github/workflows/push.yml
> Update master to track coverage again

- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #1054
* Improve testing for edge cases
* Refactor tests to use `df_equals`
* Add fixes for some edge cases that were previously untested
> Update test for groupby and clean up groupby edge cases

- docs/installation.rst
* Remove WSL recommendation
* Add new details about installing different targets
> Update Installation Documentation

- modin/backends/pandas/query_compiler.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #1033
* Adds clause to handle the `as_index` parameter
* Improve the testing for this case
> Fix `as_index=False` for `DataFrame.groupby`

- .github/workflows/push.yml
> Upload coverage correctly from merged PRs

- requirements.txt
- windows_test_requires.txt
> Unpin tables version for CI to support Ubuntu 19+

- df_test_requires.txt
- requirements.txt
- windows_test_requires.txt
* Fixes test suite failures
* Related to dask/distributed#3491
> Pin msgpack < 1.0

- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
Resolves #1085 
Split from #1078
> Add r operators to Series

- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
Resolves #1087
Split from #1078
> bugfix - sometimes df.loc[s] applies to columns instead of rows

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
* Resolves #1059
* No longer check the length of the other aggresively
* Add test cases
> Fix case where apply a Series across the columns threw error

- modin/__init__.py
- modin/engines/dask/pandas_on_dask_futures/frame/axis_partition.py
- modin/engines/dask/pandas_on_dask_futures/frame/partition.py
- modin/pandas/__init__.py
* Resolves #1031
* Preemptively serialize the function with cloudpickle ourselves
* Deserialize within the task
> Fix Dask Serialization issue

- .github/PULL_REQUEST_TEMPLATE.md
- docs/contributing.rst
> Add documentation for signed-off-by policy

- README.md
> Bump version to 0.7.1

- df_test_requires.txt
- modin/__init__.py
- modin/backends/pandas/parsers.py
- modin/data_management/factories.py
- modin/engines/base/io/io.py
- modin/pandas/__init__.py
- modin/pandas/base.py
- modin/pandas/concat.py
- modin/pandas/dataframe.py
- modin/pandas/datetimes.py
- modin/pandas/general.py
- modin/pandas/groupby.py
- modin/pandas/io.py
- modin/pandas/reshape.py
- modin/pandas/series.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
- requirements.txt
- setup.py
- windows_test_requires.txt
> Update pandas version to 1.0 and fix compatibility

- ci/teamcity/comment_on_pr.py
> Add a bot message to display TeamCity test results

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/pandas/__init__.py
> Add fix for GitHub Actions apt install

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resovles #1073
* Add additional test cases for grouping with multiple columns
> Fix error in Groupby when grouping with multiple columns

- df_test_requires.txt
- modin/pandas/__init__.py
- requirements.txt
- setup.py
- windows_test_requires.txt
> Update supported pandas version to 1.0.3

- env_windows.yml
> Add yml for creating a conda windows development environment

- ci/teamcity/comment_on_pr.py
> Update TeamCity log reporter to support multiple builds

- .coveragerc
> Add Dask to coverage tests

- modin/__init__.py
- requirements.txt
- setup.py
> Update Ray version to 0.8.4

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
> Fixed #1388. Assgning Series to an empty DataFrame is done correctly

- env_windows.yml
> Update conda environment for windows

- modin/pandas/utils.py
Signed-off-by: Yaroslav Igoshev <yaroslav.igoshev@intel.com>
> Fix description of `from_pandas` method

- modin/pandas/base.py
- modin/pandas/test/test_series.py
> Call iloc from _getitem_slice

- modin/engines/base/io/column_stores/feather_reader.py
- modin/engines/base/io/column_stores/parquet_reader.py
- modin/engines/base/io/io.py
- modin/pandas/datetimes.py
- modin/pandas/indexing.py
- modin/pandas/utils.py
Signed-off-by: Yaroslav Igoshev <yaroslav.igoshev@intel.com>
> Fix description of some methods

- modin/pandas/series.py
- modin/pandas/test/test_series.py
> #1272 'Series.nbytes' implementation

- modin/pandas/series.py
- modin/pandas/test/test_io.py
> Attempt to fix #1414. Copy name from source Series object.

- modin/engines/base/io/text/csv_reader.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
> Update test_io.py and test_io_exp.py with call to df_equals

- modin/engines/base/frame/data.py
- modin/pandas/__init__.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
> Update formatting to comply with flake8 3.8.1

- ci/teamcity/Dockerfile.teamcity-ci
it is needed to report tests status on github
> Added PyGithub to docker image

- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> #1461 default_to_pandas 'by' type fixed 

- modin/pandas/test/test_dataframe.py
> remove code duplication for test infer df math functions

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
> Move "Default to pandas" logic out of API layer

- setup.cfg
> Ignore `pass` lines in codecov

- modin/pandas/test/test_dataframe.py
> fix several todo in test_dataframe.py

- .github/workflows/ci.yml
- .github/workflows/push.yml
> Use GitHub Actions for CI

- .github/workflows/ci.yml
> added '--diff' option for black

- modin/__init__.py
- requirements.txt
- setup.py
> pin ray to 0.8.5

- ci/teamcity/comment_on_pr.py
> Fixed #1543. Add comment header after text truncation

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
Signed-off-by: Yaroslav Igoshev <yaroslav.igoshev@intel.com>
> Add `view` implementation for `Series`

- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
> Fixed bug #1568. DataFrame.sparse and Series.sparse API changed

- modin/pandas/test/test_dataframe.py
> fix arrow-2122 todo in 'test_dataframe.py'

- modin/pandas/test/test_dataframe.py
> remove code duplication in comparison' tests

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
> Fix for bug #1588

- .github/workflows/push.yml
> Upload Coverage report from GitHub Actions on master branch

- modin/engines/base/io/sql/sql_reader.py
> Change distributed `read_sql` check explictly for string

- modin/backends/pandas/query_compiler.py
* Resolves #1626
Rewrite `mean` into a `MapReduceFunction` for scalability
> Improve performance of DataFrame and Series mean

- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> Fixed #1624, losing category dtype at ravel

- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
Signed-off-by: Yaroslav Igoshev yaroslav.igoshev@intel.com
These changes add a handling of corner cases for `DataFrame.dot` and `Series.dot` methods. The new tests are created for these cases.
> Support corner cases for `dot`

- modin/backends/pandas/query_compiler.py
Signed-off-by: Yaroslav Igoshev yaroslav.igoshev@intel.com
> Fix `nsmallest` to do not recompute columns for `Series`

- modin/pandas/__init__.py
- requirements.txt
- requirements/df_test_requires.txt
- requirements/env_windows.yml
- requirements/windows_test_requires.txt
- setup.py
> Upgrade pandas to 1.0.5

- modin/backends/pandas/query_compiler.py
- modin/pandas/series.py
Signed-off-by: Yaroslav Igoshev yaroslav.igoshev@intel.com
> Support cases for operations when `Series` consist of one element

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
> DataFrame.apply for functions passed as string fix

- modin/pandas/__init__.py
> remove `num_cpus` parameter in `ray.init` call

- modin/__init__.py
- requirements.txt
- setup.py
> pin ray to 0.8.6

- modin/data_management/dispatcher.py
- modin/data_management/factories.py
- modin/engines/base/io/io.py
Add some more missing fields in base classes and type hints, for better IDE support.
> Add some typing and some missing fields in base classes

- README.md
- modin/__init__.py
> Bump version to 0.7.4

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
Signed-off-by: Hamman Samuel <hsamuel@ea.com>
> Fixed #1692

- modin/pandas/__init__.py
> Fix regression introduced in #1578 where Dask Client was created

- requirements.txt
- requirements/windows_test_requires.txt
> Restrict matlpotlib version while bug #1747 is investigated

- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> Fix for Series.attrs and Series.array

- modin/experimental/cloud/base.py
> FEAT-#1781: implement ClusterError.__str__

- modin/pandas/dataframe.py
- modin/pandas/iterator.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
> Change iterators to start using indexing with `loc`

- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
> FIX-#1610: Fix support for `loc` with MultiIndex parameter

- modin/pandas/dataframe.py
> FIX-#1774: Fix unlimited column printing for smaller dataframes

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
> FIX-#1705: Fix visual bug with repr on smaller dataframes

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
> FIX-#1467: Fix support for cummax and cummin across int and float

- modin/pandas/base.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/pandas/utils.py
> FIX-#1459: 'to_pandas' of nested objects added

- modin/experimental/cloud/cluster.py
> DOCS-#1816: Add notes about using MODIN_SOCKS_PROXY variable

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/groupby_function.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/utils.py
> FIX-#1426: Groupby on categories fixed

- modin/experimental/cloud/base.py
> FIX-#1849: Fix AttributeError in ClusterError class

- modin/experimental/cloud/rpyc_proxy.py
- modin/experimental/cloud/tracing/__init__.py
- modin/experimental/cloud/tracing/parse_rpyc_trace.py
- modin/experimental/cloud/tracing/tracing_connection.py
Implement the means to investigate the calls being done during RPyC run.
> Add optional RPyC tracing and a simple trace parser

- examples/cluster/h2o-runner.py
> DOCS-#1855: add runner of h2o benchmark as example

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/groupby.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/utils.py
- modin/pandas/utils.py
> FIX-#1154: properly process UDFs

- README.md
> Bump version to 0.8.0

- modin/experimental/cloud/ray-autoscaler.yml
- modin/experimental/cloud/rpyc_proxy.py
- requirements.txt
- requirements/env_windows.yml
> FEAT-#1861: Use cloudpickle library for experimental.cloud features

- modin/pandas/series.py
- modin/pandas/test/test_series.py
Signed-off-by: Itamar Turner-Trauring <itamar@itamarst.org>
> FIX-#1647: Support repr() on empty Series.

- environment.yml
> FIX-#1887: fix 'dask' and 'distributed' versions

- MANIFEST.in
- setup.py
> FEAT-#1881: add scale-out feature dependencies

- .github/workflows/ci.yml
- .github/workflows/push.yml
> FIX-#1904: CI fix

- .github/workflows/ci.yml
- .github/workflows/push.yml
Reverts modin-project/modin#1905
> Revert "FIX-#1904: CI fix"

- modin/pandas/test/utils.py
> FIX-#1784: remove columns sorting from testing

- modin/pandas/test/test_dataframe.py
- modin/pandas/test/utils.py
These changes save about **8 hours for CI** (when all jobs are sequentially)
> TEST-#1955: speed up TestDataFrameDefault test

- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#1646: Fix representation of `Series` with datetimelike index

- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> TEST-#1985: optimize common test dataset

- .github/workflows/ci.yml
- .github/workflows/push.yml
- environment.yml
- modin/__init__.py
- modin/engines/ray/utils.py
- modin/experimental/cloud/ray-autoscaler.yml
- requirements.txt
- setup.py
> FEAT-#1958: pin ray to 0.8.7

- requirements.txt
- requirements/df_test_requires.txt
- requirements/env_windows.yml
- requirements/windows_test_requires.txt
> FIX-#1998: Unpin msgpack to satisfy Ray requirements

- modin/engines/base/frame/partition_manager.py
- modin/engines/dask/pandas_on_dask/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_groupby.py
> FEAT-#1944: Added ability to broadcast multi-partitioned frames

- .github/workflows/ci.yml
> TEST-#2020: decrease parallel tests on Ubuntu

- .github/workflows/push.yml
> TEST-#2030: speed up cache; decrease parallel jobs in push.yml

- modin/pandas/test/dataframe/test_window.py
> TEST-#2028: speed up window tests

- modin/pandas/test/dataframe/test_join_sort.py
> TEST-#2026: speed up test_join_sort.py

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_binary.py
> TEST-#2037: speed up test_binary with refactor dataframe.py

- modin/pandas/test/dataframe/test_iter.py
> TEST-#2044: speed up iter tests

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_udf.py
> TEST-#2042: speed up udf tests

- modin/pandas/test/test_series.py
> TEST-#2033: speed up test_series.py

- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/utils.py
> TEST-#2039: speed up default tests

- .github/workflows/ci.yml
- .github/workflows/push.yml
> TEST-#2050: decrease number of parallel jobs on windows Ci

- ci/teamcity/Dockerfile.teamcity-ci
- environment.yml
> TEST-#1891: use conda instead of pip

- modin/experimental/cloud/rpyc_proxy.py
This adds extra caching for certain read-only attributes Python assumes as "always-present", to workaround the quirks of Python `issubclass()` implementation.
Note: this incorporates #1982 as it was found during testing, will be rebased when that PR is merged.
> Workaround issubclass() quirks

- modin/pandas/dataframe.py
Avoid unconditional index access in DataFrame.rename
> REFACTOR-#2101: avoid unconditional index access in DataFrame.rename

- modin/experimental/cloud/connection.py
- modin/experimental/cloud/local_cluster.py
Also increase timeout for spawining a server
> Save rpyc server output if rpyc logging is on

- .github/workflows/ci.yml
- .github/workflows/push.yml
- requirements/env_omnisci.yml
> TEST-#2123: testing of OmniSci added at CI

- modin/data_management/functions/groupby_function.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_groupby.py
I also implemented the functionality
> FIX-#1900: Fix bug in groupby when index name is passed by string

- ci/benchmarks/test_benchmarks.py
- environment.yml
- requirements.txt
- requirements/df_test_requires.txt
- requirements/env_windows.yml
- requirements/windows_test_requires.txt
Benchmarks added for the following functions:
- DataFrame.sum()
- DataFrame.agg(sum)
- DataFrame.agg("sum")
- GroupBy.sum()
- GroupBy.agg(sum)
> FEAT-#2087 Added benchmarks test suite

- modin/experimental/cloud/rpyc_proxy.py
> FEAT-#1992: enable ETL part of LoanPD in cloud

- examples/cluster/h2o-runner.py
- examples/cluster/mortgage-runner.py
- examples/cluster/taxi-runner.py
> FIX-#2148: add note about braceexpand for cloud examples

- modin/experimental/cloud/omnisci.py
> FIX-#2151: add add_conda_packages option for remote omnisci

- ci/benchmarks/test_benchmarks.py
> FEAT-#2136: Added benchmarks for mask generation and indexing

- modin/experimental/sklearn/__init__.py
- modin/experimental/sklearn/model_selection/__init__.py
- modin/experimental/sklearn/model_selection/train_test_split.py
> FEAT-#1847: High performance, no shuffle train_test_split

- setup.cfg
> FIX-#2162: exclude test folders from coverage report

- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Improve index name mangling to support duplicated values.
> FIX-#2156: improve index name mangling

- ci/benchmarks/test_benchmarks.py
> FEAT-#2166: Added benchmarks for DataFrame.merge

- docs/requirements-doc.txt
> DOC-#2176: Add plantuml and issues to doc dependencies

- README.md
> DOCS-#2179: Bump version to 0.8.1

- environment.yml
- modin/__init__.py
- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/engines/ray/task_wrapper.py
- modin/engines/ray/utils.py
- requirements.txt
- requirements/env_omnisci.yml
- setup.py
For merge when 1.0 is released
> FIX-#2113: Ray 1.0 compatibility

- README.md
> DOCS-#2185: Bump version to 0.8.1.1

- .github/workflows/ci.yml
- .github/workflows/push.yml
> FIX-#2190: update prepare-cache job with ray>=1.0.0 in CI

- modin/experimental/cloud/ray-autoscaler.yml
> FIX-#2219: use intel/label/modin channel for cloud features

- modin/backends/pandas/query_compiler.py
> FIX-#2093: Add ability displaying of method's name for inplace operations by progress bar

- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/test/test_cloud.py
> FIX-#2225: update parameters of ray APIs for cloud features

- modin/error_message.py
- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FIX-#2181: constructing OmniSci frame from unsupported types

- environment.yml
- modin/pandas/__init__.py
- modin/pandas/test/dataframe/test_binary.py
- requirements.txt
- requirements/env_omnisci.yml
- setup.py
> FIX-#2230: Updated pandas version to 1.1.3

- .github/workflows/ci.yml
- modin/pandas/indexing.py
- modin/pandas/iterator.py
- modin/pandas/series_utils.py
- modin/pandas/utils.py
> FEAT-#2223: Add pydocstyle check for modin/pandas folder

- ci/teamcity/Dockerfile.teamcity-ci
- modin/pandas/test/dataframe/test_binary.py
> FIX-#2263: fix TeamCity false positive results

- modin/pandas/indexing.py
- modin/pandas/test/test_series.py
> FIX-#1988: Fix indexing over Series via `loc` when slice is passed

- modin/engines/ray/utils.py
> FIX-#2280: use 32 bytes in secrets.token_hex

- modin/config/envvars.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/utils.py
> TEST-#2260: use recommended pandas testing api

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Enable some of DataFrame aggregates.
> FEAT-#2282: support DataFrame.[count|max|min|sum] for OmniSci backend

- setup.py
> FIX-#2234: update dask_deps in setup.py

- modin/engines/base/io/column_stores/parquet_reader.py
> FIX-#2326: move s3fs import in _read function

- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/test/test_cloud.py
> FIX-#2329: TypeError while creating cluster 

- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/indexing.py
> FIX-#2321: Indexing regression

- modin/pandas/base.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_series.py
> FEAT-#2271: Add implementation of `groupby.shift`

- README.md
- docs/UsingSQLonRay/index.rst
> FIX-#2339: Fix links to documentation

- modin/experimental/cloud/rayscale.py
> FIX-#2354: use conda activate instead of conda run

- environment.yml
- modin/engines/base/io/column_stores/feather_reader.py
- modin/pandas/test/test_io.py
- requirements.txt
- requirements/env_omnisci.yml
- setup.py
> FEAT-#1844: upgrade pyarrow to 1.0

- environment.yml
- modin/engines/base/io/file_reader.py
- modin/engines/dask/task_wrapper.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
- modin/pandas/__init__.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/test_series.py
- requirements.txt
- requirements/env_omnisci.yml
- setup.py
> FIX-#2369: Update pandas version to 1.1.4

- README.md
> Bump version to 0.8.2

- environment.yml
- requirements.txt
- requirements/env_omnisci.yml
> FIX-#2388: Fixed requirements for omnisci binaries

- modin/backends/base/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#2390: Fix inserting Series into DataFrame

- modin/config/envvars.py
> FIX-2200: Enable Calcite by default in OmniSci backend

- modin/backends/base/query_compiler.py
> REFACTOR-#2397: remove redundant assignment

- modin/experimental/engines/omnisci_on_ray/frame/data.py
Fix index name setter in OmniSci backend.
> FEAT-#2363: fix index name setter in OmniSci backend

- docs/examples/index.rst
- docs/index.rst
> DOCS-#2413: Add examples page to documentation

- docs/comparisons/dask.rst
- docs/comparisons/index.rst
- docs/comparisons/pandas.rst
- docs/comparisons/spark.rst
- docs/index.rst
> DOCS-#2415: Add comparisons section to documentation with stubs

- docs/examples/index.rst
> DOCS-#2417 add sklearn example

- docs/CONTRIBUTING.rst
Fixes #2419 
- Updated CONTRIBUTING.rst by adding info on how to locally build the documentation
Signed-off-by: Victor Fomin <vfdev.5@gmail.com>
> DOCS-#2419: Updated CONTRIBUTING.rst

- README.md
- docs/modin_vs_dask.md
Signed-off-by: Abdulelah S. Al Mesfer <abdulelah.almesfer@gmail.com>
Updates README.md.
> Updated README.md with modin_vs_dask.md doc, fixes #2433

- .github/workflows/ci.yml
- .github/workflows/push.yml
> FIX-#2450: fix CI recipe

- docs/comparisons/dask.rst
> DOCS-#2437: Add documentation contrasting Modin and Dask

- examples/docker/nyc-taxi.py
> FIX-#2456: update taxi queries with .copy usage

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#2463: Added test with callable functions as aggregate argument

- modin/pandas/test/test_io.py
> TEST-#2296: Cover by tests Error Handling parameters of read_csv

- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
> TEST-#2297: Cover by tests Internal parameters of read_csv

- modin/pandas/general.py
- modin/pandas/test/test_general.py
> FEAT-#2013: merge_asof that is a little more efficient

- asv_bench/asv.conf.json
- environment.yml
- modin/pandas/__init__.py
- requirements.txt
- requirements/env_omnisci.yml
- setup.py
> FIX-#2524: Update pandas version to 1.1.5

- modin/config/envvars.py
- modin/conftest.py
> FIX-#2540: add __iter__ implementation for PatchedEnv class

- modin/pandas/__init__.py
- modin/pandas/test/test_io.py
> FIX-#2498: Fix possible number of partitions for Dask engine

- asv_bench/benchmarks/benchmarks.py
> FIX-#2550: remove decorators usage for asv tested functions

- .github/workflows/ci.yml
- .github/workflows/push.yml
- environment.yml
- requirements/env_omnisci.yml
> Switch to Ray from conda-forge

- environment.yml
- requirements.txt
- requirements/env_omnisci.yml
> FIX-#2595: pin xlrd<=1.2.0

- README.md
> Release commit for version 0.8.3

- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/utils.py
> Fixed MultiIndex.from_frame implementation

- examples/docker/nyc-taxi.dockerfile
> FIX-#2608: Disable proxy for commands running inside container

- examples/docker/census-on-omnisci/census-omnisci.dockerfile
> FIX-#2611: Fixed crash and sklearn version

- examples/docker/plasticc-on-omnisci/build-docker-image.sh
- examples/docker/plasticc-on-omnisci/plasticc-omnisci.dockerfile
- examples/docker/plasticc-on-omnisci/plasticc-omnisci.py
> FEAT-#2604: add docker file with plasticc benchmark on omnisci

- CODE_OF_CONDUCT.md
> DOCS-#2618: Add code of conduct

- environment.yml
- requirements.txt
- requirements/env_omnisci.yml
- setup.py
> FIX-#2672: pin numpy>=1.16.5,<1.20  # pandas gh-39513

- examples/docker/census-on-omnisci/census-omnisci.dockerfile
- examples/docker/plasticc-on-omnisci/plasticc-omnisci.dockerfile
- examples/docker/taxi-on-omnisci/nyc-taxi-omnisci.dockerfile
> FIX-#2681: pin numpy<1.20.0 for docker containers with omnisci

- asv_bench/benchmarks/benchmarks.py
> TEST-#2692: add drop benchmark

- .github/workflows/ci.yml
> TEST-#2707: add lint check for ASV benchmarks

- asv_bench/benchmarks/benchmarks.py
> TEST-#2699: add append benchmark

- asv_bench/benchmarks/benchmarks.py
> TEST-#2694: add head benchmark

- asv_bench/benchmarks/benchmarks.py
> TEST-#2705: add 'value_counts' benchmarks

- asv_bench/benchmarks/benchmarks.py
- modin/pandas/indexing.py
> TEST-#2702: add loc/iloc benchmark

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/expr.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Signed-off-by: Alina <alina.bykovskaya@intel.com>
> FEAT-#1611: Add mod operation

- asv_bench/benchmarks/benchmarks.py
> TEST-#2725: add index, columns, shape benchmarks

- CODEOWNERS
> DOCS-#2584: Add CODEOWNERS file

- environment-dev.yml
- modin/backends/pandas/parsers.py
- modin/engines/base/io/text/excel_dispatcher.py
- modin/pandas/__init__.py
- modin/pandas/test/test_rolling.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- setup.py
> FIX-#2711: Update pandas to 1.2.2

- modin/config/envvars.py
- modin/engines/base/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/frame/modin_aqp.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- requirements-dev.txt
Added progress bar features to Modin
Signed-off-by: Noah Kuo <nkuo@berkeley.edu>
> FEAT-#629: Added experimental Ray progress bar

- environment-dev.yml
- requirements-dev.txt
- requirements/env_omnisci.yml
- setup.py
> FIX-#2777: Pin ray version <1.2.0

- asv_bench/benchmarks/scalability/__init__.py
- asv_bench/benchmarks/scalability/scalability_benchmarks.py
> TEST-#2785: add from_pandas, to_pandas benchmarks

- modin/engines/base/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#1476: Fix loading Parquet pandas metadata

- modin/engines/base/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#2462: change getting column names from parquet files

- modin/data_management/functions/groupby_function.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FEAT-#1594: Re-enable `level` parameter for aggregations

- .github/workflows/push.yml
> TEST-#2820: Remove test dependencies on push

- README.md
> Version 0.9.0

- docs/modin_vs_dask.md
Signed-off-by: Michael Galarnyk mgalarny@gmail.com
> DOCS-#2819: Fix broken architecture link

- modin/distributed/__init__.py
- modin/distributed/dataframe/__init__.py
> FIX-#2824: Add init files into distributed folder

- environment-dev.yml
> FIX-#2826: Add tqdm into environment-dev file

- modin/backends/pandas/query_compiler.py
- modin/conftest.py
- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_iter.py
- modin/pandas/test/utils.py
> Implemented reset_index for multiindex and multilevel indexes

- modin/config/envvars.py
- modin/engines/dask/utils.py
- modin/engines/ray/utils.py
- modin/pandas/test/test_io.py
> FIX-#2798: Fix number of partitions for dataframe on a cluster

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/mapreducefunction.py
- modin/data_management/functions/reductionfunction.py
- modin/engines/base/frame/data.py
- modin/pandas/test/dataframe/test_reduction.py
> FIX-#2859: Fix metadata calculation on reduce operations

- modin/engines/base/frame/data.py
- modin/pandas/test/dataframe/test_binary.py
> FIX-#2857: Correctly handle identical index binary operations

- asv_bench/benchmarks/utils.py
> TEST-#2867: cast all env variables in lowercase for ASV benchmarking

- modin/config/envvars.py
> FIX-#2869: Fix setting NPartitions via put

- README.md
Signed-off-by: Rehan S. Durrani <rdurrani@berkeley.edu>
> Version 0.9.1

- docker/omnisci-engine-dev.dockerfile
> FEAT-#2842: add dockerfile for omnisci engine development

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/calcite_builder.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FEAT-#2879: add 'dropna' support for OmniSci backend
