- README.md
- docs/contributing.rst
> FEAT-#2855: add ASV badge which point to dashboard

- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#2886: Match pandas error message on Series.kurt

- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FIX-#2896: revert 'dropna' logic at groupby

- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FIX-#2879: fix 'dropna' in case of specified index columns

- modin/engines/ray/utils.py
Ray recently moved utility functions to a private subpackage on latest master. This PR addresses these API changes and makes sure to stay compatible with them.
> FIX-#2881: Move to new private Ray API

- docs/supported_apis/dataframe_supported.rst
Signed-off-by: Todd Keech <tkeech1@hotmail.com>
Resolves #2428
> Fix issue 2428 - warnings during documentation build

- modin/config/envvars.py
- modin/config/pubsub.py
- modin/engines/dask/utils.py
- modin/engines/ray/utils.py
> Fix-#2798: Fix setting NPartitions

- modin/engines/ray/generic/io.py
The key idea is to use the pandas functionality to create file object from strings.
This way we can support URLS like `s3://` or `gs://`.
Meanwhile, the writing remains sequential and can be a bottleneck in the case of low internet speed.
> FEAT-#2920: add support of write into cloud storage like S3 and GCS

- asv_bench/benchmarks/benchmarks.py
> TEST-#2932: Added new cases to fillna benchmark

- modin/backends/cudf/__init__.py
- modin/backends/cudf/parser.py
- modin/backends/cudf/query_compiler.py
- modin/config/envvars.py
- modin/data_management/factories/factories.py
- modin/engines/base/io/file_dispatcher.py
- modin/engines/base/io/text/text_file_dispatcher.py
- modin/engines/ray/cudf_on_ray/__init__.py
- modin/engines/ray/cudf_on_ray/frame/__init__.py
- modin/engines/ray/cudf_on_ray/frame/axis_partition.py
- modin/engines/ray/cudf_on_ray/frame/data.py
- modin/engines/ray/cudf_on_ray/frame/gpu_manager.py
- modin/engines/ray/cudf_on_ray/frame/partition.py
- modin/engines/ray/cudf_on_ray/frame/partition_manager.py
- modin/engines/ray/cudf_on_ray/io/__init__.py
- modin/engines/ray/cudf_on_ray/io/io.py
- modin/engines/ray/cudf_on_ray/io/text/__init__.py
- modin/engines/ray/cudf_on_ray/io/text/csv_dispatcher.py
- modin/engines/ray/cudf_on_ray/series/__init__.py
- modin/engines/ray/utils.py
- modin/pandas/__init__.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/test/backends/cudf/test_gpu_managers.py
- modin/test/backends/cudf/test_internals.py
- setup.cfg
This is the first PR from the MODIN-GPU project to the parent MODIN. This PR adds the following functionality that has been developed so far by the gatech-sysml MODIN-GPU team:
- cudfQueryCompiler, cudfOnRayFrame, cudfOnRayPartition, cudfOnRayPartitionManager.
- Basic IO, read_csv
- from_pandas functionalities, basic dataframe construction.
- Indexing (still a todo).
> FEAT#2917: CudfOnRay Indexing

- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_reduction.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
- setup.cfg
> TEST-#2846: Test xfails

- .github/workflows/ci.yml
> FIX-#3054: Update node.js 10->12

- environment-dev.yml
- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/__init__.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#2976: Update pandas to 1.2.4

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/developer/partition_api.rst
- docs/flow/modin/distributed/dataframe/pandas.rst
- docs/index.rst
- modin/distributed/__init__.py
- modin/distributed/dataframe/__init__.py
- modin/distributed/dataframe/pandas/__init__.py
- modin/distributed/dataframe/pandas/partitions.py
> DOCS-#2971: Document `modin.distributed.dataframe.pandas`

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/flow/modin/experimental/pandas.rst
- modin/experimental/engines/pandas_on_ray/sql.py
- modin/experimental/pandas/__init__.py
- modin/experimental/pandas/io_exp.py
- modin/experimental/pandas/numpy_wrap.py
> DOCS-#2963: document modin.experimental.pandas

- .github/workflows/ci.yml
- modin/pandas/accessor.py
- modin/pandas/general.py
- modin/pandas/groupby.py
- modin/pandas/indexing.py
- modin/pandas/iterator.py
- modin/pandas/plotting.py
- modin/pandas/series_utils.py
- modin/pandas/utils.py
> Add docstrings in modin.pandas.[groupby, indexing, accessor, iterator, plotting, series_utils, io, general]

- environment-dev.yml
- modin/conftest.py
- requirements-dev.txt
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#2697: fix modin cloud with numpy==1.20

- .github/workflows/ci.yml
- docs/conf.py
- docs/developer/architecture.rst
- docs/flow/modin/experimental/index.rst
- docs/flow/modin/experimental/xgboost.rst
- docs/modin_xgboost.rst
- modin/experimental/xgboost/__init__.py
- modin/experimental/xgboost/test/__init__.py
- modin/experimental/xgboost/utils.py
- modin/experimental/xgboost/xgboost.py
- modin/experimental/xgboost/xgboost_ray.py
> DOCS-#2947: Update docs for `modin.experimental.xgboost` module

- modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> Fix check for unsupported columns if a column starts with a N/A value

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/flow/modin/experimental/engines/pandas_on_ray.rst
- docs/flow/modin/experimental/engines/pyarrow_on_ray.rst
- docs/flow/modin/experimental/experimental.rst
- modin/engines/base/io/text/csv_glob_dispatcher.py
- modin/experimental/engines/pandas_on_ray/__init__.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/engines/pandas_on_ray/sql.py
- modin/experimental/engines/pyarrow_on_ray/__init__.py
- modin/experimental/engines/pyarrow_on_ray/frame/__init__.py
- modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
- modin/experimental/engines/pyarrow_on_ray/frame/data.py
- modin/experimental/engines/pyarrow_on_ray/frame/partition.py
- modin/experimental/engines/pyarrow_on_ray/frame/partition_manager.py
- modin/experimental/engines/pyarrow_on_ray/io.py
- scripts/doc_checker.py
> DOCS-#2986: Document `modin.experimental.engines.{pandas_on_ray, pyarrow_on_ray}`

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/flow/modin/backends/pandas/index.rst
- docs/flow/modin/backends/pandas/parsers.rst
- docs/flow/modin/backends/pandas/query_compiler.rst
- modin/backends/pandas/__init__.py
- modin/backends/pandas/query_compiler.py
Built docs for this PR: https://modin--3041.org.readthedocs.build/en/3041/
Affected sections:
- https://modin--3041.org.readthedocs.build/en/3041/flow/modin/backends/pandas/index.html
- https://modin--3041.org.readthedocs.build/en/3041/flow/modin/backends/pandas/query_compiler.html
> DOCS-#3040: document `modin.backends.pandas`

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/flow/modin/engines/base/frame/axis_partition.rst
- docs/flow/modin/engines/base/frame/partition.rst
- docs/flow/modin/engines/dask/pandas_on_dask/frame/axis_partition.rst
- docs/flow/modin/engines/dask/pandas_on_dask/frame/data.rst
- docs/flow/modin/engines/dask/pandas_on_dask/frame/index.rst
- docs/flow/modin/engines/dask/pandas_on_dask/frame/partition.rst
- docs/flow/modin/engines/dask/pandas_on_dask/frame/partition_manager.rst
- modin/engines/dask/__init__.py
- modin/engines/dask/pandas_on_dask/__init__.py
- modin/engines/dask/pandas_on_dask/frame/__init__.py
- modin/engines/dask/pandas_on_dask/frame/axis_partition.py
- modin/engines/dask/pandas_on_dask/frame/data.py
- modin/engines/dask/pandas_on_dask/frame/partition.py
- modin/engines/dask/pandas_on_dask/frame/partition_manager.py
- modin/engines/dask/pandas_on_dask/io.py
- modin/engines/dask/task_wrapper.py
- modin/engines/dask/utils.py
> DOCS-#3023: Document `modin.engines.dask`

- docs/UsingSQLonRay/index.rst
- docs/developer/architecture.rst
- docs/experimental_features/index.rst
- docs/flow/modin/backends/pandas/index.rst
> DOCS-#3086: fix links and warnings in the docs

- .github/workflows/ci.yml
- .github/workflows/push.yml
> FIX-#3089: correct codecov script verification

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/flow/modin/pandas/series.rst
- modin/pandas/series.py
> DOCS-#3037: Document `modin.pandas.series`

- modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py
> FEAT-#3093: Fix omnisci dbe import on windows

- docs/flow/modin/engines/ray/cudf_on_ray/frame/data.rst
- docs/flow/modin/engines/ray/cudf_on_ray/frame/partition.rst
- docs/flow/modin/engines/ray/cudf_on_ray/frame/partition_manager.rst
- docs/flow/modin/engines/ray/generic.rst
- docs/flow/modin/engines/ray/pandas_on_ray/frame/data.rst
- docs/flow/modin/engines/ray/pandas_on_ray/frame/partition.rst
- docs/flow/modin/engines/ray/pandas_on_ray/frame/partition_manager.rst
- modin/engines/ray/cudf_on_ray/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/frame/data.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
> FIX-#3114: Fix links to the entities after refactor

- .github/workflows/ci.yml
- docs/_templates/layout.html
- docs/developer/architecture.rst
- docs/flow/modin/engines/python/pandas_on_python/frame/axis_partition.rst
- docs/flow/modin/engines/python/pandas_on_python/frame/data.rst
- docs/flow/modin/engines/python/pandas_on_python/frame/index.rst
- docs/flow/modin/engines/python/pandas_on_python/frame/partition.rst
- docs/flow/modin/engines/python/pandas_on_python/frame/partition_manager.rst
- modin/engines/python/pandas_on_python/__init__.py
- modin/engines/python/pandas_on_python/frame/__init__.py
- modin/engines/python/pandas_on_python/frame/axis_partition.py
- modin/engines/python/pandas_on_python/frame/data.py
- modin/engines/python/pandas_on_python/frame/partition.py
- modin/engines/python/pandas_on_python/frame/partition_manager.py
- modin/engines/python/pandas_on_python/io.py
> DOCS-#3060: Document `modin.engines.python`

- modin/engines/ray/utils.py
> FIX-#3083: Workaround for Ray import thread race condition

- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
- modin/engines/ray/task_wrapper.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
- modin/experimental/xgboost/xgboost_ray.py
Please see the related issue (#3135) for more information about changes.
> FIX-#3135: get rid of using Ray's private API

- .github/workflows/ci.yml
- docs/out_of_core.rst
- environment-dev.yml
- modin/config/envvars.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/engines/ray/utils.py
- requirements-dev.txt
- setup.py
> FIX-#3130: Update Ray version to 1.4

- README.md
> Version 0.10.0

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/flow/modin/pandas/dataframe.rst
- modin/pandas/dataframe.py
> DOCS-#3088: Document `modin.pandas.dataframe`

- modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
- modin/experimental/engines/pyarrow_on_ray/frame/partition.py
- modin/experimental/engines/pyarrow_on_ray/frame/partition_manager.py
> DOCS-#3148: fix typos in `modin.experimental.engines.{pandas_on_ray, pyarrow_on_ray}` docs

- .github/workflows/ci.yml
- docs/conf.py
- docs/developer/architecture.rst
- docs/flow/modin/config.rst
- modin/config/__init__.py
- modin/config/__main__.py
- modin/config/envvars.py
- modin/config/pubsub.py
> DOCS-#3112: Document `modin.config`

- modin/engines/ray/utils.py
> FIX-#3138: Fix consistency in connecting to Ray cluster and local cluster

- environment-dev.yml
- examples/docker/census-on-omnisci/census-omnisci.dockerfile
- examples/docker/plasticc-on-omnisci/plasticc-omnisci.dockerfile
- examples/docker/taxi-on-omnisci/nyc-taxi-omnisci.dockerfile
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3182: Restricted upper numpy version because of potential bug in it

- environment-dev.yml
- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/__init__.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3161: Update pandas to 1.2.5

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/experimental/backends/omnisci/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_series.py
> FIX-#2803: Implement Modin efficient fillna with DataFrame/Series value

- modin/config/__main__.py
> DOCS-#3168: Fix inconsistencies in the `modin.config` docs

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/experimental/engines/omnisci_on_ray/io.py
- modin/pandas/test/test_io.py
- requirements/env_omnisci.yml
> FIX-#2830: read_csv with OmniSci backend compatibility with Pandas

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/calcite_builder.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/frame/df_algebra.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Add support for `concat` operation requiring a join operation in the OmniSci engine.
> FEAT-#3042: support concat via join

- environment-dev.yml
- requirements-dev.txt
- setup.py
> FIX-#3181: Update install command for Ray

- modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py
> FIX-#3186: disable OmniSci' watchdog by default

- .github/workflows/push-to-master.yml
- environment-dev.yml
- requirements-dev.txt
- requirements/requirements-no-engine.yml
> FIX-#3173: fix `push-to-master` test

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
<s>This branch is made on top of the #3150, so it's a blocker for this PR.</s>
#3150 is merged, PR is unblocked now.
> FEAT-#3155: add 'DataFrame.nunique' implementation for OmniSci backend

- environment-dev.yml
- modin/config/envvars.py
- requirements-dev.txt
- requirements/requirements-no-engine.yml
- setup.py
> TEST-#3188: remove Dask pin

- .github/workflows/ci.yml
- docs/conf.py
- docs/developer/architecture.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/axis_partition.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/calcite_algebra.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/calcite_builder.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/data.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/df_algebra.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/expr.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/index.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/partition.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/partition_manager.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/omnisci_engine.rst
- modin/experimental/engines/omnisci_on_ray/frame/__init__.py
- modin/experimental/engines/omnisci_on_ray/frame/axis_partition.py
- modin/experimental/engines/omnisci_on_ray/frame/calcite_algebra.py
- modin/experimental/engines/omnisci_on_ray/frame/calcite_builder.py
- modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/frame/df_algebra.py
- modin/experimental/engines/omnisci_on_ray/frame/expr.py
- modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py
- modin/experimental/engines/omnisci_on_ray/frame/partition.py
- modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
- modin/experimental/engines/omnisci_on_ray/io.py
- scripts/doc_checker.py
> DOCS-#2946: Document `modin.experimental.engines.omnisci_on_ray`

- environment-dev.yml
- modin/backends/base/query_compiler.py
- modin/backends/pandas/parsers.py
- modin/backends/pandas/query_compiler.py
- modin/conftest.py
- modin/engines/base/frame/data.py
- modin/engines/base/io/io.py
- modin/engines/base/io/text/csv_dispatcher.py
- modin/engines/base/io/text/csv_glob_dispatcher.py
- modin/engines/base/io/text/fwf_dispatcher.py
- modin/engines/base/io/text/text_file_dispatcher.py
- modin/experimental/engines/omnisci_on_ray/frame/expr.py
- modin/experimental/engines/omnisci_on_ray/io.py
- modin/experimental/pandas/io_exp.py
- modin/pandas/__init__.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/groupby.py
- modin/pandas/io.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3208: Update pandas to 1.3.0

- README.md
> Release version 0.10.1

- .github/workflows/ci.yml
- .github/workflows/push.yml
> TEST-#3230: set fetch-depth = 2

- .github/workflows/ci.yml
- docs/developer/architecture.rst
- docs/flow/modin/experimental/backends/omnisci/index.rst
- docs/flow/modin/experimental/backends/omnisci/query_compiler.rst
- modin/experimental/backends/omnisci/query_compiler.py
> DOCS-#2945: Document `modin.experimental.backends.omnisci`

- .github/workflows/ci.yml
- setup.py
> FIX-#3247: Pin version of mindsdb_sql<=0.0.12

- .github/workflows/push-to-master.yml
- modin/engines/base/io/io.py
> DOCS-#3236: Fix broken documentation links

- asv_bench/benchmarks/omnisci/benchmarks.py
> TEST-#3246: fix omnisci fillna bench

- .github/workflows/ci.yml
> TEST-#3254: add check asv benchmarks on pure pandas

- asv_bench/benchmarks/io/csv.py
- asv_bench/benchmarks/omnisci/benchmarks.py
- asv_bench/benchmarks/omnisci/io.py
- asv_bench/benchmarks/omnisci/utils.py
- asv_bench/benchmarks/utils.py
> TEST-#2922: add read_csv true/false parameters for asv tests

- docs/index.rst
> DOCS-#3201: Add zsh install hint

- docs/contributing.rst
> DOCS-#3204: Add a section regarding general rules for committers

- .github/workflows/ci.yml
- .github/workflows/push.yml
- environment-dev.yml
- modin/experimental/xgboost/test/test_xgboost.py
- requirements-dev.txt
> TEST-#2646: Add tests for XGBoost

- docs/UsingOmnisci/index.rst
- docs/developer/architecture.rst
- docs/index.rst
> DOCS-#3300: Add section about OmniSci engine with initial info

- .github/workflows/ci.yml
- modin/experimental/xgboost/xgboost_ray.py
> FIX-#3203: Fix hanging of Modin XGBoost

- docs/installation.rst
> DOCS-#3097: Add section regarding installation from conda-forge

- .github/workflows/push.yml
> FIX-#3316: Fix invalid syntax in push.yml

- docs/installation.rst
> DOCS-#3098: Adding Intel distribution of Modin section

- environment-dev.yml
- modin/backends/base/query_compiler.py
- modin/pandas/__init__.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_udf.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3289: Update pandas to 1.3.1

- docs/UsingOmnisci/index.rst
> DOCS-#3318: Fix documentation related to usage of OmniSci engine

- docs/UsingPandasonRay/index.rst
> DOCS-#3319: Update section related to usage of pandas on Ray component

- modin/backends/pandas/parsers.py
- modin/data_management/utils.py
- modin/engines/base/io/text/csv_dispatcher.py
- modin/engines/base/io/text/csv_glob_dispatcher.py
- modin/engines/base/io/text/excel_dispatcher.py
- modin/engines/base/io/text/fwf_dispatcher.py
- modin/engines/base/io/text/json_dispatcher.py
- modin/engines/base/io/text/text_file_dispatcher.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
> FIX-#3276: fix ZeroDivision error during data import operation call

- docs/installation.rst
Update info about OSs where modin is available in documentation
> DOCS-#3322: Specify proper OS versions for which installation packages are available

- docs/experimental_features/index.rst
- docs/experimental_features/modin_xgboost.rst
- docs/index.rst
> FIX-#3306: Move Modin XGBoost docs under `Experimental Features`

- asv_bench/benchmarks/omnisci/benchmarks.py
> TEST-#3340: add groupby multicolumn case and '.agg' case

- README.md
> Version 0.10.2

- docs/flow/modin/experimental/xgboost.rst
- modin/experimental/xgboost/test/test_xgboost.py
- modin/experimental/xgboost/xgboost.py
- modin/experimental/xgboost/xgboost_ray.py
PR adds to Modin xgb.predict the next:
1. async execution support;
2. change approach from Ray actors using to Ray tasks;
3. exclude force data redistribution;
4. improve performance on a single node/cluster of nodes.
> FEAT-#3243: Add async execution support for Modin xgb.predict

- asv_bench/benchmarks/omnisci/benchmarks.py
- asv_bench/benchmarks/utils/data_shapes.py
> TEST-#3364: add value_counts benchmark for OmniSci backend (dataframe case)

- ci/teamcity/Dockerfile.teamcity-ci
> use strict channel priority

- modin/config/envvars.py
- modin/engines/dask/utils.py
> FEAT-#3126: use MODIN_MEMORY to specify memory for dask engine

- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_udf.py
> FEAT-#2006: support local variables in query and eval

- modin/experimental/xgboost/xgboost.py
> FIX-#3439: Remove inheritance of Modin DMatrix from `xgb.DMatrix`

- modin/experimental/engines/omnisci_on_native/frame/partition_manager.py
- modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
> FIX-#3456: Don't assert on empty record batch.

- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3481: Update pandas to 1.3.3

- modin/config/envvars.py
> FIX-#3484: Unify `PyDbEngine` import

- docs/comparisons/dask.rst
> DOCS-#3354: add note about Dask's approximate quantile

- README.md
> Release 0.11

- modin/experimental/engines/omnisci_on_native/frame/data.py
- modin/experimental/engines/omnisci_on_native/frame/expr.py
- modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
Detect heterogenous columns caused by fillna in OmniSci backend.
> FIX-#3478: Detect heterogenous fillna for OmniSci.

- modin/engines/base/io/column_stores/feather_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#2588: read_feather: cast columns from Index to list

- .github/workflows/ci.yml
- setup.py
> FIX-#3251: unpin mindsdb_sql

- modin/experimental/engines/omnisci_on_native/frame/data.py
- modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
Fix empty arrow table creation.
> FIX-#3428: Fix arrow execution for empty frame.

- examples/docker/modin-omnisci/Dockerfile
- examples/docker/modin-omnisci/census-omnisci.py
- examples/docker/modin-omnisci/nyc-taxi-omnisci.py
- examples/docker/modin-omnisci/plasticc-omnisci.py
> FIX-#3424: Switch omnisci engine to native in dockerfile and examples

- modin/engines/base/io/text/csv_dispatcher.py
> REFACTOR-3488: Refactor `read_csv` `skiprows` parameter processing

- asv_bench/benchmarks/omnisci/benchmarks.py
- asv_bench/benchmarks/utils/common.py
> TEST-#3496: add merge benchmark on omnisci where the key is unique

- setup.py
> FIX-#3502: `Unpin` boto3 in setup.py

- modin/engines/base/io/io.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
> Fix usage of modin.HDFStore in modin.read_hdf func

- README.md
> Release 0.11.1

- modin/core/io/text/text_file_dispatcher.py
> FEAT-#3507: Support reading gzipped fwf.

- examples/cluster/h2o-runner.py
- examples/cluster/mortgage-runner.py
- examples/cluster/taxi-runner.py
> FIX-#3420: update cloud images

- docs/release-procedure.md
This is a follow-up of my previous experience of doing a release.
I tried to write up the steps and be clear on all points.
> Expand release process documentation

- README.md
https://github.com/modin-project/modin/pull/3597 - Fix DataFrame.rolling function
https://github.com/modin-project/modin/pull/3608 - Pin pyparsing to make dfsql work
https://github.com/modin-project/modin/pull/2309 - Fix encodings support ("unicode_escape", "utf16", "utf32", "utf-8-sig") for read_csv and read_fwf
> Release version 0.11.3

- requirements/env_omnisci.yml
> FIX-#3538: update OmniSci to 5.8 in test deps

- modin/core/execution/ray/generic/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/axis_partition.py
> FIX-#3659: add 'max_retries=0' for to_csv on Ray engine

- modin/core/io/text/csv_dispatcher.py
> REFACTOR-#3684: remove compression check in '_read_csv_check_support'

- docs/installation.rst
Signed-off-by: Doris Lee <dorisjunglinlee@gmail.com>
- Minor fix on installation release candidates instructions
- Resolves (#3632)
> DOCS-#3632: Add Google Colab setup instructions

- docs/using_modin.rst
- modin/core/io/sql/sql_dispatcher.py
- modin/db_conn.py
Respond to @YarShev comments on PR #3629.
Respond to @YarShev comments on PR #3629.
> FEAT-#3400: Allow creating a sqlalchemy connection (2/2).

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/experimental/xgboost/test/test_dmatrix.py
- modin/experimental/xgboost/xgboost.py
- modin/experimental/xgboost/xgboost_ray.py
> FEAT-#3680: support new parameters for DMatrix

- README.md
> DOCS-#3609: Mention OmniSci engine in root README.md

- docs/UsingOmnisci/index.rst
- modin/pandas/__init__.py
> FEAT-#3536: Change work with native+omnisci

- modin/core/dataframe/algebra/groupby.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#1900: Fix `groupby` for case `by` is None

- modin/core/io/column_stores/feather_dispatcher.py
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/io/pickle/pickle_dispatcher.py
- modin/core/io/sql/sql_dispatcher.py
- modin/core/io/text/csv_glob_dispatcher.py
- modin/core/io/text/excel_dispatcher.py
- modin/core/io/text/json_dispatcher.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/io/io.py
> DOCS-#3734: remove obvious sentences from dispatcher docstrings

- docs/UsingOmnisci/index.rst
> FIX-#3732: Change doc for native+omnisci

- modin/pandas/test/test_groupby.py
> FIX-#3772: Fix failures flake8 in CI

- docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/index.rst
https://modin--3796.org.readthedocs.build/en/3796/flow/modin/core/execution/ray/implementations/pandas_on_ray/index.html
> DOCS-#3794: Update a link to the usage section for pandas on Ray

- CODEOWNERS
Signed-off-by: proxodilka <zeeron209@gmail.com>
> FIX-#3806: align CODEOWNERS file with the current project structure

- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3847: Update pandas to 1.3.5

- docs/flow/modin/core/execution/dispatching.rst
- docs/flow/modin/core/io/index.rst
- docs/flow/modin/core/storage_formats/pandas/parsers.rst
> DOCS-#3856: add dispatchers, parsers and factories public classes

- modin/core/execution/ray/common/task_wrapper.py
- modin/core/execution/ray/common/utils.py
- modin/core/execution/ray/generic/io/io.py
> REFACTOR-#3861: move 'SignalActor' class into task_wrapper.py

- README.md
Signed-off-by: jeffreykennethli <jkli@ponder.io>
Add section "What is Modin" to give users who visit our Github (possibly the most common landing spot for new users) a simple reason to use Modin.
Reword the installation instructions to recommend installing `modin[all]` means users don't have to worry about their choice of engine and hopefully gets users back to their workflows faster, and demonstrating Modin's value sooner.
> FIX-#3690: Reword README introduction and installation instructions.

- modin/core/dataframe/pandas/dataframe/dataframe.py
> FEAT-#3111: Ensure relabeling Modin Frame does not lose partition shape

- modin/core/io/io.py
> DOCS-#3943: Update a link to pandas.read_json

- .github/workflows/ci.yml
Skip test_io.py in cloud mode until we can get it to stop crashing.
> TEST-#4004: Skip test_io.py in cloud mode.

- environment-dev.yml
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3985: Update pyarrow in environment files

- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/pandas/test/test_io.py
> FIX-#4014: Apply deferred metadata before data egress

- .readthedocs.yaml
> DOCS-#4072: Build docs with Python 3.8

- .github/workflows/ci.yml
> TEST-#4032: Only run unit tests when code changes are made

- docs/release_notes/release_notes-0.14.0.rst
- examples/tutorial/tutorial_notebooks/introduction/exercise_3.ipynb
> FIX-#4136: Fix `exercise_3.ipynb` example notebook

- docs/release_notes/release_notes-0.14.0.rst
- modin/pandas/dataframe.py
fixes https://github.com/modin-project/modin/issues/4105
> FIX-#4105: fix names of pandas options to avoid OptionError 

- docs/release_notes/release_notes-0.14.0.rst
- modin/pandas/__init__.py
> FIX-#4142: Fix OmniSci enabling

- docs/getting_started/troubleshooting.rst
- docs/release_notes/release_notes-0.14.0.rst
PR adds info in troubleshooting docs about behavior of Modin on Dask outside of `__main__` block.
> DOCS-#4151: Add info in troubleshooting page related to Dask engine usage

- docs/getting_started/installation.rst
- docs/release_notes/release_notes-0.14.0.rst
> DOCS-#4172: Refresh Intel Distribution of Modin paragraph

- docs/release_notes/release_notes-0.14.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
> REFACTOR-#3997: remove code duplication for `broadcast_apply` method

- .github/workflows/ci-notebooks.yml
- docs/release_notes/release_notes-0.14.0.rst
- examples/tutorial/tutorial_notebooks/introduction/exercise_3.ipynb
- examples/tutorial/tutorial_notebooks/test/test_notebooks.py
This PR adds tests of notebooks from `examples/tutorial/tutorial_notebooks/introduction` directory (cluster notebooks are intended to be used with AWS, that will be difficult to implement using Github Actions). Since not all notebooks can be run "as is" without modifications, needed changes are added first and then resulting notebooks are run using `pytest`.
> TEST-#3938: Test tutorial notebooks in CI

- docs/release_notes/release_notes-0.14.0.rst
- environment-dev.yml
- requirements-dev.txt
- setup.py
> TEST-#4217: Pin `Dask<2022.2.0` as a temporary fix of CI

- .github/workflows/ci.yml
- .github/workflows/push.yml
- docs/release_notes/release_notes-0.14.0.rst
- environment-dev.yml
> TEST-#3628: report coverage data for `test-internals` CI job

- docs/release_notes/release_notes-0.14.0.rst
- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#4234: Upgrade pandas to 1.4.1

- modin/pandas/base.py
- modin/pandas/dataframe.py
> FIX-#4197: Remove redundant warnings

- .github/workflows/ci.yml
- asv_bench/benchmarks/utils/common.py
- docs/release_notes/release_notes-0.14.0.rst
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
> FIX-#4221: add `wait` method for `PandasOnRayDataframeColumnPartition` class

- docs/release_notes/release_notes-0.14.0.rst
- modin/core/dataframe/algebra/fold.py
- modin/core/storage_formats/base/doc_utils.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/test_rolling.py
Fix rolling across column partitions by mapping axis partitions that span the correct dimension.
> FIX-#4185: Fix rolling across column partitions.

- docs/release_notes/release_notes-0.14.0.rst
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- [N/A: I don't think we need to continuously test for this particular bug.] tests added and passing
> FIX-#4183: Make frame _siblings an instance variable.

- docs/release_notes/release_notes-0.14.0.rst
- examples/tutorial/jupyter/execution/pandas_on_dask/local/exercise_3.ipynb
- examples/tutorial/jupyter/execution/pandas_on_ray/local/exercise_3.ipynb
> DOCS-#4280: Change links in jupyter notebooks

- .github/workflows/ci-notebooks.yml
- docs/release_notes/release_notes-0.14.0.rst
- examples/tutorial/jupyter/execution/omnisci_on_native/local/exercise_1.ipynb
- examples/tutorial/jupyter/execution/omnisci_on_native/local/exercise_3.ipynb
> DOCS-#4290: Add missed changes for OmniSci notebooks

- docs/release_notes/release_notes-0.15.0.rst
> DOCS-#4350: Add release notes template for 0.15.0

- docs/release_notes/release_notes-0.15.0.rst
- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#4376: Upgrade pandas to 1.4.2

- docs/release_notes/release_notes-0.15.0.rst
- requirements-dev.txt
> FIX-#3615: Relax some deps in development env

- .github/workflows/ci.yml
- .readthedocs.yaml
- docs/conf.py
- docs/development/architecture.rst
- docs/development/using_omnisci.rst
- docs/flow/modin/core/dataframe/algebra.rst
- docs/flow/modin/core/dataframe/pandas/dataframe.rst
- docs/flow/modin/core/dataframe/pandas/index.rst
- docs/flow/modin/core/execution/dask/implementations/pandas_on_dask/partitioning/axis_partition.rst
- docs/flow/modin/core/execution/python/implementations/pandas_on_python/partitioning/axis_partition.rst
- docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/index.rst
- docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/axis_partition.rst
- docs/flow/modin/core/storage_formats/base/query_compiler.rst
- docs/getting_started/examples.rst
- docs/getting_started/troubleshooting.rst
- docs/getting_started/using_modin/using_modin_cluster.rst
- docs/release_notes/release_notes-0.14.0.rst
- docs/release_notes/release_notes-0.15.0.rst
- docs/release_notes/release_notes-template.rst
- docs/usage_guide/advanced_usage/modin_xgboost.rst
- docs/usage_guide/examples/index.rst
- modin/config/__main__.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/core/io/io.py
- modin/core/io/text/csv_dispatcher.py
- modin/core/io/text/custom_text_dispatcher.py
- modin/core/io/text/fwf_dispatcher.py
- modin/core/storage_formats/base/query_compiler.py
- modin/experimental/pandas/io.py
This PR fixes warnings/errors which occurs during docs building.
docs build: https://modin--4297.org.readthedocs.build/en/4297/
> DOCS-#4296: Fix docs warnings

- docs/release_notes/release_notes-0.15.0.rst
- environment-dev.yml
- modin/experimental/xgboost/test/test_dmatrix.py
- modin/experimental/xgboost/utils.py
- requirements-dev.txt
- requirements/requirements-no-engine.yml
> FIX-#4392: Align Modin XGBoost with xgb>=1.6

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#4394: Fix issue with multiindex metadata desync

- docs/release_notes/release_notes-0.15.0.rst
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
Add missing parameters to groupby pct_change.
> FIX-#4425: Add parameters to groupby pct_change.

- asv_bench/benchmarks/benchmarks.py
- docs/release_notes/release_notes-0.15.0.rst
- modin/config/envvars.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
> FIX-#4414: Add missing f prefix on f-strings found at https://codereview.doctor

- docs/development/contributing.rst
- docs/release_notes/release_notes-0.15.0.rst
- modin/pandas/test/dataframe/test_map_metadata.py
> DOCS-#4469: Say that commit messages can start with PERF.

- commitlint.config.js
> DOCS-#4469: Allow commit messages starting with PERF.

- docs/release_notes/release_notes-0.15.0.rst
- docs/supported_apis/defaulting_to_pandas.rst
- modin/error_message.py
> DOCS-#4487: Recommend GitHub issues over feature_requests@modin.org.

- .github/workflows/ci.yml
- docs/release_notes/release_notes-0.15.0.rst
- requirements-dev.txt
> TEST-#4516: Add numpydoc to developer requirements.

- .github/workflows/ci.yml
- environment-dev.yml
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
> TEST-#4516: (2/2) Add numpydoc to remaining developer requirements.

- .github/workflows/fuzzydata-test.yml
- docs/release_notes/release_notes-0.16.0.rst
- docs/usage_guide/advanced_usage/index.rst
- environment-dev.yml
- modin/experimental/fuzzydata/__init__.py
- modin/experimental/fuzzydata/test/__init__.py
- modin/experimental/fuzzydata/test/test_fuzzydata.py
- requirements-dev.txt
Signed-off-by: Suhail Rehman [suhailrehman@gmail.com](mailto:suhailrehman@gmail.com)
> FEAT-4463: Add experimental fuzzydata integration for testing against a randomized dataframe workflow

- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
TEST-#4613: Skip fuzzydata test for docs-only changes.
> TEST-#4613: Skip fuzzydata test for docs-only changes.

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#2064: fix `iloc`/`loc` assignment when dataframe is empty

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/test/test_io.py
> TEST-#4698: Stop passing invalid storage_options param.

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/series.py
- modin/pandas/series_utils.py
> PERF-#4703: Improve performance in accessing `ser.cat.categories`, `ser.cat.ordered`, and `ser.__array_priority__`

- modin/pandas/test/test_io.py
> TEST-#4762: Skip SQL tests on dask.

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/indexing.py
Signed-off-by: Brock Mendel <jbrockmendel@gmail.com>
Make _LocIndexer and _iLocIndexer immutable.
> REF-#4730: make Indexers immutable

- modin/core/dataframe/base/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/interchange/dataframe_protocol/column.py
- modin/core/dataframe/pandas/interchange/dataframe_protocol/dataframe.py
- modin/core/execution/ray/implementations/cudf_on_ray/dataframe/dataframe.py
- modin/core/io/text/text_file_dispatcher.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/interchange/dataframe_protocol/dataframe.py
- modin/experimental/core/storage_formats/omnisci/query_compiler.py
- modin/pandas/indexing.py
> STY: rename view/mask to take_2d and take_2d_labels_or_positional

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#4886: Use lazy index and columns evaluation in `query` method

- asv_bench/benchmarks/utils/common.py
- docs/flow/modin/experimental/core/execution/native/implementations/omnisci_on_native/index.rst
- docs/flow/modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.rst
- docs/release_notes/release_notes-0.16.0.rst
- examples/cloud/taxi-runner.py
- examples/docker/modin-omnisci/census-omnisci.py
- examples/docker/modin-omnisci/nyc-taxi-omnisci.py
- modin/config/envvars.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/base_worker.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/db_worker.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/pyhdk_worker.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/test/utils.py
- modin/test/storage_formats/omnisci/test_internals.py
- modin/utils.py
- requirements/env_omnisci.yml
> FEAT-#4913: Enabling pyhdk

- docs/release_notes/release_notes-0.16.0.rst
- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FEAT-#4925: Upgrade pandas to 1.4.4

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> REFACTOR: helpers for take_2d_labels_or_positional

- README.md
> Release version 0.15.3

- docs/getting_started/examples.rst
> DOCS-#4957: Update examples page in docs

- modin/test/interchange/dataframe_protocol/omnisci/test_protocol.py
> TEST-#4366: Added regression test

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/dask/common/__init__.py
- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/pandas/__init__.py
- modin/test/storage_formats/pandas/test_internals.py
- modin/test/test_partition_api.py
> REFACTOR-#4978: Align `modin/core/execution/dask/common/__init__.py` with `modin/core/execution/ray/common/__init__.py`

- .github/workflows/ci.yml
- docs/release_notes/release_notes-0.16.0.rst
> TEST-#4562: Use local Ray cluster in CI to resolve flaky `test-compat-win`

- README.md
- docs/release_notes/release_notes-0.16.0.rst
- docs/usage_guide/benchmarking.rst
- docs/usage_guide/index.rst
DOCS-#4521: Document how to benchmark modin.
> DOCS-#4521: Document how to benchmark modin.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/python/implementations/pandas_on_python/partitioning/partition.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/cloud/rayscale.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/base_worker.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- stress_tests/kaggle/kaggle18.py
- versioneer.py
> REFACTOR-#5026: Change exception names to simplify grepping

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/test/test_series.py
> TEST-#5040: Rework test_series using eval_general()

- .github/workflows/ci.yml
- contributing/pre-commit
- docs/release_notes/release_notes-0.16.0.rst
TEST-#5050: Add black to pre-commit hook.
> TEST-#5050: Add black to pre-commit hook.

- examples/cloud/taxi-runner.py
- examples/docker/modin-hdk/nyc-taxi-hdk.py
Signed-off-by: Petr Kurapov <petr.a.kurapov@intel.com>
> FIX-#5060 Fix hdk worker import for nyc-taxi-hdk example

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/dataframe/test_binary.py
FIX-#4691: Fix binary operations between virtual partitions.
> FIX-#4691: Fix binary operations between virtual partitions.

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
> FIX-#5098: Stop using append internally.

- README.md
> Release version 0.16.1

- docs/flow/modin/experimental/core/execution/native/implementations/hdk_on_native/index.rst
> DOCS-#5019: Update HDK on native documentation

- docs/usage_guide/advanced_usage/progress_bar.rst
- examples/tutorial/jupyter/execution/pandas_on_ray/local/exercise_4.ipynb
> DOCS-#3634: Fix examples related to ProgressBar usage

- .github/workflows/ci.yml
- .github/workflows/push.yml
Revert a commit I pushed by mistake.
> TEST-#5135: Revert commit 6bdf4e11140272ce44ab4f2481032e7bc3d82d0e

- docs/release-procedure.md
> DOCS-#5105: Update release procedure

- environment-dev.yml
- modin/pandas/__init__.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/test_groupby.py
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/requirements-no-engine.yml
- setup.py
> FEAT-#5145: Upgrade pandas to 1.5.1

- README.md
> Release verison 0.16.2

- environment-dev.yml
- requirements-dev.txt
- requirements/requirements-no-engine.yml
> FIX-#5174: Pin xgboost < 1.7.

- environment-dev.yml
- requirements-dev.txt
> FIX-#5206: pin mypy<0.990

- modin/_compat/pandas_api/latest/base.py
- modin/_compat/pandas_api/py36/base.py
- modin/_compat/pandas_api/py36/series.py
- modin/pandas/base.py
- modin/pandas/series.py
Signed-off-by: Peter Boshard Olson <peterbolson@gmail.com>
> FIX-#5114: Change mask method name to resolve a namespace conflict with the Numpy mask attribute

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
FIX-#5236: Allow binary operations with custom classes.
> FIX-#5236: Allow binary operations with custom classes.

- README.md
> Release version 0.17.1

- modin/core/execution/ray/common/utils.py
I have verified that the reproducer in
https://github.com/modin-project/modin/issues/5016 no longer throws the error spam.
> FIX-#5016: Suppress spammy ray task errors.

- docs/flow/modin/core/execution/ray/generic.rst
Signed-off-by: Kirill Suvorov <kirill.suvorov@intel.com>
> DOCS-#5314: Update documentation for Ray Generic module

- environment-dev.yml
- modin/distributed/dataframe/pandas/partitions.py
- requirements-dev.txt
> FIX-#5327: Bump mypy cap to fix CI.

- .github/workflows/push-to-master.yml
> TEST-#5341: Bump test-ray-master ray to 3.0.

- .github/workflows/push-to-master.yml
> TEST-#5343: Unpin test-ray-client ray version.

- README.md
- docs/getting_started/installation.rst
> DOCS-#5356: Update conda install instructions

- modin/_version.py
- modin/experimental/core/storage_formats/pyarrow/parsers.py
- modin/pandas/test/test_io.py
> REFACTOR-#5359: Fix code scanning alert - File is not always closed

- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#3823: Fix TypeError when creating Series from SparseArray

- docs/getting_started/quickstart.rst
- docs/getting_started/using_modin/using_modin_cluster.rst
- examples/jupyter/Modin_Taxi.ipynb
- examples/jupyter/Pandas_Taxi.ipynb
- examples/quickstart.ipynb
- examples/tutorial/jupyter/execution/hdk_on_native/local/exercise_2.ipynb
- examples/tutorial/jupyter/execution/hdk_on_native/test/test_notebooks.py
- examples/tutorial/jupyter/execution/pandas_on_dask/test/test_notebooks.py
- examples/tutorial/jupyter/execution/pandas_on_ray/cluster/exercise_6.ipynb
- examples/tutorial/jupyter/execution/pandas_on_ray/test/test_notebooks.py
- examples/tutorial/jupyter/execution/test/utils.py
> TEST-#5259: Use new URL for dataset

- requirements/env_hdk.yml
> FEAT-#5396: Bump pyhdk version to 0.3

- modin/pandas/groupby.py
> REFACTOR-#5294: Fix code scanning alert - Potentially uninitialized local variable

- docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/axis_partition.rst
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/__init__.py
- modin/pandas/test/internals/test_benchmark_mode.py
- modin/test/storage_formats/pandas/test_internals.py
> REFACTOR-#5462: Update execution.ray public api with virtual partitions

- modin/core/dataframe/pandas/dataframe/dataframe.py
dtypes are computed in the from_labels method so other subsequent methods would not need to perform remote calls.
In below code reset_index would call from_labels which would execute asynchronously. So a subsequent call to astype function which needs to access dtypes would need to go through remote calls to execute.
```
df_index_reset=df.reset_index()
df_index_reset.astype('int32')
```
Benchmarking code
```
from modin.pandas import DataFrame
import time
rows=1000
cols=1000
df = DataFrame(np.random.randn(rows, cols))
df.columns =["col"+str(i) for i in range(cols)]
df.index = ["row"+str(i) for i in range(rows)]
start_time = time.time()
df_index_reset=df.reset_index()
df_index_reset.astype('int32')
print("--- %s seconds ---" % (time.time() - …
```
> PERF-#5183: Compute dtypes when performing from_labels operation

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/pandas/dataframe.py
> FIX-#3928: Fix column insertion into empty data frame

- docs/usage_guide/optimization_notes/index.rst
> DOCS-#5498: mention 'DataFrame._repartition' API at docs

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
- .github/workflows/push.yml
> REFACTOR-#3883: Unify tests execution approach in the Github workflow files

- docs/getting_started/installation.rst
> DOCS-#3803: Update "building modin from source" docs

- modin/core/storage_formats/pandas/query_compiler.py
> REFACTOR-#5535: remove duplication for `columnarize` method

- requirements/env_hdk.yml
> FEAT-#5562: Upgrade pyhdk to 0.3.1

- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
- setup.py
> FEAT-#5559: Upgrade pandas to 1.5.3

- environment-dev.yml
- requirements-dev.txt
- requirements/env_unidist.yml
> FIX-#5568: Pin 'fastparquet<2023.1.0'

- README.md
> Release 0.18.1

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#5589: Do not trigger metadata materialization on 'filter'

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
https://github.com/pandas-dev/pandas/pull/50591
Failed CI: https://github.com/modin-project/modin/actions/runs/4028379793/jobs/6930652236
> FIX-#5597: Pin sqlalchemy<1.4.46 as pandas does to fix CI

- docs/getting_started/troubleshooting.rst
> DOCS-#5157: Add a note regarding poor perf of the first op with Modin on Ray

- asv_bench/benchmarks/benchmarks.py
- modin/conftest.py
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/storage_formats/cudf/query_compiler.py
- modin/core/storage_formats/pandas/parsers.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/cloud/rpyc_proxy.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/xgboost/xgboost_ray.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/test/storage_formats/pandas/test_internals.py
> REFACTOR-#5607: Fix missing formatting with 'black'

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
> FIX-#5608: Pin openpyxl<3.1.0

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_join_sort.py
> PERF-#5596: Do not trigger index materialization for '.merge' result

- modin/pandas/dataframe.py
> FIX-#5641: Add fastpath for numpy arrays to dataframe constructor

- asv_bench/benchmarks/hdk/benchmarks.py
- asv_bench/benchmarks/hdk/io.py
- asv_bench/benchmarks/io/csv.py
- asv_bench/benchmarks/io/parquet.py
- asv_bench/benchmarks/scalability/scalability_benchmarks.py
- asv_bench/benchmarks/utils/common.py
> TEST-#5540: add module level setup function for ASV benchmarks

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/indexing.py
> PERF-#5691: Set item via `.loc` without converting a Series to np.array

- modin/core/execution/ray/common/engine_wrapper.py
- modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/experimental/batch/test/test_pipeline.py
- modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/partitioning/partition.py
- modin/experimental/xgboost/xgboost_ray.py
- modin/test/storage_formats/pandas/test_internals.py
- modin/test/test_partition_api.py
> REFACTOR-#5685: add `RayWrapper.put` implementation

- modin/core/execution/unidist/common/engine_wrapper.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
> REFACTOR-#5687: add `UnidistWrapper.put` implementation

- modin/pandas/dataframe.py
> PERF-#5700: Treat numpy arrays more efficiently at `df.__setitem__` 

- modin/error_message.py
- modin/numpy/arr.py
- modin/numpy/math.py
- modin/numpy/test/test_array.py
- modin/numpy/test/test_array_axis_functions.py
- modin/numpy/utils.py
> FIX-#5665: Fix operations that flatten an array, as well as handling of where argument in such operations

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#5698: Read list of parquet files

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#5721: Fix loc[tuple] on multiindex.

- requirements/env_hdk.yml
> FEAT-#5751: Bump pyhdk version to 0.4

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/pandas/test/test_concat.py
> FIX-#5628: BUG: HDK: Unable to concatenate tables with different number of non-numeric columns

- modin/core/storage_formats/pandas/query_compiler.py
- modin/numpy/__init__.py
- modin/numpy/arr.py
- modin/numpy/array_creation.py
- modin/numpy/array_shaping.py
- modin/numpy/indexing.py
- modin/numpy/math.py
- modin/numpy/test/test_array_logic.py
- modin/numpy/trigonometry.py
> FEAT-#5753: Add math functions necessary for picoGPT

- .github/workflows/ci.yml
> TEST-#5764: run test-asv-benchmarks CI job only for PRs

- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
- modin/numpy/indexing.py
- modin/numpy/test/test_array_indexing.py
> FIX-#5774: Correctly calculate shape of single row

- asv_bench/asv.conf.dask.json
- asv_bench/asv.conf.unidist.json
- asv_bench/benchmarks/utils/compatibility.py
> TEST-#5790: add ASV configs for Dask and Unidist

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/push-to-master.yml
> TEST-#5802: update some actions in CI

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/pandas/test/dataframe/test_binary.py
- requirements/env_hdk.yml
> FIX-#5810: Enable test_binary test on the HDK engine

- examples/quickstart.ipynb
> DOCS-#5659: Supplement quickstart notebook with a note regarding OOM issue

- modin/pandas/general.py
- modin/pandas/test/test_concat.py
> FIX-#5776: fix IndexError when concatenating dict of series along columns

- modin/pandas/test/test_io.py
> TEST-#0000: fix typo: `read_stata kwargs` -> `read_sas kwargs`

- .github/workflows/ci.yml
- README.md
- docs/getting_started/installation.rst
- docs/getting_started/quickstart.rst
- docs/release-procedure.md
- docs/usage_guide/advanced_usage/modin_in_the_cloud.rst
- docs/usage_guide/advanced_usage/spreadsheets_api.rst
- examples/quickstart.ipynb
- modin/config/envvars.py
- modin/experimental/spreadsheet/__init__.py
- modin/experimental/sql/dfsql/query.py
> DOCS-#0000: fix pip install command for macos

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/test/dataframe/test_join_sort.py
- requirements/env_hdk.yml
> FIX-#5576: Enable test_join_sort test on the HDK engine and add to CI

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition.py
- modin/pandas/test/test_general.py
> FIX-#5870: Enable test_general test on the HDK engine and add to ci

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/push-to-master.yml
[](https://github.com/mvashishtha/modin/pull/new/5913/cancel-concurrent-test-runs)
- [] tests added and passing
> TEST-#5913: Cancel CI for commits to same branch.

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/test/test_series.py
- requirements/env_hdk.yml
This PR depends on:
FIX-https://github.com/modin-project/modin/issues/3925: Fixed AssertionError on columns and index drop
FIX-https://github.com/modin-project/modin/issues/5576: Enable test_join_sort test on the HDK engine and add to CI
FIX-https://github.com/modin-project/modin/issues/5566: Enable test_indexing test on the HDK engine and add to ci
FIX-https://github.com/modin-project/modin/issues/5580: BUG: 'AVG|SUM' is only valid on integer and floating point
> FIX-#5770: Enable test_series test on the HDK engine and add to ci

- requirements/env_hdk.yml
> FEAT-#5930: Bump pyhdk version to 0.5

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/conftest.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_series.py
> FIX-#5927: Enable `test_map_metadata` test on the HDK engine

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_window.py
> FIX-#5934: Enable test_window test on the HDK engine and add to ci

- modin/pandas/test/test_io.py
> FIX-#5941: TEST: The test test_io.py fails on HDK

- .github/workflows/ci.yml
This PR splits some CI jobs into multiple ones so they can be run in parallel and take less time overall.
> TEST-#5943: Rebalance tests between different CI jobs

- .github/workflows/push-to-master.yml
> TEST-#5977: Add AWS mock keys to moto in push-to-master.yml

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/push-to-master.yml
I think we should check every commit on the master branch. Quick fix without issue. @mvashishtha what do you think?
> TEST-#5980: use `cancel-in-progress` only for PRs

- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/pandas/test/test_io.py
> FIX-#5985: BUG: ArrowPeriodType and ArrowIntervalType are not supported by HDK

- .github/workflows/build-docs.yml
- .github/workflows/ci.yml
- docs/usage_guide/integrations.rst
> FIX-#5993: Fix documentation building in CI

- setup.cfg
> TEST-#6010: add some more test directories into `setup.cfg` to omit for coverage

- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
> TEST-#6004: add more `# pragma: no cover` for io functions

- modin/core/io/io.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
> TEST-#5991: add simple tests for `read_orc`, `read_spss`, `json_normalize`, `read_xml`, `read_gbq`

- .github/workflows/ci.yml
> TEST-#6027: Test installing Unidist via pip in a clean environment, as we do for Dask and Ray

- README.md
> Release version 0.20.1

- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#6037: Simplified filter node expression for ranges

- modin/core/execution/modin_aqp.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition_manager.py
> REFACTOR-#6046: remove code duplication for `progress_bar_wrapper`

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/series_utils.py
> FIX-#6053: align `Series.str` signatures with pandas

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
FIX-#6074: cap pyarrow<12 to fix CI
> FIX-#6074: cap pyarrow<12 to fix CI

- modin/pandas/dataframe.py
- modin/pandas/series.py
> REFACTOR-#6068: Simplify info() call

- modin/pandas/general.py
> FIX-#6115: Check for `_to_datetime` attribute in `pd.to_datetime`

- modin/core/io/column_stores/feather_dispatcher.py
This PR rewrites retrieving feather's metadata from reading the whole file to an approach suggested in the related arrow's issue: https://issues.apache.org/jira/browse/ARROW-10344
For the reproducer below, I've measured the following performance on 112 cores Intel(R) Xeon(R) Gold 6238R CPU @ 2.20GHz
| | master | this PR |
|-|-|-|
|read_feather| 6.05s | 0.99s |
```python
import tempfile
NROWS = 10_000_000
NCOLS = 32
with tempfile.NamedTemporaryFile() as file:
pd.DataFrame({f"col{i}": np.arange(NROWS) for i in range(NCOLS)}).to_feather(file.name)
t1 = timer()
df = pd.read_feather(file.name)
print("read_feather", timer() - t1)
```
> **_NOTE:_**  If you edit the PR title to match this format, you need to …
> PERF-#6122: Extract Feather's metadata without reading the whole file

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/groupby.py
> REFACTOR-#6067: Simplify describe() query compiler interface

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
REFACTOR-#6119, #6118: Add query compiler methods for groupby diff, pct_change
porting parts of commits: 
- https://github.com/ponder-org/modin-public/commit/2402cc17ca88e38066830a509d3e5a5bee02ab31
- https://github.com/ponder-org/modin-public/commit/a4f7eb5ee4cfc61fb1dd72be7ae0e75d26f11d2a
co-authored by: Karthik Velayutham <vkarthik@ponder.io>
> REFACTOR-#6119: #6118: Add query compiler methods for groupby diff, pct_change

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
upstreaming https://github.com/ponder-org/modin-public/commit/c3013cdc8fa97d7fb5dcc7c99cb5a9d8e67d55a7
> FIX-#6114: Fix series groupby list of numpy methods

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_series.py
> FIX-#6106: Fix API layer implementation of reindex_like

- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#6110: Generalize logic to test if an index is a MultiIndex

- modin/pandas/base.py
> REFACTOR-#6151: Get slicer without consructing pandas dataframe.

- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
> FIX-#6094: pin 'urllib3<2' for pip command in 'test-ray-master' job

- modin/pandas/resample.py
- modin/pandas/test/test_series.py
> FIX-#6069: Improve the way resample is handled at the API layer

- modin/pandas/base.py
> FIX-#6155: Fully implement droplevel for axis=0

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
- modin/pandas/series.py
> FIX-#6070: Simplify implementation of `shift`

- modin/numpy/arr.py
> FIX-#6186: Don't use pandas extension types

- modin/numpy/arr.py
> FIX-#6183: Ensure array resets index and columns for all storage formats

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#6194: Fix crashes on groupby.{pct_change,diff}

- modin/pandas/test/test_api.py
> TEST-#6031: test the function parameters of `Series.dt` accessor for pandas equivalence

- .github/workflows/ci.yml
> TEST-#6260: Increase test_io timeout

- requirements/env_hdk.yml
> FIX-#6189: Bump pyhdk version to 0.6

- modin/core/io/column_stores/feather_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#6212: Fix '.read_feather()' failure if the file contains index metadata

- environment-dev.yml
- modin/core/io/text/excel_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
> FIX-#6218: Fix `read_excel` and unpin `openpyxl`

- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/test/test_io.py
> FIX-#6258: Fix series to_dict

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#6246: fix `groupby(..., as_index=False).agg(...)` case

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/df_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FEAT-#6256: HDK: Add support for DataFrameGroupBy.head/tail()

- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_reduce.py
> FIX-#6273: fix DataFrame.min/max/mean/median/skew/kurt with axis=None

- asv_bench/benchmarks/scalability/scalability_benchmarks.py
- asv_bench/benchmarks/utils/data_shapes.py
> TEST-#6308: add `to_numpy` ASV bench

- .github/workflows/push-to-master.yml
> FIX-#6317: fix syntax error in 'push-to-master.yml'

- modin/utils.py
> FIX-#6313: update MIN_RAY_VERSION var: 1.4.0 -> 1.13.0

- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- requirements/env_hdk.yml
> FEAT-#6327: Bump pyhdk version to 0.7

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
**Depends on** https://github.com/intel-ai/hdk/pull/506
> FIX-#6208: HDK: Added support for median aggregation

- modin/pandas/__init__.py
> REFACTOR-#6329: deprecate cloud feature

- README.md
This patch release includes the following PRs:
* https://github.com/modin-project/modin/pull/6337
* https://github.com/modin-project/modin/pull/6307
* https://github.com/modin-project/modin/pull/6314
* https://github.com/modin-project/modin/pull/6310
* https://github.com/modin-project/modin/pull/6298
* https://github.com/modin-project/modin/pull/6036
* https://github.com/modin-project/modin/pull/6262
> Release 0.22.3

- scripts/release.py
> FIX-#6354: Skip bad and pre-release versions when generating release notes

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
- README.md
- codecov.yml
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- setup.cfg
**Note**: this leaves `push` checks as they are (i.e. running to the full extent), only lessening the load for PRs, so we should pay attention to checks running after merging to `master` when this is in place.
> TEST-#2008: Reduce runtime of CI checks a lot

- docs/conf.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
> FEAT-#6377: HDK: Do not keep reference to arrow table imported to HDK

- modin/numpy/arr.py
> FIX-#6386: don't make unnecessary 'astype' calls for `modin.array.sum` op

- docs/supported_apis/dataframe_supported.rst
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FEAT-#6401: Support compression param and more file extensions in to_parquet

- README.md
> FIX-#6410: add a link to @modin_project twitter

- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/dataframe/algebra/default2pandas/resample.py
- modin/core/dataframe/algebra/default2pandas/rolling.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/interchange/dataframe_protocol/column.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/io/text/csv_glob_dispatcher.py
- modin/numpy/test/test_array.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> FIX-#6427: make code compatible with flake8==6.1.0

- .github/workflows/ci.yml
- modin/experimental/xgboost/xgboost_ray.py
Fixes xgboost tests on master branch.
Reference: https://github.com/modin-project/modin/actions/runs/5694815741/job/15436853389
```python
...
FAILED modin/experimental/xgboost/test/test_xgboost.py::test_xgb_with_regression_datasets[load_diabetes-3-DataFrame] - ZeroDivisionError: division by zero
FAILED modin/experimental/xgboost/test/test_xgboost.py::test_xgb_with_regression_datasets[load_diabetes-3-Series] - ZeroDivisionError: division by zero
FAILED modin/experimental/xgboost/test/test_xgboost.py::test_invalid_input - ZeroDivisionError: division by zero
```
Here one can verify that the problem has been fixed: https://github.com/modin-project/modin/actions/runs/5701265682/job/15451811834
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if …
> FIX-#0000: fix xgboost tests with ray>2.6.0

- NOTICE
- docs/conf.py
> DOCS-#6452: Update copyright year

- modin/test/interchange/dataframe_protocol/pandas/test_protocol.py
> TEST-#4643: add interchange test for empty dataframe

- modin/core/dataframe/pandas/dataframe/dataframe.py
This change speeds up the workload I work on. I'll add a couple of synthetic examples a little later, but the pull request is ready for review.
Benchmark's result (best time): 5.4 sec (PR) vs 7.2 sec (master). Boost: ~25%.
<details>
<summary> Benchmark </summary>
```python
import os
os.environ["MODIN_ENGINE"] = "Ray"
os.environ["MODIN_CPUS"] = "44"
os.environ["MODIN_BENCHMARK_MODE"] = "True"
random_state = np.random.RandomState(seed=42)
df = pd.DataFrame(random_state.randint(0, 10**6, size=(5 * 10**6, 64)))
new_index = df.index.values[:int(len(df.index)*0.9) + 1]
random_state.shuffle(new_index)
for _ in range(10):
start = time()
new_df = df.iloc[new_index]
print(f"time: {time()-start}")
```
</details>
> **_NOTE:_**  If you …
> PERF-#6388: avoid masking in __getitem__ when the number of rows to be taken > 90%

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
> FIX-#6459: support fastparquet>=2023.1.0

- modin/pandas/base.py
- modin/pandas/test/test_series.py
> FIX-#6483: Default to pandas for __array_ufunc__

- modin/experimental/xgboost/test/test_dmatrix.py
> TEST-#6449: run tests in test_dmatrix.py only for Ray engine

- README.md
> Release version 0.23.1

- modin/config/envvars.py
> FEAT-#6502: HDK: Add 'enable_multifrag_execution_result=1' HDK launch parameter

- .github/workflows/ci.yml
- asv_bench/asv.conf.hdk.json
- asv_bench/asv.conf.json
> TEST-#6505: update python version for ASV benchmarks on HDK

- .github/actions/mamba-env/action.yml
- .github/actions/python-only/action.yml
- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/push-to-master.yml
- .readthedocs.yaml
- asv_bench/asv.conf.dask.json
- asv_bench/asv.conf.hdk.json
- asv_bench/asv.conf.json
- asv_bench/asv.conf.unidist.json
- environment-dev.yml
- modin/numpy/test/test_array_arithmetic.py
- modin/pandas/groupby.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_series.py
- modin/utils.py
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
- setup.py
Preparation step for migrating to pandas 2.1.*
> FEAT-#6511: update the minimum supported python version up to 3.9

- .github/workflows/push-to-master.yml
> TEST-#0000: download ray wheel for python 3.9

- modin/core/io/file_dispatcher.py
- modin/experimental/core/io/text/csv_glob_dispatcher.py
> FIX-#6519: consider 'botocore' as an optional dependency

- modin/pandas/groupby.py
I forgot to delete the switch before.
> FIX-#5536: remove branch disabling '__getattribute__' for experimental mode

- .github/workflows/ci.yml
- asv_bench/asv.conf.dask.json
- asv_bench/asv.conf.hdk.json
- asv_bench/asv.conf.json
- asv_bench/asv.conf.unidist.json
- environment-dev.yml
- requirements-dev.txt
- requirements/requirements-no-engine.yml
> TEST-#6477: Update ASV to 0.5.1

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
this is a temporary fix, a follow-up issue to fix the root cause: #6537
> FIX-#6535: Pin 's3fs<2023.9.0'

- docs/getting_started/using_modin/using_modin_cluster.rst
- docs/usage_guide/benchmarking.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
> FIX-#6565: don't implement `map` function via `applymap`

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/test/storage_formats/pandas/test_internals.py
> FIX-#6572: Execute simple queries row-wise in pandas backend

- requirements/env_hdk.yml
> FEAT-#6597: Bump pyhdk version to 0.8

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
> FEAT-#6484: HDK: Add support for nlargest/nsmallest groupby aggregation

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FEAT-#6527: HDK: Add support for the quantile group by aggregation.

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#6604: HDK: Added support for list to DataFrame.agg()

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#6600: fix usage of list of UDF functions in `Series.groupby.agg`

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#6628: Allow groupby diff for dates

- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
> PERF-#6629: HDK: Avoid LazyProxyCategoricalDtype materialization on merge

- modin/experimental/core/storage_formats/hdk/query_compiler.py
> FIX-#6642: fix `modin.numpy.array.sum` on HDK

- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
- modin/distributed/dataframe/pandas/partitions.py
> FEAT-#5634: Introduce `materialize` parameter for `partition.ip` func

- docs/getting_started/why_modin/out_of_core.rst
> DOCS-#6658: Add a note how to enable object spilling in a multi-node Ray cluster

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#6661: Do not convert columns dtypes if the new dtypes are the same

- requirements/env_hdk.yml
> FEAT-#6675: Bump pyhdk version to 0.9

- CODEOWNERS
> FIX-#6687: Explicitly add users to CODEOWNERS

- modin/core/storage_formats/base/query_compiler.py
Removes useless iteration over the result.
> PERF-#6671: don't iterate over the result of the `Series.tolist` function

- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#6712: Copy `_shape_hint` in `query_complier.copy` function

- modin/core/storage_formats/base/query_compiler.py
> PERF-#6714: Assign `_shape_hint = "columns"` into query_compiler in `columnarize` function

- README.md
> Release version 0.23.1.post0

- README.md
Release with hotfix for Unidist (incompatible new release 0.0.5).
> Release version 0.25.1

- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- setup.py
> FIX-#6745: Pin 'unidist <= 0.4.1'

- README.md
> Release version 0.24.1.post0

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#6756: Don't materialize index when sorting

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#6774: Modify conditions to get similar behavior to pandas

- docs/release-procedure.md
> DOCS-#0000: Add conda forge doc

- modin/pandas/__init__.py
- modin/pandas/errors/__init__.py
- modin/pandas/test/test_api.py
> FEAT-#6801: Add 'modin.pandas.error' module

- modin/experimental/pandas/__init__.py
- modin/experimental/pandas/io.py
> REFACTOR-#6818: don't implicitly enable experimental mode

- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
- modin/core/io/column_stores/feather_dispatcher.py
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/io/text/excel_dispatcher.py
- modin/core/io/text/json_dispatcher.py
- modin/core/io/text/text_file_dispatcher.py
- modin/experimental/core/io/pickle/pickle_dispatcher.py
- modin/experimental/core/io/text/custom_text_dispatcher.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
> FEAT-#6820: Make sure IO functions works with path-like filenames

- docs/getting_started/examples.rst
- docs/getting_started/quickstart.rst
- docs/getting_started/using_modin/using_modin_cluster.rst
- examples/jupyter/Modin_Taxi.ipynb
- examples/jupyter/Pandas_Taxi.ipynb
- examples/jupyter/integrations/huggingface.ipynb
- examples/quickstart.ipynb
- examples/tutorial/jupyter/execution/hdk_on_native/local/exercise_2.ipynb
- examples/tutorial/jupyter/execution/pandas_on_ray/cluster/exercise_6.ipynb
- examples/tutorial/jupyter/execution/test/utils.py
> FEAT-#6830: Remove public s3 bucket reference

- modin/conftest.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/df_algebra.py
> REFACTOR-#6845: Fix import issues found by CodeQL

- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
> TEST-#6893: Added support for 'pytest 8.0.0'

- modin/core/dataframe/pandas/dataframe/dataframe.py
> FIX-#6897: Preprocess kernel function that alignes columns in groupby

- modin/pandas/test/test_expanding.py
- modin/pandas/test/test_rolling.py
> REFACTOR-#6903: Remove duplicated definitions of 'create_test_series'

- docs/requirements-doc.txt
- environment-dev.yml
- examples/tutorial/jupyter/execution/pandas_on_ray/requirements.txt
- requirements-dev.txt
- setup.py
> FIX-#6916: unpin `pydantic` dependency

- modin/config/envvars.py
> PERF-#6922: Set `DaskThreadsPerWorker` to 1

- modin/config/envvars.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/test/storage_formats/pandas/test_internals.py
> FEAT-#6918: Add auto mode to the lazy execution.

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
> FIX-#6924: HDK: Use JoinNode instead of MaskNode for non-range row_position

- modin/test/test_docstring_urls.py
> TEST-#0000: fix 'push-to-master / test docs' CI job

- README.md
- docs/conf.py
- docs/contact.rst
- docs/development/architecture.rst
- docs/release-procedure.md
- docs/usage_guide/advanced_usage/index.rst
> DOCS-#6962: Remove links to https://discuss.modin.org

- modin/pandas/__init__.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
- modin/pandas/testing/__init__.py
> FEAT-#6783: Implement `modin.pandas.testing` module

- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> FIX-#7054: Update exception message for `shift` function

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/utils.py
> FIX-#7056: Update exception message for `iloc/loc` functions

- modin/pandas/base.py
- modin/pandas/test/test_series.py
> FIX-#7062: Update exception message for `aggregate` function

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/utils.py
> FIX-#7058: Update exception message for `insert` function

- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/utils.py
> TEST-#7073: Explicitly check for exceptions in `test_default.py`

- modin/pandas/test/dataframe/test_indexing.py
> TEST-#7084: Explicitly check for exceptions in `test_indexing.py`

- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> TEST-#7094: Rename `raising_exceptions` argument of `eval_general` testing function

- modin/core/dataframe/algebra/map.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
> PERF-#7068: Provide shape_hint="column" for some more operations with Series

- examples/tutorial/jupyter/execution/pandas_on_ray/cluster/modin-cluster.yaml
> REFACTOR-#0000: Remove proxy from cluster configuration

- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#7123: Preserve shape_hint for dropna

- modin/pandas/series.py
Here type hints are added mainly for return values from functions. If the function returns Series, then it will be possible to use auto completion (a list of available functions and attributes is visible), which currently does not work at all.
> FEAT-#7156: Add type hints for Series

- modin/core/storage_formats/pandas/query_compiler.py
- modin/tests/pandas/dataframe/test_indexing.py
> FIX-#7135: Fix appending a new row

- README.md
> Release version 0.28.2

- modin/pandas/general.py
- modin/pandas/io.py
> FEAT-#7180: Add type hints for modin.pandas.[functions]

- .github/workflows/ci.yml
- asv_bench/asv.conf.dask.json
- asv_bench/asv.conf.hdk.json
- asv_bench/asv.conf.json
- asv_bench/asv.conf.unidist.json
- asv_bench/benchmarks/benchmarks.py
> TEST-#7191: Fix ASV after changing default branch

- modin/config/envvars.py
- modin/tests/config/test_envvars.py
> FIX-#7185: Add extra check for some config classes

- docs/usage_guide/optimization_notes/range_partitioning_ops.rst
> DOCS-#0000: Fix a typo with MODIN_CPUS number

- docs/usage_guide/optimization_notes/index.rst
Make Modin configs more visible to users.
> DOCS-#0000: Supplement Optmization Notes with a link to configs

- README.md
> FIX-#0000: Fix badge in README.md

- modin/config/envvars.py
- modin/error_message.py
> FIX-#7234: Deprecate HDK engine

- docs/usage_guide/advanced_usage/index.rst
> DOCS-#7255: Update docs as to from_* functions

- modin/core/dataframe/pandas/dataframe/utils.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/numpy/arr.py
- modin/pandas/indexing.py
- modin/tests/numpy/test_array.py
- modin/tests/pandas/dataframe/test_binary.py
- modin/tests/pandas/dataframe/test_join_sort.py
- modin/tests/pandas/test_groupby.py
- modin/tests/pandas/test_series.py
- modin/tests/pandas/utils.py
> FIX-#7292: Prepare Modin code for NumPy 2.0

- README.md
> Release version 0.30.1

- README.md
> Release version 0.29.1

- README.md
> Release version 0.28.3

- README.md
> Release version 0.27.1

- NOTICE
- docs/conf.py
> REFACTOR-#0000: Update copyright date

- modin/pandas/base.py
> FIX-#7351: Add ipython method calls to non-lookup list

- modin/pandas/series.py
> FIX-#7379: Fix __imul__ performing addition instead of multiplication

- docs/usage_guide/optimization_notes/index.rst
> DOCS-#7382: Add documentation on how to use Modin Native query compiler

- .github/actions/upload-coverage/action.yml
- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/publish-to-pypi.yml
> FIX-#7389: Fix uploading artifacts

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/tests/core/storage_formats/pandas/test_internals.py
> FIX-#7383: Avoid broadcast issue in partition manager with custom `NPartitions`

- docs/getting_started/quickstart.rst
- docs/getting_started/using_modin/using_modin_cluster.rst
- examples/jupyter/Modin_Taxi.ipynb
- examples/jupyter/Pandas_Taxi.ipynb
- examples/jupyter/integrations/huggingface.ipynb
- examples/quickstart.ipynb
- examples/tutorial/jupyter/execution/pandas_on_dask/cluster/exercise_5.ipynb
- examples/tutorial/jupyter/execution/pandas_on_ray/cluster/modin-cluster.yaml
- examples/tutorial/jupyter/execution/test/utils.py
> TEST-#7457: Fix SSL certificate error in notebooks by using http.

- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/core/storage_formats/pandas/native_query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/api/extensions/extensions.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/indexing.py
- modin/pandas/series.py
- modin/tests/pandas/extensions/conftest.py
- modin/tests/pandas/extensions/test_base_extensions.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
- modin/tests/pandas/extensions/test_series_extensions.py
- modin/tests/pandas/native_df_interoperability/conftest.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
- modin/tests/pandas/native_df_interoperability/test_general.py
- modin/tests/pandas/native_df_interoperability/test_join_sort.py
- modin/utils.py
> REFACTOR-#7470: Combine backend casting and extension code at the API layer.

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/base.py
- modin/pandas/indexing.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
- modin/tests/pandas/extensions/test_series_extensions.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FEAT-#7475: Choose the correct __init__ method from extensions and apply casting to __init__.

- modin/conftest.py
- modin/core/execution/unidist/common/engine_wrapper.py
- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/indexing.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FEAT-#7507: Support pre-operation automatic backend switch.

- modin/config/envvars.py
- modin/core/storage_formats/base/query_compiler.py
> REFACTOR-#7564: Fix docstrings for transfer thresholds.

- modin/conftest.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/api/extensions/__init__.py
- modin/pandas/api/extensions/extensions.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/tests/pandas/extensions/test_groupby_extensions.py
> FEAT-#7543: Let plugins register groupby accessors.

- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
> FIX-#7576: Fix ambiguous AttributeError message

- README.md
Update badges for the patch release per the instructions [here](https://github.com/modin-project/modin/blob/bf5f3440743d0e0b69c84641e12796800f55db10/docs/release-procedure.md?plain=1#L55-L62).
an example of an earlier patch release PR: https://github.com/modin-project/modin/pull/7303/
> Release version 0.33.1

- docs/getting_started/quickstart.rst
- docs/getting_started/using_modin/using_modin_cluster.rst
- examples/jupyter/Modin_Taxi.ipynb
- examples/jupyter/Pandas_Taxi.ipynb
- examples/jupyter/integrations/huggingface.ipynb
- examples/quickstart.ipynb
- examples/tutorial/jupyter/execution/pandas_on_dask/cluster/exercise_5.ipynb
- examples/tutorial/jupyter/execution/pandas_on_ray/cluster/modin-cluster.yaml
- examples/tutorial/jupyter/execution/test/utils.py
Changes are the inverse of #7458.
> TEST-#7451: Use https for modin-datasets.intel.com

- modin/tests/pandas/dataframe/test_pickle.py
Prior to this commit, we were trying to pickle the pytest fixture function `modin_df` instead of trying to pickle the dataframe that `modin_df` generates. Prior to pytest 8.4, the test passed but didn't test what we wanted to. With pytest 8.4, the test started raising an error.
Resolves #7602
> TEST-#7602: Fix test_pickle by correctly using fixtures.

- .github/workflows/ci.yml
> TEST-#7611: Cap mpi4py<4.1 in CI.

- modin/pandas/groupby.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FEAT-#7620: Support pin_backend(inplace=False) for groupby objects.

- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/io/io.py
- modin/pandas/series.py
- modin/tests/pandas/test_series.py
> FIX-#7624: Add proper implementation for `Series.to_json`
