- requirements.txt
- setup.py
This adds the requirements.txt file.
It also adds support for installing ray from its latest wheels in setup.py.
The requirements are rather hacky as they rely on matching the os and python versions to the specific wheel and installing it manually in setup.py. It might make sense to exclude as the dependency on wheels will be resolved in the Ray 0.5.0 release.
This is rebased on #2.
> Adds requirements.txt with ray wheel dependencies

- README.rst
- modin/dataframe/__init__.py
- modin/dataframe/concat.py
- modin/dataframe/dataframe.py
- modin/dataframe/datetimes.py
- modin/dataframe/groupby.py
- modin/dataframe/index_metadata.py
- modin/dataframe/indexing.py
- modin/dataframe/io.py
- modin/dataframe/iterator.py
- modin/dataframe/reshape.py
- modin/dataframe/series.py
- modin/dataframe/utils.py
Also renaming some functions to match the convention.
> Cleaning up and structuring the imports

- README.rst
Updating readme to reflect a better description and update the broken tag.
> Making changes to readme

- modin/dataframe/dataframe.py
This is a patch for a bug where the index of a `Series` inserted was not default. Inserted values were not correctly added.
See https://github.com/ray-project/ray/issues/2263
> Fixing bug in insert

- README.rst
This makes it easier for people to find the documentation and collaboration links
> Add Documentation link and Collaboration links to the readme

- modin/pandas/test/test_groupby.py
See issue #21, this test is non-deterministic for now. 
Doing type checking and casting on the entire result dataframe is expensive; we need to figure out a better way in the future.
> Skip large_row_groupby

- modin/pandas/utils.py
In `_blocks_to_col`, we can use `np.concatenate` instead of `pd.concat` to speedup our concatenation. Because blocks belongs to the same column group often have the same type or (due to limited col width) few types, the casting will be fast even when it is required.
> Performance boost in _blocks_to_col by np.concatenate

- modin/pandas/indexing.py
- modin/pandas/utils.py
Some classes don't inherit from object which causes errors in python 2. This PR fixes this issue.
> Make classes inherit from object

- modin/pandas/dataframe.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
This PR builds on top of #4. In addition to the Pandas 0.22 API, it also includes bugfixes.
> Fix read_csv for Pandas 0.22

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
There were some completeness regressions:
* head/tail
* idxmax/idxmin
I ran out of time to completely implement these after the performance updates.
Performance pre-memoization is on-par with pandas. After memoization, it is ~2x faster on 4 cores.
> Improve groupby performance while keeping API compatibility

- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/reshape.py
Correcting the link in the error.
> Fixing the NotImplementedError name

- modin/pandas/utils.py
Return a `Series` object is not correct for empty partitions. Also added this check for row partitions, though this could only happen if the entire DataFrame was empty.
> Fixing the correct return object and error checking for functions in utils

- modin/pandas/indexing.py
- modin/pandas/utils.py
There was a complication from PR #19 that breaks accessing a row using loc/iloc
> Fix indexing 1-D series

- README.rst
Fixes link to documentation in README.
> DOC: Fixes link in readme

- modin/pandas/dataframe.py
Fixes performance bugs from #37, no longer concatenating the full column into memory
#37
> Head tail performance

- modin/pandas/groupby.py
- modin/pandas/utils.py
Add a decorator that perform manual GC after the task. It can help containment memory hungry task or pandas operator that does not deallocation memory correctly. 
(https://stackoverflow.com/questions/35782929/pandas-groupby-memory-deallocation/37790738)
> Implement post task gc hook

- modin/pandas/dataframe.py
- modin/pandas/index_metadata.py
Refactors `drop` so that there is not a loop of `df._col_partitions` being set. Should be more performant as well.
#52
> Fixing bug in drop where col_partitions were set incorrectly

- modin/pandas/dataframe.py
Fixes the bug where each column/row is assumed to be unique on the partition.
#50
> Fix bug where fillna assumes each column is its own partition

- modin/pandas/groupby.py
Fixes a bug where `groupby` with a list of integers could have an incorrect grouping based on the internal index.
Resolves #56
> Fix bug where interal index would affect the groupby.

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/utils.py
These changes re-enable disabled regression tests for the `iloc()` method. The newly-enabled tests exposed a minor bug in `DataFrame.equals()`, so I fixed that too. After these changes, all regression tests pass on my local copy.
N/A
> Re-enable disabled regression test and fix a minor bug in equals method

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
The `__repr__()` method of Modin dataframes hits different code paths depending on whether the number of colums is >20, as well as on whether the number of rows is >60. The case where columns<=20 and rows>60 was not covered by the regression tests and had a bug. The bug caused the index column not to be rendered properly in Jupyter notebooks, displaying: 
instead of:
This PR fixes the bug and adds a regression test that covers the previously untested case.
N/A
- [x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
> Fix repr when cols<=20 and rows>60

- modin/__init__.py
- modin/pandas/__init__.py
Adds `__git_revision__` and `__version__` to `modin.pandas`.
```python
In [1]: import modin
In [2]: modin.__version__
Out[2]: '0.1.1'
In [3]: modin.__git_revision__
Out[3]: '98fb533f6b8b20615e62f9c10a412d3c781349c9'
In [4]: import modin.pandas as pd
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:16321 to respond...
Waiting for redis server at 127.0.0.1:11240 to respond...
Starting local scheduler with the following resources: {'CPU': 8, 'GPU': 0}.
In [5]: pd.__version__
Out[5]: '0.1.1'
In [6]: pd.__git_revision__
Out[6]: '98fb533f6b8b20615e62f9c10a412d3c781349c9'
```
Resolves #71, Resolves #72 
cc @jangorecki
> Adding __git_revision__ and __version__

- .travis/install-dependencies.sh
- modin/pandas/concat.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/index_metadata.py
- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/utils.py
- requirements.txt
Our travis tests are failing because it can't find ray 0.4.0 wheels on s3. (Probably because they were deleted).
> Set Ray dependency to 0.5.2

- .flake8
- .travis.yml
- .travis/install-dependencies.sh
- README.rst
- modin/__init__.py
- modin/data_management/data_manager.py
- modin/data_management/factories.py
- modin/data_management/partitioning/axis_partition.py
- modin/data_management/partitioning/partition_collections.py
- modin/data_management/partitioning/remote_partition.py
- modin/data_management/partitioning/utils.py
- modin/pandas/__init__.py
- modin/pandas/concat.py
- modin/pandas/dataframe.py
- modin/pandas/datetimes.py
- modin/pandas/groupby.py
- modin/pandas/indexing.py
- modin/pandas/io.py
- modin/pandas/iterator.py
- modin/pandas/reshape.py
- modin/pandas/series.py
- modin/pandas/test/test_concat.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/pandas/utils.py
- modin/sql/connection.py
Reformat codebase to use black formatting instead of yapf
Resolves #87
> Reformatting code with black instead of yapf

- modin/__init__.py
- modin/pandas/__init__.py
Currently there is a bunch of git errors thrown when you are not running from the default directory.
This will get the `__git_revision__` hash regardless of where the code is being run from.
Resolves #82
> Stop __git_revision__ from throwing errors in non-git repos

- modin/data_management/data_manager.py
Improve performance of `repr(df.T)` by a significant factor.
```python
frame_data = np.random.randint(0, 100, size=(2**20, 2**8))
df = pd.DataFrame(frame_data)
repr(df.T)
```
The `repr(df.T)` previously took more than 20 seconds. 
After this change it takes ~350 ms. 
The change is related to removing the cost of computing `dtype` if we aren't going to use them. `dtype` can be expensive to compute if there are a large number of columns.
Resolves #110
> Fix repr(df.T) performance

- modin/pandas/dataframe.py
Uses `pandas.DataFrame._get_axis_number` to parse the `axis` argument
resolves #130
> Fixed diff

- modin/pandas/dataframe.py
Ensures that the columns are all numeric when necessary for cumulative functions such as `cummax` and `cumsum`. Also throws a `TypeError` when the columns are not all numeric but should be. This error message is different from that of pandas' in order to have `_validate_dtypes` be a more general purpose function instead of only for cumulative functions. 
Resolves #126
> Fixed cumulative functions

- modin/data_management/data_manager.py
- modin/pandas/dataframe.py
Fixed mean to return correct value even when there are `NaN` values and when `numeric_only=False`
Resolves #128
> Fixed mean

- modin/data_management/partitioning/partition_collections.py
Sometimes we can get `np.nan` values when we are performing `mean` across rows.
Resolves #118
> Fix issue where empty partitions caused incorrect behavior

- .github/PULL_REQUEST_TEMPLATE.md
Adding `black --check modin/` to the template to help prevent lint errors.
> Adding black check to PR template

- modin/data_management/partitioning/axis_partition.py
The partitioning can become off when we operate on specific columns or rows. This is particularly evident after a `read_csv`.
This fixes the issue by returning the partitioning in the same number of partitions it was given along a single axis.
N/A
> Fixing partitioning offset

- modin/data_management/data_manager.py
`df.min()` and `df.max()` work correctly on DataFrames with mixed data types. Fixes https://github.com/modin-project/modin/issues/162 and https://github.com/modin-project/modin/issues/163
> Fixed Min and Max

- modin/pandas/dataframe.py
We don't have code in place to verify user-defined functions against the dtypes of the DataFrame. This may result in modin not raising a TypeError when an invalid user-defined function is passed to functions like `df.apply()`, `df.applymap()`, `df.query()`, `df.aggregate()`, and `df.transform`.
> Adding warnings when using user-defined functions

- modin/data_management/data_manager.py
- modin/pandas/dataframe.py
Fixed issues in`df.sum()` and `df.prod()` related to throwing TypeErrors for invalid arguments and computing the result with the `min_counts` argument. Fixes #169 and https://github.com/modin-project/modin/issues/172 and #167  and #166
> Fixed Sum and Prod and Mean

- modin/pandas/dataframe.py
`info` will now default to pandas until we have a faster implementation
> Info default to pandas

- modin/pandas/groupby.py
Makes a minor change so that we support more functionality without defaulting to pandas. This functionality was already supported, but now we do not default to pandas when trying to use it.
Edit: These changes are specific to `groupby`
N/A
> Updating so more functionality does not default to pandas

- modin/pandas/io.py
> Ignoring flake8 error in regex

- .gitignore
> Adding pytest benchmarks folder to gitignore

- .jenkins/build-tests/Dockerfile
- .jenkins/performance-tests/Dockerfile
> Missing Pytest Dependencies in Jenkins Build Process

- modin/__init__.py
- modin/pandas/__init__.py
Some Ubuntu users are unable to use Modin because of the `__git_revision__` addition. I don't think we use this in our regular development, and since it's causing problems we can just drop it and revisit a new fix if others are using it in their development.
#235 multiple users reporting this issue
> Dropping git revision because it causes problems for some Ubuntu users

- modin/pandas/__init__.py
- modin/pandas/io.py
Adds `read_gbq` to `modin.pandas`. As a first pass, we will have it default from pandas.
#243
> Adding read_gbq as a default from pandas implementation

- modin/pandas/groupby.py
Because of the complexities with iterating over groups in `groupby`, we use a different method of grouping (that way we don't trigger full computation when we are accessing only a subset of groups).
For `groupby` where multiple columns are given, we were not correctly returning the groups. For now, we have to default to pandas, pending the distributed `Series` object completion.
Resolves #234
> Fixing issue iterating over groupby with multiple columns

- modin/pandas/io.py
modin.pandas.io.read_parquet now partitions columns into sets of size equal to the available CPU cores (according to Ray) and then reads multiple columns at once 
#205
> Improve speed of read_parquet by reading sets of columns in parallel

- modin/data_management/partitioning/axis_partition/pandas_on_ray.py
- modin/data_management/partitioning/partition_collections/base_block_partitions.py
Fixes `to_pandas` for `Series` objects. Instead of splitting the `Series` we just return it whole.
> Fix to_pandas for Series objects

- modin/data_management/query_compiler/pandas_query_compiler.py
Revert some of the changes to `sum` and `prod` that reverted behaviors.
N/A
> Revert some changes in behavior for sum/prod

- docs/using_modin.rst
> Adding advanced usage docs

- modin/pandas/__init__.py
Exception thrown if we `ray_init()` before importing modin. This PR fixes that issue.
> Ignore Double ray_init errors

- .jenkins/build-tests/Dockerfile
- .jenkins/performance-tests/Dockerfile
Pytest 4 has some new functionality that cause our current tests to break. This pins the pytest version to 3.9.3 for the Jenkins builds.
> pin pytest version to 3.9.3

- modin/pandas/io.py
Fixes filtering on the `names` argument in `read_csv`.
Resolves #239
> Fixing filter for read_csv args

- modin/pandas/dataframe.py
Update UDF warning thrown when `apply` is called
> Update apply's warning

- modin/data_management/partitioning/remote_partition/pandas_on_python.py
- modin/data_management/query_compiler/pandas_query_compiler.py
Flushes `self.call_queue` when we call `get` in `PandasOnPythonRemotePartition`
#286
> Fixed python backend to flush call queue

- .gitignore
- .jenkins/performance-tests/run_perf_test.sh
- modin/__init__.py
- modin/pandas/__init__.py
- modin/pandas/test/performance-tests/conftest.py
- setup.py
- For Dask 🎉:
- Add optional dependency in setup.py. So user can `pip install modin[dask]`
- `execution_engine.title()`
- Allows user to pass in `MODIN_ENGINE=ray` or `MODIN_ENGINE=RAY`
- Add `Dask` and `Python` engine to perf_test for sanity check and basic comparison
> Several Cleanup

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/engines/base/block_partitions.py
Returns a new `QueryCompiler` object instead of a `View` when performing operations on the `View`. The previous problem presented itself when operations resulted in changes in the underlying structure.
Resolves #147
> Change __constructor__ to return a QueryCompiler instead of a View object.

- modin/data_management/query_compiler/pandas_query_compiler.py
* Only occurs when a `set_index` is called, followed by a `drop`
* Only fails the first time, resulting the a `call_queue` that is not
empty
* Fails differently on `df.iloc[[0]]` and `df.iloc[0]` but cause is the
same
* The failure is a result of some partitions not filtering out the data:
e.g. The first column of block partitions in the affected partitions
does not properly remove all of the data.
* Only fails when a certain number of partitions are present. No error on
4x4, but error occurs on 8x8.
* Fixed by removing lazy operator.
* Creating a new issue to track #293
Disable lazy operation for correctness until root of bug is discovered.
> Fixing strange partitioning-related iloc bug

- modin/engines/base/block_partitions.py
Previously, during `__repr__` the `bin_lenghts` were getting reversed which was modifying the metadata of the object directly. Now, we create a view of the object's reverse
Resolves #298
> Fix __repr__ bug

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/engines/base/block_partitions.py
- modin/engines/ray/pandas_on_ray/axis_partition.py
- modin/pandas/test/test_dataframe.py
Sometimes we keep around extra partitions. This PR fully filters out those partitions. 
When we keep empty partitions around, there can be mismatches between how things are represented and how they are. e.g. A `drop` followed by indexing into the frame can result in errors getting thrown from the remote partitions.
N/A
> Improve the way that Modin filters out empty partitions

- modin/pandas/__init__.py
- modin/pandas/dask_client.py
No longer requires Dask for importing `modin.pandas`. The location of the dask imports has been moved to ensure that we do not depend on it unless it is specifically requested.
N/A
> Simplify Dask import and startup

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
Fixes `get_dtype_counts` error of the resulting index having mixed dtypes and issues with handling the conversion from pandas datetime[ns] to numpy
> Fix index of the result of get_dtype_counts

- modin/engines/ray/pandas_on_ray/io.py
* Changed the zipping of provided and default arguments to no longer be
off-by-one
* Changed the boolean condition for filtering out keyword arguments to
be correct
Resolves #311
> Fixing bug in read_csv erroneously filtered out provided keyword arguments

- modin/pandas/concat.py
* Now creates a MultiIndex correctly from the keys provided
* Better error checking (closer to pandas)
* Correct order of keyword arguments
* Minor refactor
Resovles 316
> Fix bug in concat where keys were improperly assigned

- modin/data_management/query_compiler/pandas_query_compiler.py
* This will give the correct result when `df.describe` is called
* Fixes an index mismatch error between the remote and local
Resolves #320
> Adding dtypes to the `exclude` parameter in the remote partition

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/data_management/utils.py
- modin/engines/base/block_partitions.py
- modin/engines/ray/pandas_on_ray/axis_partition.py
- modin/engines/ray/pandas_on_ray/io.py
This is not comprehensive, though it is a solid start.
* Initial partitioning can also be determined by size now
* Fixed some internal bugs around having 1x1 partitions (previously an
extreme edge case -- 1x1 DataFrame)
* Still encountering some edge case bugs
>  Making Modin more efficient with smaller DataFrames

- modin/pandas/dataframe.py
Always converts `dropna`'s `axis` argument from a string to an integer before passing to `self.query_compiler`
> Fix dropna when axis argument is a string

- modin/data_management/query_compiler/pandas_query_compiler.py
Removes a reindex and `mode` works properly when `axis=1`
> Fix mode when axis=1 and remove a reindex

- modin/engines/base/block_partitions.py
* Scenario that caused the bug:
* `query` or a similar filter operation run
* Some partitions completely removed from the dataframe
* During `get_indices`, the filter optimization on BlockPartitions
caused the empty partitions to not count toward the index
computation
* Fix: Use _partitions_cache, which is not modified when accessed.
Resolves #347
> Fix a bug in `get_indices`

- modin/data_management/query_compiler/pandas_query_compiler.py
* This allows the partition to return a valid DataFrame and not an
Exception
* In the future, additional post-processing may be needed to throw the
pandas error that gets thrown if no data of that type exists.
Resolves #364
> Adding try-except block to internal partition computation for describe

- modin/engines/base/block_partitions.py
* Adding a condition for selective apply operations that will simply
return an empty 2D numpy array for partitions if there are no
partitions.
* This is added to both `apply_func_to_select_indices` and
`apply_func_to_select_indices_along_full_axis`
Resolves #368
> Correctly handling empty DataFrames for selective operations

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/iterator.py
* Resolves #384
* Make changes to the functions that use getitem_array to now use
indices instead
> Converting PandasQueryCompiler.getitem_array to accept numeric indices

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/indexing.py
* Resolves #392
* This creates a view on all objects, even PandasQueryCompilerView
objects, when using an Indexer (e.g. LocIndexer)
* Allows `df.iloc[...].iloc[...]` to be supported now
> Removing is_view from PandasQueryCompilerView and codepath requiring it

- modin/pandas/indexing.py
Dataframe().loc will verify row and col locations before setting the item. if these are single locations, one row or one col, and either do not exist, it will be created.
This is to align according to pandas behaviour
#399
> support for DataFrame().loc when location (row/col) does not exist

- modin/pandas/dataframe.py
* Resolves #402
* Adds a condition that allows DataFrames to be inserted as long as they have 1 column
> Adding support for inserting DataFrames with 1 column

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #409
* Removes a grouped column from the result to match pandas
* Changes the way we compute `size` to match pandas
* Adds consisntecy between the DataFrame being computed on and the result
> Add a fix to Groupby for aggregations by a column from the DataFrame

- modin/pandas/dataframe.py
* Resolves #422
* Adds a warning if it appears that users are trying to set a new column with
`__setattr__`. This matches pandas behavior.
* Uses `__setitem__` if the `key` passed is a column in the DataFrame
> Adding a way to set existing columns using __setattr__

- modin/engines/base/block_partitions.py
- modin/pandas/test/test_dataframe.py
Uses the argument `ordered` when calling `_get_dict_of_block_index` to ensure that we get things ordered if `keep_remaining = False` when `apply_func_to_indices_both_axis` is called. We also add code similar to `apply_func_to_select_indices` when `keep_remaining = False`
Fixes #421
> Fixes out of order columns for loc based indexing

- modin/data_management/query_compiler/pandas_query_compiler.py
* Skips reindexing if there is already a match
* Since some operations always need the reindex, add a flag for that
* Add docs
* Lint
(Above)
N/A
> Add a way to skip the initial reindex phase for left and right

- modin/engines/base/axis_partition.py
- modin/engines/python/pandas_on_python/axis_partition.py
- modin/engines/ray/pandas_on_ray/axis_partition.py
- modin/pandas/__init__.py
* Create PandasOnXAxisPartition abstract class to contain common code
* Remove common code between `PandasOnRay` and `PandasOnPython` `AxisPartitions`
* Register a custom serializer for Ray to fit with the new code
N/A
> Refactor Pandas Axis Partition objects to avoid duplicate code

- modin/__init__.py
* Declutters the warning message so the message is easier to see
* Removes the `warnings.warn(message)` from the message as well.
* Difference between old and new shown below:
Previous:
```
/Users/DevinPetersohn/software_builds/modin/modin/error_message.py:32: UserWarning: `cov` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
warnings.warn(message)
```
This commit:
```
UserWarning: `cov` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
```
> Removing path and line number from warnings.

- modin/data_management/factories.py
- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/engines/base/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_io.py
Implementation of `Dataframe.to_sql()`
The major challenge was writing the index to the database, as the partitions don't hold the original index. The solution was to add the index as a column if needed.
One remaining issue,  when saving the index, the resulting DB file is not of the same size as the one that is saved by `pandas`. other than that, loading from a DB table which was saved by `pandas.Dataframe.to_sql()` or by  `modin.Dataframe.to_sql()` will result in the same Dataframe (verified in the unit tests).
#453
> parallel to_sql()

- modin/engines/ray/pandas_on_ray/io.py
- modin/pandas/test/test_io.py
Add logic to handle the column name updates when `parse_dates` is passed to `read_csv`
#470
> Fix issue by properly handling parse_dates

- .coveragerc
- .travis.yml
- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/engines/base/io.py
- modin/pandas/__init__.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/utils.py
- requirements.txt
- setup.py
* pandas release notes: http://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html
* Update imports to match changes in pandas
* Add functionality for list of functions on `axis=1` for `apply`
* Remove `pd.match` from API
* Small regression in pandas requires regression in Modin
* pandas-dev/pandas#25101 reports this issue
* pandas-dev/pandas#25102 resolves this issue
* TODO: Expose `pandas.Array` once we properly test
> Update pandas version to 0.24

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves $484
* Adds correct support for all `include` values passed
* Previously, the behavior was to use `include` to compute `exclude`
* The correct behavior is that `include` is strictly inclusive, such
that only types in the `include` list are included, rather than
those being included in addition to the default types.
* Also correctly throws the same error type as pandas (with the same
message, though the message is not informative
* Add tests for `include="all"` and `include=[np.timedelta64, np.datetime64, np.object, np.bool]`
> Add correct support for `include="all"`

- modin/data_management/query_compiler/pandas_query_compiler.py
- modin/engines/base/block_partitions.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves #474
* Adds `PandasQueryCompiler.setitem` to avoid multiple maps
* Correctly handles the initial insertion when there is no index
* Fix `PandasQueryCompiler._prepare_method` to allow `internal_indices`
to be used.
> Correctly match pandas behavior when iteratively updating columns

- modin/experimental/engines/pandas_on_ray/io_exp.py
Moves the `sqlalchemy` import statement to `read_sql`
Fixes #497
> Move `sqlalchemy` import statement in experimental io

- requirements.txt
> pin pytables version in tests to avoid dependency mismatches

- docs/installation.rst
- docs/out_of_core.rst
- modin/pandas/__init__.py
- setup.py
* Cast `MODIN_MEMORY` to `int`
* Remove unreachable code
* No longer require `psutil` to use `OUT_OF_CORE`
* Fix documentation links to installing for out of core
* Remove setup.py target
N/A
>  Cleanup `pandas.__init__.py`

- modin/engines/ray/pandas_on_ray/io.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/pandas/test/test_io.py
Implementation of parallel read_sql(). Partitioning the data with `LIMIT` and `OFFSET`. 
There is an initial query that gets the number of expected rows, using `COUNT`. Then, divid the query with limit and offset for each partition accordingly.
#418
> parallel read_sql() using limit and offset

- requirements.txt
- setup.py
Updates modin to be compatible with numpy 1.16.0
fixes #482
> Update numpy version to 1.16

- modin/pandas/test/test_io.py
* Since it is defaulting to pandas, the tests are ok to fail
* The failures are typically due to the bytes not being identical,
* but the data in them is identical.
N/A
- [N/A] tests added and passing
> Mark `to_excel` as ok to fail

- modin/backends/pandas/query_compiler.py
- modin/pandas/__init__.py
- requirements.txt
- setup.py
Update the pandas version to 0.24.2
N/A
> Bump pandas version to 0.24.2

- requirements.txt
An update to xdist breaks our pin to pytest
- [N/A] tests added and passing
> Fix Travis incompatibility

- modin/engines/base/io.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
Fix read_excel when sheet_name=None, return corrected type (OrderedDict) 
#512
> read_excel(sheet_name=None) not working  (#512)

- .travis.yml
- modin/pandas/test/test_dataframe.py
* Sometimes, especially if there are failures, the Ray engine will take
longer due to the IPC and startup cost of Ray.
* This splits the test_dataframe.py file into two parts and runs each
separately for the Ray engine.
* Nothing changes for the Python backend
> Split DF testing for Ray backend

- modin/pandas/io.py
- modin/pandas/test/test_io.py
* Resolves #546
* When `sep=False`, adds the sep as `"\t"`, in order to work with the
internal parser
* Adds test case for `read_table`
* Adds parameter to `make_csv_file` fixture to allow a delimiter to be
passed
> Correct behavior for `read_table` when `sep=False`

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
* Resolves #551
* Add some sanitization from the API layer in `DataFrame` and `Series`
* Fix `df.head(0)` and `df.tail(0)`
* Fix `repr` for empty DataFrames
* Fix `tail` when `transpose` was called
> Fix issue where `repr` was not correct after mapreduce operation

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
* Resolves #186
* Corrects the previous behavior by setting the name of the new column
to the name of the index
* Add tests to verify the behavior
> Fix `reset_index` when `name` field of the index is set

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #533
* Defaults to pandas until we implement a way to be compatible with
the `Grouper`
> Fix `groupby` with `by=pandas.Grouper` object

- modin/pandas/io.py
- modin/pandas/test/test_io.py
* Resolves #560
* Adds the `kwds` to the `kwargs` we pass to `pandas.read_fwf`
* Previously this was treated as `kwds={...}` which was not correct
* Introduced by #480
* Add tests to validate correct behavior when given keyword arguments
not explicitly in the signature.
> Support for arguments not explicity in the signature for  `read_fwf`

- modin/pandas/__init__.py
- modin/pandas/test/test_api.py
Add datetime attribute from pandas, tryied to remove "datetime" from ignored in test_top_level_api_equality test, but pandas doesn't have a signature for datetime so the test breaks (maybe test it in another place, i try running some examples to check the attribute)
#542
> Add `datetime` to top level API. issue: #542

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves #517
* No longer trigger compute with an empty mask
* Add tests
> Add fastrack for empty mask computation

- modin/backends/pandas/query_compiler.py
- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
* Resolves #524
* Changes `QueryCompiler.view` to use index-based lookup instead of
label-based lookup.
* Update tests to include testing for duplicate index
> Change `QueryCompiler.view` to use index-based lookup

- modin/pandas/concat.py
- modin/pandas/test/test_concat.py
* Resolves #557
* Zips the `keys` and `objs` parameters together to determine index instead of accessing via index
* Adds test to validate new behavior
> Allow `concat` to accept non-subscriptable objects as `keys` parameter

- modin/pandas/dataframe.py
- modin/pandas/series.py
* Warns user that using the constructor to distribute a large object can
take some time.
> Add warning when using the constructor of DataFrame and Series

- .travis.yml
* DataFrame test part one now runs alone if triggered
* DataFrame test part two also runs alone if triggered
* Other tests will run otherwise, even if All DataFrame tests are triggered
* Supports slowdown in Ray>0.6.2
> Updating tests to support slower execution

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #574
* Defaults to pandas for `level` parameter
* Fixes cases where `by` is not set to enable better edge-case handling
> Fix support for `level` parameter in groupby

- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
* Resolves #579
* Adds a check in the constructor for the index
* Sometimes when we pass a QueryCompiler object to the constructor, it's
not oriented correctly. We have to transpose the data if we want to
ensure it is correct. This corrects the check for whether or not we
need to transpose to be more correct and robust.
> Fix single-column DataFrame index on MapReduce operations

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
* Resolves #581
* Adds a clause that avoids extra computation by transposing back and swapping
`columns` and `index` parameters, then transposing back
> Fix drop after transpose

- modin/pandas/concat.py
- modin/pandas/test/test_concat.py
* Resolves #562
* Adds support for empty DataFrames in concat
* Adds support for Modin distributed Series in concat
* Cleans up concat.py
* Add tests for concat
> Add support for concat with empty DataFrames and new Series

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
* Resolves #586
* If it is not a numpy dtype, it will throw a `ValueError`, which is
caught and we then just use the value passed. We can pass a string to
the compute kernels.
> Fix `astype` with `"category"` as the type passed

- modin/pandas/series.py
- modin/pandas/test/test_series.py
* Resolves #590
* For Series boolean indexers, we convert to pandas first because it is
faster than looping through.
> Fix Series.__getitem__ for bool indexers and slices

- modin/backends/pandas/query_compiler.py
* Resolves #592
* PandasQueryCompilerView does not need a different way of determining
the `dtypes` of a View object, the code was duplicated
> Remove unneeded duplicate code in child class of PandasQueryCompiler

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
* Resolves #588
* Adds a `prepare_method` call before binary operations to ensure they
are correctly operated on remotely
> Fix binary operation after transpose

- modin/data_management/factories.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/pandas/io_exp.py
Add parameter to limit parallel read_sql connections to the minimum of max_sessions, now it is only limited in cpu count.
#455
> Add parallelism parameter to read_sql() #455

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
Sets `__getitem__` to default to pandas if the dataframe is empty
#595
> Fix indexing on empty_series

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
* Resolves #599
* Adds a clause similar to other functions to perform the operation
across the opposite axis
* Create a parameter for `_is_transposed` flag in the constructor
* Simplify `transpose` logic internally
> Correctly compute `reindex` after a transpose

- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/utils.py
* Resolves #597
* Mimic the error handling/cases of pandas
* Add checks for UDFs which use args/kwargs
* Add `str` to the tests for `apply`
* Remove those from `DataFrame.apply` tests because of #469
> Correctly apply Series functions element-wise for correct cases

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
Removes the dtype checking if one of the objects being compared is a scalar
> Fix dtype checking if other is a scalar

- modin/engines/ray/pandas_on_ray/io.py
… on parquet
The change allows you to use predicate pushdown with parquet with the use of filters kwarg.
#636
> Replace read_pandas with ParquetDataset to support predicate pushdown

- modin/backends/pandas/query_compiler.py
- modin/pandas/indexing.py
* Resolves #610
* Adds a fastrack to lists of columns and boolean indexers
> Support boolean indexers and other properties in `loc`

- modin/engines/ray/generic/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
* Move `ParquetDataset` functionality to experimental
* Filter columns read in the partitions when there is at least one partition column
* Resolves #642
> Fix Parquet reader for partitioned files

- modin/pandas/test/test_io.py
Remove extraneous teardown module
> Remove extraneous teardown module for parquet

- docs/using_modin.rst
- examples/cluster/aws_example.yaml
- modin/backends/pandas/query_compiler.py
- modin/pandas/__init__.py
Changes how modin is initialized in a cluster environment and provides a sample script for launching a ray autoscaled cluster in aws. 
This is a first pass so there are still lots of work needed to be done before this is ready for proper workloads but it is in a working state.
#660
> Initial ray autoscaler support

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
`memory_usage()` for transposed dataframes was broken. This fixes the error
> Fix memory_usage() for transposed dataframes

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
> Improve performance of Groupby

- modin/backends/pandas/query_compiler.py
* Resolves #675
* Adds some logic on how to handle the `transpose` case when left is
transposed
* If right is transposed, internally that case is already handled.
> Fix binary operations after transpose

- modin/backends/pandas/query_compiler.py
* Resolves #680
* Adds a condition similar to other transpose handling that changes the
axis
> Fix `concat` when QueryCompiler is transposed

- modin/pandas/concat.py
* Resolves #683
* Adds logic to handle edge case where keys is not None and all objects
are Series.
> Fix `concat` with all Series and axis=1

- modin/engines/ray/generic/frame/partition_manager.py
* Resolves #692
* Checks that each object is an integer for `width()` or `length()`
* If not, calls `ray.get` on it.
> Fix how we compute the block_widths/lengths after single update

- modin/engines/base/frame/partition_manager.py
* Resolves #690
* Previously we were always triggering computation on the first
partition, but now we filter it out if there is nothing to compute.
> Fix internal indices calculation for non-compute partitions

- modin/backends/pandas/query_compiler.py
Checks to make sure that the calls are not empty
Resolves #685
> Fix dtypes on empty dataframes calls to to_pandas

- modin/backends/pandas/query_compiler.py
- modin/data_management/utils.py
- modin/engines/base/frame/axis_partition.py
- modin/engines/base/frame/partition_manager.py
- modin/pandas/dataframe.py
* Resolves #696
* Doesn't require repartitioning every time
* Create a fasttrack for the case where partitioning is already aligned
* Change the concat functionality internally to make all indices align
* This is possible because we track metadata separately
* Reduce adding new columns from products of old columns take 10's of ms
> Improve performance of __setitem__ on new column

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
* Resolves #698
* Correctly creates a new DataFrame based on the QueryCompiler instead of the DataFrame object itself
* Adds conditional checking for MultiIndex when `axis=0` and `axis=1`.
* Add tests
> Fix sorting for MultiIndex

- modin/engines/ray/generic/io.py
* Resolves #694
* Alias the tables as 'foo' because this is a requirement for postgres
> Fix parallel read_sql on Postgres tables

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
Changes how `fillna` is applied to the partitions depending on the arguments being passed in
> Improve fillna performance depending on arguments passed in

- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
* Returns the length and width of each partition to the partition so it
doesn't have to be recomputed
* Reduces the overhead of 2 additional tasks to compute this data
> Add metadata to be returned by operations along entire axis

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/axis_partition.py
> Add fix for axis_partition operations after a join/concat

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
The index calculation for `add` did not account for the fact that `add` would increase the number of columns.
#708
> Fix index mismatch for add

- modin/engines/base/frame/partition.py
- modin/engines/python/pandas_on_python/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/pandas/test/test_dataframe.py
These changes add an abstract `to_numpy` method to the `BaseFramePartition` class and implement it in the `PandasOnRayFramePartition` class.
> Add to_numpy method

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/backends/pyarrow/query_compiler.py
- modin/engines/base/frame/partition_manager.py
- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
Add the to_numpy method to the BaseFrameManager, Python and PyArrow QueryCompiler and the BaseDataFrame.
> Add to_numpy to Frame Manager, Query Compiler, and BaseDataFrame

- modin/pandas/base.py
* Resolves #738
* Fixes the default behavior to return the correct object and not
error
> Default to pandas on MultiLevelIndex `reset_index`

- modin/engines/ray/generic/io.py
- modin/pandas/test/test_io.py
Workaround for unclosed socket warning caused by s3fs during testing.
> Temporarily patch s3fs unclosed socket warning issue

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
Calling `df.count()` with specified level on a MultiIndex DataFrame will default to the Pandas implementation instead of raising an error.
> count with level defaults to pandas

- modin/pandas/__init__.py
Add a function to be ran right after ray.init to move manipulate `sys.path` such that standard libraries have higher priority than site-packages. 
Resolves #647, Resolves #746
> Resolves Typing in Python3.7 Issue

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/engines/ray/generic/io.py
* Renaming methods to be more accurate.
* `fold` is a better name than `map_full_axis`.
> Rename `map_full_axis` style functions to `fold`

- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves #764
* No longer try to serialize a `Series` object when assigning a new
column
* Convert the value to a pandas Series to reuse current logic for
setitem
* In the future we should use the `join` functionality to reduce the
overhead of `setitem`
> Fix issue where assigning a column value to overwrite a column

- modin/engines/ray/generic/io.py
* Resolves #741
* Add a warning to users to let them know that the parallel
implementation requires the string so Modin can create the connections
to the database.
> Add a warning message when passing a SQLAlchemy connection object to read_sql

- modin/pandas/groupby.py
* Resolves #734
* Adds a function that contains the correct name instead of using an
anonymous lambda.
* User will now see:
```
UserWarning: `DataFrame.groupby_on_multiple_columns` defaulting to pandas implementation.
```
> Add better defaulting to pandas message for `groupby`

- modin/pandas/dataframe.py
Pandas changed the default to 10 lines in the most recent release. We don't need to fetch so much data anymore
> Reduce the amount of data we deserialize to match pandas

- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #758
* Update the index extraction to be correct (bug: axis=1 -> 0)
* Send the level name to the partitions if it is specified
* Don't always default to pandas when a MultiIndex is the grouping axis
> Update components of groupby when level is being used

- modin/pandas/dataframe.py
- modin/pandas/test/test_groupby.py
* Resolves #783
* Updates error checking to allow multiple level values to be passed
for the `by` parameter as long as they are included in `names`.
* Add tests for checking this behavior matches pandas
> Support multiple `names` values for groupby on MultiLevelIndex

- modin/experimental/engines/pyarrow_on_ray/io.py
* Resolves #793
* Moves the pyarrow import after ray to use the pyarrow ray ships
> Move pyarrow import after Ray

- modin/backends/pandas/query_compiler.py
* Resolves #747
* No longer assume more than one row in the data
* Change the squeeze on the `by` parameter to only squeeze along the
opposite axis as the groupby.
> Fix `groupby` + `reduce` for partitions with only 1 row

- README.md
- docs/UsingSQLonRay/index.rst
- docs/using_modin.rst
Fixup broken documentation link and while at it convert http urls to https
> Fixup a broken docs link

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/pandas/test/test_dataframe.py
* Resolves #790
* Wrap the result of `apply` in a `pandas.DataFrame` to correctly use
the results to compute metadata
> Fix `DataFrame.apply` when the result of the `apply` is a `Series`

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
* Resolves #798
* Slices using pandas logic on an intermediate pandas object to compute correct
offsets
* Add tests for both datetime and regular slices
> Fix slicing issue for datetime and other objects

- modin/engines/dask/pandas_on_dask_futures/frame/partition.py
This commits empties the `call_queue` after calling `partition.drain_call_queue` for the dask backend.
#809
> Empty call queue after drain_call_queue for dask backend

- docs/requirements-doc.txt
* Resolves #810
* Adds `[all]` target to modin install from pip
> Fix build issue for documentation

- modin/engines/base/frame/data.py
* Resolves #817
* This is a common usecase, where the partitioning is already aligned
* Performance is improved significantly, operations that took O(10s) are taking 300ms
* Properly propagate metadata to further improve performance
> Add fast path for `concat` when the axes and partitioning is aligned

- modin/engines/base/frame/data.py
* Resolves #816
* Only passes `dtypes` through if they have been computed
* Several operations that do not have a `dtypes` inferred or passed through
will be positively affected by this.
> Remove dtype requirement from `head`, `tail`, etc.

- .coveragerc
- .travis.yml
- modin/__init__.py
- modin/pandas/__init__.py
- requirements.txt
- setup.py
* Resolves #821
* Introduces a new hack which overrides ray's memory util
> Update Ray version to 0.7.5

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
* Removes a lot of unneeded code from implementation
* Moves some of the pandas-specific metadata changes to the API layer
* Names the result if it is a `Series`
> Adding `quantile` to list of Reductions

- modin/data_management/factories.py
- modin/engines/base/io.py
- modin/pandas/dataframe.py
- modin/pandas/utils.py
* Resolves #807
* Adds a BaseFactory method to create a DataFrame from a non-pandas object
* New query compilers are free to override the BaseIO functionality, which only returns None
* If the query compiler only has certain types of data customized, it can still return None
for the not-yet-implemented types.
* If there is no custom way of handling the type provided, we just default back to the pandas
DataFrame behavior and use `from_pandas`
> Adding hooks to be able to custom distribute non-pandas objects

- .coveragerc
- .travis.yml
- modin/__init__.py
- modin/pandas/__init__.py
- requirements.txt
- setup.py
Reverts modin-project/modin#822.
I ran into several bugs that exist in earlier versions of Ray when using exceptionally large nodes. It appears that Ray is not equipped to deal with these nodes in newer releases, so we are rolling back to a version we have found to be more stable.
> Revert "Update Ray version to 0.7.5"

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
Refactored code supporting the `level` argument in `count`.
Added support for the `level` argument for:
* `any`
* `all`
> Add support for level argument in any, all

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_groupby.py
* Resolves #837
* Add logic for handling unnamed levels for both aggregations and `groupby`
* Clean up some of the implementations.
* It should be possible to drop the `DataFrame._handle_level_agg` now.
* Remove unnecessary logic in `DataFrame.groupby` that deals with `level`
* Add additional check for `DataFrameGroupby._is_multi_by` with `is_list_like`
* Remove defaulting to pandas logic if `level` is set. We no longer need this.
> Fix level parameter for aggregations when names are `None`

- modin/pandas/series.py
- modin/pandas/test/test_series.py
* Resolves #839
* Adds additional syntax for checking that the value returned by
`pandas.isnull` is `True`. This is because list values are unpacked
by `pandas.isnull` and will be returned as a list. The fix is to just
add `is not True` instead of just `not`.
* Add tests to avoid regressions.
* Additional test for creating a list from a non-list object.
> Fix `map` and `apply` over a `Series` that contains list values

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_reshape.py
* Resolves #842
* Instead of using `fold`, which maintains metadata from the previous
object, we must use `apply`, primarily because it will recompute the
metadata (columns) at the end.
* Added to the tests to verify that the behavior no longer exists.
> Fix metadata computation for `get_dummies`

- modin/data_management/utils.py
Remove an unused util function (if remember correctly, introduced by me 😄)
- [n/a] tests added and passing
> Remove legacy datamanagement/utils/_get_nan_block_id

- ci/travis/install-dependencies.sh
- modin/pandas/base.py
Code in master does not pass formatting checks with
latest black version (19.10b0).
* Reformatted black 19.10b0.
* Ensure that black and flake8 are up to date in CI,
even if using caching.
- ~[ ] tests added and passing~ (N/A)
> ci: upgrade linters (flake8, black)

- .github/workflows/ci.yml
Adds [GitHub Actions](https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-github-actions) support.
It currently runs everything that is setup with `.travis.yml`, and adds Python 3.7.x to the build matrix.
See an example run here: https://github.com/smola/modin/commit/391596d961039cdf4358c675de424b80fa54ae6c/checks?check_suite_id=290849650
* Higher [usage limits](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#usage-limits) than Travis: 20 concurrent jobs with 6 hours timeout per job. This allows to finish a full run in less than 40 minutes, even adding an additional Python version to the build matrix.
* Integration of results right in GitHub.
* Apparently better performance per worker.
* …
> [WIP] add GitHub Actions workflow for CI

- modin/pandas/series.py
- modin/pandas/test/test_series.py
* re._pattern_type was removed in Python 3.7. re.Pattern can be used
instead.
* Try re.Pattern first, and fall back to re._pattern_type otherwise.
- ~[ ] tests added and passing:~ Not applicable, tests are present, but they need to run with Python 3.7.
> fix for Python 3.7: re._pattern_type no longer exist

- modin/engines/base/frame/data.py
* Resolves #852
* Changes where we do the cumulative sum, no longer incorporating INT_MAX into the sum result
> Fix integer overflow when doing a mask for Windows users

- modin/pandas/__init__.py
- requirements.txt
- setup.py
> Upgrade to pandas 0.25.3

- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/pandas/test/test_dataframe.py
* Resolves #865
* Allows repartitioning to only happen if the number of input partitions
exceed the number of cores.
* Maintain partitioning schema if the number of partitions is less than
the number of cores.
* Add tests to verify this behavior is corrected.
> Fix issue where partition metadata would be off after insert + window

- modin/engines/base/frame/data.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
* Resolves #864
* Forces Modin to compute the dtypes in the case of categorical in
`astype`. It is not currently possible (and may never be) to determine
what the categories would be before computing the `astype` in the
partitions.
* Adds tests specific to the `CategoricalDtype` for `astype`.
> Fix issue for updating to Categorical Dtypes from `astype`

- modin/backends/pandas/parsers.py
- modin/engines/base/frame/data.py
- modin/engines/ray/pandas_on_ray/frame/data.py
* Resolves #874
* Creates a new utility in the pandas parsers that overrides the default
behavior
* Union the values in the `categories` field of `CategoricalDtype` list
to merge the values
* Set `ordered` to `True` if all are ordered, else `False`
* Issue created in pandas to fix the behavior in pandas:
pandas-dev/pandas#29980
> Correctly merge `CategoricalDtype` dtypes

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
* Resolves #876
* Convert all DataFrame and Series arguments to pandas when doing a
pandas default implementation
* Add tests
> Fix issue where certain arguments were not defaulting to pandas

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
this is an implementation of `Dataframe.duplicated()` that also adds support for `Series.drop_duplicates()` and `Dataframe.drop_duplicates()`.
It transformes either one to a single column `Dataframe` and checks for duplicates using `Dataframe.apply()`
#634
> support for duplicated() and drop_duplicates()

- modin/engines/base/io/file_reader.py
- modin/engines/base/io/text/csv_reader.py
- modin/engines/base/io/text/json_reader.py
* Resolves #882
* Extracts full path and sends that to workers to avoid issues where
the driver process changed directories but the children had not.
> Send full path to workers on `read_csv`

- modin/pandas/series.py
* Resolves #885
* Get rid of deprecated functionality
> Remove `__array_prepare__` from Series API

- modin/backends/pandas/query_compiler.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
* Resolves #887
* Add Series.str.title to API
> Add Series.str.title to API

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves #891
* Force transposes a DataFrame before it is passed to the Series constructor
when `axis=0`.
* Previous implementation assumed that there would be >1 row and that
the Series constructor logic could handle the transpose if necessary.
> Fix `df.squeeze` when `axis=0` on a 1x1 dataframe

- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
* Resolves #878
* Create a `SeriesGroupBy` object that intercepts every call to the
`SeriesGroupBy` object, applies it to the pandas object, then
re-distributes the object if it is a `pandas.Series` or a
`pandas.DataFrame`. This is a temporary measure until we can implement
a `SeriesGroupBy` object with all of the methods.
* This issue originally surfaced with issues handling interactions
between pandas and modin Series objects.
* A further pass is required to remove other cases where Modin can
return a pandas object.
> Create SeriesGroupBy wrapper to default to pandas and return to Modin

- requirements.txt
- windows_test_requires.txt
> Change Coverage version to avoid sqlite3 errors

- modin/engines/base/io/text/csv_reader.py
- modin/pandas/test/test_io.py
* Resolves #897
* Adds logic to handle `skiprows` for all cases
* Removes unnecessary logic that added to `read_csv` runtime
* Add tests
* Add logic for weird pandas edge case with `names` and `skiprows`
> Fix `skiprows` logic for `read_csv`

- modin/pandas/io.py
- modin/pandas/test/test_io.py
In `modin.read_sql()` when `chunksize` is given, the operation will default to `pandas.read_sql()`. The returned instance will be wrapped as an a generator of `modin.Dataframe`.
#909
> read_sql() will default to pandas when chuksize is given

- modin/engines/base/io/text/csv_reader.py
Reverts modin-project/modin#922
Due to testing changes this no longer passes.
> Revert "Remove top of file import for `py`"

- modin/__init__.py
* Resolves #944
- ~[x] tests added and passing~
> Restructure import attempt to only try Ray if on a non-windows machine

- modin/pandas/test/test_io.py
> Fix pyarrow.parquet import in tests

- modin/engines/ray/generic/io.py
- modin/pandas/io.py
* Resolves #949
* Removes the duplicated line and fixes in one place
> Fix DeprecationWarning: invalid escape sequence \d

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
* Resolves #915
* Send `args` as another keyword argument instead of unpacking the tuple
* Add tests to verify correctness of fixed functionality
> Fix `apply` when `args` is set

- run-tests.sh
* Resolves #958
* Support passing in an engine/test suite
* Also supports parameters to be passed to pytest e.g. -k, -v, -x, etc.
> Support parameters with run-tests.sh

- modin/pandas/__init__.py
* Resolves #954
* Increases the number of workers for Dask to the number of cores
> Increase `n_workers` for Dask from default to number of cores

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/pandas/test/test_dataframe.py
* Progress toward #853
* Adds more tests to the matrix to take better advantage of concurrent
builds
* Classify tests into categories better
> Make test_dataframe.py more granular with test suite

- modin/backends/pandas/parsers.py
- modin/pandas/test/test_io.py
* Resolves #976
* Change default value in `kwargs.get` to match pandas
* Add parametrized test for `encoding` with a variety of new encodings
> Fix bug where certain encodings were throwing an error

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
* Resolves #982
* Adds clause for operations that default to pandas that do not return
any value
* In these cases, we build the object based on the class name of the
object in pandas
* Add some error checking cases to the default code
* Add more test cases for the emtpy dataframe case.
> Fix inplace operations without inplace keyword on emtpy dataframes

- modin/pandas/dataframe.py
* Resolves #898
* Pre-compute the number of columns based on the width of the column
names
* This guarantees that we will get at least as many columns from the
partitions as we need.
* Compute width using pandas utility to match the behavior
* Tested locally to verify behavior
> Support console with __repr__ like pandas

- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #75
* Adds support for grouping by multiple columns.
* Does this grouping by broadcasting the columns.
* A preliminary performance evaluation shows that it is significantly
faster than before, but still has some room for improvement.
* Minimal code changes to add this new feature.
* We still default to pandas when the user is looping over the dataframe
* Even though this is common, it is exceptionally hard to optimize,
and out of scope for this PR.
> Add support for grouping by multiple columns when doing a reduction

- docs/UsingPandasonRay/dataframe_supported.rst
- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
* Resolves #999
* Adds implementation for `droplevel for `Series` and `DataFrame` by
creating a copy of the object and assigning the new index/columns to
the copy.
* Update tests
> Add implementation for `droplevel` for `Series` and `DataFrame`

- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
* Resolves #1023
* Add condition to keep fastpath for __getitem__
* Reroute to `iloc` to handle the slice in one place
* Add test
> Fix bug in `loc` where slice on columns only threw Exception

- modin/engines/base/io/text/csv_reader.py
- modin/engines/base/io/text/text_file_reader.py
- modin/pandas/test/data/newlines.csv
- modin/pandas/test/test_io.py
* Resolves #1008
* Fast-forward to end of quotes when figuring out the partition offsets
* Add test and testfile
> Fix bug where Parsing error was thrown when text spanned multiple lines

- .github/workflows/ci.yml
- .github/workflows/push.yml
- pytest.ini
- run-tests.sh
* Previously ran into errors with too many changes, this resolves that
* Still update the testmon files in S3
* Force run certain tests no matter what
> Update Test infrastructure to use testmon when possible

- modin/engines/base/io/file_reader.py
* Resolves #1037
* S3FS does not allow capitalized S, so we change it to lower case
* Tested locally
> Fix opening a file from s3 when S is capitalized

- modin/pandas/datetimes.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
* Resolves #1034
* Restructure defaulting to pandas code
* Add tests for dataframe, series, and other types
> Fix pd.to_datetime when using a Series object.

- modin/__init__.py
- setup.py
* Resolves #1043
* Adds a dependency packaging to enable simpler version comparison
> Fix issue with Dask engine where users were not able to use Dask 2.10+

- modin/pandas/__init__.py
* Resolves #1046
* Allow users to choose their pandas version, but mention that it's not
supported
> Change Error to warning for pandas version pin

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves #1069
* Change the way we treat the object immediately
* First treat as `DataFrame`, then try to `squeeze`
* This has the benefit of not needing to look at the index from the
API layer
* Add simple unit tests
> Fix column indexing when 2 or more columns have same name

- modin/pandas/series.py
- modin/pandas/test/test_series.py
Resolves #1083 
Split from #1078
> Fix Series.__getitem__ to accept a callable as key

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
DataFrame.rename() will now change column names if `mapper` and `axis=1` are provided as parameters, and axis names of `mapper` and `axis=0` are provided
Resolves #1056
> df.rename works with 'mapper' and 'axis' params

- modin/pandas/__init__.py
> Add randomly generated redis password for Ray by default

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/__init__.py
- modin/data_management/functions/binary_function.py
- modin/pandas/base.py
* Resolves #1064
* Add a new function type for internal query compilers
* `BinaryFunction`
* Enumerate the binary function calls into the query compiler
* Code quality updates and organization
> Make query compiler interface consistent for binary ops

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
* Resolves #1108
* Fixes parameter passed to the query compiler layer
* Add tests for `fill_value`
> Fix `fill_value` parameter for `DataFrame.sub`, other binary ops

- pytest.ini
> Add cov flags to pytest.ini so coverage is always computed

- df_test_requires.txt
- docs/using_modin.rst
- modin/pandas/__init__.py
- modin/pandas/test/test_api.py
- requirements.txt
- windows_test_requires.txt
* Resolves #1136
* Parallel testing will be done through xdist
* pytest-xdist added to requirements.txt
* TeamCity testing will use 1 CPU for Modin and Ray to aviod concurrent
test issues.
> Add MODIN_CPUS env variable for command line CPU specification

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/utils.py
- DataFrame.drop_duplicates correctly identifies subset type now
- Check for Series type in DaraFrame.apply is done not based on presence
of "name" attribute any more.
> Fixed #1115

- .github/workflows/ci.yml
- .github/workflows/push.yml
* Resolves #1149
* Removes tests from the Ubuntu line that are already done in TeamCity
* Keep tests for Windows since we do not have that setup yet in TeamCity
* Lint and API checks are now mandatory before every other PR test runs
> Update GitHub Actions to remove those tests run on TeamCity

- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_series.py
* Resolves #1114
* Uses `DataFrameGroupBy` object for implementation and squeeze the
result to a Modin `Series` object after operator.
* Implementation overrides `__getattribute__` and intercepts method
to apply and `squeeze` the return value before it is returned to the
user
> Add Implementation for `SeriesGroupBy`

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/binary_function.py
- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/engines/dask/pandas_on_dask_futures/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
Evaluating the performance, this PR represents a 4-5x improvement over previous implementation for `df.add(df["col0"], axis=0)` and other binary functions.
> Add parallel support for binary functions with Series `other`

- modin/backends/base/query_compiler.py
I was having a look at the query compiler, and thought it could be a good idea to use a Python ABC. So an exception is raised if children is missing one of the methods, and it's also more readable.
After changing that, I realized and made couple of adjustments:
- `isnull` and `notnull` wheren't being implemented, I made them aliases of `isna` and `notna` in the base class
- `to_datetime` was listed as a reduction. I think pandas provides just as a helper, and it's not part of the dataframe API. Removed it here.
- `squeeze` was not implemented in the pandas query compiler, I made it explicit in the pandas compiler itself.
- `binary_op` is implemented in the base class, but not in the pandas query compiler, where individual methods are defined. I added a comment, and make the method call …
> Make query compiler base class a Python ABC

- modin/pandas/__init__.py
Attempt to address issues raised in https://github.com/ray-project/ray/issues/7879
> Add temporary fix for ray import pandas race condition

- modin/__init__.py
- modin/engines/base/frame/data.py
- modin/pandas/dataframe.py
Updated imports to use official api packages instead of unofficial deprecated ones.
> Fixed #1368. Import official api packages instead of deprecated

- docs/release-procedure.md
- setup.py
* Resolves #1123
* Adds logic in setup.py to handle different operating systems and
ensure that we upload wheels with proper targets for the operating
system being used.
* Add documentation for release on how to handle the upload of these
wheels.
* Include logic to handle the developer case where they would like to
install with `modin[all]` on Windows without building a wheel for
upload.
> Choosing depedencies for `pip install modin[all]` based on platform

- modin/pandas/dataframe.py
- modin/pandas/indexing.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
* Resolves #1166
* Resolves #1167
* Resolves #1374
* Handle case where DataFrame is passed index and columns with a Modin
DataFrame object
* Handle case where Series is passed index and name with a Modin Series
* Add error checking for `loc`, which we use to subset the values.
* Add tests
> Make DataFrame and Series behavior match pandas

- modin/pandas/io.py
- modin/pandas/utils.py
* Progress toward #1099
* `import modin.pandas as pd` imported everything, even though the
user only needs top-level objects imported.
* The offender turned out to  be `BaseFactory`
* It was imported at the top of many files
* It triggers the import of all of the distributed components
* Solution: Move `BaseFactory` import inside the functions that use it
* This does not affect performance from my tests
* This improves import time
> Improve import performance and reduce sys.modules

- modin/backends/pandas/parsers.py
- modin/engines/base/io/column_stores/column_store_reader.py
- modin/engines/base/io/column_stores/parquet_reader.py
- modin/pandas/test/test_io.py
* Resolves #1366
* Add a check for the Index columns from the pandas metadata maintained
by parquet.
* Do not assign work for the columns that are actually pandas Index
objects.
* Add tests for this behavior.
Also test for MultiIndex object
> Fix parquet file reading when file was written with pandas Index

- df_test_requires.txt
- modin/engines/base/io/io.py
- modin/pandas/test/test_io.py
- requirements.txt
* Resolves #1398
* Add tests for `read_gbq` and `to_gbq`.
> Fix internal APIs for `read_gbq`

- modin/engines/base/io/text/csv_reader.py
- modin/engines/base/io/text/json_reader.py
- modin/engines/base/io/text/text_file_reader.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
* Resolves #1379
* Adds cases for when we are passed objects strings directly or if we
are passed some IO object. For these cases we default to pandas.
* Add tests to verify behavior
> Fix cases where `read_json` should fall back to pandas

- modin/pandas/__init__.py
This PR turns on LRU eviction. This is a new flag added in recent ray version. By default ray will crash when all the memory is used up while there are references to all the objects. When this flag is turned on, Ray will LRU evict objects with references.
Signed-off-by: simon-mo <xmo@berkeley.edu>
> [Ray] Turn on lru_evict=True to ensure plasma LRU eviction

- README.md
- ci/teamcity/Dockerfile
- ci/teamcity/Dockerfile.modin-base
- ci/teamcity/Dockerfile.teamcity-ci
- ci/teamcity/build-docker.py
When these images are in master branch, we'll be able to switch TeamCity to run all tests in docker containers.
> Add docker images to run TeamCity CI tests

- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
> Changes in column are propagated to dataframe if column belongs to one

- modin/backends/pandas/parsers.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
* Resolves #1452
Change the way we check for `sep=False`. Previously, pandas allowed
`sep=False` for tab delimeted text files. Because we explicitly look for
a `sep` character we converted `sep=False` to `sep="\t"`. We checked
with a line `if not sep` which also evaluated to True when `sep` is
`None`. `sep=None` has a different behavior as outlined in #1452.
> Fix CSV reader when `sep=None`

- modin/engines/base/frame/data.py
* Resolves #1395
In our internal Modin DataFrame, we previously used `mask` to
select rows/columns in the order they were given. The problem here is
that the `mask` functionality was creating potentially thousands of
partitions in an attempt to avoid communication. This killed performance
for all backends, and made operations like `sample` impossible.
Additionally, `train_test_split` from sklearn was impacted and not
usable.
To solve this, I separated the indexing and the reordering into two
separate APIs in the internal DataFrame. This gives us flexibility, but
does not impact performance on the already fast and well supported
indexing of values that are sorted. The result is improved performance
for the case where the `mask` call was also intended to reorder the
columns or rows. Further …
> Separate indexing and reordering in Modin DataFrame

- modin/engines/base/frame/partition_manager.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
Fixed __setitem__ when column has name "index".
Fixed to_records test to catch exceptions (they happen because of
index column).
Fixed python engine when series object contains only 1 partition.
> Fix for #1403. Added test for dataframe with "index" column

- modin/engines/base/io/column_stores/parquet_reader.py
- modin/pandas/test/test_io.py
* Resolves #1451
Previously, we computed metadata for partitioned columns separately.
This was changed so that now partitioned parquet files are computed with
standard parquet files at the same time.
> Fix metadata for partitioned parquet datasets

- modin/backends/pandas/parsers.py
- modin/engines/base/io/__init__.py
- modin/engines/base/io/io.py
- modin/engines/base/io/text/fwf_reader.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
Parallelize `read_fwf` with `FWFReader` and `PandasFWFParser`. 
Note: There is a lot of duplicate code between `FWFReader` and `CSVReader` in order to support `read_csv` arguments for `read_fwf`, probably should look into how we can reduce this.
> Add implementation of read_fwf

- README.md
This more closely reflects what people are often using instead of opaquely giving a percentage.
Signed-off-by: Devin Petersohn devin.petersohn@gmail.com
> Add explicit `read_*` instead of giving percentage

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
> Fixed #1490. New column case is checked first in __setitem__

- .github/stale.yml
* Resovles #1507
* Start with marking at 365 days of inactivity
> Add stale.yml to enable stalebot

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
when as_index is True and a single column name is passed as not a list.
> Fixed #1509. Indexing DataFrameGroupBy should return SeriesGroupBy

- setup.py
> Updated required python version to 3.6.1+

- .github/workflows/ci.yml
- modin/__init__.py
- modin/data_management/dispatcher.py
- modin/data_management/test/test_dispatcher.py
- modin/pandas/__init__.py
- modin/pandas/test/test_api.py
- modin/test/test_publisher.py
Currently most modules are not ready to switch dynamically, will be added later
* Add class that provides Pubish-Subscribe model to enable the possibility to change execution engine or partition format on the fly
* Old `modin.__execution_engine__` and `modin.__partition_format__` are retained for compatibility, will be removed when all parts are migrated
* `modin.pandas` client instantiation and `EngineDispatcher` are fully migrated
> Add Pub-Sub class to enable switching of execution engine on the fly

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
> Fixed bugs #1581 and #1583. Restore frame indexes after shift

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/__init__.py
- modin/data_management/functions/groupby_function.py
- modin/pandas/groupby.py
* Resolves #1062
Instead of passing some opaque functions into the query compiler,
the api layer of groupby has been rewritten to call directly into
some new `grouby_<function>` methods that were also added to the query
compiler.
> Move groupby aggregate functionality into query compiler

- ci/teamcity/comment_on_pr.py
> Fixed bug #1604. Check for word FAILURES in comment before truncating

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
* Resolves #1458
* Change `agg` parameter to `func=None`
While the public pandas API shows `agg` to accept an `arg` parameter
that is not optional, the actual implementation allows for an optional
func parameter instead.
> Match `groupby.agg` to pandas API

- modin/__init__.py
- modin/backends/pyarrow/query_compiler.py
- modin/data_management/dispatcher.py
- modin/data_management/factories.py
- modin/data_management/test/test_dispatcher.py
- modin/engines/base/io/file_reader.py
* Remove legacy `modin.__partition_format__` and make all its users use new PubSub model introduced in #1578
* Handle "experimental-only" factories nicer
* Now all factories do not import their engines immediately, but only when requested. This should shorten import time further from #1385 while allowing to remove some of its effects and also works towards #1099. It also allows to enable switching engines on the fly.
> Make all factories initialize .io_cls lazily

- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
* Resolves #1456
* Add extra check for `slice` when new columns are recomputed
> Fix issue with MultiIndex slicing on columns

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
> Fixed bug #1619. If dataframe.index contains duplicates sort should work correctly

- modin/__init__.py
- modin/data_management/factories.py
- modin/engines/dask/pandas_on_dask/frame/axis_partition.py
- modin/engines/dask/pandas_on_dask/frame/data.py
- modin/engines/dask/pandas_on_dask/frame/partition.py
- modin/engines/dask/pandas_on_dask/frame/partition_manager.py
- modin/engines/dask/task_wrapper.py
- modin/engines/ray/generic/frame/partition_manager.py
- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
- modin/engines/ray/pandas_on_ray/frame/data.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- modin/engines/ray/task_wrapper.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
- modin/experimental/engines/pyarrow_on_ray/frame/data.py
- modin/experimental/engines/pyarrow_on_ray/frame/partition.py
- modin/pandas/test/test_io.py
- modin/test/test_publisher.py
Remove conditions in engine-related parts, as since #1601 they should be imported only when requested engine is activated.
When this set of changes is merged, it should be possible to switch the engine used by Modin on the fly by calling `moding.execution_engine.put('NewName')`.
Note that this PR does not implement any validation yet, and on-the-fly switching is yet untested - all those are questions for later.
This set basically completes _enabling_ of dynamic switching, but so far it just retains the current behaviour.
> Make all engine-related imports unconditional, as engines are imported lazily now

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
> Fixed #1412, losing dtypes when constructing DataFrame

- modin/pandas/dataframe.py
- modin/pandas/indexing.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
Implemented correct Series assignment to DataFrame parent depending on
which axis was used for indexing.
> Fixed #1675. Added setting parent in loc and iloc

- modin/engines/base/frame/data.py
- modin/pandas/test/test_dataframe.py
> Fixed #1678. Added missing default case in dtypes translation

- modin/backends/pandas/parsers.py
- modin/engines/base/io/__init__.py
- modin/engines/base/io/text/excel_reader.py
- modin/engines/dask/pandas_on_dask/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/pandas/test/test_io.py
* Resovles #1298
Implementation at a high level:
* Parse header on driver.
* Compute partition offsets based on chunks. Ensure that entire rows are
read by detecting `</row>` closing tag.
* Send header and args to each partition.
* Create fake spreadsheet with header and subset of rows.
* Parse with openpyxl.
* Create dataframe from parsed sheet with pandas.
Currently not implemented:
* Multiple sheets
* `engine` specified as anything but `openpyxl`
* Python 3.6 - need `Zipfile` capabilities only available in 3.7+
> Add parallel read_excel feature

- modin/__init__.py
- modin/data_management/test/test_dispatcher.py
Previously added `Publusher` mechanism lacked the ability to change the _pair_ of engine and partition, which might lead to a case when changing from one pair to another is impossible (each pair must have a corresponding factory, which means that to switch from pair AxB to CxD either AxD must exist or CxB, and user must know which exists).
This newly added method defers callbacks execution until both elements are changed, thus we only require that final pair is valid.
> Implement a method to switch a pair of engine and partition

- modin/engines/base/io/text/text_file_reader.py
- modin/pandas/test/test_io.py
This PR updates the `call_deploy` method on `TextFileReader` to handle an edge case where an odd number of quotes in a file causes an infinite loop.
In addition, the entire quoting check is skipped if `csv.QUOTE_NONE` or `3` are passed as arguments to the `quoting` variable of `read_csv`.
> Correctly handle mismatched quotes and csv.QUOTE_NONE flag.

- requirements.txt
Signed-off-by: amyskov <alexander.myskov@intel.com>
The last versions of Distributed and Dask (versions 2.20.0) packages causes CI fails of Modin, so these packages were downgraded to the previous versions (2.19.0).
> Fix CI failures on Dask/Windows

- examples/cluster/experimental_cloud.py
- modin/experimental/cloud/__init__.py
- modin/experimental/cloud/base.py
- modin/experimental/cloud/cluster.py
- modin/experimental/cloud/connection.py
- modin/experimental/cloud/ray-autoscaler.yml
- modin/experimental/cloud/rayscale.py
* Add `modin.experimental.cloud` package that will be dealing with spawning clusters in a cloud
* Implement spawning a cluster using Ray autoscaler (based on https://github.com/modin-project/modin/pull/1659)
* Implement making an RPyC connection to spawned cluster to enable running things remotely
**Notes**:
- Requires https://github.com/ray-project/ray/pull/8833 to be merged if SSH through proxy is needed
- Merging it alone won't complete the "Modin in the cloud" story, there is a separate tracker for that: https://github.com/modin-project/modin/issues/1701
> Implement cluster spawning API

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
> Move logic of `sort_values` into the query compiler

- modin/engines/base/frame/data.py
- modin/engines/dask/pandas_on_dask/frame/partition.py
- modin/engines/python/pandas_on_python/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/pandas/indexing.py
* Resolves #1752
* Resolves #1728
> Improve performance of slice indexing

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- commitlint.config.js
- docs/contributing.rst
> TEST-#1759: Add commitlint check on pull requests

- modin/pandas/base.py
Sub PR of #1718 , function implementation slightly changed in order to better match Pandas behavior.
> REFACTOR-#1741: Use low-level api for kurt function implementation with defined level parameter

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/binary_function.py
- modin/data_management/functions/groupby_function.py
- modin/engines/base/frame/data.py
- modin/engines/ray/generic/io.py
- modin/pandas/groupby.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
Initially, this PR was fixing that `to_pandas` in pandas backend does not consider information about indices/columns of modin frame, only from partitions. But after that fix many tests started to fail because `df_equals`, that uses in many tests, use `to_pandas` to convert modin frame to pandas and then compare it with an expected result. It revealed that many operations returns modin frame with incorrect indices, so this PR is also fixing all of them.
> [FIX] Fix of inconsistent indices #1726 #1731 #1732 #1734

- modin/backends/pandas/query_compiler.py
- modin/data_management/utils.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
These changes move out the logic of `merge` and `sort_index` from API layer into the query compiler, fix incorrect computing of `row_lengths` and `column_widths` as well.
> REFACTOR-#1763: Move logic of `merge` into the query compiler

- commitlint.config.js
> TEST-#1785: Change size of commit message header

- modin/pandas/indexing.py
- modin/pandas/test/test_dataframe.py
> FIX-#1775: Add support for callable in `loc`/`iloc`

- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
> FIX-#1556: Fix support for nested assignment with `loc`/`iloc`

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/pandas/test/test_concat.py
> FIX-#1700: Fix metadata for concat and mask when `axis=1`

- modin/pandas/concat.py
- modin/pandas/test/test_concat.py
- stress_tests/kaggle/kaggle12.py
> FIX-#1631: Fix support for dictionary in `pd.concat`

- modin/pandas/test/test_dataframe.py
> TEST-#1119: Re-enable skipped Windows tests for `DataFrame.prod`

- modin/pandas/test/test_dataframe.py
Reverts modin-project/modin#1801
> Revert "TEST-#1119: Re-enable skipped Windows tests for `DataFrame.prod`"

- docs/architecture.rst
Signed-off-by: ikedaosushi <ikeda.yutaro@gmail.com>
I fixed the missing links in the documentation.
> DOCS-#1809 missing links in the architecture page

- .github/workflows/ci.yml
- .github/workflows/push.yml
This should (hopefully) fix Ray testing on Windows in CI and after pushes to master, as they currently turned red.
Tests start to run locally on my laptop after this change (and they didn't prior to it because Ray was told to allocate 20 GB of storage (out of my 32 GB of RAM) but my guess is Ray tried to allocate those on my disk which has less free space than 20 GB).
> TEST-#1779: Limit object store to 1GB during CI tests

- modin/__init__.py
- modin/pandas/__init__.py
There are cases where callback order matters. For instance, whenever we import `pd.DataFrame` the engines must be initialized.
This is especially needed for implementing a "remote Ray" engine (which will be initialized separately).
> FIX-#1803: Change the order of execution engine change callbacks

- modin/experimental/cloud/cluster.py
- modin/experimental/cloud/rayscale.py
* Fix ability to specify availability zone for a provider
* Add ability to specify image id for a provider
> FIX-#1807: Fix passing zone in rayscale, add ability to override image

- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
Fixing that `Series.reset_index` does not consider `name` parameter
> FIX-#1457: Series.reset_index considering 'name' fix

- modin/pandas/base.py
- modin/pandas/test/test_series.py
> FIX-1708: Don't sort indexes in Series functions with level parameter

- examples/cluster/mortgage-runner.py
- modin/data_management/factories.py
- modin/engines/ray/utils.py
- modin/experimental/cloud/connection.py
- modin/experimental/cloud/meta_magic.py
- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/rpyc_proxy.py
- modin/pandas/__init__.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/pandas/test/test_api.py
This enables the story of scaling out Modin on cloud-based clusters.
Mortgage benchmark from https://github.com/intel-go/omniscripts/ could now be run using provided runner.
**Note**: this is a replacement for https://github.com/modin-project/modin/pull/1750
> Enable running remote Ray on spawned cluster

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/pandas/test/test_series.py
> FIX-#1729: Fix incorrect result of `Series.dt.components/freq/tz` 

- examples/cluster/taxi-runner.py
> DOCS-#1835: add runner of taxi benchmark as example

- modin/data_management/factories.py
- modin/experimental/cloud/connection.py
- modin/experimental/cloud/rpyc_proxy.py
* Cache remote class types of known classes (RPyC by default reconstructs them upon each call)
* Use more efficient "batching" `.deliver()` which transfers all arguments in a single RPyC call instead of one call per argument
* Override inspecting certain classes, cache some getting attributes, hashes and strings for known static-ish items in `numpy`
* Obtain as local tuple the results of calling `DF.dtypes.items()` and `DF.dtypes.iteritems()`, as iterating over a remote connection introduces a lot of latency.
> Speed up RPyC connection

- examples/cluster/mortgage-runner.py
- examples/cluster/taxi-runner.py
- modin/data_management/factories.py
- modin/experimental/pandas/__init__.py
- modin/experimental/pandas/numpy_wrap.py
This replaces `numpy` module whenever a user code executes `import numpy` with a special class that returns different things in local and remote contexts.
It also registers special reducers (support for pickling), as, when trying to pickle an object from "local" numpy when "remote" is activated leads to `TypeError: different class` without special reducer.
Note that access to `numpy` is always local for `modin.*` and `pandas.*` packages, as NumPy is used internally there and is not needed to be proxied to the remote.
> Implement numpy autowrapping in remote context

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> FIX-#1464: product/sum incorrect behavior of 'min_count' fixed

- modin/pandas/dataframe.py
- modin/pandas/test/test_groupby.py
My attempt (may or may not be correct!) to fix the issue where `groupby()` blows up if the `by` includes a column from the DataFrame rather than the name of the DataFrame.
> FIX-#1770: Support for groupby() with original Series in by list.

- modin/data_management/test/test_dispatcher.py
- modin/pandas/__init__.py
* Add a registry of known engines that don't require initialization.
* Register stub engines used in `test-internals` prior actually running the tests
> FIX-#1852: Add stub engines to known ones during test-internals

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_dataframe.py
> FIX-#1857: make 'sort_index' consider axis parameter

- requirements.txt
- requirements/env_windows.yml
- setup.py
> FIX-#911: Pin Dask Dependency for Python 3.8 compatiblity

- .gitignore
- modin/experimental/cloud/meta_magic.py
- modin/experimental/cloud/rpyc_proxy.py
The root cause for #1873 was that `RemoteMeta` was returning wrongly-bound `__new__` method - `object.__new__` instead of `type.__new__` (because of it being retrieved via `object.__getattribute__(self, name)` instead of `type.__getattribute__(self, name)`).
As a metaclass (`RemoteMeta` in this case) is a descendant of `type` it should be using `type.__getattribute__()` to get attributes from itself, not `object.__getattribute__()`. To remove the ability to do wrongly in case it will ever be inherited from some `type` descendent instead of `type` itself, relevant calls were replaced with `super().__getattribute__(name)`.
Also the list of attributes that are always-local was expanded, both for performance reasons and to fix running it in remote context'
> Fix access to special attributes in experimental mode

- modin/experimental/cloud/meta_magic.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
Before the changes the wrappers needed to enable remote context were done as two classes named samely, one inheriting the other and replacing the other in globals of the module. This lead to `super(Class, self).method` recursing in itself, because both `Class` and parent of `Class` had the exact same method.
I'm changing the method to replacing the classes instead of inheriting.
I've also had to remove `BasePandasDataset.__name__` property, so `self.__name__` no longer works,  using `type(self).__name__` yields the same result.
> Fix recursion in experimental mode in some cases

- .github/workflows/ci.yml
Add one more test group that runs ordinary non-experimental Modin tests with `MODIN_EXPERIMENTAL` set to `True`.
This should prevent accidental breakage of at least basic functionality in experimental mode in the future.
> Add tests running under experimental mode

- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
Series.apply and DataFrame.apply functions are reworked in order to match Pandas behavior.
> FIX-#1674: Series.apply and DataFrame.apply

- modin/pandas/base.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_series.py
> FIX-#1869: index sort for count(level=...)

- modin/engines/base/frame/data.py
- modin/pandas/dataframe.py
- modin/pandas/test/test_concat.py
- modin/pandas/test/test_dataframe.py
> FIX-#1497: Don't sort in concat() when sort=False

- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
Move part of set_index implementation to a backend to allow other backends support multi-index reset.
> REFACTOR-#1917: move part of reset_index code to backend

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/data_management/dispatcher.py
- modin/data_management/factories.py
- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/engines/base/io/io.py
- modin/pandas/test/test_io.py
- modin/pandas/utils.py
Add API to build modin dataframes from arrow tables. This is an important feature for arrow based OmniSci backend. For pandas based backend we simple convert arrow table to pandas dataframe.
> FEAT-#1925: add import from arrow table

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/series.py
This patch helps lazy backend to avoid index accesses in Series constructor by moving columnarization part into the backend.
> REFACTOR-#1928: move columnarization to backend

- modin/pandas/groupby.py
Signed-off-by: ienkovich <ilya.enkovich@intel.com>
Avoid unconditional index access in each groupby statement. This helps lazy engines to be lazier.
> REFACTOR-#1929: avoid unnecessary index access in groupby

- modin/backends/pandas/query_compiler.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
Signed-off-by: ienkovich <ilya.enkovich@intel.com>
Support cat.* methods. We are still defaulting to pandas but modifying operations work with this patch. cat.codes implementation is moved to backend because we have it implemented for OmniSci backend.
> FEAT-#1911: support cat methods

- modin/pandas/base.py
This patch allows column references without index access which is essential for lazy engine.
> REFACTOR-#1938: avoid index access in a simple column reference

- modin/pandas/dataframe.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/utils.py
Signed-off-by: Itamar Turner-Trauring <itamar@itamarst.org>
Make `df[df > 2] = 3` work (previously it did not).
> FIX-#1898: Support DataFrame.__setitem__ with boolean mask.

- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
Avoid index access in API layer when scalar is inserted as a new column.
> REFACTOR-#1941: move index access from DataFrame.insert to backend

- modin/pandas/test/test_dataframe.py
1) Removed `itertuples` call with default values, because this set of parameters is specified explicitly.
2) Iteration should not depend on the type of values in the dataframe, so it is suggested to use only the first dataset from `test_data_values` variable. (test coverage did not decrease after these changes; these changes save **more than 6 hours for CI**)
> TEST-#1950: improve TestDataFrameIter test time

- modin/backends/base/query_compiler.py
- modin/backends/pandas/parsers.py
- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/axis_partition.py
- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition.py
- modin/engines/base/io/column_stores/column_store_reader.py
- modin/engines/dask/pandas_on_dask/frame/axis_partition.py
- modin/engines/dask/pandas_on_dask/frame/partition.py
- modin/engines/python/pandas_on_python/frame/axis_partition.py
- modin/engines/python/pandas_on_python/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
- modin/experimental/cloud/rpyc_proxy.py
- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/engines/pandas_on_ray/sql.py
- modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
- modin/experimental/pandas/io_exp.py
- modin/pandas/base.py
- modin/pandas/general.py
- modin/pandas/indexing.py
- modin/pandas/io.py
- modin/pandas/plotting.py
- modin/pandas/series.py
- modin/pandas/test/test_concat.py
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_rolling.py
- modin/pandas/test/test_series.py
> REFACTOR-#1973: Refactor code in accordance with formatting style of new released version of black

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/indexing.py
Another refactoring to move index accesses to backend to enable lazy computations
> REFACTOR-#1934: move MultiIndex checks to backend

- modin/engines/base/frame/partition_manager.py
- modin/pandas/test/test_dataframe.py
> FIX-#1679: Assignment df.loc["row"]["col"] fixed in case of one row

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/pandas/test/test_dataframe.py
- modin/pandas/test/utils.py
> TEST-#1961: speed up TestDataFrameReduction_* test

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/pandas/test/dataframe/__init__.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_iter.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_reduction.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/dataframe/test_window.py
Signed-off-by: Alina <alina.bykovskaya@intel.com>
> REFACTOR-#1527: split test_dataframe.py into several others

- modin/backends/pandas/query_compiler.py
- modin/pandas/groupby.py
> REFACTOR-#1879: Move logic for `groupby.agg` into query compiler

- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_reduction.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_series.py
> FIX-#1953: Fix computing of reduced indices for reduction operation

- modin/pandas/base.py
- modin/pandas/indexing.py
- modin/pandas/series.py
- modin/pandas/utils.py
Wrap pandas.is_scalar method to handle `BasePandasDataset` objects separately. The problem is that calling `pandas.is_scalar` for `BasePandasDataset` object triggers execution for lazy frames.
> REFACTOR-#2009: avoid index access in is_scalar calls

- modin/engines/base/io/file_reader.py
- modin/engines/base/io/text/csv_reader.py
- modin/engines/base/io/text/fwf_reader.py
- modin/engines/base/io/text/json_reader.py
- modin/engines/base/io/text/text_file_reader.py
- modin/pandas/test/data/newlines.csv
- modin/pandas/test/test_io.py
> FEAT-#1523: 'nrows' support to 'read_csv' added

- .github/workflows/ci.yml
Speed up prepare-cache job by ~2 minutes.
> TEST-2022: speed up prepare-cache job

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
Fix incorrect work of `duplicated` and `drop_duplicates` functions.
> FIX-#1959 #1987: Fix incorrect work of `duplicated` and `drop_duplicates` functions

- MANIFEST.in
- modin/data_management/test/__init__.py
- modin/experimental/backends/__init__.py
- modin/experimental/engines/omnisci_on_ray/__init__.py
- modin/experimental/engines/omnisci_on_ray/frame/__init__.py
- modin/experimental/engines/omnisci_on_ray/test/__init__.py
- modin/experimental/pandas/test/__init__.py
- modin/pandas/test/data/__init__.py
- scripts/conda-recipe/conda_build_config.yaml
- scripts/conda-recipe/meta.yaml
- scripts/conda-recipe/run_test.py
> Conda recipe for Modin

- modin/data_management/functions/groupby_function.py
- modin/pandas/groupby.py
In OmniSci backend we can handle some cases of `grouby` where `by` holds both column names and series. We need this feature for NYC Taxi benchmark. To utilize backend support we need to move `default_to_pandas` call from API level to the backend.
> REFACTOR-#2011: move default_to_pandas in groupby to backend

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/groupby_function.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/groupby.py
- modin/pandas/io.py
- modin/pandas/plotting.py
- modin/pandas/reshape.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
- modin/pandas/utils.py
- modin/utils.py
> FIX-#2054: Moved non-dependent on modin.DataFrame utils to modin/utils.py 

- ci/teamcity/Dockerfile.teamcity-ci
- environment.yml
- modin/experimental/cloud/ray-autoscaler.yml
- modin/experimental/cloud/rayscale.py
- requirements.txt
- requirements/env_windows.yml
- requirements/windows_test_requires.txt
- setup.py
> FIX-#2052: fix spawning of remote cluster

- modin/data_management/__init__.py
- modin/data_management/factories.py
- modin/experimental/cloud/meta_magic.py
- modin/experimental/pandas/numpy_wrap.py
- modin/pandas/__init__.py
* Extract common part of defining proxying factory to a separate class
* Change how other parts of code check for engine being a remote one
* Determine the list of remote engines from defined factories automatically
> FEAT-#2058: Improve how remote factories are defined

- modin/engines/ray/utils.py
It can be possible, that default plasma directory can be space limited, so in that case we have to redefine plasma directory parameter to avoid core dumped issue.
> FIX-#1918: fix core dumped issue

- modin/engines/base/io/text/csv_reader.py
- modin/pandas/test/test_io.py
> FIX-#1386: Fix `read_csv` for incorrect csv data

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/dataframe.py
This patch moves `getitem_array` implementation from API level to the backend. This allows OmniSci backend to have its own implementation with a lazy bool indexer support.
> REFACTOR-#2035: move getitem_array to the backend

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_series.py
> FIX-#1997: Fix `unstack` for MultiIndex with different inner lvl-nodes

- modin/conftest.py
- modin/data_management/factories/factories.py
- modin/experimental/cloud/cluster.py
- modin/experimental/cloud/connection.py
- modin/experimental/cloud/local_cluster.py
- modin/pandas/__init__.py
Add optional switch for running tests `--sumulate-cloud` with values `off` (normal behaviour), `normal` (simulate cluster with Modin in non-experimental mode) and `experimental` (simulate cluster with Modin in experimental mode).
When `--simulate-cloud=off` (default), no tests are impacted.
Tests failing in simulated mode are a subject for subsequent issues and pull requests.
Also make rpyc server (on remote side) to pick the same port as the forwarded port. This allows parallel connects to single cluster, proper connects to an already running cluster, and parallel local testing (both as `pytest -n JOBS` and by several developers simulateneously).
> Simulate cluster for testing remote context

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/utils.py
Fix `unstack` for case when columns are non-tree MultiIndex
> FIX-#1997 #2084: Fix `unstack` for case when columns are non-tree MultiIndex

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
- modin/pandas/test/utils.py
> FIX-#2110: get rid of 'NotImplementedError' at OmniSci query compiler

- .github/workflows/ci.yml
- modin/conftest.py
- modin/experimental/cloud/rpyc_proxy.py
Both adapt local testing to possibility of having a remote proxy (by transferring the proxy by-value as low in the call hierarchy as possible) and by fixing `obj.__array__()` method.
With these changes applied, `python -m pytest --simulate-cloud=normal modin\pandas\test\test_io.py::test_from_csv` pass.
> Fix test_from_csv for simulated remote case

- examples/cluster/taxi-runner.py
- modin/conftest.py
- modin/data_management/factories/dispatcher.py
- modin/data_management/factories/factories.py
- modin/experimental/cloud/cluster.py
- modin/experimental/cloud/connection.py
- modin/experimental/cloud/omnisci.py
- modin/experimental/cloud/ray-autoscaler.yml
- modin/experimental/cloud/rayscale.py
- modin/pandas/__init__.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
**Note**: this changes API of `create_cluster()` by renaming `__spawner__` (considered internal) to `cluster_type` (considered public).
This enables running workloads remotely on Omnisci-enabled Modin.
This also changes Modin installation to be `conda`-based (because OmniSci Python engine is published only in conda for now).
With those changes, `taxi-runner.py --omnisci` runs fine.
> Enable OmniSci on cloud

- modin/engines/base/io/column_stores/parquet_reader.py
> FIX-#1144: Fix `read_parquet` for working with HDFS

- modin/engines/base/io/text/text_file_reader.py
> FIX-#2115: Use `seek` when we don't need to check quotes for CSV

- modin/backends/__init__.py
Relax requirements on having `pyarrow` installed.
After these changes if there is `pyarrow` is only required to have `modin.backends.PyarrowQueryCompiler`, base and Pandas backends always exist.
> Do not always require pyarrow

- modin/experimental/engines/omnisci_on_ray/frame/calcite_builder.py
- modin/experimental/engines/omnisci_on_ray/frame/expr.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Add support for `skew` aggregate for OmniSci backend
> FEAT-#2141: support skew aggregate in omnisci backend

- environment.yml
- setup.py
* Pin cloudpickle to 1.4.1 to avoid `ValueError: pickle protocol must be <= 4` problem for mortgage-runner.py.
* Add boto3 to dev environment.
* Move rpyc from pip section to avoid conflicts of versions of packages installed with conda.
> FIX-#2145: add cloud dependencies to conda dev environment

- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/test/test_cloud.py
For RPyC to work correctly, the micro part of the python version may not match, so we can specify an interval from which the conda will choose the appropriate one. (for example 3.7.*)
> FIX-#2147: return interval for python micro version - *.*.X

- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/pandas/test/dataframe/test_indexing.py
Add a simple shuffle internal mechanism to have more performant insertions and concatenation when index objects already match.
> FIX-#2134: Fix mismatch partitioning insertions with same index

- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Add MultiIndex columns generation into OmniSci version of groupby.agg
> FEAT-#2154: generate MultiIndex for columns in groupby.agg

- modin/experimental/cloud/ray-autoscaler.yml
- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/test/test_cloud.py
> FEAT-#2138: sync modin version between local and remote contexts

- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Avoid useless projection for a `concat` of a single frame
> REFACTOR-#2170: simplify concat of a single frame

- modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Support float32 in calcite serializer
> FIX-#2172: support float32 in calcite serializer

- requirements/env_omnisci.yml
> FIX-#2212: changed label to 'modin' in intel conda channel

- modin/pandas/iterator.py
We doesn't support python 2.X, so we can remove `next` method (For details see [PEP3114](https://www.python.org/dev/peps/pep-3114))
> REFACTOR-#2221: Remove `PartitionIterator` methods related to the python 2.X iterator interface.

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_reduction.py
In previous implementation parameter `numeric_only` was needed only for checking that `dtypes` is numeric else it was raising an exception. This changes make possible work with this parameter according pandas.
> FIX-#1965: Fix `count` func in case `numeric_only`==True

- modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py
Avoid float fragment size passed to DBE
> FIX-#2237: use floordiv to get fragment size.

- modin/engines/base/io/text/csv_reader.py
- modin/pandas/test/data/issue_2074.csv
- modin/pandas/test/test_io.py
#2074   What do these changes do?
> FIX-#2074: CSVReader changes index_col if length names mismatch

- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/utils.py
> FIX-#2249: changed 'return' -> 'assert' in df_equals

- modin/experimental/cloud/cluster.py
- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/test/test_cloud.py
> FEAT-#2232: add way to specify modin version in the cloud

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_reduction.py
> FIX-#2195: fix describe error for datasets with datetimes

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
For details about that issue see [this](https://github.com/modin-project/modin/issues/1906#issuecomment-710090761) comment
> FIX-#1906: fixed incorrect behaviour of 'groupby.__getattr__'

- modin/pandas/test/utils.py
> FIX-#2277: applied Title Case to the names of DATASET_SIZE_DICT keys

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#2254: handling dictionary functions at groupby aggregation improved

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/__init__.py
- modin/data_management/functions/foldfunction.py
- modin/data_management/functions/function.py
- modin/data_management/functions/mapreducefunction.py
- modin/data_management/functions/reductionfunction.py
- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_reduction.py
- modin/pandas/test/utils.py
You can find reproducer and short explanation at #1976. We're getting error, because of mismatching between internal and external indices. Currently, we're trying to precompute new labels for indices and columns of the resulted frame in reduction operations, but sometimes we're failing to do so.
It happens when `numeric_only` parameter in reduction operations considered to be `None`, going from [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sem.html?highlight=numeric_only) in that case pandas determines whether to drop or not to drop non-numeric column only after applying numeric function and so we also can't predict that columns, so we need to compute new labels explicitly, after …
> FIX-#1976: indices matching at reduction functions fixed

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/frame/expr.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Support value_counts in OmniSci backend. We have undefined order in OmniSci with no sorting, so test sorted option only.
> FEAT-#2299: support value_counts in OmniSci backend.

- modin/backends/pandas/parsers.py
- modin/engines/base/frame/data.py
- modin/engines/base/io/column_stores/parquet_reader.py
- modin/pandas/test/test_io.py
- requirements/env_omnisci.yml
> FIX-#1765: Fix support of s3 in `read_parquet`

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/default_methods/binary_default.py
- modin/data_management/functions/default_methods/default.py
- modin/data_management/functions/default_methods/groupby_default.py
- modin/data_management/functions/default_methods/resample_default.py
- modin/data_management/functions/default_methods/rolling_default.py
- modin/data_management/functions/default_methods/series_default.py
- modin/pandas/test/test_general.py
Example of improved warning:
```
UserWarning: <function DefaultMethod.call.<locals>.applyier at 0x7f8a004300d0> defaulting to pandas implementation.
UserWarning: <function GroupBy.prod> defaulting to pandas implementation.
```
> FIX-#2285: Default to pandas warning message improved

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
This patch fixes args handling for simple aggregates and adds `mean` support.
> FEAT-#2303: fix OmniSci aggregates and add mean

- .github/PULL_REQUEST_TEMPLATE.md
- docs/developer/contributing.rst
> FIX-#2258: return 'Commit Message formatting' topic

- modin/data_management/functions/binary_function.py
- modin/engines/base/frame/data.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_binary.py
> FIX-#2133 #2265: Fix binary operations in case when partitioning isn't aligned

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
You can find a brief bug explanation and reproducer at #2253
- Moved logic about determining assignment axis from `__setitem__` to a separate method, `__setitem__` now obtains assignment axis as a parameter
- Since for frames with shape `(1, 1)` we can't compute assignment axis by row and column lookups, now for `(1, 1)` shape frames we're doing it by row and column scaler parameters. The idea is that if row identifier was scalar, and column don't, then it's definitely a row assignment and vie-versa
```
Example:
df.loc["a", any_non_scalar_indexer] -> row_scaler = True   | This is going to be row assignment
-> col_scaler = False  |
df.loc[any_indexer, "a"] -> row_scaler = False | This is goint to be a column assignment
-> …
```
> FIX-#2253: loc assignment fixed in case of (1, 1) shape frame

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_reduction.py
- Removed logic by computing new axis in case of `numeric_only=None` from `_compute_map_reduce_metadata`, to have all logic about validating axis in `_validate_internal_axis`
- Added new mode at `_validate_internal_axis`, where we're also validating not reduced axis with `force=True` on it
- Now `_compute_map_reduce_metadata` uses new added mode to validate axes in case of `preserve_index=False`
- Removed unnecessary `dtypes` recomputing at `_compute_map_reduce_metadata` in case of `axis=0`
- Now, in case of `numeric_only=None` at reduction operations, we're checking is all columns of the frame are numeric, and if it is, then setting `numeric_only=False` to preserve labels
Regression in cases not affected by bug described in #1976 …
> FIX-#2311: fixed performance regression at reduction operations

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
> TEST-#2288: Cover by tests delimiters parameters of read_csv

- modin/engines/base/io/text/csv_reader.py
- modin/engines/base/io/text/fwf_reader.py
- modin/engines/base/io/text/text_file_reader.py
Refactor `offset` and `_read_rows` functions in order to separate areas of responsibility.
One function is responsible for reading lines, another for reading bytes.
> REFACTOR-#2343: refactor offset, _read_rows, partitioned_file

- modin/pandas/accessor.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_series.py
Time of `hasattr` for `pandas.DataFrame.sparse` = 0.00023566000163555145
Time of `hasattr` for `modin.pandas.DataFrame.sparse` = 3.1324103474617004e-05
<details><summary> script </summary>
```python
import pandas
NCOLS = 2 ** 10
NROWS = 2 ** 10
RAND_LOW = 0
RAND_HIGH = 100
random_state = np.random.RandomState(seed=42)
def measure(df):
start = timer()
hasattr(df, "sparse")
end = timer()
return end - start
float_nan_data = {
f"col{int((i - NCOLS /2)% NCOLS + 1)}": [
x if (j % 4 == 0 and i > NCOLS // 2) or (j != i and i <= NCOLS // 2) else np.nan
for j, x in enumerate(random_state.uniform(RAND_LOW, RAND_HIGH, size=(NROWS)))
]
for i in …
```
> FIX-#1927: Fix performance issue related to `sparse` attribute access

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/default_methods/groupby_default.py
- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/conftest.py
- modin/test/test_backends_api.py
> FIX-#2269: Move `default_to_pandas` logic from API layer to backend

- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
This PR adds unit tests for Datetime handling parameters of `read_csv`.
> TEST-#2292: Cover by tests Datetime Handling parameters of read_csv

- modin/backends/pandas/query_compiler.py
> FIX-#2348: Fix default to pandas warnings

- .github/PULL_REQUEST_TEMPLATE.md
> FIX-#2357: Fix path to documentation for contributing

- modin/experimental/cloud/ray-autoscaler.yml
> FIX-#2352: remove deprecated option: 'num-redis-shards'

- modin/backends/base/query_compiler.py
- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
- modin/pandas/groupby.py
Add methods to QueryCompiler to manipulate index names.
> FEAT-#2363: introduce getter and setter for index name

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_series.py
> FIX-#2365: Fix `Series.value_counts` when `dropna=False`

- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/test/test_cloud.py
> FIX-#2386: add new location for import ray functions

- modin/data_management/utils.py
- modin/engines/base/frame/axis_partition.py
- modin/engines/dask/pandas_on_dask/frame/axis_partition.py
* Add `lengths` parameter handling for dask engine.
* Make `split_result_of_axis_func_pandas` always return a list value and removes a bug in which the wrong number of partitions is returned (in the case when `num_splits==1` and `lengths != 1`)
> FIX-#2380: don't ignore lengths parameter for dask engine

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/default_methods/groupby_default.py
- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> Merged groupby_agg and groupby_dict_agg to implement dictionary functions aggregations

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_groupby.py
> Fix bug 2406: filter dictionary aggregation keys to limit them to keys only present in current partition

- docs/developer/architecture.rst
Fixes #2421 
- Fixes bad link on contributing from architecture.rst
Signed-off-by: Victor Fomin <vfdev.5@gmail.com>
> DOCS-#2421: Fixes bad link on contributing from architecture.rst

- docs/contributing.rst
- docs/developer/architecture.rst
- docs/index.rst
- Closes #2424, CONTRIBUTING.rst does not render the commit message formatting example
- Closes #2426, Bad links in index.rst
- Renamed CONTRIBUTING into contributing
Signed-off-by: Victor Fomin <vfdev.5@gmail.com>
> DOCS-#2426,DOCS-#2424: Fixed docs issues and warnings

- examples/docker/taxi-on-omnisci/build-docker-image.sh
- examples/docker/taxi-on-omnisci/nyc-taxi-omnisci.dockerfile
- examples/docker/taxi-on-omnisci/nyc-taxi-omnisci.py
> FEAT-#2444: add docker file for nyc on omnisci

- examples/docker/nyc-taxi.dockerfile
While building [nyc-taxi.dockerfile](examples/docker/nyc-taxi.dockerfile) I noticed `psutil` installation failed and the following error was reported:
```
ERROR: Command errored out with exit status 1:
command: /home/modin/miniconda/envs/modin/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s_zbgkmi/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s_zbgkmi/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-02t4eer9/install-record.txt --single-version-externally-managed --compile --install-headers /home/modin/miniconda/envs/modin/include/python3.7m/psutil
cwd: …
```
> Fix 'psutil' install

- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
Using `git bisect` it was found that commit b867edfba345e5f3c28398274b876d7b31f5a5ba introduced regression. This commit was reverted. Measurement results of commit with revert are next (given relation of queries execution times t_0.7.4/t_master, numbers lower 1 corresponds to degradation from 0.7.4 release to current master)
read_csv 1.12 (reading from local csv)
reductions 1.03
map operations 1.13
apply operation 1.8
add column operation 0.96
groupby.agg operation 1.04
mean value for all queries 1.18
As it can be seen degradation is not present now.
> FIX-#2470: Performance regression relative to 0.7.4 release

- modin/config/envvars.py
- modin/config/pubsub.py
- modin/config/test/test_envvars.py
Some configuration variables should not be transformed upon reading them from user input (e.g. Ray plasma directory), fix that.
> FIX-#2473: Some configuration values should not be transformed

- modin/engines/base/frame/axis_partition.py
- modin/engines/base/frame/partition.py
- modin/engines/base/frame/partition_manager.py
> REFACTOR-#2467: Convert internal base dataframe objects to ABC

- ci/teamcity/Dockerfile.modin-base
- ci/teamcity/Dockerfile.teamcity-ci
- environment.yml
> FIX-#2459: Updated TeamCity tests image to use Ray as base image

- commitlint.config.js
> TEST-#2488: Increase commitlint message length limit to 88 characters from 70

- docs/supported_apis/series_supported.rst
- docs/supported_apis/utilities_supported.rst
- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
Because there is the issue #1650 we can remove the logic related to sorting indices for equal values. So we can significantly improve execution time `Series.value_counts` itself and also one of our benchmark.
> FIX-#2453: Remove sorting indices for equal values in `Series.value_counts`

- modin/backends/pandas/parsers.py
- modin/engines/base/io/__init__.py
- modin/engines/base/io/column_stores/column_store_dispatcher.py
- modin/engines/base/io/column_stores/feather_dispatcher.py
- modin/engines/base/io/column_stores/hdf_dispatcher.py
- modin/engines/base/io/column_stores/parquet_dispatcher.py
- modin/engines/base/io/file_dispatcher.py
- modin/engines/base/io/sql/sql_dispatcher.py
- modin/engines/base/io/text/csv_dispatcher.py
- modin/engines/base/io/text/excel_dispatcher.py
- modin/engines/base/io/text/fwf_dispatcher.py
- modin/engines/base/io/text/json_dispatcher.py
- modin/engines/base/io/text/text_file_dispatcher.py
- modin/engines/dask/pandas_on_dask/io.py
- modin/engines/ray/pandas_on_ray/io.py
- modin/experimental/engines/pyarrow_on_ray/io.py
> REFACTOR-#2496: Change internal reader names to dispatcher

- modin/pandas/test/test_io.py
PR moves existent `read_csv` tests with `chunksize` into `TestReadCSV` class and adds tests for `iterator` parameter.
> TEST-#2294: Cover by tests Iteration parameters of read_csv

- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
> TEST-#2295: Cover by tests Quoting, Compression, and File Format parameters of read_csv

- .github/workflows/ci.yml
- .gitignore
- asv_bench/asv.conf.json
- asv_bench/benchmarks/__init__.py
- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils.py
- environment.yml
- requirements.txt
* `TimeArithmetic` benchmark - an alternative for `ci/benchmarks/pandas/arithmetic_benchmark.py` (except `df.T` op)
* `TimeMerge` benchmark - an alternative for `ci/benchmarks/test_benchmarks.py::test_merge`
* `TimeJoin` benchmark made by analogy with `TimeMerge`
* Data generation functionality is just copied from `test_benchmarks.py` (I suppose we can remove duplicated functionality later)
* **Note** we should run asv with `--launch-method=spawn` (forkserver is not work)
What needs to be completed:
* look at `modin/ci/benchmarks` for benchmarks that can be used with asv (This is an experimental feature, out of scope for now)
* define new microbenchmarks based on workloads (This is an experimental feature, out of scope for now)
* …
> FEAT-#2479: integrate asv

- asv_bench/benchmarks/benchmarks.py
- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/pandas/dataframe.py
- modin/test/backends/pandas/test_internals.py
* for concat operation, repartition occurs only when it is necessary to re-index or align the partitions(`force_repartition=False`)
* new behavior for `broadcast_axis_partitions` function - we save the partitioning also in the case when `keep_partitioning=False` and lengths are passed
* new behaviors for `_join_index_objects`:
* self.axes[axis] should be passed via others_index[0]
* in the case when all indexes are equal, we do not perform join operation, but simply return `self.axes[axis]` as `joined_index`
* the reindex operation does not work when the object (Series or DataFrame) for which the operation is being performed contains an index with duplicate values - but we can do this using indexers and the private pandas function …
> FIX-#2374: remove extra code; add pandas way to handle duplicate values in reindex func for binary operations

- modin/config/envvars.py
- modin/engines/base/io/text/excel_dispatcher.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
`openpyxl` has either a long-standing bug or a design decision that, when opening a file in read-only mode, it does not close the file handle (maybe it does so for caching purposes, no idea).
They have introduced a new `.close()` method, but people say it does not fully close all the handles.
So what I instead did was open the file if passed in a string and close it explicitly.
Also I've optimized the code a little bit by effectively inlining `load_workbook()` function which allowed to eliminate creation of _two_ `ExcelReader()` objects for a single read.
I've also decorated all the excel-reading tests with the checker ~~from Pandas test utils which they introduced in https://github.com/pandas-dev/pandas/pull/30096 when they were fixing this exact issue :)~~ inspired by Pandas but with a …
> Ensure excel reader closes file if it is passed as path

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/default_methods/groupby_default.py
- modin/data_management/functions/groupby_function.py
- modin/engines/base/frame/axis_partition.py
- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/utils.py
Check #2375 to see the basic idea of this implementation.
- Added ability to broadcast multiple modin frames with different partitioning.
- Reworked handling internal + external 'by'. Now if every 'by' are internal (columns names or Series whos `parent is self`) then 'by' will be a query compiler that contains all columns. If we have internal + external 'by', then 'by' will be a list of column names and external 'by's (or their query compilers if they have one). If we have only external 'by' then 'by' will be a list of external 'by's (or their query compilers if they have one). 
Previously it was possible that we're passing modin Series to a backend, now it could be only query compiler.
- Removed `squeeze` parameter from …
> FEAT-#2375: implementation of multi-column groupby aggregation

- README.md
- docs/using_modin.rst
Explain how in local ( single node ) modin work and use a simulated dark or ray cluster
Closes #2436
> DOCS-#2436: Explicit local / single node backend

- modin/pandas/test/test_io.py
Ensure each run of `test_HDFStore` uses different test file, also clean it up after test is over.
> FIX-#2527: Use random name for hdf file test, clean file after testing

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
> FIX-#2169: avoid unnecessary index access in groupby

- asv_bench/benchmarks/benchmarks.py
- modin/backends/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_reduction.py
asv results:
```
asv continuous src/master HEAD -b TimeArithmetic --launch-method=spawn -a warmup_time=1
BENCHMARKS NOT SIGNIFICANTLY CHANGED.
```
> FIX-#2313: improved handling non-numeric types at 'mean' when 'axis=1'

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
This PR refactors IO tests in order to unify source code, group similar tests in classes and capability to run io tests in parallel. Changes are next:
1) Similar tests were grouped in classes.
2) Source code unifications - used common `eval_io`, `eval_from_str`, ... functions, unique test filenames for each tests are used (needed to provide capability to run io tests in parallel), some duplicated code removement.
3) Add capability to process warnings by `eval_general` function.
> TEST-#2509: Io tests refactoring

- asv_bench/benchmarks/benchmarks.py
- modin/config/envvars.py
* Removed extra code: `pd.DEFAULT_NPARTITIONS = CpuCount.get()`. To manipulate the number of partitions, it is enough to define `MODIN_CPUS` env variable.
* Unified datasets for binary and unary operations:
* For binary operations added a more general case of source data when `left.shapes != right.shapes`
* By default, the comparison with Pandas is removed to save resources. To get the results of the pandas, just define `MODIN_ASV_USE_IMPL` env variable with `pandas` value.
* Removed all tests that, for various combinations of parameters, fall back to the pandas implementation.
* Added a call to `.shape` property for results of all operations to accurately calculate the time, even if there is lazy evaluation inside.
> FEAT-#2520: add most important operations for asv benchmarks

- modin/engines/ray/utils.py
> FEAT-#2236: Handling of space limited Ray Plasma directories

- docs/contributing.rst
> DOCS-#2518: add asv usage topic

- asv_bench/benchmarks/benchmarks.py
- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/__init__.py
- modin/data_management/functions/groupby_function.py
- modin/engines/base/frame/data.py
- modin/engines/base/frame/partition_manager.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- Added [`groupby_reduce_functions` dictionary](https://github.com/dchigarev/modin/blob/021d45e900455eddbbaf1bffa295d50fdfa838ba/modin/data_management/functions/groupby_function.py#L229) of all supported reduction operation in pandas backend, it contains map and reduce functions for every method. That was done to easily translate function name in aggregation dictionary to its proper map and reduce functions.
- Now, when `PandasQueryCompiler.groupby_agg` obtains dictionary as a function, it checks that all function exists in the `groupby_reduce_functions` dictionary, if it is - going to new added [`PandasQueryCompiler._groupby_dict_reduce`](https://github.com/dchigarev/modin/blob/021d45e900455eddbbaf1bffa295d50fdfa838ba/modin/backends/pandas/query_compiler.py#L2459) method, otherwise …
> FEAT-#2491: optimized groupby dictionary aggregation

- asv_bench/benchmarks/benchmarks.py
> FEAT-#2553: add ability to run microbenchmarks for old Modin version

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
P.S. Thanks @dchigarev for root causing the issue!
> Fix .loc[] assignment for Modin Series

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/groupby_function.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
Previously we used `isinstance(by, str)` to check that 'by' is a column name, however, it doesn't work when columns have non-str type, so this PR changes all 'is instance' check to 'is hashable'
> FIX-#2482: improved handling non-str 'by'

- modin/experimental/cloud/rayscale.py
- modin/experimental/cloud/test/test_cloud.py
> Fix taxi-runner.py cluster example

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
The problem in current code is that it treats index and columns uniformely, while Pandas seems to be treating them differently.
Current code provides an indexing in the columns, but then checks for column names in the object being assigned (also `pandas.reindex()` expects column names, not column positions).
So I'm converting positions to names before trying to assign.
> Fix loc/iloc assignments when columns are selected

- modin/pandas/test/utils.py
> FIX-#2559: Ignore files from /proc/ when detecting file leaks

- modin/pandas/series.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
Ensures that `Series.unique` does not return a scalar when there is only one unique value. This solves the problem of the behavior of Modin and Pandas differing when there is only one unique value (https://github.com/modin-project/modin/issues/2566). Modin will return a scalar if there is only one unique value because the `unique` function calls `squeeze`, removing any axes of length 1. Pandas' `unique` function does not return a scalar when there is only one unique value.
Removing `squeeze` from the `unique` definition causes tests to fail because there can be additional axes where Pandas doesn't have any.
The current tests do not catch this because they use `np.testing.assert_array_equal`, which treats scalars as an array. I have added an assert to check that the shapes of Modin's and …
> FIX-#2566: Ensure `Series.unique` does not return a scalar when there is only one unique value

- requirements/env_omnisci.yml
> FIX-#2572: pinned arrow version in OmniSci CI dependencies

- modin/engines/dask/pandas_on_dask/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
There is a small typo in modin/engines/dask/pandas_on_dask/frame/partition.py, modin/engines/ray/pandas_on_ray/frame/partition.py.
Should read `partition` rather than `parition`.
Fixes #2578
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> DOCS-#2578: fix simple typo, parition -> partition

- modin/backends/pandas/query_compiler.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#2543: fixed handling 'as_index' at GroupBy dictionary renaming aggregation

- modin/engines/dask/utils.py
- modin/engines/ray/utils.py
- modin/error_message.py
- modin/experimental/pandas/io_exp.py
- modin/pandas/__init__.py
- modin/pandas/dataframe.py
- modin/pandas/io.py
- modin/pandas/series.py
* Resovles #2580
Instead of automatically starting the engine when Modin is imported,
we start it after the first time the user reads or creates a dataframe.
This is intended to help downstream libraries not need the engine to
check for typing, as well as clear up some transient errors that can
occur with certain engines on large machines.
I have also added a warning message that informs the user how to clear
the message. We will likely need a way to suppress these errors, because
many users will not care about them and potentially want to suppress.
We will probably also want to add a benchmarking page on best practices
for benchmarking because this change can give the impression of a
performance degradation on data ingestion even though nothing is
changing from that perspective. …
> REFACTOR-#2580: Move automatic engine init to after data ingestion

- .github/workflows/ci.yml
* Resolves #2598
This change adds a test for installing Modin without all of the testing
dependencies.
It is intended to test how a user who does not have all of the test
dependencies will see a Modin import.
> TEST-#2598: Add test for clean install from source

- asv_bench/benchmarks/benchmarks.py
> TEST-#2601: reduce data size for some asv tests

- modin/engines/base/io/text/csv_dispatcher.py
- modin/engines/base/io/text/fwf_dispatcher.py
- modin/engines/base/io/text/json_dispatcher.py
- modin/engines/base/io/text/text_file_dispatcher.py
- modin/pandas/test/test_io.py
Resolves #2624 
See some of the context in #2624 -- what this PR does is adds in some code so that when a file handle is passed into `modin.pandas.read_*` - we extract the filepath from it using the `.name` attribute of the buffer, check if it exists, convert it to an absolute path and then let the rest of the `read_*` code move ahead as though that string was passed in initially.
The reason that a file handle has to fall back to Pandas in a single worker is because file handles can't be pickled and sent across processes, since they aren't serialisable. This PR should hopefully do nothing but make the `read_*` method more performant where possible, and continue to fallback to single worker Pandas where not. So hopefully a win-win.
Certainly on my laptop (Macbook Pro 13" 2019 with 16G Ram, …
> FEAT-#2624: Allow read_csv,json,fwf to use file handles without falling back to Pandas 

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: William Ma <williamwma5@gmail.com>
Fixes the deadlink in the pr template
> DOCS-#2649: Fix github pr template's dead link.

- modin/backends/pandas/parsers.py
- modin/pandas/iterator.py
- stress_tests/kaggle/kaggle14.py
- stress_tests/kaggle/kaggle4.py
- stress_tests/kaggle/kaggle5.py
This also fixes below warnings : 
```
find . -iname '*.py' | xargs -P4 -I{} python3.9 -Wall -m py_compile {}  
./modin/backends/pandas/parsers.py:251: DeprecationWarning: invalid escape sequence \d
b"\d+",  # noqa: W605
./modin/backends/pandas/parsers.py:258: DeprecationWarning: invalid escape sequence \d
bytes_data = re.sub(b'r="[A-Z]*\d+"', update_row_nums, bytes_data)  # noqa: W605
./versioneer.py:421: DeprecationWarning: invalid escape sequence \s
LONG_VERSION_PY['git'] = '''
./stress_tests/kaggle/kaggle14.py:53: DeprecationWarning: invalid escape sequence \.
"([A-Za-z]+)\."  # noqa: W605
./stress_tests/kaggle/kaggle4.py:54: DeprecationWarning: invalid escape sequence \m
["Normal dist. ($\mu=$ {:.2f} and $\sigma=$ {:.2f} )".format(mu, sigma)],
./stress_tests/kaggle/kaggle4.py:67: …
```
> Fix Python 3.9 warnings

- docs/UsingSQLonRay/index.rst
- docs/contributing.rst
- docs/developer/architecture.rst
- docs/index.rst
- docs/installation.rst
- docs/out_of_core.rst
- docs/supported_apis/index.rst
- docs/supported_apis/series_supported.rst
- docs/using_modin.rst
This changes add new way of linking internal pages and fix some not working links.
> DOCS-2653: Fix links in Modin's documentation

- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
Resolves #2663
This operator is necessary for efficient `reset_index` operations. See
this paper for more information on the operator:
http://www.vldb.org/pvldb/vol13/p2033-petersohn.pdf
> FEAT-#2663: Add algebraic operator `from_labels`

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils.py
> FEAT-#2675: Added benchmark for sort_values

- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/engines/base/frame/data.py
- modin/pandas/dataframe.py
Resolves #2664
This add the algebraic operator for `to_labels`, which enables Modin to
better optimize the movement of data to metadata. See more in the paper
about the algebraic operator:
http://www.vldb.org/pvldb/vol13/p2033-petersohn.pdf
> FEAT-#2664: Add `to_labels` algebraic operator

- .github/workflows/ci.yml
- .github/workflows/push.yml
- setup.py
> FIX-#2614: Up python version for test jobs

- docs/conf.py
- docs/index.rst
- docs/modin_xgboost.rst
This changes add documentation for distributed XGBoost on Modin
> DOCS-2633: Add documentation for distributed XGBoost on Modin

- .github/workflows/ci.yml
- .github/workflows/push.yml
- environment-dev.yml
- modin/experimental/xgboost/test/__init__.py
- modin/experimental/xgboost/test/test_default.py
- modin/experimental/xgboost/xgboost.py
- requirements-dev.txt
This changes move checking of backend to separate function to make importing module possible.
> FIX-#2658: Move backend check in xgb to train/predict

- asv_bench/asv.conf.json
- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils.py
- modin/config/envvars.py
* `join`, `merge` operations are performed by row index instead of random generated columns;
* `groupby` operations are performed on the initially known number of groups;
* use `(nrows, ncols)` order when setting the size of the generated data;
* returned the original data sizes for operations: `merge` and `groupby` with multi columns.
> TEST-#2670: some updates to improve asv tests stability

- asv_bench/benchmarks/benchmarks.py
> TEST-#2686: add fillna benchmark

- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/partition_manager.py
- modin/experimental/engines/omnisci_on_ray/frame/axis_partition.py
- modin/experimental/engines/omnisci_on_ray/frame/partition.py
- modin/pandas/dataframe.py
> FIX-#2688: Update ray.ObjectID to ray.ObjectRef for Ray 2.0

- docs/conf.py
- docs/modin_xgboost.rst
- docs/requirements-doc.txt
> FIX-#2684: Add method level docs for Modin XGBoost

- modin/engines/base/frame/data.py
- modin/pandas/test/dataframe/test_indexing.py
There are two related arrays that we operate on at `_copartition`: `other` and `other_frames`. 
`other` - function parameter, it contains frames to concatenate with `self`. After joining indices we're [picking the first non-empty frame](https://github.com/modin-project/modin/blob/e74e01279b8c1b6d01652e2e24a060e3ee47b919/modin/engines/base/frame/data.py#L1778-L1780) in a `[self] + [other]` list to be our `base_frame` with which we're aligning partitioning with, all other frames are moved into the `other_frames`. So if `self` is not empty then `other == other_frames` and we couldn't see any errors. However when `self` is empty (for example when we're replacing the first column) then `other[base_index: base_index + 1] == …
> FIX-#2709: fixed typo in '_copartition'

- asv_bench/benchmarks/benchmarks.py
> TEST-#2690: add astype benchmark

- asv_bench/benchmarks/benchmarks.py
> TEST-#2716: add describe bench

- docs/requirements-doc.txt
The latest version of master branch will be used for building the latest documentation pages.
> DOCS-#2717: Fix version of Modin for building latest docs

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_udf.py
See #2305 for the problem description. This PR adds `func is None` check to the if-statement which dispatches aggregation execution to the dict branch.
> FIX-#2305: fix handling of renaming aggregation

- modin/pandas/series.py
- modin/pandas/test/test_series.py
See #2362 for the problem explanation. Old `Series.__setitem__` logic assumed, that the `key` could only be a scalar. However, it also could be a slice, list of labels, boolean mask, etc. There are `loc/iloc` accessors to handle all of this variety of `key` types. So now all `Series.__setitem__` calls are dispatched to `.loc[key]` since `setitem` is a label-based value-accessor, and to `.iloc[key]` if `key` is a int-slice (must to use `iloc` here because `loc` can't manage location-based slices).
> FIX-#2362: fix key handling in 'Series.__setitem__'

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/io/__init__.py
- asv_bench/benchmarks/io/csv.py
- asv_bench/benchmarks/utils.py
This PR added ASV benchmark for `read_csv` function with `skiprows` parameter. Also some common for IO and others benchmarks functions and configuration parameters were moved into `utils` module.
Note: subpart of https://github.com/modin-project/modin/pull/2607
> TEST-#2722: add ASV read_csv skiprows benchmark

- modin/conftest.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
> REFACTOR-#2739: io tests refactoring

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils.py
> TEST-#2753: add GroupBy benchmarsk with huge amount of groups

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_series.py
> FIX-#2362: fix handling slices in 'DataFrame.__setitem__'

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/groupby_function.py
You can see the problem explanation in #2742. This PR replaces all the callables in [`groupby_reduce_functions`](https://github.com/modin-project/modin/blob/8ebbad9bca36aba0ddfc58dac89b9a66b0bfe41a/modin/data_management/functions/groupby_function.py#L234) to its string names, so now dictionary aggregation applies string functions to the columns and therefore performs much faster with a-lot-of-groups groupby. This PR also brings an ability to pass only a function name to the `GroupByReduce.register` for simplicity.
```
MODIN_CPUS=4 MODIN_TEST_DATASET_SIZE=Big asv continuous src/master HEAD --launch-method=spawn -b TimeGroupByDictionaryAggregation --split
[aa818f5a]       [c177b8aa]
<master> …
```
> FIX-#2742: fix performance degradation for dictionary GroupBy aggregation

- modin/experimental/engines/omnisci_on_ray/io.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
- modin/pandas/test/utils.py
> FIX-#2737: fix handling of dates for read_csv with OmniSci backend

- modin/experimental/engines/omnisci_on_ray/io.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FEAT-#2629: implement usecols for read_csv with OmniSci backend

- modin/engines/base/io/text/csv_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#2307: Fix usage of callable usecols in read_csv

- asv_bench/benchmarks/io/csv.py
> TEST-#2779: add read_csv benchmark with dtype/names parameters and parsing dates

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/io/csv.py
- asv_bench/benchmarks/utils.py
> TEST-#2766: use string keyword instead of lambdas in ASV benchmarks

- modin/engines/base/io/text/csv_dispatcher.py
- modin/engines/base/io/text/text_file_dispatcher.py
This PR refactores `csv_dispatcher.py` module, most significant changes are:
- Some code blocks moved into functions.
- Fallback-to-pandas checks grouped and moved on the top of `_read` function.
- Modification of original `read_csv` kwargs parameters was removed
> REFACTOR-#2748: CSV IO part refactoring

- modin/conftest.py
Signed-off-by: Marat Idrisov <idrisov.mt@yandex.ru>
___
A question may arise: Why is the default value not `None` but `object()`?
`os.environ` returns an object of the class `os._Environ`. `_Environ` is inherited from `_collections_abc.MutableMapping`. The [MutableMapping.pop](https://github.com/python/cpython/blob/3.8/Lib/_collections_abc.py#L790) method has `object()` as default value.
> FIX-#2522: Added optional default parameter to pop method

- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- setup.py
> FIX-#2795: Update pandas to 1.2.3

- asv_bench/benchmarks/scalability/scalability_benchmarks.py
- asv_bench/benchmarks/utils.py
**Note**: there is no need to wait https://github.com/modin-project/modin/pull/2801, because we should have another implementation inside `asv_bench` folder which will be used for old commits.
> TEST-#2805: use wait function to get the right performance times

- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> TEST-#2809: move sort function from 'value_counts' tests to utils

- .github/workflows/ci.yml
- .github/workflows/push.yml
> REFACTOR-#2832: removed limitation on the micro part of python version in CI

- .github/workflows/ci.yml
- requirements/env_omnisci.yml
It seems that `pyarrow==1.0.0` doesn't work with `numpy>=1.20.0`, so we have to use a newer version of `pyarrow` (cc @Garra1980 )
The PR also change conda channel to simplify development, since the package can be updated more often without affecting users.
UPD: tested with `numpy==1.20.0, 1.20.1`
> FIX-#2680: fix omnisci engine work with numpy>=1.20.0

- environment-dev.yml
- requirements/env_omnisci.yml
Manually pin `libthrift` to `0.14.0` as required by current `arrow` builds in conda-forge.
Should not be needed in a day or two when updated `arrow` and `thrift` packages are ready, so we may want to revert it after they fix the dependencies.
The main reasoning behind this (temporary) PR is to unblock the "red CI".
> Workaround for libthrift issues in CI

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/backends/base/query_compiler.py
- modin/backends/pandas/query_compiler.py
- modin/config/envvars.py
- modin/conftest.py
- modin/engines/base/frame/data.py
- modin/experimental/backends/omnisci/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_pickle.py
- modin/test/test_backends_api.py
* Fix Pickle support for Modin `DataFrame` and `Series` by implementing `__reduce__` protocol (ref: [Python docs](https://docs.python.org/3/library/pickle.html#object.__reduce__))
* Add new protected method `_materialize` to Modin Frame which makes sure all deferred functions for each partition are executed
* Add configuration variable `PersistentPickle` that controls how objects are pickled (backed by `MODIN_PERSISTENT_PICKLE` environment variable): in light mode we store all internals (like partitions), which should be faster for e.g. huge distributed DataFrames (we'll store just arrays of `Ray.ObjectIDs` instead of full data), in full mode it is possible to save pickled objects to disk and restore them in other Modin session but it is slower because we pull in all the data to the …
> Fix Pickle support for DataFrame and Series

- modin/pandas/test/test_io.py
I suspect the original issue had the same root cause as #2404 which I had earlier fixed by #2526, so #1733 should be fixed as well.
I'm now just enabling the test, as it passes fine on my local machine anyway.
> Re-enable TestExcel::test_read_excel

- docs/modin_xgboost.rst
- modin/experimental/xgboost/__init__.py
- modin/experimental/xgboost/test/test_default.py
- modin/experimental/xgboost/xgboost.py
This refactoring makes possible of using Modin XGBoost instead of classic xgboost by one-line code changes.
> REFACTOR-#2853: Add support of drop-in replacement of xgboost

- asv_bench/benchmarks/benchmarks.py
Motivation for these changes described in #2871.
> FIX-#2871: fix 'value_counts' benchmarks

- .github/workflows/ci.yml
- .github/workflows/push.yml
> FIX-#2882: Set timeout for IO tests on Windows

- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#2887: Match pandas error message on `Series.sum`

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_udf.py
> FIX-#2885: Allow level=-1 for non-multiindex in any/all

- modin/engines/base/io/text/csv_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#2073: Fix column names when `parse_dates` is enabled

- environment-dev.yml
- modin/engines/ray/pandas_on_ray/frame/partition.py
> FIX-#2844: Check for both types of ray.ObjectRef

- modin/experimental/cloud/meta_magic.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_general.py
* Fix defaulting to Pandas for empty Modin objects - only default if Pandas class we mimick has the attribute being called
* Allow potential renaming (or inheritance) of mimicking classes by introducing `._pandas_class` class attribute
* Slightly improve `_get_axis_number()` (plus add proper docstring to it)
> Fix defaulting to Pandas for empty Modin objects

- .github/workflows/ci.yml
- modin/experimental/sql/__init__.py
- modin/experimental/sql/test/__init__.py
- modin/experimental/sql/test/test_sql.py
- setup.cfg
- setup.py
Adds the ability to query Modin DataFrames with SQL statements.
How it works:
1. Install modin with [dfsql](https://github.com/mindsdb/dfsql).
``pip install modin[sql]``
2. Query using the `sql_query` interface:
```
>>> import modin.pandas as pd
>>> import modin.experimental.sql as mdsql
>>> df = pd.DataFrame({'col1': [1, 2, 3]})
>>> df.head()
col1
0     1
1     2
2     3
>>> mdsql.sql_query("SELECT col1 FROM df WHERE col1 = 1", from_tables={'df': df})
1
``` 
3. Alternatively, use the added `.sql` DataFrame accessor. It's registered when `modin.experimental.sql` is imported. In this case the `FROM` can be omitted:
```
>>> df.sql("SELECT col1 WHERE col1 = 1")
UserWarning: `from_dict` defaulting to pandas implementation.
1
```
> Experimental SQL support via dfsql

- modin/experimental/xgboost/test/test_default.py
- modin/experimental/xgboost/utils.py
- modin/experimental/xgboost/xgboost.py
- modin/experimental/xgboost/xgboost_ray.py
This changes add performance improvements to xgboost using several ways:
1. Variable number of actors, instead of `actor per node` approach
2. Evenly distribution with minimal difference of number parts per node(max difference is 1) for nodes in cluster.
3. Additional manipulation with cluster resources using ray placement groups.
> FIX-#2936: Improve performance of Modin XGBoost 

- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/pandas/utils.py
- modin/utils.py
<details><summary>How pandas processes grouping on index level</summary>
- We can specify level name in `by` parameter, mixing with column names is allowed: `df.groupby(by=["level_name", "col_name"])`
- We can specify index of the level via `level` parameter: `df.groupby(level=[0, 1])`
- We can't specify both `by` and `level` parameter (undocumented behaviour): `df.groupby(by="col_name", level=0) # Error`
</details>
This PR changes the way of handling grouping on the index level. Now it's splitting axis-by and level-by into two different variables (`by` and `level`) and then it's backend responsibility to make proper groups. Keeping columns and level names in different variables seems more convenient to me, rather than having a …
> FIX-#2531: fix handling level parameter in groupby

- modin/config/test/test_envvars.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FIX-#3017: Fix formatting for new `black` package

- modin/experimental/engines/pandas_on_ray/io_exp.py
- modin/experimental/engines/pandas_on_ray/sql.py
- modin/experimental/pandas/test/test_io_exp.py
Experimental `read_sql` was disabled for a long time, so some functions it is uses were deprecated and interconnections with the rest of the Modin code was outdated. This PR aims to fix this.
> FIX-#2194: fix experimental read_sql

- modin/engines/ray/generic/io.py
> FIX-#3025: use pandas.DataFrame as return value

- .github/workflows/ci.yml
- .github/workflows/push.yml
> FIX-#3031: Added -n 2 to long running pytest tasks and paralellized windows tasks

- .github/workflows/ci.yml
- asv_bench/benchmarks/utils.py
- modin/engines/base/frame/data.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/groupby.py
- modin/pandas/io.py
- modin/pandas/plotting.py
- modin/pandas/series.py
- modin/pandas/series_utils.py
- modin/test/test_utils.py
- modin/utils.py
- scripts/doc_checker.py
- scripts/test/examples.py
- scripts/test/test_doc_checker.py
**Note**: this is based on #3034 and should be rebased when that one is merged.
Improve `doc_checker.py` to handle a few specific corner cases.
Also make it skip numpydoc-validating inherited docstrings without requiring to disable numpydoc check.
> Improve doc checker

- modin/test/test_utils.py
- modin/utils.py
Fix handling `@staticmethod` and `@classmethod` decorators, add tests for `@_inherit_docstrings` (finally 🤣, should have made those from the start).
> Fix docstring inheritance

- modin/pandas/series_utils.py
- modin/pandas/test/test_series.py
> FIX-#3027: Removed unnecessary 'str.repeats' function, fixed test

- modin/backends/pandas/query_compiler.py
- modin/data_management/functions/groupby_function.py
- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/pandas/test/test_groupby.py
The original problem was that we were accessing `.columns` field from a grouping object, which is a Series sometimes. ~~Got rid of it by refactoring `groupby.size()`.~~ Now we're converting Series to DataFrame while constructing SeriesGroupBy object to be able to write common logic for DataFrame and Series (which sometimes involves accessing of DataFrame-specific attributes like `.columns`) at the base groupby class
> FIX-#2811: fix 'groupby.size' for Series

- modin/config/envvars.py
- modin/engines/ray/utils.py
Add `MODIN_REDIS_PASSWORD` environment variable (and corresponding `RayRedisPassword` configuration object) to allow controlling Redis password to be used during Ray initialization. This should allow connecting to an already spawned cluster in a non-cloud mode.
> FIX-#3116: Add variable to be able to set Redis password

- modin/engines/base/frame/partition.py
- modin/engines/dask/pandas_on_dask/frame/partition.py
- modin/engines/python/pandas_on_python/frame/partition.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/pandas/test/test_api.py
- modin/test/test_partition_api.py
This PR adds logic of partition's shape cache re-computing for the result of `.mask(slice)` based on the self shape cache. The common `.mask` logic was moved to the base pandas partition class, the differences of the shape re-computing based on the cache futures of different engines remained to the inheritors.
> FIX-#3110: preserve partitions shape cache when masking with a slice 

- .github/workflows/push-to-master.yml
- modin/config/envvars.py
- modin/conftest.py
Signed-off-by: Chris Wong <chriskw.xyz@gmail.com>
Same as #3140 but puts the ray client tests in push-to-master instead. Feel free to merge whichever of these PRs works better on your end, and close the other.
> TEST-#3085: Add testing for ray-client to push-to-master.yml

- docs/developer/architecture.rst
- docs/flow/modin/pandas/series.rst
- modin/pandas/series.py
> DOCS-#3153: add API section for `modin.pandas.series` in the documentation

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
This PR changes `not skipna` check to the `skipna is False` as the condition to do defaulting to pandas in the OmniSci reduction operations, so it won't do unnecessary fallbacks.
Please visit the [related issue](https://github.com/modin-project/modin/issues/3150) for more information.
> FIX-#3150: fix defaulting to pandas for reduction operations at OmniSci backend

- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FIX-#3160: handle columns metadata more carefully at 'reset_index'

- .github/workflows/ci.yml
- asv_bench/asv.conf.omnisci.json
- asv_bench/benchmarks/omnisci/__init__.py
- asv_bench/benchmarks/omnisci/benchmarks.py
- asv_bench/benchmarks/omnisci/io.py
- asv_bench/benchmarks/omnisci/utils.py
- asv_bench/benchmarks/scalability/scalability_benchmarks.py
- asv_bench/benchmarks/utils.py
- environment-dev.yml
- requirements-dev.txt
- requirements/requirements-no-engine.yml
* Add separate configuration for omnisci backend - `asv_bench/asv.conf.omnisci.json`, since the configuration name is different from the default (`asv.conf.json`) - we should explicitly specify it through the `--config` parameter
* Add trigger of omnisci execution via `frame._execute`
* Add new ASV version which is needed to be able to create an conda environment from yml file
* Benchmarking only working subset of all operations
> TEST-#2951: add ASV config for omnisci backend

- modin/backends/pandas/query_compiler.py
- modin/pandas/test/test_general.py
> FIX-#3063: Handle inplace side effect in `to_datetime`

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Remove the restriction for `on` param in merge operation in OmniSci backend to be a string.
> FEAT-#3193: support non-string column names for merge in OmniSci backend

- modin/engines/ray/utils.py
> FIX-#3151: Fix default size of Ray obj store memory

- modin/engines/base/frame/data.py
- modin/pandas/test/test_series.py
> FIX-#2164: Fix tests for BaseOnPython: test___repr__, test_dtype_empty

- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/pandas/indexing.py
Rewritten `OmnisciOnRayFrame._arrow_row_slice` function so now instead of slicing a table into small parts when the row indices are not continuous it just takes the specified indices by a single call of `pyarrow.Table.take`.
Performance changes at ASV:
```
MODIN_TEST_DATASET_SIZE=Big asv continuous origin/master HEAD --launch-method=forkserver --config asv.conf.omnisci.json -b omnisci.benchmarks.TimeIndexing --show-stderr --split --no-only-changed -a repeat=3
Benchmarks that have improved:
[a946564e]       [3157289b]
<master>       <slow-indexing>
-       318±0.3ms         188±20ms     0.59  omnisci.benchmarks.TimeIndexing.time_iloc((1000000, 10), 'list')
-        994±20ms          599±3ms …
```
> FIX-#3198: Rewrite arrow row slice

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FIX-#3171: compute shape hint at the QueryCompiler constructor

- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
> TEST-#3214: Add test for df/series.index after PandasFrame.to_pandas is called

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Buggy behavior presented in [the issue](https://github.com/modin-project/modin/issues/2856) was caused due to a naming conflict of "by" and the aggregation column names. The previous logic didn't handle such conflicts, which caused duplicated columns at the groupby result:
```python
>>> df
col1
0     1
1     1
2     2
3     3
>>> modin_frame.groupby_agg(by="col1", agg={"col1": "sum"})
col1  col1 # first column is an index col, and the second is actual column
1     2
2     2
3     3
```
Changes in this PR prevents GroupBy from producing frames with the duplicated columns by resolving column naming conflict in the same way as pandas do:
1. If `as_index=True` all by-columns gets `__index__` prefix and became a frame index
2. If …
> FIX-#2856: prevent duplicated columns at the groupby result

- modin/experimental/backends/omnisci/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
> FIX-#3195: Do not pass None parameters value to the backend, when it can be replaced by default one

- modin/config/envvars.py
- modin/config/pubsub.py
- modin/config/test/test_parameter.py
- modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py
> FEAT-#3191: make OmniSci engine configurable

- modin/experimental/engines/omnisci_on_ray/io.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> FIX-#3215: fix handling of `parse_dates` parameter by `read_csv` with OmniSci backend

- modin/engines/base/io/text/json_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#3313: Fix `read_json` metadata definition

- .github/workflows/ci.yml
- modin/experimental/cloud/rpyc_patches.py
- modin/experimental/cloud/rpyc_proxy.py
The error was in the module `rpyc.core.netref`. 
For the solution, it was necessary to patch the `_make_method` method. In the `_make_method` method, in the `name == "__array__ "` block, the `_array__` method must accept two parameters: `self` and `type`. Adding logic from `rpyc_patches.py`, I am correcting this error. Now the `__array__` method accepts the `type` parameter and processes it correctly. More information about the solution is written in https://github.com/modin-project/modin/issues/3296.
> Fix-#3296: Patch __array__ method for RPyC proxy objects

- .gitignore
- docs/developer/architecture.rst
- docs/flow/modin/backends/index.rst
- docs/flow/modin/data_management/factories.rst
- docs/flow/modin/experimental/backends/index.rst
- docs/flow/modin/experimental/backends/omnisci/index.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/frame/index.rst
- docs/flow/modin/experimental/engines/omnisci_on_ray/omnisci_engine.rst
- docs/installation.rst
- modin/experimental/engines/omnisci_on_ray/frame/df_algebra.py
- modin/spreadsheet/general.py
> FIX-#3311: Fix part of warnings in docs build

- .github/workflows/ci.yml
- modin/pandas/test/test_io.py
In the file `modin/pandas/test/test_io.py` many tests are marked as `xfail` in `"modin in the cloud"` mode. In addition, these `xfail` are located in the `if` blocks in the test body itself. This is wrong, as if this test somehow works, then there is no way to find out about it.
I looked through the entire file and rearranged `xfail` into the decorators. More information about the solution is written in https://github.com/modin-project/modin/issues/3295.
> Moving the `xfail` in the `test_io` file from the test code to the decorator

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_ray/frame/data.py
- modin/experimental/engines/omnisci_on_ray/frame/expr.py
- modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Support `nunique` aggregate in `groupby.agg` method.
> FEAT-#3336: support nunique aggregate in OmniSci backend

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_default.py
This PR does the next:
- fixes #3292 
- improves performance of `shift` operation
<details><summary>Performance results</summary>
The average time from 10 runs is shown (in seconds) in the tables below.
`df.shift(periods=10)`.
| nrows x ncols  | master  | PR #3345  | pandas  |
|---|---|---|---|
| 1k x 100 | 0.036  | 0.030| 0.0006  | 
| 1m x 100 |  0.871  | 0.042  | 0.729  | 
| 10m x 100  | 9.706   | 0.087 | 7.588  |
| 1k x 1k | 0.120   | 0.117 | 0.006   | 
| 10k x 10k | 1.062  | 1.087 | 0.733  | 
| 1m x 1k  | 1.124  |  0.293 | 7.156  | 
`df.shift(periods=500)`.
| nrows x ncols  | master  | PR #3345  | pandas  |
|---|---|---|---|
| 1k x 1k | 0.659   | 0.661 | 0.005 | 
| 10k x 10k | 3.498 | 3.480 | 0.710 | 
| 1m x 1k  | 1.626 | …
> FIX-#3292: Fix `shift` function when index has duplicates

- .github/workflows/ci.yml
- .github/workflows/push.yml
- environment-dev.yml
- modin/conftest.py
- modin/experimental/engines/omnisci_on_ray/io.py
- modin/pandas/__init__.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#3342: Update pandas to 1.3.2

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#3291, #3258: Fix `__setitem__` when key is unhashable list

- modin/pandas/test/test_io.py
> FIX-#3384: Fix `test_io.py::TestHdf::test_HDFStore` test

- modin/engines/base/io/text/json_dispatcher.py
`read_json` function doesn't have quoting parameter, so `is_quoting` variable is always True (QUOTE_NONE == 3), but `is_quoting` parameter default value is also True, so we don't need to explicitly define this parameter here.
> FIX-#3381: JSON dispatcher data file split correction

- asv_bench/benchmarks/utils/data_shapes.py
> FIX-#3401: all shapes don't depend on MODIN_BACKEND env

- modin/experimental/xgboost/test/test_xgboost.py
- modin/experimental/xgboost/xgboost_ray.py
> FIX-#3242: Fix processing of `evals` parameter in Modin xgb

- modin/engines/ray/pandas_on_ray/frame/axis_partition.py
- modin/engines/ray/pandas_on_ray/frame/partition.py
- modin/experimental/xgboost/xgboost_ray.py
> FIX-#3426: Use ray.util instead of ray.services for get_node_ip_address

- environment-dev.yml
> REFACTOR-#3176: Use ray from conda instead of pip

- modin/experimental/xgboost/xgboost.py
> FIX-#3395: Make `label` param of DMatrix optional

- modin/experimental/backends/omnisci/query_compiler.py
- modin/experimental/engines/omnisci_on_native/frame/expr.py
- modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
> FEAT-#3444: support logical 'and' and 'or' in filters.

- modin/experimental/engines/omnisci_on_native/frame/data.py
- modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
Fix `DataFrame.dtypes` for OmniSci backend by excluding index types from it.
> FIX-#3470: fix dtypes for OmniSci dataframes.

- docs/troubleshooting.rst
- modin/backends/pandas/parsers.py
- modin/engines/base/io/text/csv_dispatcher.py
> FIX-#3437: Warn user about heterogeneous data presence during read_csv call and propose workaround

- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
> TEST-#3474: fix pip install commmand in push-to-master

- modin/pandas/__init__.py
- modin/pandas/test/test_rolling.py
> FIX-#3447: Add attribute `api` in `modin.pandas`

- modin/engines/base/io/io.py
> FIX-#3475: pandas.read_gbq: remove deprecated parameters

- modin/core/io/text/csv_dispatcher.py
> DOCS-#3617: Fix typos in `modin.core.io.text.csv_dispatcher`

- modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition.py
Execute `DROP TABLE` for imported partitions on their deallocation.
> FIX-#3533: Drop OmniSci table on partition deallocation.

- environment-dev.yml
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
Ref: https://github.com/dask/s3fs/issues/514
> FIX-#3648: Pin minimal s3fs which is not aiobotocore-broken

- modin/experimental/core/execution/native/implementations/omnisci_on_native/expr.py
With OmniSci 5.8.0 we have to use FLOOR instead of CAST for float to int conversion to ensure truncate semantics.
> FIX-#3574: use floor for float to int cast.

- modin/core/io/column_stores/feather_dispatcher.py
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/io/file_dispatcher.py
- modin/core/io/text/csv_glob_dispatcher.py
- modin/utils.py
Make Modin throw custom errors when the optional s3fs and parquet modules are
missing, as Pandas would.
I tested this manually by uninstalling pyarrow and running `read_parquet` and
`read_feather`. I copied some of the common implementation from
[pandas.compat._optional.import_optional_dependency](https://github.com/pandas-dev/pandas/blob/a0660b2e3a0fbe872ff9a587af40d3633777107f/pandas/compat/_optional.py#L64).
Make Modin throw custom errors when the optional s3fs and parquet modules are
missing, as Pandas would.
> FIX-#3505: Throw custom errors for some missing packages.

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#3619: Fix ValueError when doing loc on empty dataframe

- modin/core/io/column_stores/feather_dispatcher.py
- modin/core/io/file_dispatcher.py
- modin/core/io/text/csv_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/pandas/test/test_io.py
PR adds support of `storage_options` parameter for (`read*` functions which have distributed implementation):
- `read_csv`
- `read_fwf`
- `read_json`
- `read_feather`
Support of `storage_options` for `read_excel` will be added in a separate PR #3565.
> FIX-#2301: Add support of `storage_options` in `read_*`

- modin/core/execution/ray/generic/io/io.py
> FIX-#3695: use 'ray.get' to pending completion for 'to_csv' and 'to_parquet'

- modin/core/execution/ray/common/utils.py
- modin/core/execution/ray/generic/io/io.py
- modin/pandas/test/test_io.py
If an exception occurs in one of the tasks, we must complete the rest, which are waiting for messages from `Queue` (communication channel). When using `get` function, this is done automatically.
Another reason for the hang could be the implementation of communication between tasks using one queue. Situations could arise when the same task put and took a message from the queue many times in a row, preventing other tasks from taking the message. To avoid this situation, I propose to use its own communication channel for each task (a separate events).
**Performance**:
Version| Master| PR
-|-|-
Pandas| 40,5 sec| 40,5 sec
Modin - 4 cores| 12,4 sec| 12,7 sec
Modin - 8 cores| 7,0 sec| 7,1 sec
Modin - 16 cores| 4,6 sec| 4,5 sec …
> FIX-#3551: fix hanging behaviour for to_csv

- docs/release-procedure.md
Clarify the GitHub release naming - it should read `Modin X.Y.Z`, not just `X.Y.Z` as GitHub fills it from tag initially.
> DOCS-#3712: Clarify GitHub release naming

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
> FEAT-#3554: Add support for `set_index` with different input types

- docs/release-procedure.md
- setup.py
Deletes platform-specific logic in setup.py so that the Python wheel file is [pure python](https://packaging.python.org/guides/distributing-packages-using-setuptools/#pure-python-wheels) so that all platforms can use the same wheel.
> FIX-#3616: Remove setup.py platform-specific logic to make distribution pure Python

- asv_bench/benchmarks/omnisci/benchmarks.py
> TEST-#3710: add groupby benchmarks with dict aggregation for omnisci

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_default.py
> FEAT-#3303: Add __getitem__ for Resampler

- ci/teamcity/Dockerfile.teamcity-ci
Updates the image in order not to use the outdated one.
> TEST-#3708: use 'latest' tag for 'rayproject/ray' base Ray image

- asv_bench/benchmarks/omnisci/benchmarks.py
- asv_bench/benchmarks/utils/common.py
> TEST-#3672: do fair 'join' at OmniSci's join bench

- docs/flow/modin/core/io/index.rst
> DOCS-#3610: Add section about handling of `read_csv` `skiprows` parameter

- modin/core/dataframe/algebra/default2pandas/resample.py
- modin/core/storage_formats/base/doc_utils.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
self.resample_args for Resampler converted into a dict to ensure simplicity of handling resample parameters at the query compiler level.
> FEAT-#3724: Converting self.resample_args for Resampler into a dict

- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_reduction.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
In #1628, some functions didn't work on Series with category dtype. Test some
other functions that Categorical natively supports.
In #1628, some functions didn't work on Series with category dtype. Test some
other functions that Categorical natively supports.
> TEST-#1628: Test some methods of categorical dataframes and series.

- modin/core/dataframe/algebra/groupby.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_reduction.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_series.py
Since this PR doesn't fix the actual problem but just hiding it, we should keep the #3571 open after the PR is merged.
> FIX-#3571: fallback to 'sort=True' on categorical keys in groupby

- modin/pandas/test/test_io.py
The HDF files that Modin and Pandas write sometimes have different bytes.
Instead of checking that they are exactly equal, check that they contain
the same dataframes.
I ran:
```
pytest modin/pandas/test/test_io.py -k test_HDFStore --count 100
```
locally and got 4 failures for 100 attempts. After this commit, I got no
failures.
> FIX-#3706: Deflake TestHdf.test_HDFStore.

- modin/config/envvars.py
- modin/core/execution/ray/common/utils.py
PR changes default Redis password to bo aligned with Ray default. This makes possible to not provide redis password in case using of default Ray cluster.
> FIX-#3744: Align default value of REDIS_PASSWORD with Ray

- .github/workflows/ci.yml
Retry setup-miniconda if it errors. This should reduce CI flakes due to Conda HTTP errors.
> TEST-#3729: Retry setup-miniconda if it errors.

- modin/core/io/text/text_file_dispatcher.py
- modin/pandas/test/test_io.py
Process `skiprows` more carefully to support different types of `skiprows` callable.
> FIX-#3510: Correct processing of callable `skiprows` parameter of `read_csv` function

- modin/pandas/test/test_groupby.py
Replaces `zip` to `zip_longest` in the GroupBy objects comparator. With this change the iteration over groups won't stop if one of the sequences has ended, it will only stop when <i>all of the</i> values have been compared, which properly raises an error when the sequences mismatch.
> FIX-#3756: compare all of the groups in GroupBy objects comparator

- modin/core/execution/ray/common/utils.py
This PR removes providing of `address` parameter for Ray local cluster.
> FIX-#3749: Remove providing of `address` for `ray.init` in case local cluster

- modin/experimental/xgboost/test/test_dmatrix.py
- modin/experimental/xgboost/test/test_xgboost.py
This PR fixes periodic failures in CI on `experimental/xgboost/test/test_dmatrix.py`. The fix is in changing of random generated data for training/prediction purposes to existing known dataset.
> FIX-#3767: Fix tests for Modin XGB Dmatrix

- modin/core/dataframe/pandas/dataframe/dataframe.py
Adds conditioning on computing new 'dtypes' at transpose: if `._dtypes` is None (computation delayed) keep it None for the transposed frame as well. Transpose of a frame with delayed 'dtypes' is a part of reduction operations flow ([columnarization at `Series` constructor](https://github.com/modin-project/modin/blob/f2133da30ba40786fcd421396b92f29bd121083c/modin/pandas/series.py#L160)), so these changes should speed-up at least reduction operations.
<details><summary>ASV benchmarks</summary>
Launch command:
```
MODIN_CPUS=16 MODIN_TEST_DATASET_SIZE=Big asv continuous -b "^benchmarks.TimeArithmetic" --show-stderr --no-only-changed 698f3632 lazy_transpose
```
```
[698f3632]       [a869c096] …
```
> FIX-#3725: do not trigger computation of lazy 'dtypes' on transpose

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/experimental/xgboost/test/test_dmatrix.py
- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_series.py
Work around https://github.com/pandas-dev/pandas/issues/44703 by not converting a categorical scalar to a 2-d array to set a categorical column.
> FIX-#3736: Don't use a 2-d array to set a categorical column.

- docs/developer/architecture.rst
- docs/developer/index.rst
- docs/developer/using_pandas_on_python.rst
- docs/flow/modin/core/execution/python/implementations/pandas_on_python/index.rst
PR adds `using_pandas_on_python.rst` doc
Actual doc build is here: https://modin--3809.org.readthedocs.build/en/3809/developer/using_pandas_on_python.html
> DOCS-#3782: Add `using_pandas_on_python.rst` doc

- modin/experimental/pandas/io.py
Remove second `FactoryDispatcher` import. The first is placed in  https://github.com/modin-project/modin/blob/195b66856b937af9e30c7baddcca7780478a55d2/modin/experimental/pandas/io.py#L27
> REFACTOR-#3820: remove extra 'FactoryDispatcher' import statement

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_series.py
- modin/pandas/utils.py
Adds a unified check of whether a slice indexer grabs the whole sequence (`is_full_grab_slice`) and replaces an incorrect full-grab check at the `df.__getitem__` with the call of the new function.
> FIX-#3702: add proper check for none-slice at `df.__getitem__`

- modin/pandas/test/utils.py
Signed-off-by: jeffreykennethli <jkli@ponder.io>
[test_io.p::TestExcel](https://github.com/modin-project/modin/blob/7c847581f8ce8b61307690c87884775eba8d034b/modin/pandas/test/test_io.py#L1482) open file handle checks currently catches our [check_file_leaks decorator](https://github.com/modin-project/modin/blob/7c847581f8ce8b61307690c87884775eba8d034b/modin/pandas/test/utils.py#L1083) check due to Ray session driver logs that are still open after read_excel(). check_file_leaks compares open files before and after a test case, therefore only the first instance where a Ray session is initiated will catch check_file_leaks.
The session logs still being open is the [intended Ray behavior](https://github.com/modin-project/modin/issues/3818#issuecomment-989332461), so our tests should ignore …
> FIX-#3818: Ignore files from /private/tmp/ray/ when detecting file leaks

- docs/developer/troubleshooting.rst
- docs/developer/using_omnisci.rst
- modin/config/envvars.py
- modin/core/storage_formats/pyarrow/query_compiler.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/utils.py
- setup.cfg
There is an interesting thing with omnisci import. We have to import it with dlopen flags. Wherein, if we perform this, we have to import omnisci after Modin itself is imported, i.e. the following code snippet won't work:
```python
cfg.Engine.put("Native")  # 'omniscidbe'/'dbe' would be imported with dlopen flags first time
cfg.StorageFormat.put("Omnisci")
cfg.IsExperimental.put(True)
import modin.pandas as pd  # Error
CommandLine Error: Option 'enable-vfe' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```
The error is apparently arisen since there are other libraries which use LLVM and may register an option in the same address space. …
> FIX-#3774: Fix omnisci import

- .github/workflows/ci.yml
- modin/experimental/cloud/rpyc_proxy.py
Signed-off-by: aleksandr.lozovskii <aleksandr.lozovskii@intel.com>
The problem was that in the `cloud` mode modin was created a proxy `DataFrame`, where the element type was not `float64`, as intended, but a proxy object. To solve this problem for `DataFrame`, we will pass the data parameter from the local side to the remote side.
> FIX-#3741: Added delivery of the data argument to df

- docs/flow/modin/core/dataframe/base/index.rst
- docs/flow/modin/core/dataframe/base/partitioning/axis_partition.rst
- docs/flow/modin/core/dataframe/pandas/dataframe.rst
- docs/flow/modin/core/dataframe/pandas/index.rst
- docs/flow/modin/core/dataframe/pandas/partitioning/axis_partition.rst
This expands the documentation sections about `modin.core.dataframe.base` and `modin.core.dataframe.pandas`.
They're mostly fine to my taste, but need a little of high-level sauce.
Do note that these changes introduce a `BaseDataframe` object which is _not_ actually in the code - it's going to be added by #3717, but that section felt too empty and meaningless without at least mentioning the interface class.
@RehanSD I think this should be the point where you would probably be inserting the documentation after #3717 is merged.
Preview: https://modin--3851.org.readthedocs.build/en/3851/developer/architecture.html
Any readability improvements are welcome!
> DOCS-#3850: Elaborate on modin.core.dataframe.base and .pandas

- modin/core/storage_formats/pandas/parsers.py
- modin/experimental/pandas/test/test_io_exp.py
This PR add possibility to specify storage options for remote buckets for `read_csv_glob` function.
> FEAT-#3829: Add support of `storage_options` for `read_csv_glob`

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/test/storage_formats/omnisci/test_internals.py
Adds a test, verifying that the natural ways of importing Modin with OmniSci backend don't fail, and also a test, indicating the current status of compatibility of PyDbEngine and pyarrow.gandiva packages.
> TEST-#3852: add a test for OmniSci import

- modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/test/test_dataframe.py
Optimize `append` with `ignore_index=True` by bypassing omnisci engine and doing all operations with arrow table.
> FEAT-#3875: Optimize append time for omnisci engine

- modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
> REFACTOR-#3881: remove unused '_read_parquet_columns' function

- docs/flow/modin/experimental/pandas.rst
> DOCS-#3873: fix 'more than one target found for cross-reference DataFrame' warning

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
Fix https://github.com/modin-project/modin/issues/3860 by setting the correct `axis` argument to the query compiler's `setitem` method. In the case where a single row and column are to be replaced, we are assigning both an entire row and an entire column, so `axis` should be `None` instead of `1`, so we don't transpose the new value [here](https://github.com/modin-project/modin/blob/d8963a691958d34627e503c7a437adade4935aa8/modin/core/storage_formats/pandas/query_compiler.py#L2230).
> FIX-#3860: Fix single row Series assignment.

- modin/pandas/accessor.py
- modin/pandas/test/test_io.py
- requirements/env_omnisci.yml
Fix the default to pandas in pd.DataFrame.sparse.from_spmatrix by not trying to use an instance method.
> FIX-#3890: Fix the default to pandas in pd.DataFrame.sparse.from_spmatrix.

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/dataframe/pandas/utils.py
> REFACTOR-#3885: Move PandasDataframePartitionManager.concatenate to a utils

- .github/workflows/ci.yml
1. For now, after building docs, we can simply look at the current warnings. After they are fixed (in a separate pull request), we should add `-W --keep-going` so that any warning leads to an error.
> TEST-#3869: add build-docs check in CI

- NOTICE
- docs/conf.py
> DOCS-#3936: Update copyright year

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/utils.py
At the issue discussion (#3219) it was decided to move the frame's type inference for the `.apply()` result to the QC level, since the result type strictly depends on the UDF's behavior, which is only known at the execution level. This PR updates the contract for the `query_compiler.apply()` method as well as its behavior to do the inferring.
> FIX-#3219: delegate 'apply' result type inference to backend

- .github/PULL_REQUEST_TEMPLATE.md
Fix links to the contributing page in the pull request template.
- [N/A] tests added and passing
> DOCS-#3960: Fix links to the contributing page.

- modin/core/dataframe/algebra/default2pandas/groupby.py
- modin/core/dataframe/algebra/groupby.py
- modin/core/storage_formats/base/doc_utils.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/test/test_dataframe.py
- modin/experimental/core/storage_formats/omnisci/query_compiler.py
- modin/pandas/groupby.py
This PR gets rid of passing Python lambdas to the backend as an implementation for basic GroupBy aggregations. Instead of passing lambdas to a single `groupby_agg` method, different aggregations were dedicated into separate query compiler methods. This PR adds 15 new methods to the query compilers API, all of them implemented like:
```python
def groupby_some_aggregation(self, *args, **kwargs):
return self.groupby_agg(agg_func="some_aggregation", *args, **kwargs)
```
this allows for previous implementations at the different query compilers to work the same as before, because actual computations are still performed by the `groupby_agg`, the only difference is that it now takes string function names instead of callable. It's supposed …
> FIX-#3197: do not pass lambdas to the backend in GroupBy

- docs/conf.py
Signed-off-by: jeffreykennethli <jkli@ponder.io>
Change the docs copyright statement to match the statement in our [NOTICE](https://github.com/modin-project/modin/blob/master/NOTICE) file.
> FIX-#3962: Change docs copyright statement to 'Modin Developers.'

- setup.py
Exclude `scripts` and its subdirectories from setup package.
> Exclude "scripts" from setup package

- modin/core/dataframe/pandas/dataframe/dataframe.py
Moves the code that raises an error in `_propagate_index_objs` if an incorrect axis argument is provided out of the codepath for when the axis provided is the column axis, and into its own codepath.
> FIX-#4026: Move code to raise error to appropriate place.

- modin/pandas/series.py
- modin/pandas/test/test_series.py
Signed-off-by: jeffreykennethli <jkli@ponder.io>
Modify Series.values to default to Series.to_numpy(), which conveniently handles the empty dataframe/series case from #3896.
In [pandas/base.py](https://github.com/modin-project/modin/blob/master/modin/pandas/base.py#L3075-L3087), notice that if an attr is callable and self.empty, we default to pandas like in [Series.to_numpy()](https://github.com/modin-project/modin/blob/master/modin/pandas/series.py#L1863-L1877) which would fix our empty Series case from #3896. 
Because to_numpy() and .values are supposed to have identical behavior (see [pandas.Series.values](https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html) and [this PR](https://github.com/pandas-dev/pandas/pull/23623)), we can safely make Series.values call …
> FIX-#3896: Change Series.values to default to to_numpy().

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/omnisci_on_native/test/utils.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
We are currently converting Categoricals to lists, losing their dtypes.
Fix assigning a Categorical to a column.
We are currently converting Categoricals to lists, losing their dtypes.
> FIX-#3895: Fix assigning a Categorical to a column.

- modin/__main__.py
- modin/config/envvars.py
- modin/pandas/__init__.py
- modin/test/test_utils.py
- modin/utils.py
- setup.cfg
This is an augmentation for [pandas.show_versions()](https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.show_versions.html) plus an ability to call this from command line in an easy way.
<details><summary>Example output</summary>
```
>python -m modin --versions
INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Russian_Russia.1251
Modin dependencies
------------------
modin            : 0.12.0+80.gdd2c53f6
ray …
```
> Implement "modin.pandas.show_versions()" and "python -m modin --versions"

- .github/workflows/ci.yml
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/test/test_dataframe.py
- modin/pandas/io.py
The problem is that when `FactoryDispatcher` is imported, command `Engine.subscribe(FactoryDispatcher._update_factory)` is executed before `Engine` config correction in `Engine.subscribe(_update_engine)`, that leads to incorrect factory search. To fix it we need to update `Engine` before `FactoryDispatcher` import.
> FIX-#4017: Fix OmniSci engine enabling for IO functions

- README.md
- docs/getting_started/faq.rst
- docs/getting_started/installation.rst
- docs/getting_started/troubleshooting.rst
- docs/getting_started/using_modin/using_modin_locally.rst
- docs/getting_started/why_modin/modin_vs_dask_vs_koalas.rst
- docs/getting_started/why_modin/pandas.rst
Fix links in the Modin README and improve some of the wording in both the FAQ and README. Resolves https://github.com/modin-project/modin/issues/3904
> DOCS-#3904: Improving Modin README

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/test/utils.py
- requirements/env_omnisci.yml
This PR bumps OmniSci version to 5.10.1 and PyArrow to 6.* as well (as this is the minimum supported version by OmniSci now).
Arrow introduced an implicit `time32` values parsing when reading from CSV ([ARROW-11243](https://issues.apache.org/jira/browse/ARROW-11243)), this brought 2 problems for us:
1. We can't easily disable the automatic inference (the same problems as in #3485), that's why we just ignore the differences in dtypes between Modin on OmniSci and pandas in IO-tests (added another exception in [`align_datetime_dtypes`](https://github.com/dchigarev/modin/blob/3738915bdb43fe6308857da8021331ff1ed5644e/modin/experimental/core/execution/native/implementations/omnisci_on_native/test/utils.py#L76) - preprocessor function …
> FIX-#3945: bump omnisci version to 5.10.1

- .github/workflows/ci.yml
Delete the failed attempt from #3760 to retry setup-miniconda. The new arguments don't do anything as explained [here](https://github.com/modin-project/modin/issues/3729#issuecomment-1017777466).
> TEST-#3729: Delete the failed attempt to retry setup-miniconda.

- docs/flow/modin/core/dataframe/base/dataframe.rst
> DOCS-#4079: Fix link PandasDataframe in docs

- .github/PULL_REQUEST_TEMPLATE.md
- docs/release_notes/release_notes-0.14.0.rst
- docs/release_notes/release_notes-template.rst
> DOCS-#4077: Add release notes template to docs folder

- .readthedocs.yaml
- docs/release_notes/release_notes-0.14.0.rst
PR adds missed after #4073 formats of doc builds
> DOCS-#4082: Add `pdf`/`epub`/`htmlzip` formats for doc builds

- docs/release_notes/release_notes-0.14.0.rst
- docs/requirements-doc.txt
- modin/core/storage_formats/pandas/parsers.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/test_concat.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
- modin/test/test_envvar_npartitions.py
- modin/test/test_partition_api.py
- scripts/doc_checker.py
These changes fix the failed CI. Issues list:
1. #4113 
2. #4115 
3. #4116
> FIX-#4113, FIX-#4116, FIX-#4115: Apply new `black` formatting, fix pydocstyle check and readthedocs build

- .github/PULL_REQUEST_TEMPLATE.md
> FIX-#4122: align links in PR template with the actual docs structure

- docs/release_notes/release_notes-0.14.0.rst
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_pickle.py
Allow pickling empty dataframes and series.
We need to implement [`__reduce_ex__`](https://docs.python.org/3/library/pickle.html#object.__reduce_ex__) for `Series` and `Dataframe` for `pickle` to pickle them with their own `__reduce__` methods instead of defaulting to pandas for `__reduce_ex__`.
> FIX-#4058: Allow pickling empty dataframes and series.

- .github/workflows/ci.yml
- .github/workflows/push.yml
- docs/release_notes/release_notes-0.14.0.rst
> TEST-#3227: use codecov github action instead of bash form

- docs/release_notes/release_notes-0.14.0.rst
- modin/pandas/test/test_io.py
> FIX-#4162: Use `skipif` instead of `skip` for compatibility with pytest 7.0

- docs/release_notes/release_notes-0.14.0.rst
- modin/config/envvars.py
Explicitly passes `--enable_thrift_logs=0` parameter to the OmniSci server to omit thrift logs.
> FIX-#4158: Do not print OmniSci logs to stdout by default

- docs/getting_started/troubleshooting.rst
- docs/release_notes/release_notes-0.14.0.rst
> DOCS-#4168: Fix rendering the examples on troubleshooting page

- docs/release_notes/release_notes-0.14.0.rst
- docs/requirements-doc.txt
PR removes temporary workaround for building our docs.
> FIX-#4115: Unpin `pip` in readthedocs deps list

- docs/getting_started/installation.rst
- docs/release_notes/release_notes-0.14.0.rst
Conda is rather slow installing modin-all and some other packages. Using strict channel priority speeds up the process
> DOCS-#4173: Mention strict channel priority in conda install section

- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- docs/release_notes/release_notes-0.14.0.rst
1. PR add `lint-commit` check as separate workflow `ci-required` to be run in each PR.
2. The list of triggers-paths in workflow `ci` is expanded to list described here https://github.com/modin-project/modin/pull/4092#issuecomment-1026210166
3. As `lint-commit` became a separate workflow it was removed from dependencies of jobs in `ci` workflow.
> TEST-#4153: Fix condition of running lint-commit and set of CI triggers

- docs/release_notes/release_notes-0.14.0.rst
- modin/core/io/file_dispatcher.py
- modin/pandas/test/test_io.py
Support `read_feather` from pathlike objects.
> FIX-#4177: Support read_feather from pathlike objects.

- docs/release_notes/release_notes-0.14.0.rst
- modin/pandas/__init__.py
- modin/pandas/test/test_api.py
> REFACTOR-#4229: remove unused `dask_client` global variable in `modin\pandas\__init__.py`

- docs/release_notes/release_notes-0.14.0.rst
- modin/core/storage_formats/pandas/parsers.py
- modin/pandas/test/test_series.py
Fixed the issue in #4257. `np.sort()` cannot be called on 0-dimensional arrays, so create a special case.
> FIX-#4257: Fix Categorical() for scalar categories

- docs/release_notes/release_notes-0.14.0.rst
- modin/core/dataframe/algebra/__init__.py
- modin/core/dataframe/algebra/groupby.py
- modin/core/storage_formats/pandas/query_compiler.py
Move `is_reduce_fn` outside of the pandas query compiler's `groupby_agg`.
> REFACTOR-#4322: Move is_reduce_fn outside of groupby_agg.

- README.md
- docs/requirements-doc.txt
- modin/core/storage_formats/pandas/parsers.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/test_concat.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
- modin/test/test_envvar_npartitions.py
- modin/test/test_partition_api.py
- scripts/doc_checker.py
This change is for _0.13.3 release_ branch, and its point is to make the link to documentation to always point to its documentation (not to the latest or stable or anything), so it keeps the same regardless of our further actions.
We also introduce the changes from PR #4114, which fixes issues #4113, #4116, #4115 to make CI green. The changes almost match the ones from the PR #4114 except pinning pip in `docs/requirements-doc.txt`. We unpin pip since we did that in master and the issue was temporary.
> Release version 0.13.3 - pin pypi and docs

- .github/workflows/ci.yml
- .github/workflows/push.yml
- docs/release_notes/release_notes-0.14.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/test/exchange/dataframe_protocol/pandas/__init__.py
- modin/test/exchange/dataframe_protocol/pandas/test_protocol.py
> FEAT-#4342: Support `from_dataframe` for pandas storage format

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/dataframe/base/exchange/dataframe_protocol/dataframe.py
- modin/core/dataframe/pandas/exchange/dataframe_protocol/dataframe.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/dataframe.py
- modin/test/exchange/dataframe_protocol/omnisci/test_protocol.py
- modin/test/exchange/dataframe_protocol/pandas/test_protocol.py
> FEAT-#4359: Add __dataframe__ method to the protocol dataframe

- docs/release_notes/release_notes-0.15.0.rst
- environment-dev.yml
- requirements-dev.txt
- requirements/requirements-no-engine.yml
PR updates min pin for xgboost, because Modin uses behavior of xgboost which started from 1.5.0.
> FIX-#4327: Update min pin for xgboost version

- docs/release_notes/release_notes-0.15.0.rst
- environment-dev.yml
- requirements-dev.txt
- requirements/requirements-no-engine.yml
PR removes explicit dependency `pathlib` from all deps because `pathlib` is a part of python standard lib starting from py3.4.
> FIX-#4383: Remove `pathlib` from deps

- .github/workflows/push-to-master.yml
- docs/release_notes/release_notes-0.15.0.rst
- modin/pandas/general.py
- modin/pandas/io.py
Signed-off-by: alexander3774 <myskova977@gmail.com>
This PR fixes failed `test docs` CI job.
> FIX-#4370: Fix broken docstring links

- .readthedocs.yaml
- docs/release_notes/release_notes-0.15.0.rst
Signed-off-by: alexander3774 <myskova977@gmail.com>
Closes #4388.
This PR turns off `fail_on_warning` option for readtrhedocs docs build since this option can cause docs build fail.
> DOCS-#4388: Turn off `fail_on_warning` option for docs build

- docs/release_notes/release_notes-0.15.0.rst
- environment-dev.yml
- modin/config/envvars.py
- modin/core/io/sql/sql_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/db_conn.py
- modin/pandas/test/test_io.py
- requirements-dev.txt
- requirements/requirements-no-engine.yml
Add connectorx as an alternative engine for `read_sql`. #4320
I tested locally by setting the env var `READ_SQL_ENGINE` to `connectorx` and it works fine. However, when I set the config by `ReadSqlEngine.put("connectorx")` (like [here](https://github.com/wangxiaoying/cx-modin/blob/main/tpch-modin.py#L29)), the result of `ReadSqlEngine` retrieved in the `PandasSQLParser` is `pandas`. It's very likely that I missed some setup of the config. Can you take a look?
> FEAT-#4320: Add `connectorx` as an alternative engine for `read_sql`

- .github/workflows/push-to-master.yml
- docs/release_notes/release_notes-0.15.0.rst
PR removes using of deprecated functionality of pip during creating of dev env.
> FIX-#4385: Get rid of `use-deprecated` option in `pip`

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/io/column_stores/column_store_dispatcher.py
- modin/pandas/test/test_io.py
In #3527 , we found that partitions from `read_parquet` would have negative `_length_cache`, giving a `ValueError: lengths cannot be negative` when trying to materialize results, such as when indexing into a DataFrame by column name. `_length_cache` is set when the DataFrame is initialized and partitioned. For parquet files, this is in the [column_store_dispatcher](https://github.com/modin-project/modin/blob/master/modin/core/io/column_stores/column_store_dispatcher.py).
The previous logic would partition the row lengths with a minimum chunk size (32 rows). For DataFrames with less than 32 total rows, it would partition the rows:
`[32, 0, 0, .... , 0]` for each of the N partitions.
For DataFrames with more than `num_partitions * min_chunk_size` rows i.e. `index_len >= min_chunk_size * …
> FIX-#3527: Fix parquet partitioning issue causing negative row length partitions

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/execution/ray/common/utils.py
Override the memory limit to start ray 1.11.0 on Macs.
- [🚫 ] tests added and passing, but I did test manually with object store sizes 2147483648 and 2147483649
> FIX-#4330: Override the memory limit to start ray 1.11.0 on Macs.

- .github/workflows/ci.yml
- docs/development/architecture.rst
- docs/flow/modin/core/storage_formats/index.rst
- docs/flow/modin/experimental/core/storage_formats/index.rst
- docs/flow/modin/experimental/core/storage_formats/pyarrow/index.rst
- docs/flow/modin/experimental/core/storage_formats/pyarrow/parsers.rst
- docs/flow/modin/experimental/core/storage_formats/pyarrow/query_compiler.rst
- docs/release_notes/release_notes-0.15.0.rst
- modin/core/storage_formats/__init__.py
- modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/io/io.py
- modin/experimental/core/storage_formats/pyarrow/__init__.py
- modin/experimental/core/storage_formats/pyarrow/parsers.py
- modin/experimental/core/storage_formats/pyarrow/query_compiler.py
- modin/test/test_executions_api.py
Signed-off-by: Igoshev, Yaroslav <Poolliver868@mail.ru>
> REFACTOR-#3642: Move PyArrow storage format usage from main feature to experimental ones

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/io/text/csv_glob_dispatcher.py
- modin/experimental/pandas/test/test_io_exp.py
Signed-off-by: Anatoly Myachev <anatoliimyachev@mail.com>
> FIX-#4373: Fix invalid file path when trying `read_csv_glob` with `usecols` parameter

- docs/release_notes/release_notes-0.15.0.rst
- modin/test/test_utils.py
Signed-off-by: proxodilka <zeeron209@gmail.com>
> FIX-#4422: get rid of case sensitivity for warns_that_defaulting_to_pandas

- docs/release_notes/release_notes-0.15.0.rst
- modin/pandas/test/test_groupby.py
- [N/A] tests added and passing
> TEST-#4426: Stop passing is_default kwarg to Modin and pandas.

- docs/release_notes/release_notes-0.15.0.rst
- modin/config/__main__.py
- modin/experimental/cloud/tracing/parse_rpyc_trace.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/df_algebra.py
- setup.cfg
Signed-off-by: alexander3774 <myskova977@gmail.com>
In the new release of the `flake8-print` plugin error code `T001` was changed to `T201`. We need to reflect this change in the Modin CI to avoid CI fail.
> FIX-#4439: Fix `flake8` CI fail

- docs/release_notes/release_notes-0.15.0.rst
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
> FIX-#4409: Fix `eval_insert` utility that doesn't actually check results of `insert` function

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/test/dataframe/test_indexing.py
> TEST-#4482: Fix getitem and loc with series of bools.

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
> FIX-#4449 Drain the call queue before waiting on result in benchmark mode.

- docs/release_notes/release_notes-0.15.0.rst
- environment-dev.yml
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
Signed-off-by: Andrew Li <orcahmlee@gmail.com>
Add black and flake8 into requirements-dev.txt
> FIX-#3689: Add black and flake8 into development environment files

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/io/text/excel_dispatcher.py
- modin/error_message.py
> DOCS-#4466: Recommend GitHub issues over bug_reports@modin.org.

- docs/release_notes/release_notes-0.15.0.rst
- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
Signed-off-by: Anatoly Myachev <anatoliimyachev@mail.com>
> FIX-#4456: fix loc in case when need reindex item

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_series.py
> FIX-#4481: Allow clipping with a Modin Series of bounds.

- docs/release_notes/release_notes-0.15.0.rst
- modin/logging/config.py
Make the memory thread [daemonic](https://docs.python.org/3/library/threading.html#thread-objects) so that "the entire Python program exits when only daemon threads are left."
> FIX-#4503: Stop the memory logging thread after session exit.

- docs/release_notes/release_notes-0.15.0.rst
- modin/error_message.py
Modin Logging currently reports several lines like:
> 88001, 4538414592, 2022-05-26,16:44:07.377470, START::MODIN-ERROR::ErrorMessage.catch_bugs_and_request_email
> 88001, 4538414592, 2022-05-26,16:44:07.377538, STOP::MODIN-ERROR::ErrorMessage.catch_bugs_and_request_email
We want to only report the specific errors and not the API calls to these functions that do not raise the actual exceptions.
> FIX-#4518: Fix Modin Logging to report specific Modin warnings/errors

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_indexing.py
Signed-off-by: Anatoly Myachev <anatoliimyachev@mail.com>
> FIX-#4438: Fix `reindex` function that doesn't preserve initial index metadata

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/ray/common/utils.py
- modin/pandas/test/dataframe/test_map_metadata.py
> PERF-#4493: Use partition size caches more in Modin dataframe.

- docs/release_notes/release_notes-0.15.0.rst
- modin/experimental/pandas/io.py
Signed-off-by: alexander3774 <myskova977@gmail.com>
Refactoring `modin.experimental.pandas.io` to be in line with changes introduced in #4017.
Closes #4510.
> REFACTOR-#4510: Align experimental and regular IO modules initializations

- docs/flow/modin/core/io/index.rst
Leftover from https://github.com/modin-project/modin/pull/4514 and referenced in https://github.com/modin-project/modin/pull/4514#discussion_r890815750
> DOCS-#0000: Correct typo in flow/modin/core/io/index.rst

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
> FIX-#4531: Fix a makedirs race condition in to_parquet.

- scripts/doc_checker.py
Show `pydocstyle` standard error as well as its output if it fails a check on something.
I haven't added a line to release notes because it seems a little pointless 🙃
> FIX-#4538: Show pydocstyle stderr

- docs/release_notes/release_notes-0.15.0.rst
- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/test_series.py
Fix to_pydatetime dtype for timezone None.
> FIX-#4436: Fix to_pydatetime dtype for timezone None.

- .github/workflows/ci.yml
- docs/release_notes/release_notes-0.16.0.rst
Reduce test_partition_api pytest threads to deflake it.
I was able to reproduce the failure in 3/3 CI runs on a branch where the CI in push.yml only ran this test. I reduced the number of pytest cores to the default of 1 and 4/4 runs passed.
> TEST-#4508: Reduce test_partition_api pytest threads to deflake it.

- docs/requirements-doc.txt
- environment-dev.yml
- modin/config/envvars.py
- modin/utils.py
- requirements-dev.txt
- setup.py
> FIX-#4566: Pin Ray < 1.13.0 to avoid deserialization race condition.

- docs/release_notes/release_notes-0.15.0.rst
- docs/release_notes/release_notes-0.16.0.rst
- modin/core/io/text/text_file_dispatcher.py
- modin/pandas/test/data/issue_4543.csv
- modin/pandas/test/test_io.py
This PR fixes corner cases when `read_csv` is used with `skiprows` + `usecols` parameters.
> FIX-#4543: Fix `read_csv` in case skiprows=<0, []>

- asv_bench/benchmarks/utils/common.py
- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/partition.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/virtual_partition.py
- modin/core/execution/ray/generic/modin_aqp.py
- modin/core/execution/ray/generic/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/distributed/dataframe/pandas/partitions.py
- modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/partitioning/axis_partition.py
- modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/partitioning/partition.py
- modin/test/test_partition_api.py
This PR unifies the API for accessing to the internal data in partition.
> REFACTOR-#4530: Standardize access to physical data in partitions

- docs/release_notes/release_notes-0.16.0.rst
- docs/requirements-doc.txt
- environment-dev.yml
- requirements-dev.txt
- setup.py
> FIX-#4589: Pin protobuf<4.0.0 to fix ray.

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_iter.py
This PR addresses issue #4577 which ended up being quite a simple fix but involved a fair amount of soul-searching (thank you to @RehanSD for helping me with this on your day off). Previously, update to DataFrame columns via attribute manipulation would handle things correctly internally, but wouldn't set the attribute properly for the Modin DataFrame. As a result, if a column were to be set to a list, it would return a list when we tried to access the column by attribute (when it really should have been a pandas Series). The test included has a good example of this behavior.
> FIX-#4577: Set attribute of Modin dataframe to updated value

- docs/release_notes/release_notes-0.16.0.rst
- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/requirements-no-engine.yml
- setup.py
> FEAT-#4598: Add support for pandas 1.4.3

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/base.py
- modin/pandas/test/test_series.py
This PR addresses #4411 which tried to add a pandas.timedeltas to a datetime64 Series. The bug ended up being tied up with how we validated binary operations, so I took the liberty to clean up code in `_validate_other` since I didn't see any of the dtype flags used anywhere else in the code. I also added in a test to validate the original posted issue.
> FIX-#4411: Fix binary_op between datetime64 Series and pandas timedelta

- docs/release_notes/release_notes-0.16.0.rst
- modin/logging/class_logger.py
- modin/test/test_logging.py
Fix inheritance of custom log layer. It's still possible to use `PANDAS-API` log layer in subclasses, but to do so one has to set it explicitly.
> FIX-#4582: Inherit custom log layer

- .github/workflows/ci-notebooks.yml
- docs/release_notes/release_notes-0.16.0.rst
This PR removes explicit installation of black and flake8 packages from conda for `ci-notebooks` (omnisci_on_native) because the packages were already installed from pip.
> TEST-#4610: Remove explicit installation of `black`/`flake8` for omnisci ci-notebooks

- .github/workflows/ci.yml
- contributing/pre-commit
- docs/release_notes/release_notes-0.16.0.rst
- environment-dev.yml
- modin/config/envvars.py
- modin/config/pubsub.py
- modin/conftest.py
- modin/logging/class_logger.py
- modin/logging/config.py
- modin/logging/logger_decorator.py
- mypy.ini
- requirements-dev.txt
This PR addresses #4619 and implements the first cut of mypy integration. The goal is to start off with small modules and work our way up to the majority of our codebase. I decided to start off with the logging module since the amount of code is fairly small. Please note that this PR is still in the works as I need to add CI integration and make other changes.
> FEAT-#4619: Integrate mypy static type checking

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_iter.py
Signed-off-by: Hazem Elmeleegy <hazem@ponder.io>
> FIX-#4593: Ensure Modin warns when setting columns via attributes

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/push-to-master.yml
- .github/workflows/push.yml
- docs/release_notes/release_notes-0.16.0.rst
Bring back caching for conda setup and switch to `mamba` solver for faster environment creation during CI runs.
This should reduce CI run time yielding better turnaround for churning through PRs.
I have seen this PR reducing the conda environment creation time from ~8-10 minutes up to 3 minutes (which might not seem as a big improvement, but remember to multiply by amount of jobs and then by amount of pushes to PRs).
> TEST-#2564: Add caching and use mamba for conda setups in GH

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#4604: fix groupby+agg in case when multicolumn can arise

- docs/release_notes/release_notes-0.16.0.rst
- docs/supported_apis/dataframe_supported.rst
Documentation update to specify Dask vs Ray differences and parallel implementation cases of to_parquet with Ray as per discussion within #4624.
Note: no tests added as update only changes documentation.
> DOCS-#4628: add to_parquet partial support notes

- docs/release_notes/release_notes-0.16.0.rst
- modin/conftest.py
- modin/experimental/cloud/local_cluster.py
Enable using `pdb.set_trace()` and stuff like that on remote side of cloud connection, to facilitate debugging cloud-related issues.
> FIX-#4584: Enable pdb debug when running cloud tests

- docs/getting_started/troubleshooting.rst
- docs/release_notes/release_notes-0.16.0.rst
- docs/requirements-doc.txt
- environment-dev.yml
- modin-autoimport-pandas.pth
- modin/config/envvars.py
- modin/core/execution/ray/common/utils.py
- modin/utils.py
- requirements-dev.txt
- setup.py
Based on what I found in https://github.com/modin-project/modin/issues/4564#issuecomment-1165419056, I think the real root cause of #4564 (and other similar issues with inability to import pandas) is the Python bug https://bugs.python.org/issue38884, which rises from the fact that they seem to have dropped the idea of the import lock in Python 3.3+.
This PR aims to workaround that by doing the following:
1. Create special `.pth` file to be shipped which, when package is installed, is placed under `site-packages` automatically and, when processed by Python interpreter, imports `pandas` if special environment variable is set
2. Change `setup.py` so this special file is part of both source and binary distributions
3. Initialize Ray so it sets this environment variable on each worker
4. Check …
> FIX-#4564: Workaround import issues in Ray: auto-import pandas on python start if env var is set

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_reduce.py
`df.describe(include='all')` can sometimes encounter cases where partitions have different indexes as a result of having different data types (e.g. categorial data returns different summaries as opposed to numerical data). Since we already know what the index of the final DataFrame should look like, we can set the correct index for the partition via `reindex`. Special thanks to @mvashishtha and @RehanSD for helping me understand what was going on in the lower-levels of Modin. This was a fun one to track down.
> FIX-#4641: Reindex pandas partitions in `df.describe()`

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/dataframe.py
- modin/pandas/test/test_groupby.py
`FrozenList` should be treated as a "list-like" object in `groupby`. However, compared to most list-like objects, `FrozenList` is actually hashable, which causes us to go down the wrong code path. This PR addresses that issue.
> FIX-#4634: Check for FrozenList as `by` in `df.groupby()`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
When running in benchmark mode, results from partitions are waited for with a single call to `ray.get` rather than iterating over each partition and calling `ray.wait` under the hood. As the original issue (#4491) suggests, the performance improvement seems to be fairly negligible.
> FIX-#4491: Wait for all partitions in parallel in benchmark mode

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_map_metadata.py
Implements `convert_dtypes` by mapping across partitions instead of defaulting to pandas.
> FEAT-#4670: Implement convert_dtypes by mapping across partitions

- docs/conf.py
- docs/release_notes/release_notes-0.16.0.rst
> DOCS-#4668: Set light theme for readthedocs page, remove theme switcher

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/io/file_dispatcher.py
- modin/core/io/text/csv_glob_dispatcher.py
- modin/pandas/test/test_io.py
The PR expand the set of handled exceptions in `read_*` functions from s3 storages by `EndpointConnectionError` exception
> FIX-#4658: Expand exception handling for `read_*` functions from s3 storages

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
Add Modin-level logging to PandasDataframePartitionManager.
> FEAT-#4706: Add Modin ClassLogger to PandasDataframePartitionManager

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
This PR speedups sequential-execution part of `drop` implementation.
<details><summary>Benchmark results</summary>
<details><summary>Benchmark code</summary>
```python
import time
import pandas as pd
from modin.config import BenchmarkMode
BenchmarkMode.put(True)
def get_time(op):
start = time.time()
result = op()
return time.time() - start
if __name__ == "__main__":
n_runs = 3
nrows = 10_000_000
df = pd.Series([0] * nrows)
def operation():
return df.drop(df.index)
all_time = 0
print(f"\tZero call: {get_time(operation)} s")
for i in range(n_runs):
t = get_time(operation)
print(f"\tIteration #{i}: {t} s")
all_time += t
print(f'Time drop op: {all_time / n_runs} s')
```
</details>
1. Performance results for operation `df.drop(df.index)`: …
> PERF-#3844: Improve perf of `drop` operation

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/series.py
```
cfg.BenchmarkMode.put(True)
import ray
ray.init()
arr = np.random.randn(100_000, 2)
df = pd.DataFrame(arr)
df.index = pd.MultiIndex.from_product([list('abcdefghij'), np.arange(10_000)])
df = pd.concat([df]*10)
In [4]: %timeit df[0] + df[1]
337 ms ± 6.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # <- master
264 ms ± 6.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # <- PR
In [5]: df = pd.concat([df]*10)
In [6]: %timeit df[0] + df[1]
3.29 s ± 132 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # <- master
2.63 s ± 334 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # <- PR
```
> PERF-#4705: Improve perf of arithmetic operations between `Series` objects with shared `.index`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/ray/implementations/pandas_on_ray/dataframe/dataframe.py
- modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/dataframe/dataframe.py
REFACTOR-#4708: Delete combine dtypes.
> REFACTOR-#4708: Delete combine dtypes.
