modin-project/modin

- docs/release_notes/release_notes-0.16.0.rst
- modin/config/__main__.py
- modin/config/envvars.py
- modin/config/pubsub.py
- mypy.ini
This PR adds type annotations and various fixes found by `mypy` to `modin/config`.
> REFACTOR-#4629: Add type annotations to `modin/config`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/io/pickle/pickle_dispatcher.py
- modin/distributed/dataframe/pandas/partitions.py
- modin/experimental/batch/pipeline.py
- modin/experimental/core/storage_formats/pyarrow/query_compiler.py
Make some sane default for `index_func=None` argument of `PartitionManager.get_indices()`, which improves its usability.
Also return internal partition indices as well as the total frame index - this allows to compute the `row_lengths` / `column_widths` information later on without some separate remote calls.
> REFACTOR-#4717: Improve PartitionMgr.get_indices() usage

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_default.py
Signed-off-by: Brock <jbrockmendel@gmail.com>
Stop emitting incorrect warning.
> FIX-#4672: Fix incorrect warning when setting frame.columns or frame.index

- docs/release_notes/release_notes-0.16.0.rst
- modin/distributed/dataframe/pandas/partitions.py
- modin/test/test_partition_api.py
FIX-#4686: Propagate metadata and drain call queue in unwrap_partitions.
> FIX-#4686: Propagate metadata and drain call queue in unwrap_partitions.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/exchange/dataframe_protocol/column.py
- modin/test/exchange/dataframe_protocol/pandas/test_protocol.py
Currently we do not handle the case when we call `from_dataframe` on a DF containing category types. This is because `_get_validity_buffer` didn't account for the fact that category types use sentinel values instead of a bit mask for null types. This PR adds a bit of clean-up and fixes this issue.
> FIX-#4652: Support categorical data in `from_dataframe`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/experimental/batch/pipeline.py
Allow _not_ specifying `index` and `columns` when constructing `PandasDataframe`, they would be computed on-demand when accessing `.index` and `.columns`.
> FEAT-#4725: Make index and columns lazy in Modin DataFrame

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci.yml
- docs/release_notes/release_notes-0.16.0.rst
- environment-dev.yml
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/environment-py36.yml
- requirements/requirements-no-engine.yml
1. Pin `flake8` to be `<5` everywhere, as `5.0.x` seems to be in flux release process right now (and missing in `conda-forge` whatsoever leading to issues like #4745).
2. Use `pip install` for omnisci notebook test, so we _always_ install `flake8` and its plugins from `pip` (this was the only exclusion)
> TEST-#4745: Pin flake8 to <5 to workaround installation conflict

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/base/partitioning/axis_partition.py
- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/partitioning/axis_partition.py
REFACTOR-#4750: Delete BaseDataframeAxisPartition.shuffle.
> REFACTOR-#4750: Delete BaseDataframeAxisPartition.shuffle.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
Results for [the benchmark](https://github.com/modin-project/modin/issues/4727#issue-1320028513) (Benchmark mode should be disabled):
| Pandas | Modin master | The PR |
|-|:-:|-|
| 0.89 sec | 4.5 sec | 0.0 sec
> PERF-#4727: Improve perf of `concat` operation

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/io/column_stores/parquet_dispatcher.py
This PR addresses a bug where we do not propagate `storage_options` to the `read_table` call in `build_index`. This wasn't caught by any of our CI tests since we didn't stringently check for the options pass in for `read_parquet`. I'm working on getting access to a bucket so we can make sure that this works accordingly.
> FIX-#4756: Correctly propagate `storage_options` in `read_parquet`

- docs/release_notes/release_notes-0.16.0.rst
- examples/cloud/aws_example.yaml
- examples/spreadsheet/requirements.txt
- examples/spreadsheet/tutorial.ipynb
- examples/tutorial/jupyter/execution/pandas_on_dask/requirements.txt
- examples/tutorial/jupyter/execution/pandas_on_ray/requirements.txt
- modin/core/io/file_dispatcher.py
- modin/core/io/text/csv_glob_dispatcher.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
- modin/test/storage_formats/base/test_internals.py
This PR changes handling of `s3`-like paths from direct `s3fs` to `fsspec` for `read_csv`/`read_csv_glob`. Also some tests for `read_csv_glob` was stabilizied.
In the result:
1. `s3fs` package is used in test system only now
2. New approach allows to switch on parallel implementation of `read_csv` in case `http/https`-like paths instead of defaulting to pandas.
Exceptions: `read_csv_glob` still doesn't support `http`-like paths because `fsspec.HTTPFileSystem.glob` isn't working as expected (always gives empty list instead of all files in remote directory).
> FIX-#4657: Use `fsspec` for handling s3/http-like paths instead of `s3fs`

- .github/workflows/ci.yml
- .github/workflows/push.yml
- modin/experimental/cloud/ray-autoscaler.yml
- modin/pandas/test/test_io.py
TEST-#4760: Limit only ray memory to 1 GB.
Since 53f38a4518996455b3cddaf31fd8fbf833aeee13, github CI has limited memory for
almost all tests to 1 GB, but that change was only meant for ray.
This change should not only deflake dask CI, but also speed it up significantly.
> TEST-#4760: Limit only ray memory to 1 GB.

- .github/ISSUE_TEMPLATE/bug-report.md
- docs/release_notes/release_notes-0.16.0.rst
The existing "bug" label is broken, presumably because it uses `bug :bug:` instead of `bug 🦗`
> DOCS-#4748: Apply the Triage label to new issues.

- .github/workflows/ci.yml
- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/dask/implementations/pandas_on_dask/dataframe/dataframe.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/experimental/batch/pipeline.py
- modin/test/storage_formats/pandas/test_internals.py
Drain the call queues of virtual partition `P1` that constitutes part of a virtual partition `P2` before using the blocks constituting `P1`. Otherwise, we drop the call queue of `P1`.
> FIX-#4676: drain sub-virtual-partition call queues.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
Signed-off-by: Brock <jbrockmendel@gmail.com>
> PERF-#4732: Avoid overwriting already-evaluated _width_cache and _length_cache

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> REFACTOR-#4774: remove `_build_treereduce_func` call from `_compute_dtypes`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
> PERF-#4773: Compute `lengths` and `widths` in `put` method of Dask partition like Ray do

- docs/release_notes/release_notes-0.16.0.rst
- environment-dev.yml
- requirements-dev.txt
- requirements/requirements-py36.txt
- setup.py
FEAT-#4202: Allow dask past 2022-2-0. Increasing the dask memory limit in #4768 should prevent the memory failures that caused dask to get stuck in #4202.
> FEAT-#4202: Allow dask versions past 2022.2.0.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/partition.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition.py
> PERF-#4772: Remove `df.copy` call from `from_pandas` since it is not needed for Ray and Dask

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- docs/release_notes/release_notes-0.16.0.rst
DOCS-#4790: Give all templates issue type and triage labels.
> DOCS-#4790: Give all templates issue type and triage labels.

- docs/release_notes/release_notes-0.16.0.rst
- modin/_compat/pandas_api/latest/base.py
- modin/_compat/pandas_api/latest/dataframe.py
- modin/_compat/pandas_api/latest/io.py
- modin/_compat/pandas_api/latest/series.py
- modin/_compat/pandas_api/latest/utils.py
- modin/_compat/pandas_api/py36/io.py
- modin/_compat/pandas_api/py36/series.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/column.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/dataframe.py
- modin/pandas/series.py
- setup.cfg
Re-enables lint F821, which checks for undefined symbols. This also fixes all occurrences of the error that were suppressed, usually by adding the appropriate import (usually from `typing` or `pandas._typing`).
The only error that was not type-only was `modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/dataframe.py:191:52: F821 undefined name 'is_range_like'`: I fixed this by adding `from modin.pandas.indexing import is_range_like`, which appears to not use any pandas-specific functions. I'm not sure how to write a test that would check for this fix.
> REFACTOR-#4722: Stop suppressing undefined name lint

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
This PR fixes a bug where `read_parquet` would not ignore certain metadata files that are normally ignored by `pyarrow`.
> FIX-#4782: Exclude certain non-parquet files in `read_parquet`

- docs/flow/modin/core/storage_formats/index.rst
- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/dataframe/algebra/default2pandas/groupby.py
- modin/core/dataframe/algebra/groupby.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/exchange/dataframe_protocol/column.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py
- modin/experimental/core/storage_formats/omnisci/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/pandas/test/test_groupby.py
- modin/utils.py
Signed-off-by: Jonathan Shi <jhshi@ponder.io>
Adds the `MODIN_UNNAMED_SERIES_LABEL` to replace hardcoded instances of `"__reduced__" found throughout the codebase.
> REFACTOR-#4796: Introduce constant for __reduced__ column name

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_series.py
> FIX-#4808: Set dtypes correctly after column rename.

- docs/release_notes/release_notes-0.16.0.rst
- environment-dev.yml
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/pandas/test/test_io.py
- requirements-dev.txt
- requirements/environment-py36.yml
- requirements/requirements-py36.txt
This PR adds `fastparquet` as a supported engine for `read_parquet`. I took the liberty to abstract some details of the underlying engine in a way I thought best fit. Please drop suggestions for code cleanup.
> FEAT-#4733: Support fastparquet as engine for `read_parquet`

- docs/release_notes/release_notes-0.16.0.rst
- modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/omnisci_on_native/test/test_dataframe.py
The method Table.rename_columns() accepts a list of strings, but not numbers, thus, the columns must be converted to strings.
> FIX-#4099: Use mangled column names but keep the original when building frames from arrow

- docs/release_notes/release_notes-0.16.0.rst
- docs/requirements-doc.txt
- environment-dev.yml
- examples/spreadsheet/requirements.txt
- requirements-dev.txt
- requirements/environment-py36.yml
- requirements/requirements-no-engine.yml
- requirements/requirements-py36.txt
> FIX-#4838: Bump up modin-spreadsheet to latest master

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/pandas/utils.py
> REFACTOR-#4832: unify `split_result_of_axis_func_pandas`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#4835: Handle Pathlike paths in `read_parquet`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#4842: `copy` should not trigger any previous computations

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#4849: compute `dtypes` in `concat` also for ROW_WISE when possible

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/test/test_io.py
Mark tests that check `read_csv` against S3 file suddenly gone missing as "expected to fail".
We should unmark them back when file is brought back.
> TEST-#4875: XFail tests failing due to file gone missing

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
> PERF-#4862: Don't call `compute_sliced_len.remote` when `row_labels/col_labels == slice(None)`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/test/storage_formats/pandas/test_internals.py
FIX-#4848: Fix rebalancing partitions when NPartitions == 1. Each partition after rebalancing partitions should always have `full_axis=False`.
>  FIX-#4848: Fix rebalancing partitions when NPartitions == 1.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/algebra/default2pandas/default.py
- modin/pandas/base.py
> PERF-#4851: Compute `dtypes` for binary operations that can only return bool type and the right operand is not a Modin object

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
> PERF-#4860: `deploy_axis_func` should be serialized only once

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/ray/common/utils.py
Stop checking the private ray mac memory limit.
> FIX-#4872: Stop checking the private ray mac memory limit.

- asv_bench/benchmarks/utils/common.py
- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/core/dataframe/pandas/partitioning/partition.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/dataframe/dataframe.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/virtual_partition.py
- modin/core/execution/ray/generic/modin_aqp.py
- modin/core/execution/ray/generic/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/distributed/dataframe/pandas/partitions.py
- modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/partitioning/axis_partition.py
- modin/test/test_partition_api.py
This PR adds public API for block partition class to access to actual `._data`. Now, naming between axis/block partitions to access to physical data is aligned.
> REFACTOR-#4530: Unify access to physical data for any partition type

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
> PERF-#4890: `PandasDataframeAxisPartition.drain` should be serialized only once

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
> PERF-#4866: `iloc` function that used in `partition.mask` should be serialized only once

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/io/file_dispatcher.py
- modin/core/io/text/csv_glob_dispatcher.py
- modin/core/io/text/text_file_dispatcher.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
This PR adds proper support for fsspec URLs that matches pandas behavior for `read_csv`.
> FEAT-#4766: Support fsspec URLs in `read_csv` and `read_csv_glob`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/test_series.py
This PR implements a proper implementation for `radd` which is needed for string concatenation on DataFrames and Series objects.
> FIX-#4907: Implement `radd` for Series and DataFrame

- docs/release_notes/release_notes-0.16.0.rst
- modin/conftest.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
This PR does some test cleanup to ensure that `io_tests_data` gets cleaned up after pytests finish. There was also another lingering file from another test that was changed to use the `get_unique_filename` method.
> TEST-#4879: Use pandas `ensure_clean()` in place of `io_tests_data`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/ray/implementations/cudf_on_ray/dataframe/dataframe.py
There's a ton in the cuDFOnRayDataframe method that looks like it should be the same as the parent method but just was never updated.  If I'm right about this, this is a textbook reason why the code should be shared.
Not bothering with opening a dummy issue or formatting the commit because I'm a cranky old man.
> REF: de-duplicate take_2d_labels_or_positional methods

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> FIX-#4914: `base_lengths` should be computed from `base_frame` instead of `self` in `copartition`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
This PR addresses a bug where `Series.apply` returns the incorrect value when the return type of the function is a `DataFrame`.
> FIX-#4734: Handle `Series.apply` when return type is a `DataFrame`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/algebra/default2pandas/any.py
- modin/core/dataframe/algebra/default2pandas/dataframe.py
- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/dataframe/algebra/default2pandas/groupby.py
- modin/core/dataframe/algebra/default2pandas/resample.py
- modin/core/dataframe/algebra/default2pandas/rolling.py
- modin/core/dataframe/algebra/fold.py
- modin/core/dataframe/algebra/groupby.py
- modin/core/dataframe/algebra/map.py
- modin/core/dataframe/algebra/operator.py
- modin/core/dataframe/algebra/reduce.py
- modin/core/dataframe/algebra/tree_reduce.py
> REFACTOR-#4942: Remove `call` method in favor of `register` due to duplication

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/utils.py
> PERF-#4940: Optimize categorical dtype check in `concatenate`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#4945: Fix `_take_2d_positional` that loses indexes due to filtering empty dataframes

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#4963: Use partition `width/length` methods instead of `_compute_axis_labels_and_lengths` if index is already known

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/series_utils.py
> PERF-#4944: avoid default_to_pandas

- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
TEST-#4985: CI: Exclude .github changes that don't affect workflows/
> TEST-#4985: CI: Exclude .github changes that don't affect workflows/

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_default.py
We forgot to return the return value from `_default_to_pandas` 🤣
> FIX-#4993: Return `_default_to_pandas` in `df.attrs`

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci.yml
- contributing/contributing.md
- docs/release_notes/release_notes-0.16.0.rst
- environment-dev.yml
- requirements-dev.txt
- requirements/env_omnisci.yml
- requirements/environment-py36.yml
- requirements/requirements-no-engine.yml
TEST-#4998: Add flake8 plugins to dev requirements.
> TEST-#4998: Add flake8 plugins to dev requirements.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
> PERF-#4999: speed up virtual `drain_call_queue`

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/__init__.py
This PR makes the warning message for pandas version mismatch less confusing.
Should this be categorized as a FEAT? I'll change the commit message + PR title once I know how to categorize this.
> REFACTOR-#4755: Rewrite Pandas version mismatch warning

- .github/workflows/ci.yml
- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/pandas/test/internals/test_benchmark_mode.py
FIX-#4996: Evalute BenchmarkMode at each function call.
> FIX-#4996: Evaluate BenchmarkMode at each function call.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
> REFACTOR-#5005: Use `finalize` method instead of list comprehension + `drain_call_queue`

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#5017: `reset_index` shouldn't trigger index materialization if possible

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/interchange/dataframe_protocol/column.py
- modin/core/dataframe/pandas/interchange/dataframe_protocol/dataframe.py
- modin/core/execution/ray/implementations/cudf_on_ray/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/xgboost/xgboost.py
- modin/test/storage_formats/pandas/test_internals.py
> REFACTOR-#5024: Make `_row_lengths` and `_column_widths` public

- .github/workflows/fuzzydata-test.yml
Signed-off-by: Suhail Rehman <suhailrehman@gmail.com>
> FIX-#5032: Enable fuzzydata artifact upload on test failure also

- asv_bench/benchmarks/utils/common.py
- docs/release_notes/release_notes-0.16.0.rst
> FIX-#5043: fix `execute` function in ASV utils failed if `len(partitions) == 0`

- docs/release_notes/release_notes-0.16.0.rst
- modin/__init__.py
- modin/__main__.py
- modin/_version.py
- modin/conftest.py
- modin/db_conn.py
- modin/error_message.py
- modin/utils.py
- mypy.ini
This PR adds type annotations to `modin/{_version,db_conn,error_message,utils}.py` in anticipation of adding more annotations to the rest of the codebase.
A few notes:
- In cases where the same variable is reassigned to a different type (like assigning `s = [s]` to convert a string to list of strings), mypy's preferred solution is to create a new variable for the new type.
- mypy supports [structural subtyping](https://mypy.readthedocs.io/en/stable/protocols.html), which lets us define what are essentially placeholder classes to perform `isinstance` checks on in cases where we would otherwise use `hasattr` for duck-typed function calls/field accesses.
- In some situations where the origin of a property is not obvious, or is hard to convey to the type checker via annotations, I threw in a …
> REFACTOR-#5012: Add mypy checks for singleton files in base modin directory

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/resample.py
> REFACTOR-#5038: Remove unnecessary `_method` argument from resamplers

- docs/release_notes/release_notes-0.16.0.rst
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
* Fixed HdkOnNativeDataframe._is_trivial_index()
* Do not preserve a trivial index in the underlying arrow table
> FIX-#4090: Fixed check if the index is trivial

- asv_bench/benchmarks/benchmarks.py
- docs/release_notes/release_notes-0.16.0.rst
> TEST-#5064: Update `TimeConcat` benchmark with new parameter `ignore_index`

- docs/release_notes/release_notes-0.16.0.rst
- modin/pandas/series.py
- modin/pandas/test/test_series.py
FIX-#5042: Fix the error message from series __getitem__ for invalid strings.
> FIX-#5042: Fix series __getitem__ with invalid strings.

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/execution/ray/common/utils.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/test/storage_formats/pandas/test_internals.py
Signed-off-by: Jonathan Shi <jhshi@ponder.io>
Introduces a new wrapper method for `ray.wait` that automatically gets `num_returns` to wait for every item in the list, and also removes duplicate object refs before passing it to ray.
> FIX-#5045: Fix ray virtual_partition.wait with duplicate object refs

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/__init__.py
- modin/pandas/general.py
- modin/pandas/test/test_general.py
Signed-off-by: Bill Wang <billiam@ponder.io>
Added implementation for `to_timedelta` instead of using pandas version. Previously returned incorrect output when using a Modin Series as input.
Added tests for `to_timedelta` with Modin Series.
> FIX-#4966: Fix `to_timedelta` to return Series instead of TimedeltaIndex

- modin/conftest.py
TEST-#5074: Fix --extra-test-parameters for pytest --discover-only. 
Both before and after this commit, `--extra-test-parameters` sets `extra_test_parameters` in a testing util file to False. The result is that `--extra-test-parameters` enables tests like this:
```shell
python -m pytest --extra-test-parameters    modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[rotate_decimal_digits_or_symbols-ignore_index_None-last-heapsort-inplace_None-ascending_list_first_False-over_columns_str-first,last,middle-float_nan_data] -rP  --execution=BaseOnPython
```
Both before and after this test, tests like the one above are skipped without `--extra-test-parameters`:
```shell
python -m pytest modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[rotate_decimal_digits_or_symbols-ign …
```
> TEST-#5074: Fix --extra-test-parameters for pytest --collect-only.

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Jonathan Shi <jhshi@ponder.io>
> DOCS-#5095: Remove release note checkbox from PR template

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#5087: use cache for widths/lengths/index/columns if possible

- docs/release_notes/release_notes-0.16.0.rst
- modin/_compat/pandas_api/latest/base.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/dataframe/test_map_metadata.py
> REFACTOR-#5092: Fix future warning for `set_axis` function

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils/__init__.py
- asv_bench/benchmarks/utils/common.py
- asv_bench/benchmarks/utils/data_shapes.py
Broken off from #4988
Closes #5111
> BENCH: add some cases for `join` and `merge` ops from pandas

- modin/_compat/pandas_api/latest/base.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
Duplicate column names are not supported by the omnisci backend. To workaround this issue - fall back to pandas in case of duplicates.
> FIX-#4016, FIX-#4086, FIX-#4039: Fall back to pandas in case of duplicate column names

- codecov.yml
- modin/pandas/test/internals/test_benchmark_mode.py
I confirmed that I no longer get the comment on this PR even when I make a test run for this PR by editing a test file.
For rationale see #5122.
> TEST-#5124: Disable codecov comments.

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#5128: Fix reading parquet directory from s3.

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
The PR gets rid of defaulting to pandas in cases of 2D Modin DFs insertions via `df.__setitem__` API. The functionality was already implemented in lower-levels in [`BaseQueryCompiler.insert_item`](https://github.com/modin-project/modin/blob/08ec2e1397cf48fd26cb2a69fb378bb2f38c5d16/modin/core/storage_formats/base/query_compiler.py#L3109) so the PR just makes a bridge between pandas API and the QC method.
> FEAT-#5141: Implement 2D insertion of Modin DFs in `.__setitem__`

- modin/core/io/text/text_file_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#5150: Sync row labels after read_csv when index_col is False

- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/pandas/test/test_io.py
> FIX-#5158: Synchronize metadata before `to_parquet`

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
MultiIndex columns are not currently supported by HDK.
> FIX-#4023: Fall back to pandas in case of MultiIndex columns

- modin/core/dataframe/pandas/interchange/dataframe_protocol/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/interchange/dataframe_protocol/dataframe.py
Signed-off-by: Jonathan Shi <jhshi@ponder.io>
> FIX-#5168: module 'collections' has no attribute 'Sequence' in dataframe protocol

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/core/storage_formats/pandas/utils.py
- modin/test/storage_formats/pandas/test_internals.py
The PR adds precomputation of row/column lengths cache for the `._reorder_labels` result based on the source frame. You can find more info on why we can do it in such a way in source issue #5162.
> PERF-#5162: precompute new row/column lengths in '._reorder_labels'

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#5188: Fix `getitem_bool` when the key is Series with empty partition

- docs/requirements-doc.txt
- environment-dev.yml
- requirements-dev.txt
- requirements/environment-py36.yml
- requirements/requirements-py36.txt
- setup.py
The PR limits Ray version under 2.1.0 until we figure out the root cause of the #5208
> FIX-#5208: pin ray version under 2.1.0

- modin/core/dataframe/algebra/binary.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_binary.py
The PR fixes the [` ._validate other()`](https://github.com/modin-project/modin/blob/c30ab4c132295b1e168fbb06a050c76554759e11/modin/pandas/base.py#L212) behavior when the `other` is a dictionary. The function iterates through the `other` container in order to extract the inner types:
```python
other_dtypes = [type(x) for x in other]
```
It appeared that this doesn't work for dictionaries as the `dict.__iter__()` iterates on the keys but not on the values. So, the PR introduces a special case for dictionaries in the [`._validate_other()`](https://github.com/modin-project/modin/blob/c30ab4c132295b1e168fbb06a050c76554759e11/modin/pandas/base.py#L212).
> **_NOTE:_**  If you edit the PR title to match this format, you need to add …
> FIX-#5204: fix binary operations with a dictionary

- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
The PR introduces a way of constructing a new modin DataFrame from multiple modin Series' passed as a dict without converting them to pandas. The logic in the constructor now just concatenates the Series' using `modin.pandas.concat` which is literally concatenating partitions without any materialization and thus is very fast.
Here are the performance measurements of constructing frames on master and on this PR, the table shows an average of 20 runs in seconds. The test cases are the following:
1. Construction: `pd.DataFrame(data_dict)`
2. Construction + custom columns, thus reindexing is required: `pd.DataFrame(data_dict, columns=custom_columns)`
3. Construction + custom columns and custom dtype, thus reindexing and type casting is required: `pd.DataFrame(data_dict, …
> FEAT-#4263: Efficiently construct dataframes from a dict of modin Series

- docs/requirements-doc.txt
- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/requirements-no-engine.yml
> FIX-#5171: Allow xgboost >= 1.7.0.

- .gitignore
- docs/release-procedure.md
- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/environment-py36.yml
- requirements/requirements-no-engine.yml
- scripts/release.py
This implements a release notes generator. The CLI is designed to (eventually) hold the whole release procedure with subcommands, but for now only `notes` (which drafts the notes) is implemented.
> FEAT-#4747: Implement release notes generation

- modin/core/storage_formats/pandas/query_compiler.py
The PR gets rid of conversion to a python list of any list-like `value` passed to `PandasQueryCompiler.insert`. This allows us not to meet with a bad side of Ray serializer that is painfully slow when it deals with pure python lists.
This change allowed to significantly improve the time of `.insert()` operation:
| |Master branch | This PR |
|-|-|-|
|Inserting a numpy array | 33.3s | 0.02s |
|Inserting a list | 53.97s | 1.78s |
<details><summary>Code to measure</summary>
```python
df = pd.DataFrame({"a": np.arange(10_000_000)})
numpy_array = np.arange(10_000_000)
python_list = list(numpy_array)
t1 = timer()
df["new_col_numpy"] = numpy_array …
```
> PERF-#5225: do not convert 'value' to a list at '.insert()'

- modin/config/envvars.py
- modin/config/pubsub.py
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/execution/dispatching/factories/test/test_dispatcher.py
- modin/pandas/__init__.py
> FEAT-#5230: Support external query compiler and IO

- modin/pandas/series_utils.py
FIX-#5234: Use query compiler str_repeat.
> FIX-#5234: Use query compiler str_repeat.

- modin/config/envvars.py
- modin/config/test/test_envvars.py
> FIX-#5187: Fixed RecursionError in OmnisciLaunchParameters.get()

- environment-dev.yml
- requirements/environment-py36.yml
> FIX-#5240: fix `dask[complete]` syntax in conda environment files

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/pandas/test/test_io.py
Signed-off-by: Bill Wang <billiam@ponder.io>
Added support for `read_parquet` on column partitioned parquet files in non-local filesystems. Includes tests on non-local S3 parquet files.
> FIX-#4636: allows `read_parquet` to detect column partitioning in non-local filesystems

- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
Only column drop is currently supported by the omnisci engine.
> FIX-#4100: Fall back to Pandas on row drop

- modin/pandas/test/utils.py
Fixes a redundant comparison caused by a typo.
> FIX-#5138: df_categories_equals typo

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#4859: Added support for PyArrow Dictionary Arrays to type mapping

- examples/tutorial/jupyter/execution/hdk_on_native/test/test_notebooks.py
- examples/tutorial/jupyter/execution/pandas_on_dask/test/test_notebooks.py
- examples/tutorial/jupyter/execution/pandas_on_ray/test/test_notebooks.py
> FIX-#5252: Disable notebook tests until access control issues are resolved for `modin-test` bucket

- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#5232: Stop changing original series names during binary ops.

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/push-to-master.yml
- .github/workflows/push.yml
- environment-dev.yml
- modin/pandas/__init__.py
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/requirements-no-engine.yml
- setup.py
> FEAT-#5253: Upgrade pandas to 1.5.2

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
> PERF-#5268: Call `get` on all partitions at once in `to_pandas`

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> FIX-#5238: Make rmul really rmul instead of mul.

- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/test_series.py
> TEST-#5280: Test pandas objects for non-commutative multiply.

- asv_bench/benchmarks/utils/common.py
- asv_bench/test/test_utils.py
> FIX-#5277: fix internal `execute` function

- modin/pandas/test/test_series.py
`CodeQL` defines this place as problematic, I see no reason not to delete it.
> REFACTOR-#5287: remove code to test getting TypeError for Series.dropna

- modin/core/io/column_stores/parquet_dispatcher.py
As explain in https://github.com/modin-project/modin/issues/5285, [Line 606-609 from parquet_dispatcher.py](https://github.com/modin-project/modin/blob/master/modin/core/io/column_stores/parquet_dispatcher.py#L606-L609) only check for `pyarrow` while modin support both `pyarrow` and `fastparquet`.
With this fix, one should be able to read Parquet format with `fastparquet` without the need for installing `pyarrow`.
> FIX-#5285: Check for both pyarrow and fastparquet when read parquet format

- README.md
I got all the raw URLS with "copy image address" on the images shown in my browser.
> DOCS-#5292: Make readme image links raw so they render on pypi.org.

- modin/pandas/test/dataframe/test_map_metadata.py
> REFACTOR-#5301: Fix code scanning alert - Duplicate key in dict literal

- modin/pandas/test/utils.py
> FIX-#5306: Fix code scanning alert - Use of the return value of a procedure

- modin/experimental/batch/test/test_pipeline.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/test/interchange/dataframe_protocol/hdk/test_protocol.py
> REFACTOR-#5303: Fix code scanning alert - Unused local variable

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
Gets rid of FutureWarnings raised by `.iteritems()` usage.
> FIX-#5319: Do not use deprecated '.iteritems()'

- modin/logging/config.py
Adds a timestamp to the folder name pattern that the logger stores its logs so one could easily identify the required logs.
How the logs used to look like:
```
└─.modin
├─── job_a7fc1cf78051447a88bb65734b577285
│    ├─── error.log
│    ├─── memory.log
│    └─── trace.log
├─── job_c819f2f7c0514693bf72cdc75b06ce15
└─── job_3045a14facbd4c9a9e655e193ebceed0
```
How they now look like:
```
└─.modin
├─── job_2022.12.02_20-49-00_a7fc1cf78051447a88bb65734b577285
│    ├─── error.log
│    ├─── memory.log
│    └─── trace.log
├─── job_2022.12.02_20-54-01_c819f2f7c0514693bf72cdc75b06ce15
└─── job_2022.11.26_02-11-45_3045a14facbd4c9a9e655e193ebceed0
```
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit …
> FEAT-#5255: Add a timestamp to the folder names generated by the logger

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/io.py
> REFACTOR-#5332: define `PQ_INDEX_REGEX` as class variable

- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/utils.py
Check that read_csv can use a parse_dates dict.
> TEST-#2073: Check that read_csv can use a parse_dates dict.

- modin/core/io/io.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
We already have `_read` methods in the dispatcher hierarchy. Since there is no need to make such a method also in the IO hierarchy, we can remove it and this will help us stop figuring out which method from the hierarchy was called.
> REFACTOR-#5330: remove `BaseIO._read`

- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/experimental/xgboost/test/test_xgboost.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/utils.py
> REFACTOR-#5335: remove unnecessary lambdas

- .github/workflows/ci.yml
- .github/workflows/fuzzydata-test.yml
Using the syntax shown [here](https://github.com/mvashishtha/modin/pull/new/5345-skip-ci-for-workflow-changes), skip PR CI for changes to workflows that only run on push to master.
> TEST-#5345: Stop running CI for some worfklow changes.

- environment-dev.yml
- requirements-dev.txt
> TEST-#5348: Instead of capping mypy, exclude 0.990.

- .github/workflows/ci.yml
- .github/workflows/push.yml
Results from comparing infinite tries on baseline on  [this branch](https://github.com/mvashishtha/modin/tree/4562-windows-matrix-ray-startup-playground) versus  [base](https://github.com/mvashishtha/modin/tree/4562-windows-matrix-ray-startup-playground-base):
- base: 2/38 runs had the time out error. First round was 1/8 (it was [this one](https://github.com/mvashishtha/modin/actions/runs/3190138370/jobs/5204845152) out of all the commits between [Test only test-windows[ray] in push.yml.](https://github.com/mvashishtha/modin/commit/c5a7d6be82273df72861cd833dd07131d3de5abc) and [Empty commit 7 to trigger CI.](https://github.com/mvashishtha/modin/commit/9bfd7a5fd0bd1658ff32f0d929fb0e84679d633a)). Later i ran another series of 30 tests from [this …
> TEST-#4562: In windows CI, try to start ray a few times

- modin/core/io/text/csv_glob_dispatcher.py
- modin/experimental/pandas/test/test_io_exp.py
> FIX-#5325: fix `read_csv_glob` with non-empty `parse_dates` dict

- modin/pandas/accessor.py
> REFACTOR-#5334: make `_validate` as classmethod

- modin/core/io/text/csv_glob_dispatcher.py
> REFACTOR-#5322: remove python3.7 related code from read_csv_glob

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils/data_shapes.py
Adding 2 benchmark classes from pandas benchmark
Source PR https://github.com/modin-project/modin/pull/5047
> TEST-#5350: port DropDuplicates and LevelAlign benchmarks from pandas github 

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> REFACTOR-#5299: `Variable defined multiple times` error found by CodeQL

- scripts/doc_checker.py
> TEST-#4821: monkeypatch `cache_readonly` to avoid errors in `doc_checker.py`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
> FIX-#5364: fix `get_indices` internal function

- modin/pandas/base.py
- modin/pandas/groupby.py
- modin/pandas/indexing.py
- modin/pandas/utils.py
> REFACTOR-#5310: Remove some hasattr('columns') checks.

- modin/core/dataframe/pandas/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/partition.py
- modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition.py
> REFACTOR-#5363: introduce partition constructor; move `add_to_apply_calls` impl in base class

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_iter.py
- modin/pandas/utils.py
> FIX-#5380: Fix warning about setting _cache attribute.

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/test_groupby.py
- modin/test/test_partition_api.py
> FEAT-#5387: Enable `rebalance_partitions` for Unidist

- modin/core/dataframe/pandas/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
> REFACTOR-#5386: move `partition.split` implementation in base class

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition.py
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
> REFACTOR-#5382: use `pandas.util.cache_readonly` for `__constructors__`

- modin/core/io/file_dispatcher.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/base.py
> REFACTOR-#5312: Let lazy query compilers check for astype and drop errors.

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils/data_shapes.py
Adding 3 benchmark classes from pandas benchmark TimeSimpleReshape , TimeReplace and TimeGroups.
Source PRs #5055 , #5056 , #5057 
> TEST-#5378: port stack, unstack, replace and groups benchmarks from pandas

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> REFACTOR-#5413: check `Index.dtype` instead of `isinstance(obj, Int64Index)`

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/general.py
Some modin implementations might not want to use the current implementation, which is at the API layer and partially defaults to pandas.
> REFACTOR-#5370: Move merge_asof implementation to base query compiler.

- modin/pandas/indexing.py
> REFACTOR-#5393: remove unused `_VIEW_IS_COPY_WARNING` global var

- modin/core/dataframe/algebra/groupby.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/groupby.py
- modin/pandas/utils.py
Here are some performance comparisons of `.groupby().skew()` between the current master and MapReduce implementation. The comparison was run via ASV with our existing groupby scenarios. CPU: 2x 28 Cores (56 threads) Xeon Platinum-8276L @ 2.20
<details><summary>NCPUS=112</summary>
```
[a77a6464]       [05027610]
<master>         <skew_impl>
+      1.46±0.04s        7.03±0.3s     4.83  benchmarks.TimeGroupByDefaultAggregations.time_groupby_skew([5000, 5000], ngroups=100)
+      1.85±0.06s       7.59±0.03s     4.09  benchmarks.TimeGroupByMultiColumn.time_groupby_agg_skew([5000, 5000], ngroups=100, by_ncols=6)
+       3.53±0.1s        7.11±0.1s     2.02  benchmarks.TimeGroupByDefaultAggregations.time_groupby_skew([5000, 5000], 'huge_amount_groups')
+ …
```
> PERF-#5369: `GroupBy.skew` implementation via MapReduce pattern

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/dataframe/test_indexing.py
Fixes a bug when a list was assigned to the `.index` attribute of an empty frame.
> FIX-#5436: Fix '.index' extraction for an empty frame 

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#4154: add `value_counts` method for `SeriesGroupBy` and `DataFrameGroupBy`

- asv_bench/benchmarks/benchmarks.py
- asv_bench/benchmarks/utils/data_shapes.py
> TEST-#5448: reduce Dataframe' shape for `time_merge_default` asv bench

- asv_bench/benchmarks/utils/data_shapes.py
> TEST-#5451: reduce shapes for TimeLevelAlign, TimeStack and TimeUnstack ASV benchmarks

- asv_bench/benchmarks/benchmarks.py
> TEST-#5444: reduce Series' shape for `TimeReindex` asv bench

- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> FIX-#1503: Proper implementation of `Series.values`

- modin/pandas/dataframe.py
- modin/pandas/series.py
> REFACTOR-#3948: Use `__constructor__` in `DataFrame` and `Series` classes

- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/test_series.py
> FIX-#5488: Remove usage of deprecated numpy types

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
> REFACTOR-#1531: move `default_to_pandas` into base query_compiler class

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci.yml
- environment-dev.yml
- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/common/engine_wrapper.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/test_series.py
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
> REFACTOR-#5459: Install code linters through conda and unpin flake8

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#5473: Fix `TypeError(DataFrameGroupBy.take() missing 1 required positional argument: 'indices')`

- modin/core/dataframe/pandas/utils.py
> REFACTOR-#5467: remove FutureWarning for `df.iloc[:, i] = newvals`

- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#4186: Fix `__repr__` of Modin categorical Series

- modin/core/io/text/text_file_dispatcher.py
- modin/pandas/test/test_io.py
Both the dispatcher and the parser can work only with the default rows separator for now.
> FIX-#2493: Defaults to pandas for read_csv if `lineterminator!=None`

- modin/core/io/text/text_file_dispatcher.py
- modin/pandas/test/test_io.py
If a csv' object is passed as a dialect, then Modin does not work, since this object is not serializable. If its name is passed as a dialect, then this dialect will not be found on the workers, since it is registered only in the main process.
> FIX-#2508: Defaults to pandas for read_csv if `dialect!=None`

- modin/core/io/text/text_file_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#2494: Defaults to pandas for read_csv if `escapechar!=None`

- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
> FIX-#5492: Fix `Series.values` when `Series.dtype==ExtensionDtype`

- modin/core/io/text/text_file_dispatcher.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
- modin/pandas/test/test_io.py
> FIX-#2320: Raise exceptions in read_csv in some cases with `skipfooter!=0`

- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#1227: Avoid `RecursionError` for `__int__` and `__float__`

- .github/workflows/ci.yml
- modin/pandas/groupby.py
> FIX-#5537: disable empty-groupby handling logic in experimental mode

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#5550: Don't trigger axes computation in `to_pandas` function

- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#5549: copy dtypes for `__invert__` op

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/test_groupby.py
The PR aligns modin's behavior with pandas' logic on how to behave on invalid results for `groupby.skew`.
`groupby.skew()` performance hasn't changed significantly:
<details><summary>ASV benchmarks</summary>
Steps to run the benchmarks were taken from #5318
```
[53d9096d]       [959a3eac]
<master>       <issue-5545>
338±30ms         358±20ms     1.06  benchmarks.TimeGroupByMultiColumn.time_groupby_agg_skew([1000000, 32], 'huge_amount_groups', 6)
1.64±0.2s       1.74±0.06s     1.06 …
```
> FIX-#5545: Align error-handling logic with pandas for `groupby.skew`

- modin/core/storage_formats/pandas/query_compiler.py
The changes allow for partitioning to be changed during the `.merge()` operation. This could be useful in cases when a user inserts a bigger frame into a smaller one. You can find more info motivating the changes in #5539.
> FIX-#5539: Allow partitioning to adapt to the shape changes caused by '.merge'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/partition.py
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/test/internals/test_repartition.py
> PERF-#5551: Preserve index and columns on `_repartition`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/base.py
Accidentally added `inplace` in one of the previous pull requests.
> FIX-#5581: Don't use deprecated `inplace` parameter for `set_axis` function

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/storage_formats/pyarrow/query_compiler.py
> PERF-#5573: Don't trigger axes computation in `columnarize` function

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/internals/test_repartition.py
> PERF-#5557: Don't trigger axes computation in `pivot_table`

- modin/core/io/text/excel_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/pandas/test/test_io.py
> FIX-#3305: Fix `read_excel` when `usecols` and `index_cols` parameters are provided

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#5561: CalciteSerializer does not support unsigned integers

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#5589: Do not trigger 'dtypes' materialization for '.filter()'

- modin/core/dataframe/algebra/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#5604: Fix dictionary groupby aggregation for a single col partition case

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_map_metadata.py
> FIX-#5600: Copy '.dtypes' on 'df.copy()'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_indexing.py
> PERF-#5575: Don't trigger axes computation in `reset_index` function

- modin/db_conn.py
Not adding a test because setting up and maintaining a test snowflake account is too much effort. This fix works in practice.
> FIX-#5629: Make read_sql alias compatible with snowflake.

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_series.py
> FIX-#5625: Fix set_index with modin series.

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/experimental/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
Add parameters 
- apply_indices
- enumerate_partitions
to `apply_full_axis` function in `modin/core/dataframe/pandas/dataframe/dataframe.py` to match with the parameters of the function `broadcast_apply_full_axis`.
> FEAT-#5620: Synchronize parameters of `apply_full_axis` with `broadcast_apply_full_axis`

- modin/conftest.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/test_series.py
- modin/test/storage_formats/pandas/test_internals.py
> FIX-#5650: Restore the right dtype for applying Series.cat

- modin/core/dataframe/algebra/map.py
- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#5657: Don't trigger axes computation when accessing `.str.*` methods

- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#5660: Don't trigger axes computation when accessing cat.codes

- .github/workflows/ci.yml
> TEST-#5664: speedup `Post Run conda-incubator/setup-miniconda@v2` step on Windows

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/test/storage_formats/pandas/test_internals.py
This may increase data transfer between workers when `keep_partitioning=False`, however, don't we always want the data to be shuffled when this parameter is passed?
The problem is that `keep_partitioning=False` is the default one for `PartitionManager.map_axis_partition`, so it may affect cases where some code calls this method without explicitly specifying this argument:
https://github.com/modin-project/modin/blob/0df5fbf7a66663110878633467e4488ad37b0337/modin/core/dataframe/pandas/partitioning/partition_manager.py#L537
Most of the cases we explicitly specify `keep_partitioning=True`, there's only one case that use the default value for this parameter:
https://github.com/modin-project/modin/blob/0df5fbf7a66663110878633467e4488ad37 …
> FIX-#5621: Do not preserve suboptimal partitioning on `keep_partitioning=False`

- modin/core/dataframe/algebra/map.py
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
> PERF-#5682: Don't trigger axes computation when calling `isin`

- modin/core/io/text/csv_dispatcher.py
- modin/core/io/text/custom_text_dispatcher.py
- modin/core/io/text/fwf_dispatcher.py
- modin/core/io/text/text_file_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
> PERF-#5690: move `read_callback` from dispatchers into parsers

- modin/core/dataframe/algebra/binary.py
> PERF-#5680: Don't trigger axes computation when doing binary operations

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_iter.py
- modin/pandas/test/test_series.py
> PERF-#5710: Avoid re-putting a distributed Series to the engine's object store at `.isin()`

- modin/pandas/series.py
> PERF-#5709: Avoid re-putting a distributed Series to the engine's object store at `.map()`

- modin/pandas/general.py
- modin/pandas/test/test_concat.py
> FIX-#5714: BUG: Empty frames concatenation with inner join is not valid

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#5705: Preserve metadata when applying `Series.cat.codes`

- modin/core/io/text/csv_glob_dispatcher.py
- modin/core/io/text/excel_dispatcher.py
- modin/core/io/text/json_dispatcher.py
- modin/core/io/text/text_file_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
> REFACTOR-#5718: add `columns` parameter for `get_dtypes` function

- modin/core/storage_formats/pandas/utils.py
This change should decrease memory consumption for dataframes that use MultiIndex ([see this comment](https://github.com/modin-project/modin/issues/5247#issuecomment-1420781893)).
> PERF-#5247: Decrease memory consumption for MultiIndex

- modin/numpy/arr.py
- modin/numpy/test/test_array_axis_functions.py
> FIX-#5720: Ensure that modin.numpy.array's propagate NaN values when computing mean

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
> PERF-#5613: Optimize `duplicated` in case there is only one column partition

- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
Fall back to pandas in case of binary operations on strings. Such operations are not supported by HDK.
> FIX-#5742: BUG: HDK: Binary operations on strings are not supported

- modin/core/execution/dask/common/engine_wrapper.py
- modin/core/execution/ray/common/engine_wrapper.py
- modin/core/execution/unidist/common/engine_wrapper.py
Allows instead of a function to pass `distributed.Future` into `deploy` (`client.submit` doesn't support this out of the box). There are no tests for this, but it is planned to use for https://github.com/modin-project/modin/pull/5678.
> REFACTOR-#5703: align `DaskWrapper.deploy` behavior with others

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/test/dataframe/test_indexing.py
FIX-#5702: Fix passing RangeIndex to loc.
> FIX-#5702: Fix passing RangeIndex to loc.

- .github/workflows/ci.yml
It turned out that the main jobs do not start if the jobs on which they depend are skipped. This is a hotfix, I think it's not a problem that we also run linters when pushing, since they are fast enough.
> TEST-#0000: correct behavior of CI for push action

- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
- modin/numpy/__init__.py
- modin/numpy/arr.py
- modin/numpy/linalg.py
- modin/numpy/math.py
- modin/numpy/test/test_array_linalg.py
This PR adds support for `np.dot` and `np.linalg.norm`.
> FEAT-#5754: Add np.linalg operations

- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
> FIX-#0000: Fix a typo in `expr.py`

- modin/core/storage_formats/pandas/query_compiler.py
- modin/numpy/arr.py
- modin/numpy/math.py
- modin/numpy/test/test_array_arithmetic.py
> FIX-#5761: Add _exp, _sqrt to query compiler

- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
> REFACTOR-#5786: align logging of Dask partitions with other executions

- modin/numpy/arr.py
- modin/numpy/logic.py
- modin/numpy/math.py
Cleans up a lot of duplicated code in numpy array operations, especially for the dispatching of math operators and output dtype computation of binary operators.
> REFACTOR-#5799: Clean up numpy array operations

- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
> FIX-#5580: BUG: 'AVG|SUM' is only valid on integer and floating point

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
1. Index drop is not supported by the HDK engine. In this case - fall back to pandas.
2. If all columns are dropped and the index is trivial, we are not able to restore it, since we don't know the number of rows. In this case, we calculate the index from the current frame.
**Fixes #3916**
> FIX-#3925: Fixed AssertionError on columns and index drop

- modin/core/dataframe/pandas/partitioning/partition_manager.py
This PR removes unnecessary conversion to row partitions while reshuffling partitions.
Changes of our ASV benchmark:
```
MODIN_TEST_DATASET_SIZE="Big" asv continuous origin/master issue_5778 --launch-method=spawn -b TimeSortValues --no-only-changed -a repeat=5
All benchmarks:
[8d3db2b4]       [b50ee4e2]
<issue_5778~1>       <issue_5778>
-       7.52±0.1s       1.15±0.04s     0.15  benchmarks.TimeSortValues.time_sort_values([1000000, 10], 1, True)
-       7.74±0.4s       1.17±0.03s     0.15  benchmarks.TimeSortValues.time_sort_values([1000000, 10], 2, True)
SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your …
> PERF-#5778: Avoid extra materialization at range-based reshuffling

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/experimental/sql/hdk/query.py
- modin/experimental/sql/test/test_sql.py
> FIX-#5737: BUG: String columns are converted to Categorical, if exported from HDK

- modin/pandas/base.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
Keep `Series.name` intact when shifting.
> FIX-#5373: Fix Series.shift() for named Series

- .github/workflows/ci.yml
- modin/numpy/arr.py
- modin/numpy/test/test_array_math.py
Fixes a bug where argmax/argmin on 1D arrays were giving incorrect results. There may still be bugs left over for 2D arrays, which we plan to address later with more comprehensive tests for our numpy API.
> FIX-#5819: Fix np.argmax/argmin on 1D arrays

- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_join_sort.py
> TEST-#5826: remove `_propagate_index_objs` internal function usage from tests

- modin/core/dataframe/pandas/dataframe/utils.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/test/storage_formats/pandas/test_internals.py
> FIX-#5781: Fix sort in descending order for columns with highly dense values

- setup.cfg
See linked issue. cc @anmyachev to make extra sure this doesn't break anything.
> TEST-#5832: Suppress pytest coverage messages in terminal

- modin/core/dataframe/pandas/partitioning/partition_manager.py
> PERF-#5777: Filter out empty bins at range-based reshuffling

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_series.py
The current solution just copies the required function from pandas. It would be great to be able to reuse it directly from pandas, however it's not that easy as this function is a private class method used for indexing.
> FIX-#5309: series iloc/loc raises IndexingError if a key is too long

- docs/flow/modin/experimental/pandas.rst
- docs/usage_guide/advanced_usage/index.rst
> DOCS-#5852: Add mention of `read_custom_text` experimental api in docs

- modin/experimental/pandas/io.py
Such changes have already been in Modin. For example, in `PandasDataframePartitionManager.n_ary_operation`.
> FIX-#5862: fix Inline strong start-string without end-string for read_custom_text

- modin/pandas/dataframe.py
- modin/pandas/series.py
> REFACTOR-#5863: remove `Engine.subscribe(_update_engine)` in DataFrame/Series constructors

- modin/core/io/__init__.py
- modin/core/io/pickle/pickle_dispatcher.py
- modin/core/io/text/custom_text_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/experimental/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/experimental/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
- modin/experimental/core/io/__init__.py
- modin/experimental/core/io/sql/sql_dispatcher.py
> REFACTOR-#5830: rename experimental dispatchers and parsers

- setup.cfg
We don't have to calculate test coverage for the test files themselves. This is also now causing the coverage percentage to fluctuate all the time.
> TEST-#5878: exclude modin/experimental/batch/test/ folder from computing coverage

- modin/core/storage_formats/pandas/query_compiler.py
> REFACTOR-#5875: use default implementations for dt methods from the base query compiler

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/test/storage_formats/pandas/test_internals.py
This PR adds several safeguards allowing us not to fail on an empty pivots list in `.sort_by()`.
> FIX-#5859: Fix '.sort_values()' when there's only one row partition

- modin/pandas/test/test_rolling.py
> TEST-#4261: test rolling with axis=1, win_type=, and center=True

- docs/supported_apis/dataframe_supported.rst
- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
Let's think about code duplication after a new release.
> FEAT-#4624: add `to_parquet` parallel implementation for Dask

- modin/core/dataframe/pandas/partitioning/partition_manager.py
Using `other_name` option looks like a complication. In all cases where `broadcast_apply` function is used, it is assumed that the user-defined function has the following signature: `func(df, other)` (only the name of `other` parameter changes on different calls). Nothing prevents us from passing this parameter as a positional one.
> REFACTOR-#2863: remove `other_name` from broadcast_apply

- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
Let's think about code duplication after a new release.
> FEAT-#5880: add `to_sql` parallel implementation for Dask

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_map_metadata.py
It looks like we can just pass `errors` to a function that runs on partitions.
> FIX-#5618: don't ignore 'errors' parameter for astype

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/test_series.py
> FIX-#2850: use modin.pandas.Series instead of pandas.Series for `where` func

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
> REFACTOR-#5908: remove unused parameters from `run_exec_plan`

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
> REFACTOR-#5910: remove `_dtypes_for_cols` internal function as unused

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
`dataframe.py` file is very large and the decorator is very easy to move.
> REFACTOR-#5874: move `lazy_metadata_decorator` into `utils.py`

- docs/supported_apis/io_supported.rst
- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
> FEAT-#5901: add `read_fwf` parallel implementation for Dask

- modin/pandas/groupby.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_groupby.py
> FIX-#5454: add missed methods for `SeriesGroupBy`, `DataFrameGroupBy` objects

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#5509: default to pandas for read_parquet if any additional kwargs are passed to the engine

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/test/storage_formats/pandas/test_internals.py
This PR delays the resulting index computation by removing an explicit call of the `._compute_axis_labels_and_lengths`.
> PERF-#5808: Delay metadata computations for '.sort_values' result

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#5767: cast `pathlib.Path` to str for `read_parquet`

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/df_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_utils.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/experimental/sql/hdk/query.py
- modin/pandas/test/dataframe/test_indexing.py
- requirements/env_hdk.yml
Reworked column names encoding.
Fixes.
Depends on #5156
> FIX-#5566: Enable test_indexing test on the HDK engine and add to ci

- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/resample.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/utils.py
- modin/pandas/window.py
> FIX-#4635: allow pass modin functions to `apply`

- .github/workflows/upload-coverage/action.yml
This will allow us to see if something goes wrong.
> REFACTOR-#5922: let `upload-coverage` action fail if there is no `.coverage` file

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/batch/pipeline.py
- modin/experimental/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/experimental/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
- modin/experimental/core/io/sql/utils.py
This will allow us to get more accurate coverage numbers.
> REFACTOR-#5923: add `pragma: no cover` for functions that used in `apply_full_axis`

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
> FIX-#5432: don't return None when `astype` used with `copy=False` parameter

- modin/pandas/indexing.py
- modin/pandas/test/dataframe/test_indexing.py
> FIX-#5829: fix ndarray assignment via loc

- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
- modin/numpy/arr.py
- modin/numpy/test/test_array.py
- modin/numpy/test/test_array_arithmetic.py
- modin/numpy/test/test_array_indexing.py
- modin/numpy/test/test_array_linalg.py
- modin/numpy/test/test_array_math.py
- modin/numpy/test/test_array_shaping.py
This PR adds tests for several previously uncovered test cases in the numpy API.
<details>
<summary>New test cases:</summary>
- Error cases for improper broadcast dimensions
- Broadcasting with an `out` array specified
- Basic behavior for `__setitem__` and `_set_shape`
- Binary operations with a scalar argument
- remainder, mod, argmax, and argmin basic behavior
- shape, transpose, split, hstack, and append basic behavior
</details>
This PR also includes a few minor bugfixes related to broadcasting issues (I did not file issues for those), and adds xfail'd tests for the following:
- #5831
- #5886
- #5893
- #5894
- #5896
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the …
> TEST-#5897: Add more robust tests for numpy API

- modin/core/io/text/excel_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#4924: fix read_excel when header is None

- modin/core/dataframe/algebra/groupby.py
- modin/core/storage_formats/pandas/query_compiler.py
The PR moves index renaming from the main process to the kernel function which allows us to not materialize the index for renaming.
> PERF-#5837: Defer index materialization for MapReduce implemented groupby

- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
> REFACTOR-#5902: use `__make_read` for non experimental IO classes

- .github/workflows/ci.yml
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/utils.py
Depends on:
FIX-https://github.com/modin-project/modin/issues/3925: Fixed AssertionError on columns and index drop
FIX-https://github.com/modin-project/modin/issues/5576: Enable test_join_sort test on the HDK engine and add to CI
FIX-https://github.com/modin-project/modin/issues/5566: Enable test_indexing test on the HDK engine and add to ci
FIX-https://github.com/modin-project/modin/issues/5580: BUG: 'AVG|SUM' is only valid on integer and floating point
> FIX-#5794: Enable test_default test on the HDK engine and add to ci

- README.md
After we merge the PR the gif should be rendered correctly at our [pypi page](https://pypi.org/project/modin/).
The GIF now takes 250kb instead of 18.9mb.
> DOCS-#5957: Compress `Import.gif` as it's too large

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_join_sort.py
> FIX-#5203: don't raise `AttributeError: 'list' object has no attribute '_query_compiler'` in `join` op

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
> REFACTOR-#5844: remove `inplace` kwarg from query compiler `clip` arguments

- modin/core/dataframe/base/partitioning/axis_partition.py
- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
The PR introduces an implementation of the `.split()` method for axis partitions, making it possible to avoid materialization of the virtual row partitions during reshuffling.
ASV results:
```
MODIN_TEST_DATASET_SIZE="Big" asv continuous origin/master HEAD --launch-method=spawn -b TimeSortValues --no-only-changed -a repeat=5
All benchmarks:
[cd7611cd]       [9316fbcc]
<master>       <issue_5816>
949±50ms         910±50ms     0.96  benchmarks.TimeSortValues.time_sort_values([1000000, 10], 10, False)
947±40ms         898±20ms     0.95  benchmarks.TimeSortValues.time_sort_values([1000000, 10], 1, False)
1.03±0.04s         909±60ms    ~0.89  benchmarks.TimeSortValues.time_sort_values([1000000, 10], 2, False)
```
> **_NOTE:_**  If you edit the PR title to …
> FEAT-#5816: Implement '.split' method for axis partitions

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#5988: BUG: Concatenation of frames with strings is not supported by HDK

- modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
The read_cvs() method disables the timestamp fields parsing if the parse_dates argument is of type bool, however, the default value is None and, in this case, the parsing should also be disabled.
Note: dates without timezone are still parsed. See #3485.
> FIX-#6000: HDK: read_csv(): Do not parse dates, if the parse_dates argument is not specified

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_udf.py
> FIX-#4828: allow `dict_apply_builder` use keyword argument `internal_indices`

- setup.cfg
> TEST-#6020: exclude `_version.py` from coverage

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition_manager.py
> REFACTOR-#6044: remove code duplication for `get_objects_from_partitions`

- modin/conftest.py
- modin/core/storage_formats/pandas/parsers.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
This is necessary step to migrate to pandas 2.0.0.
> TEST-#6009: use `tmp_path` fixture instead of `ensure_clean_dir` as pandas 2.0.0 does

- modin/core/execution/ray/common/utils.py
> PERF-#5999: Do not set Ray's `runtime_env` for a single-node case

- .github/workflows/ci.yml
this saves about 26 minutes of test time for the slowest job:
- before: https://github.com/modin-project/modin/actions/runs/4874354044/jobs/8698000226?pr=6077
- after: https://github.com/modin-project/modin/actions/runs/4872924504/jobs/8691948397
> TEST-#6076: Use 2 cores for experimental groupby on dask

- modin/core/dataframe/algebra/default2pandas/__init__.py
- modin/core/dataframe/algebra/default2pandas/rolling.py
- modin/core/storage_formats/base/doc_utils.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_expanding.py
- modin/pandas/test/test_series.py
- modin/pandas/window.py
Ports pandas expanding window methods implemented in https://github.com/ponder-org/modin-public, and adds simple tests.
The implementation for `Expanding.aggregate` has been changed to match that of `Rolling.aggregate` in order to support lists of multiple aggregation functions; it seems like this method was not tested in the other repository's version.
> REFACTOR-#6062: Add query compiler interfaces for expanding methods

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/series_utils.py
- modin/pandas/test/test_series.py
> REFACTOR-#6063: Add query compiler interfaces for some strings methods.

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
> REFACTOR-#6091: Push more of memory_usage down to query compiler.

- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
> FIX-#6097: Pass storage_options to the to_csv function of PandasOnRay class with fsspec

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
REFACTOR-#6071: Push first and last down to query compiler. (#64) [core]
> REFACTOR-#6071: Push first and last down to query compiler. (#64)

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_default.py
> FIX-#6112: Ensure that `truncate` verifies that before <= after

- modin/pandas/series.py
> REFACTOR-#6105: Explicitly pass default value of np.nan to Series.reindex

- modin/pandas/dataframe.py
> FIX-#6109: Don't use join() when indicator is true

- modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
- modin/pandas/test/test_io.py
> FIX-#6120: HDK read_csv(): Fixed parsing dates with nanosecond precision

- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
> FEAT-#6144: Stop defaulting at API layer for a bunch of methods

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
> FIX-#6107: Allow pass through of `tz_convert` and `tz_localize` to QC if possible

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
> REFACTOR-#6065: Use between_time in at_time

- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
- modin/core/dataframe/algebra/default2pandas/rolling.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_expanding.py
- modin/pandas/test/test_groupby.py
- modin/pandas/window.py
FEAT-https://github.com/modin-project/modin/issues/6153: Add API layer implementations for some stat methods.
Also fix some other expanding methods that were not tested and/or were broken. test_expanding wasn't running in CI until this commit, so we missed some errors.
> FEAT-#6153: Add API layer implementations for some stat methods.

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/series.py
- modin/pandas/series_utils.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_general.py
> REFACTOR-#6159: Stop defaulting at API layer for a few more methods

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> REFACTOR-#6116: Move `groupby_ohlc` implementation to QC layer

- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
Transferring changes made on ray in #6098 to unidist
> FIX-#6172: Pass storage_options to the to_csv function of PandasOnUnidist class with fsspec

- modin/core/storage_formats/pandas/groupby.py
- modin/pandas/test/test_groupby.py
FIX-#6175: Fix groupby agg columns for empty column partition
> FIX-#6175: Fix groupby agg columns for empty column partition

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/pandas/test/test_concat.py
The outer join is not supported by HDK, however, if all the frames have a trivial index, we can simply concatenate the columns with arrow.
> FEAT-#6147: HDK: Arrow-based columns concatenation of frames with trivial index.

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/groupby.py
> FIX-#6113: Add QC Layer implementation for idxmin/max

- modin/pandas/base.py
> FIX-#6181: Do not ignore `copy` argument in `tz_convert` and `tz_localize`

- modin/pandas/dataframe.py
- modin/pandas/test/test_general.py
> FIX-#6146: Fix `pivot` when `values=None`

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_window.py
> FIX-#6117: Add error checking at API level for `diff`

- modin/pandas/groupby.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_groupby.py
> FIX-#6154: Ensure GroupBy.__getitem__ preserves key order

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
This PR addresses two issues - it handles pd.Grouper objects correctly and also obeys the order of the groupby sorting keys as passed in. 
> FIX-#5091: Handle pd.Grouper objects correctly

- modin/config/__main__.py
> DOCS-#6078: correct default values for MODIN_CPUS and MODIN_NPARTITIONS

- modin/core/execution/ray/common/utils.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/unidist/common/utils.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
> TEST-#6198: add `pragma: no cover` for unidist and ray utils that used in remote context

- modin/pandas/series_utils.py
- modin/pandas/test/test_api.py
> FIX-#6196: Align `Series.cat` signatures with pandas

- modin/pandas/base.py
> FIX-#6204: Use reset_index instead of insert in to_sql

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_iter.py
- modin/test/storage_formats/base/test_internals.py
> FIX-#6104: Stop selecting same column twice for repr.

- modin/core/io/io.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
> FIX-#6199: make sure `read_html` return a list of DataFrames

- modin/pandas/groupby.py
- modin/pandas/test/test_api.py
> FIX-#6201: align groupby objects signatures with pandas

- modin/pandas/groupby.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/test_series.py
This PR removes `.fillna(0)` from `groupby.size()` and `groupby.count()` as this is not needed anymore. For more information visit the related issue #6126
> PERF-#6126: Remove redundant '.fillna(0)' at the end of '.size()' and '.count()'

- environment-dev.yml
- modin/pandas/test/test_io.py
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
> FIX-#6072: unpin pyarrow and xfail `test_read_parquet_pandas_index` test

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/pandas/test/test_series.py
> FIX-#5722: Use full axis function when casting to "category"

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/df_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
1. If all frames are either FrameNode(materialized frame) or UnionNode, containing only FrameNodes and having the same concatenation options, put all frames into a single UnionNode. It allows to concatenate multiple frames with arrow in a single batch operation.
2. Use iteration instead of recursion for lazy frames materialization.
> FIX-#5889: HDK: Combine multiple lazy concat operations into a single one and replace recursion with iteration

- modin/core/dataframe/base/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
After #6222 we guarantee that each partition has knowledge about the whole categorical table, meaning that we don't need to build the whole axis no more in order to retrieve valid categorical codes. So this PR basically replaces `.fold(axis=0, ...)` to the `.map(...)` in the `.cat_codes` implementation.
> PERF-#6224: Use 'Map' operator to retrieve categorical codes

- modin/logging/logger_decorator.py
- modin/test/test_logging.py
- modin/utils.py
> FIX-#6237: Log errors only from deepest modin layer

- modin/core/storage_formats/pandas/aggregations.py
- modin/pandas/dataframe.py
> FIX-#6215: Process '.corr(numeric_only=False)' parameter at the qc level

- modin/core/execution/dask/common/engine_wrapper.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/modin_aqp.py
- modin/core/execution/ray/common/engine_wrapper.py
- modin/core/execution/ray/common/utils.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/core/execution/unidist/common/engine_wrapper.py
- modin/core/execution/unidist/common/utils.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition_manager.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
> FEAT-#6048: add `wait` method for Dask/Ray/Unidist wrappers

- modin/core/io/file_dispatcher.py
> REFACTOR-#0000: rename `exc` -> `err`

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
- setup.py
Remove pandas patch level pin  as we agreed [here](https://github.com/modin-project/modin/issues/3371#issuecomment-1317976944).
> FIX-#3371: Remove pandas patch level pin

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/test/interchange/dataframe_protocol/hdk/test_protocol.py
> FIX-#6245: support datetime64 with different resolutions types for HDK

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
> FIX-#6259: Fix astype("category") causing read-only buffer error

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_default.py
> FIX-#6232: support DataFrame.cov(numeric_only=False) without fallback to pandas

- modin/experimental/core/execution/native/implementations/hdk_on_native/base_worker.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/df_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/interchange/dataframe_protocol/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/test_general.py
- Reimplemented _union_all(), that used non-lazy arrow-based frames concatenation.
- Added functionality to dataframe tree nodes and expressions for arrow execution. The arrow execution is performed if the frame has an arrow table in partitions and all the nodes support the arrow execution. It allows to save on the table import to HDK.
- The arrow execution is also performed for the operations, not supported by HDK, for example, bitwise not '~'.
[_execute()](https://github.com/modin-project/modin/pull/6251/files#diff-d1a0db76b871ca475d604ff109cc3ebf13d7ead8ce07cca7caa54ace5f736cc0R1842). The main changes here:
- Now the method returns either `pyarrow.Table` or `pandas.Dataframe`. Dataframe is returned if we have an unsupported data.
- Added new condition - `if not …
> FEAT-#5759: Implement lazy Arrow execution for the HDK engine

- modin/core/io/column_stores/feather_dispatcher.py
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/pandas/io.py
> FEAT-#6253: add `dtype_backend` parameter support for read_parquet/read_feather

- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#6035: Fall back to Pandas, when merging unsupported column types

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/df_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
Now the partitions could be either None or contain a single non-empty partition.
- [] tests added and passing
> REFACTOR-#6279: HDK DataFrame should not have more than one partition

- modin/numpy/arr.py
- modin/numpy/test/test_array.py
> FIX-#6297: fix experimental numpy.argmax/argmin with Nans in data

- modin/core/storage_formats/pandas/query_compiler.py
This improves Modin's asynchronous execution.
> FIX-#6309: do not materialize axes for 'rank' operation

- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_binary.py
- modin/pandas/test/test_series.py
> FIX-#6229: fix `Series.equals`/`DataFrame.equals` with NA entries

- modin/core/dataframe/algebra/default2pandas/groupby.py
- modin/core/dataframe/algebra/default2pandas/rolling.py
- modin/core/storage_formats/base/doc_utils.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/pandas/window.py
> FEAT-#6191: Implement `groupby.rolling` API

- asv_bench/asv.conf.dask.json
- asv_bench/asv.conf.hdk.json
- asv_bench/asv.conf.json
- asv_bench/asv.conf.unidist.json
Avoid errors like in https://github.com/modin-project/modin/actions/runs/5406761992/jobs/9825588358?pr=6286
```bash
File "/usr/share/miniconda/lib/python3.10/site-packages/asv/plugins/conda.py", line 227, in _run_conda
return util.check_output([conda] + args, env=env)
File "/usr/share/miniconda/lib/python3.10/site-packages/asv/util.py", line 754, in check_output
raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/share/miniconda/bin/conda env create -f ../requirements/env_hdk.yml -p /home/runner/work/modin/modin/asv_bench/.asv/env/6df994238d3562d4e97431b9f4cec556 --force' timed out
```
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the …
> TEST-#6315: increase 'install_timeout' for ASV benchmarks: 600 -> 6000 sec

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#6319: remove '__make_init_labels_args' explicit calls that materialize axes

- docs/requirements-doc.txt
- environment-dev.yml
- examples/tutorial/jupyter/execution/pandas_on_ray/requirements.txt
- requirements-dev.txt
- setup.py
> FIX-#6336: pin 'pydantic<2' to fix CI

- modin/pandas/__init__.py
CI using pandas version 2.0.3 for a couple of days now and it works.
> FEAT-#6322: Give a warning only if the major or minor part of pandas version are different

- modin/core/io/text/excel_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
It is correct to call property only from a class instance.
> FIX-#6338: fix TypeError: WorksheetReader.__init__() got an unexpected keyword argument 'rich_text'

- modin/pandas/series.py
- modin/pandas/test/test_api.py
> FIX-#5077: fix `Series.rename_axis` signature

- docs/development/using_hdk.rst
- modin/config/envvars.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py
Add an option to run Modin on GPU via HDK. The behavior is controlled by an existing `cpu_only` config option as described in the updated doc.
> FEAT-#6325: Add GPU execution option for HDK backend

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/test/storage_formats/pandas/test_internals.py
> FIX-#6341: call `_filter_empties` only if shapes are different on particular axis

- modin/experimental/core/execution/native/implementations/hdk_on_native/base_worker.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py
Set fragment size to a constant for GPU execution via HDK.
> FEAT-#6351: Add a simple heuristic for fragment size when running on a GPU

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_series.py
> FIX-#4485: fix 'clip' with list-like bounds and axis=None

- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition.py
> FIX-#6352: Fix the HdkOnNativeDataframePartition._width_cache property computation

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
In case of multiple sequential LogicalProject nodes, Calcite squashes them, but gets the column names from the first one. To fix the issue, squash on the Modin side and keep the names from the last one.
> FIX-#1851: Squash multiple LogicalProject nodes

- docs/conf.py
- modin/config/envvars.py
- modin/config/test/test_envvars.py
* Adds feature flag controlling lazy dictionary materialization. Lazy dict materialization delays building dictionaries for text types until query time. For datasets with large numbers of text columns that are not directly processed, this can speed up import and querying. 
* Adds feature flag to set the log file directory. Can be set to the tmp directory to suppress log artifacts. This was a request from a benchmarking team. 
These features are available in HDK main branch now and will be released this week. The version check prevents passing the flags to earlier versions of HDK which do not support them.
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to …
> FEAT-#6296: Add pyhdk feature flags

- modin/core/execution/dispatching/factories/dispatcher.py
> FIX-#6334: improve error message if hdk isn't installed in the environment

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/pandas/series.py
> FIX-#5627: Stop checking temp_df.dtype == 'category'

- modin/core/dataframe/pandas/partitioning/partition_manager.py
> FIX-#6364: Make reshuffling work with 'BenchmarkMode.put(True)'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/test_groupby.py
Check the [linked issue](https://github.com/modin-project/modin/issues/6368) for the motivation of this changes
> FIX-#6368: Apply deferred indices before map-reduce groupby

- .github/workflows/ci.yml
- modin/conftest.py
- modin/pandas/test/internals/test_benchmark_mode.py
> TEST-#5008: Set benchmark mode within unit test instead of with environment variable

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_series.py
> FIX-#6219: don't default to pandas for 'copy' on empty DataFrame/Series objects

- modin/core/storage_formats/base/query_compiler.py
> PERF-#6373: preserve dtypes cache for '_repartition'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/test/storage_formats/pandas/test_internals.py
> PERF-#6332: don't materialize axes in concat operation

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/ray/implementations/cudf_on_ray/dataframe/dataframe.py
Based on https://github.com/modin-project/modin/pull/6379
Command: `MODIN_CPUS=44 MODIN_TEST_DATASET_SIZE="Big" asv continuous master vnlitvin/use-numpy-iloc -b "^benchmarks.TimeIndexing" --launch-method=spawn --no-only-changed -a repeat=5 -a warmup_time=2`
Perf results (44 CPUs, Ray):
<details>
```bash
All benchmarks:
[ea0a6acb]       [691fffd3]
<master>
7.240.1ms      7.980.07ms    ~1.10  benchmarks.TimeIndexing.time_iloc([1000000, 10], 'continuous_slice')
54410ms         59610ms     1.10  benchmarks.TimeIndexing.time_iloc([5000, 5000], 'slice')
5.190.06ms       5.670.2ms     1.09  benchmarks.TimeIndexingNumericSeries.time_loc_scalar([100000, 1], <class 'numpy.uint64'>, 'nonunique_monotonic_inc')
7.280.1ms      7.880.09ms     1.08 …
```
> PERF-#6378: use numpy.array operations in internals of iloc/loc operation

- modin/numpy/test/test_array.py
- modin/pandas/base.py
> FIX-#6299: __array__ method always returns array of vanilla numpy

- modin/core/execution/dispatching/factories/dispatcher.py
> FIX-#6396: set `__factory` to `None` in case of any problems during initialization

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_window.py
- modin/pandas/test/test_series.py
> FIX-#6402: Allow datetime and timedelta types in `diff`

- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/series.py
> FIX-#6405: Apply `disable_logging` to `__getattr__`

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
> FEAT-#5645: add support for modin's numpy array in `dataframe.insert` function

- modin/core/storage_formats/pandas/parsers.py
The changes tested in https://github.com/modin-project/modin/pull/6413 with `pyarrow==7.0.0`.
> FIX-#6414: fix 'read_feather' with pyarrow<11.0

- .github/workflows/push-to-master.yml
Fix CI on master branch. We need to either install `xgboost` explicitly or not test `xgboost` at all. I see no reason to test `test_default.py` file, since the test in it does not run for Ray.
Failed CI run: https://github.com/modin-project/modin/actions/runs/5691288650/job/15426197945
> FIX-#0000: don't test experimental xgboost with Ray nightly build

- environment-dev.yml
- requirements-dev.txt
- requirements/env_unidist.yml
> FIX-#6429: exclude pymssql==2.2.8 from environments

- modin/core/dataframe/algebra/tree_reduce.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
> FIX-#6372: precompute dtypes for 'sum' operation

- .github/workflows/ci.yml
- asv_bench/asv.conf.hdk.json
The changes works: https://github.com/modin-project/modin/actions/runs/5729826080/job/15527659650
> TEST-#6439: create HDK environment manually for ASV

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
> REFACTOR-#4278: remove unused arguments from `BasePandasDataset.apply`

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
Disable lazy_fetch and columnar_output for groupby and enable for join queries.
> FEAT-#6440: Use different HDK parameters for different queries

- docs/conf.py
- docs/getting_started/using_modin/using_modin_cluster.rst
It is strange that this problem did not appear before. Perhaps there was some kind of caching that I did not take into account.
> FIX-#6456: create fake xgboost module for building docs

- modin/experimental/pandas/io.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
- modin/utils.py
Implemented a decorator which would expand user paths (i.g. `~/foo.txt` or `~user/bar.txt`) passed as given argument in the decorated function. This should stop unnecessary defaulting to pandas for some implementations (where we checked that file existed, which it doesn't until one expands the path).
Note: supersedes #4724.
> FIX-#6436: Support ~ in paths in IO functions correctly

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
> FIX-#6443: Cast boolean columns before sum|mean|median groupby aggregations

- modin/core/storage_formats/pandas/query_compiler.py
- modin/test/storage_formats/pandas/test_internals.py
> PERF-#6437: preserve dtypes for 'reindex'

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
> TEST-#6469: pin numexpr<2.8.5

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
> FIX-#6479: HDK CalciteBuilder: Do not call is_bool_dtype() for categorical

- CODEOWNERS
Stop requiring modin-xgboost approval for xgboost code. Current @modin-project/modin-xgboost members don't know much more than other members of modin-core about the xgboost code.
> FIX-#6446: Stop requiring modin-xgboost approval

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/dataframe.py
- modin/test/storage_formats/pandas/test_internals.py
- setup.cfg
The PR adds this new behavior for `._set_columns()` only, this is for the reason that the row indices are usually much longer and more complex than columns, thus their equality comparison may be much more expensive and would require additional heuristics valuing whether it's worth performing expensive comparison or not.
**Motivation for this PR:**
There are quite a few places where modin's implementations unconditionally overwrite the frame's columns with some specified key even if the original columns are identical to this key. For example, when setting new values for a column, the implementation sets the key as a new column value:
https://github.com/modin-project/modin/blob/3b3bba9a83b6bec35e86826800004987afe24d47/modin/core/storage_formats/pandas/query_compiler.py#L2817-L2818
New …
> PERF-#6478: Do not propagate new columns if they're identical to the previous ones

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
This PR replaces a full-column implementation of `.dropna()` with a chain of two row-axis/map functions. 
At the first stage, we submit a row-axis function evaluating whether each column should be dropped for this specific row partition and builds a boolean mask for that matter, at the second stage those masks are being merged and the columns to be dropped are being dropped.
<details><summary>perf results</summary>
Here's the comparison for `df.dropna(axis=1, how="any")` between these two implementations:
<details><summary>code to measure</summary>
```python
cfg.BenchmarkMode.put(True)
pd.DataFrame([np.arange(cfg.MinPartitionSize.get()) for _ in range(cfg.NPartitions.get() ** …
```
> PERF-#6433: Implement '.dropna()' using map-reduce pattern

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist.yml
- requirements/requirements-no-engine.yml
`boto3` is still installed as an implicit dependency.
> TEST-#6497: remove `boto3` from environments to speedup creation

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_map_metadata.py
As in the linked issue, we now check that the argument to an `__invert__` (`~` operator) is integral or boolean at the API layer. The raised error message slightly differs from that raised by pandas, but is arguably clearer:
```
import pandas
>>> ~pd.DataFrame([1.1])
UserWarning: Distributing <class 'list'> object. This may take some time.
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/jhshi/code/modin/modin/logging/logger_decorator.py", line 128, in run_and_log
return obj(*args, **kwargs)
File "/Users/jhshi/code/modin/modin/pandas/base.py", line 3699, in __invert__
raise TypeError(
TypeError: bad operand type for unary ~: 'float64'
>>> ~pandas.DataFrame([1.1])
Traceback (most recent call last):
File "<stdin>", line 1, in …
```
> REFACTOR-#6489: Enforce API-layer bool/integer argument for __invert__

- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
> FEAT-#6500: HDK: Add support for datetime64 to int64 cast

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/test/conftest.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_groupby.py
Wrap a list-like object into a single-column query compiler before the insertion.
Note: this PR does not cover the HDK backend. For HDK a separate PR is created https://github.com/modin-project/modin/pull/6412, but it's not ready yet due to the HDK issue https://github.com/intel-ai/hdk/issues/588.
> PERF-#6398: Improved performance of list-like objects insertion into DataFrames

- modin/conftest.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/test_groupby.py
- modin/test/storage_formats/pandas/test_internals.py
This PR changes the old condition dispatching to the reshuffling implementation for non-numeric keys (`if dtype == object:`) to a broader one: (`if not is_numeric_dtype(dtype):`)
> FIX-#6509: Fix 'reshuffling' in case of a string key

- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#6514: test_sort_cols_str from test_dataframe.py crashed on HDK 0.7.0 and python 3.9

- modin/conftest.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/test_groupby.py
- modin/test/storage_formats/pandas/test_internals.py
Roughly speaking, reshuffling groupby is performed row-wise. Which means, that if we're dealing with some really complex user-defined function in `.apply()` that produces results with arbitrary shapes/labels, then we can end up with an invalid dataframe at the end:
```python
grp.apply(
lambda group: (
pandas.Series([1, 2], index=["a", "b"])
if random_int() % 2
else pandas.Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
)
)
potential result:
a  b
0   1  2         <---- row partition №1  |                                          in pandas the result would be like:
1   1  2                                 |  two row partitions have different    |    a  b  c   d
2   1  2                                 |  columns, which means that the frame  | 0  1  2  NaN NaN
------------- …
```
> FIX-#6465: Fix `groupby.apply()` for UDFs that change the output's shape

- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_algebra.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py
> FIX-#6516: HDK: test_dataframe.py is crashed if Calcite is disabled

- modin/core/storage_formats/pandas/query_compiler.py
> FIX-#6392: Compute detypes for the DataFrame.mean() result

- modin/core/io/io.py
- modin/core/io/text/excel_dispatcher.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
> FIX-#4347: read_excel: defaults to pandas for unsupported types of 'io'

- modin/core/dataframe/algebra/reduce.py
- modin/core/storage_formats/pandas/query_compiler.py
We always get a single-column qc at the end of `.to_datetime()`, so it's worth adding a shape hint.
> PERF-#6524: Add a 'column' shape hint for the results of 'qc.to_datetime()'

- modin/core/dataframe/pandas/interchange/dataframe_protocol/column.py
- modin/test/interchange/dataframe_protocol/test_general.py
> FIX-#4687: change 'Column.null_count' to return a builtin int instead of NumPy scalar

- README.md
Update the link of the CI badge so it would _not_ show unsuccessful CI runs for pull requests (they aren't considered for the badge itself, but are displayed when clicking it, which is confusing).
> DOCS-#0000: Update CI link in README to show only pushes

- modin/core/storage_formats/pandas/parsers.py
> FIX-#6532: fix `read_excel` so that it doesn't use `rich_text` param for old `openpyxl`

- modin/core/storage_formats/pandas/query_compiler.py
- modin/numpy/test/utils.py
Fix [CI](https://github.com/modin-project/modin/actions/runs/6093900128/job/16536041233) on master branch after upgrading to pandas 2.1.
> FIX-#6541: fix "ValueError: buffer source array is read-only" for `iloc`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/test_groupby.py
- modin/test/storage_formats/pandas/test_internals.py
The current implementation of reshuffling groupby takes the first column that was specified as the `by` argument (for example, if `groupby(["col1", "col2"])` was called, then the "col1" will be taken) and builds range partitioning based on that picked column. The problem here is that, if the "col1" has very low cardinality (too few unique values) then there will be too few range partitions at the end and so poor cores utilization.
```python
>>> df
col1  col2  # 'col1' has only 2 unique values, meaning that there will be only 2
0    Y     1  # range partitions, so no matter how many cores we have, we couldn't
1    Y     2  # use more than 2 to process this groupby
2    N     3
3    Y     4
```
We can't do much about this problem (at least in terms of range-partitioning implementation) when …
> PERF-#6464: Improve reshuffling for multi-column groupby in low-cardinality cases

- modin/pandas/test/dataframe/test_udf.py
Looks like #4477 is resolved, so I'll just add a test (the same for #5511 which I closed recently).
> TEST-#4477: add tests for `df.eval` with scalar and `groupby.transform` call in the expr

- modin/conftest.py
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
This change also fixes #6543.
Corrects the handling of range indices in read_parquet.
Specifically:
- Use all the pandas metadata present, including start, step, and name
- Emulate pyarrow and fastparquet behavior in the case of invalid metadata for a directory (which was actually the common case, or at least the only one we were testing)
- Add tests for all this functionality, including more cases such as (correctly) shared metadata between files in a directory
> FIX-#6540: Correct handling of range indices in read_parquet

- modin/core/io/text/text_file_dispatcher.py
- modin/pandas/test/test_io.py
This case is not supported and should work correctly by defaulting to pandas.
> FIX-#6553: fix 'read_csv' with 'iterator=True'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/cudf/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/numpy/indexing.py
- modin/pandas/dataframe.py
- modin/pandas/indexing.py
- modin/pandas/utils.py
- modin/test/storage_formats/pandas/test_internals.py
> FIX-#6394: preserve dtypes for __setitem__ op when using not hashable key

- modin/distributed/dataframe/pandas/partitions.py
- modin/test/test_partition_api.py
Continues work started in https://github.com/modin-project/modin/pull/5258. сс @mvashishtha @RehanSD 
> FIX-#5164: Fix unwrap_partitions for virtual partitions when `axis=None`

- modin/core/io/column_stores/column_store_dispatcher.py
- modin/core/io/column_stores/parquet_dispatcher.py
This PR brings the following changes to how parquet reading is being distributed:
1. <b>The number of column partitions is now depended on the number of row partitions.</b> Before, the implementation tended to create as much column partitions as possible (it often resulted into that column partitions consisted of only one column) which worked relatively fine if there were no row-groups in the parquet file (and so no row partitions):
```python
NUM_CPUS=16
parquet_file # has 1 row group and 16 columns
pd.read_parquet(parquet_file)._partitions.shape # (1, 16) - 1 row partition and 16 column parts
```
However, if there were enough row groups to keep all the workers busy, this excessive amount of column partitions resulted into an over partitioned frame:
```python
file1 # has 9 row groups and …
```
> FIX-#6558: Normalize the number of partitions after `.read_parquet()`

- modin/config/envvars.py
- modin/config/test/test_envvars.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py
> FIX-#6561: remove `MODIN_OMNISCI_*` env vars in favor of `MODIN_HDK_*`

- modin/core/storage_formats/pandas/parsers.py
- modin/core/storage_formats/pandas/utils.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_io.py
> REFACTOR-#6569: use 'contextlib.nullcontext' instead of custom one

- .github/workflows/ci.yml
- asv_bench/benchmarks/utils/data_shapes.py
> TEST-#4270: revert disabling `time_groupby_agg_nunique` ASV bench 

- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
- modin/pandas/test/utils.py
> REFACTOR-#6576: Don't use deprecated `is_int64_dtype` and `is_period_dtype` functions

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_udf.py
- modin/pandas/test/utils.py
> PERF-#6583: Remove redundant index reassignment in query()

- requirements-dev.txt
I guess we don't have to worry about how users install this dependency in production.
> TEST-#4348: use `psycopg2-binary` for testing and developing purpose

- docs/usage_guide/advanced_usage/spreadsheets_api.rst
> DOCS-#6416: fix import path for spreadsheet feature

- .github/workflows/ci.yml
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
> FIX-#6587: Use different env files for unidist engine for windows and linux

- modin/core/dataframe/pandas/partitioning/partition_manager.py
This PR changes the logic of partitioning pandas dataframes in `.from_pandas()`. We used to call `.iloc` in a loop with two arguments - row and column slice, the new logic now first splits a dataframe into column chunks and then each column chunk into row chunks.
A [recently introduced regression in pandas 2.1](https://github.com/pandas-dev/pandas/issues/55202) highlighted that columns slicing may sometimes be quite expensive, that's why it might not be a good idea to call it in a loop.
So here is the performance comparison showing the difference between the old and the new approach of slicing a pandas dataframe, note that the new approach is also better even on pandas 2.0.3 where the problem of columns slicing was not yet that visible.
<details><summary>performance difference</summary> …
> PERF-#6590: Chunk axes independently in '.from_pandas()'

- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_io.py
> TEST-#6593: adapt tests for pandas 2.1.1

- modin/core/dataframe/algebra/default2pandas/groupby.py
- modin/core/dataframe/pandas/interchange/dataframe_protocol/column.py
- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/core/execution/dask/common/utils.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/partition.py
- modin/core/execution/ray/common/utils.py
- modin/core/execution/unidist/common/utils.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
- modin/core/execution/utils.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/pandas/base.py
- modin/pandas/groupby.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_groupby.py
- setup.cfg
The unwanted `FutureWarning`s can occur in the main process or in workers:
* For worker processes, the simplest solution is to use `PYTHONWARNINGS` environment variable (for example, `PYTHONWARNINGS="ignore::FutureWarning"`).
* For the main process, we cannot use this variable because otherwise we will not be able to show the necessary warnings (warnings that are explicitly defined by us at the upper levels, not lower than the compiler version). Another solution is to use a context manager and an warnings filter (by warning type and content). The main difficulty here is that there are a lot of points where these warnings occur - potentially any place where we use pandas functions. I believe that the most convenient level for catching warnings will be the partition level (the basis through …
> FIX-#6552: avoid `FutureWarning`s in `groupby` unless necessary

- modin/pandas/base.py
> FIX-#6582: avoid `FutureWarning`s in `bfill/backfill/ffill/pad` unless necessary

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/test/storage_formats/pandas/test_internals.py
Different implementations of `.sort_values()` (row-wise and the one based on range-partitioning) produce different partitioning and so different cache propagation logics should be applied.
Before this PR, the cache was unconditionally set based on the assumption that we're always dealing with range-partitioning implementation, which is not true (check #6607 for more details). The cache-setting logic was now moved from the `.sort_by()` method (that doesn't know which implementation is used) to the `._apply_func_to_range_partitioning()` which dispatches between row-wise and range-partitioning implementations based on the data size and so can propagate the cache properly.
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or …
> FIX-#6607: Fix incorrect cache after '.sort_values()'

- modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py
> PERF-#6614: HDK: Use MODIN_CPUS instead of os.cpu_count() for the fragment size calculation

- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_series.py
> REFACTOR-#6622: don't use deprecated `random_integers` func

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/utils.py
This PR changes logic of `__setitem__` on assigning multiple columns. 
<details><summary>micro-benchmark</summary>
```python
cfg.BenchmarkMode.put(True)
shapes = [(1_000_000, 10), (1_000_000, 100), (10_000_000, 10), (10_000_000, 100)]
for nrows, ncols in shapes:
df = pd.DataFrame({f"col{i}": range(nrows) for i in range(ncols)})
subset = df.columns[[0, 1, 2, 4, 6, -1, -2, -3]].tolist()
item = df[subset] * 10
t1 = timer()
df[subset] = item
print(timer() - t1)
```
</details>
> PERF-#6362: Implement 2D setitem without to-pandas conversion

- modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
> FIX-#6635: HDK: read_csv(): treat object dtype as string

- modin/core/io/text/excel_dispatcher.py
- modin/core/storage_formats/pandas/parsers.py
- modin/pandas/test/test_io.py
Since `skiprows` is not supported, we need to default to pandas if this option is used.
> FIX-#6637: Fix `skiprows` parameter usage for `read_excel`

- setup.cfg
This will help me since I'm currently working on warnings (removing extras/adding missing ones). On the other hand, this should not complicate much reading CI runs.
> TEST-#5489: Allow for pytest to print warnings in tests output

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/test_series.py
> FIX-#6624: Add `FutureWarning`s for `first/last/bool`

- modin/core/execution/ray/common/utils.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/test/storage_formats/pandas/test_internals.py
The PR was brought to eliminate `ray.get()` calls from inside the ray kernel that executes the partitions call queue, which sometimes triggered a deadlock. Before this PR, materialization of all the futures was explicitly triggered inside the kernel using `ray.get()`, and now all the futures are being passed to the kernel as a variable-length parameter, allowing for Ray [to materialize them implicitly beforehand](https://docs.ray.io/en/latest/ray-core/walkthrough.html#passing-an-object).
Testing performance shows no major difference for other cases:
<details><summary>case 1 (getitem + transpose); 29 elements in queue</summary>
```python
from asv_bench.benchmarks.utils.common import execute
import …
```
> FIX-#4507: Do not call 'ray.get()' inside of the kernel executing call queues

- modin/experimental/sql/hdk/__init__.py
By making a contribution to this project, I certify that:
1.) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or 2.) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or 3.) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it. 4.) I understand and agree that this project and the contribution are public and …
> BUG-#6647: Added init file to make modin/experimental/sql/hdk/query.py part of modin package

- modin/config/envvars.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
- modin/pandas/test/test_io.py
So I've implemented the distributed `from_pandas()` approach suggested in [this comment](https://github.com/modin-project/modin/issues/2813#issuecomment-1753024035) and ran some perf testing with it. 
The first observation being made, is that the new approach seems to work better only with numerical data, as with python strings, putting the whole big dataframe into the storage takes too much time. I believe it's a topic for a further fine-grained tuning to determine how much of string columns in a dataframe is okay for the distributed implementation. As for now, I suggest proceeding with only numericals.
Then I ran this micro benchmark for each engine, in order to determine with what data sizes of numerical data it makes sense to use the distributed implementation.
<details><summary>the …
> PERF-#2813: Distributed 'from_pandas()' for numerical data in Ray

- modin/core/storage_formats/pandas/query_compiler.py
Manually aligning indexes is much cheaper than using `sync_label` option, which creates a copy for each partition with an updated index (lazy map operation).
> PERF-#6645: avoid label synchronization for `dot` operation

- modin/pandas/base.py
> PERF-#6653: value_counts(): Eliminate redundant sorting.

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
> FIX-#6651: make sure `Series.between` works correctly

- modin/pandas/test/test_series.py
I believe that such low-level commits need not be shown in the change notes. That’s why I don’t create a separate issue so that later I can (or someone) exclude commits that have the `#0000` number.
> TEST-#0000: remove test for deprecated `reshape` func

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#6632: Return Series instead of Dataframe for groupby.apply in case of experimental groupby 

- docs/conf.py
> FIX-#6680: Specify navigation_with_keys=True to fix docs build

- modin/pandas/base.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
The changes according to https://pandas.pydata.org/pandas-docs/version/2.1.2/whatsnew/v2.1.2.html#deprecations.
> FIX-#6684: Adapt to pandas 2.1.2

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/groupby.py
> PERF-#6668: Use `copy=False` for internal usage of `set_axis`

- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#6690: Use `sync_labels=False` for `rank` function

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#6694: Use lazy_map_partitions() for dtypes conversion

- modin/pandas/test/test_io.py
> TEST-#6705: Don't compare `pkl` files

- modin/core/storage_formats/pandas/query_compiler.py
IIUC `reset_index` [was needed](https://github.com/modin-project/modin/pull/1695#discussion_r453586525) to build the correct RangeIndex. However, this can be done in a cheaper way by passing the lengths to internal partitions.
> PERF-#6666: Avoid internal `reset_index` for left `merge`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#6702: don't materialize axes when calling `to_numpy`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
- modin/core/storage_formats/pandas/query_compiler.py
Length materialization is in most cases cheaper than index materialization.
> PERF-#6710: Don't materialize index in `_groupby_shuffle` internal function

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
> PERF-#6701: use `get_axis` internal function instead of `axes` property

- modin/pandas/groupby.py
This code was added quite a long time ago. I don’t know exactly which case this fixes, but all tests pass. I suggest deleting it, since it materializes the index (and it seems to be unnecessary).
> FIX-#6703: don't use `set_index_name(None)`

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#6716: Avoid materializing axes in `_filter_empties`

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#6718: Use `_get_axis_lengths` func instead of `_axes_lengths` property

- modin/core/dataframe/pandas/dataframe/dataframe.py
Revert https://github.com/modin-project/modin/pull/6267 as pandas fix its bug.
> FIX-#6693: revert creating an additional copy in `astype` function

- modin/pandas/groupby.py
> PERF-#6727: Remove remaining `result.name = None` in groupby code

- modin/core/dataframe/pandas/dataframe/dataframe.py
> FIX-#6664: Use `@lazy_metadata_decorator` for `PandasDataFrame.finalize`

- modin/core/storage_formats/pandas/query_compiler.py
The main idea is that the resulting mask (from `duplicated`) is often used on the same dataframe, for example in the implementation of `drop_duplicates` function, and if we do not change the partitioning, we will be able to avoid the co-partitioning phase.
**Results (best):** 19.39 (master) vs 17.35 (PR)
Benchmark
```python
np.random.seed = 42
df = pd.DataFrame(np.random.rand(10 ** 7, 10))
for _ in range(5):
start = time()
execute(df.drop_duplicates())
print(f"drop_duplicates time: {time()-start}")
```
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up …
> PERF-#6721: Use `keep_partitioning=True`, for `duplicated` implementation

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
> PERF-#6696: Use cached dtypes in fillna when possible.

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/dataframe/dataframe.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/dataframe/dataframe.py
- modin/core/storage_formats/base/query_compiler.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_pickle.py
- modin/pandas/test/test_series.py
The PR also fixes https://github.com/modin-project/modin/issues/4919
> FIX-#6594: fix usage of Modin objects inside UDFs for `apply`

- modin/core/execution/ray/generic/partitioning/partition_manager.py
- modin/core/execution/unidist/generic/partitioning/partition_manager.py
8 cores Ray: 2.54 (Master) vs 1.24 (PR)
8 cores Unidist: 6.11 (Master) vs 0.22 (PR)
Benchmark:
```python
for _ in range(5):
df = pd.DataFrame(np.random.rand(10 ** 6, 10).astype(str))
start = time()
arr = df.to_numpy()
print(f"to_numpy conversion: {time()-start}, {arr.size=}")
```
> PERF-#6728: In the case of narrow dataframes, it is cheaper to convert partitions to numpy in the main process.

- modin/core/dataframe/algebra/binary.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_binary.py
Instead of using `find_common_dtype` that sometimes gives incorrect results, we now run a binary operation on small pandas DataFrames to get proper dtypes.
> FIX-#6732: Fix inferring result dtypes for binary operations

- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
> REFACTOR-#6739: Use `execution_wrapper` instead of directly addressing `DaskWrapper`

- .github/workflows/ci-notebooks.yml
- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- README.md
- docs/conf.py
- docs/development/architecture.rst
- docs/development/index.rst
- docs/development/partition_api.rst
- docs/development/using_pandas_on_mpi.rst
- docs/flow/modin/core/execution/unidist/implementations/pandas_on_unidist/index.rst
- docs/getting_started/faq.rst
- docs/getting_started/installation.rst
- docs/index.rst
- docs/requirements-doc.txt
- examples/tutorial/jupyter/README.md
- examples/tutorial/jupyter/execution/pandas_on_unidist/Dockerfile
- examples/tutorial/jupyter/execution/pandas_on_unidist/jupyter_unidist_env.yml
- examples/tutorial/jupyter/execution/pandas_on_unidist/local/exercise_1.ipynb
- examples/tutorial/jupyter/execution/pandas_on_unidist/requirements.txt
- modin/core/execution/unidist/common/utils.py
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- setup.py
> FEAT-#6735: Make Modin on MPI through unidist component more obvious

- docs/release_notes/release_notes-0.16.0.rst
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/dataframe/pandas/utils.py
> PERF-#4777: Don't use `copy=True` parameter for `concat` calls inside `to_pandas`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/test/storage_formats/pandas/test_internals.py
Preserve partial dtypes for the result of `.reset_index()` by using `ModinDtypes.concat()` API
> PERF-#6749: Preserve partial dtype for the result of 'reset_index()'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/test/storage_formats/pandas/test_internals.py
Detect the value's dtype and insert in into partial dtypes for the result of `.insert()`
> FIX-#6752: Preserve dtypes cache on '.insert()'

- modin/core/dataframe/base/dataframe/utils.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_join_sort.py
Add logic handling simple cases of joining on an index level in `join_columns()` and rewrite logic of dtypes preserving so it would also consider index dtypes where possible
> PERF-#6747: Preserve columns/dtypes cache when merging on a single index level

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/metadata/__init__.py
- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/test/storage_formats/pandas/test_internals.py
Detect the value's dtype and insert in into partial dtypes for the result of `.setitem()`
> PERF-#6753: Preserve dtypes cache on '.__setitem__()'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/test/storage_formats/pandas/test_internals.py
- setup.cfg
This PR adds `ModinDtypes.concat(axis=0)` method, that allows to merge partial dtypes on `pd.concat(axis=0)`
> PERF-#6754: Merge partial dtype caches on '.concat(axis=0)'

- modin/core/dataframe/algebra/groupby.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/metadata/index.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/test/storage_formats/pandas/test_internals.py
This PR adds `._dtypes` property to `ModinIndex`, one can pass it to the object's constructor and indicate dtypes of index levels, even if the index values are yet unknown.
This was done mainly to preserve dtypes in the following case:
```python
df.dtypes # known_dtypes: {"a": int, ...}
res = df.groupby("a", as_index=True).sum()
res # 'a' column is now in the index, but we lost its dtypes
res = res.reset_index(drop=False)
res.dtypes # cols_with_unknown_dtypes: ["a"]
```
With the changes in this PR, the presented scenario will preserve dtype for "a" column in the end.
> PERF-#6762: Carry dtypes information in lazy indices

- modin/core/dataframe/pandas/partitioning/partition.py
- modin/core/execution/ray/generic/partitioning/partition_manager.py
- modin/core/execution/unidist/generic/partitioning/partition_manager.py
- modin/pandas/test/test_series.py
> FIX-#6768: make sure `to_numpy` use `**kwargs` after #6704

- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/pandas/test/test_series.py
> FIX-#6771: avoid `ValueError: assignment destination is read-only` for `cumsum`

- modin/core/dataframe/pandas/utils.py
- modin/pandas/test/test_general.py
> FIX-#6773: make sure `_to_pandas` return mutable pandas objects

- modin/pandas/indexing.py
- modin/pandas/test/test_series.py
> FIX-#6779: pass only one indexer into `Series.__getitem__`

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_binary.py
> FEAT-#6784: Add d2p implementations for `DataFrame.__rdivmod__/__divmod__`

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_join_sort.py
> FIX-#6786: properly d2p for cross `DataFrame.join`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/dataframe/test_reduce.py
> FIX-#6781: Use `pandas.api.types.pandas_dtype` to convert to valid numpy and pandas only dtypes

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
In supporting fastparquet, modin takes the paths provided, globs them, and filters them to only look at files with the .parq or .parquet extension. This commit adds support so that if the path supplied is explicitly a file, it will be included.
Signed-off by: Ari Brown <ari@aribrown.com>
If a a file is passed to `modin.pandas.read_parquet(..., engine='fastparquet')` but the file does not have ".parq" or ".parquet" in the name, it will be ignored when determining the number of partitions. This change looks at all of the paths passed, and if the path is a file, then it considers it to be a parquet file.
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up …
> FIX-#6778: Read parquet files without file extensions using fastparquet

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/test/storage_formats/pandas/test_internals.py
> PERF-#4804: Preserve lengths/widths caches in `broadcast_apply_full_axis`

- asv_bench/benchmarks/scalability/scalability_benchmarks.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/test_dataframe.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/io.py
- modin/pandas/plotting.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
- modin/pandas/utils.py
- modin/test/interchange/dataframe_protocol/base/test_sanity.py
- modin/test/interchange/dataframe_protocol/hdk/test_protocol.py
- modin/utils.py
This PR moves the following IO function to the `modin.pandas.io` module:
- `from_pandas()`
- `from_arrow()`
- `from_dataframe()`
- `from_non_pandas()`
- `to_pandas()`
- `to_numpy()`
The `try_cast_to_pandas()` function was not moved as IMO it's more of a utility function rather than a pure IO. However, if reviewers think differently, I still can move it to the IO module.
> REFACTOR-#6805: Move all IO functions to 'modin.pandas.io' module

- modin/conftest.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/utils.py
- setup.cfg
> TEST-#6729: Use custom pytest mark instead of `--extra-test-parameters` option

- modin/core/dataframe/algebra/binary.py
- modin/pandas/test/test_series.py
> FIX-#6782: filter pandas warnings when precomputing dtypes

- docs/getting_started/using_modin/using_modin_cluster.rst
- docs/getting_started/using_modin/using_modin_locally.rst
- modin/core/execution/ray/common/utils.py
> DOCS-#6819: Update Modin on cluster documentation

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/metadata/index.py
- modin/test/storage_formats/pandas/test_internals.py
Invalidate old row/column lengths stored in `ModinIndex._lengths_cache` and `ModinIndex._lengths_id` if partitioning was modified during the empty partitions filtering.
> FIX-#6824: Invalidate 'ModinIndex._lengths_id' on empty partitions filtering

- modin/core/execution/ray/common/utils.py
- modin/utils.py
> REFACTOR-#0000: cleanup one todo and flake8 issues in `modin/utils.py`

- modin/config/envvars.py
> REFACTOR-#6833: Remove `SocksProxy`, `DoLogRpyc`, `DoTraceRpyc` outdated classes

- modin/pandas/test/test_io.py
> TEST-#6846: Skip unstable Unidist to_csv tests

- examples/docker/modin-hdk/plasticc-hdk.py
- examples/docker/modin-ray/plasticc.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/io/io.py
- modin/core/storage_formats/cudf/parser.py
- modin/core/storage_formats/pandas/parsers.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/experimental/core/io/sql/utils.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
> REFACTOR-#6852: Remove OrderedDict in favor of builtin dict

- .github/workflows/ci.yml
> TEST-#6777: Make `to_csv` tests on Unidist more stable (for `test-all-unidist` CI job)

- docs/flow/modin/experimental/pandas.rst
- docs/supported_apis/dataframe_supported.rst
- docs/supported_apis/io_supported.rst
- docs/usage_guide/advanced_usage/index.rst
- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
- modin/core/io/io.py
- modin/experimental/core/io/__init__.py
- modin/experimental/core/io/glob/__init__.py
- modin/experimental/core/io/glob/glob_dispatcher.py
- modin/experimental/core/storage_formats/pandas/parsers.py
- modin/experimental/pandas/__init__.py
- modin/experimental/pandas/io.py
- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/accessor.py
- modin/pandas/dataframe.py
> FEAT-#6831: Implement read_parquet_glob and to_parquet_glob

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/common/engine_wrapper.py
- modin/core/execution/python/common/engine_wrapper.py
- modin/core/execution/ray/common/engine_wrapper.py
- modin/core/execution/ray/implementations/pandas_on_ray/dataframe/dataframe.py
- modin/core/execution/unidist/common/engine_wrapper.py
> REFACTOR-#6858: Rename _get_dimensions and change arguments

- docs/ecosystem.rst
- docs/index.rst
> DOCS-#6860: Add an ecosystem page to the docs

- modin/experimental/core/execution/native/implementations/hdk_on_native/expr.py
> FEAT-#6382: Execute bitwise NOT (~) operations on HDK

- modin/core/io/column_stores/parquet_dispatcher.py
- modin/pandas/test/test_io.py
> FIX-#6855: Make sure read_parquet works with integer columns for pyarrow engine

- modin/core/dataframe/pandas/dataframe/dataframe.py
This PR extends the idea originally introduced in #6423.
<b> What's the idea </b>
The masking pipeline consists of two stages:
1. Compute individual indexers for each partition and mask them.
2. If the indexing forces reordering, apply a full-column reordering function to the result of the first stage.
In theory, the second stage can function without the first one, the first stage is needed in order to reduce the dimension of the input for the second stage. However, sometimes the first stage can be quite expensive, and it could be reasonable to skip it and jump to the second one right away.
This PR extends the number of cases where we skip the first stage with the cases where we know for sure that the reordering stage will be required. Based on the measurements below, I found out the …
> PERF-#6876: Skip the masking stage on 'iloc' where beneficial

- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/ray/common/engine_wrapper.py
Added functions cache to RayWrapper.
Removed lambda wrapper for the binary functions.
> FEAT-#6835: Do not put binary functions to the Ray storage multiple times.

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/test_series.py
> FIX-#6881: Make sure `astype` works correctly with `int32` and `float32` dtypes

- modin/experimental/pandas/test/test_io_exp.py
- modin/pandas/test/test_io.py
> TEST-#6868: Remove tests for 'gs' remote protocol since Modin rely on 'fsspec'

- modin/core/dataframe/algebra/default2pandas/groupby.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/dataframe/pandas/utils.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/test_groupby.py
- setup.cfg
This PR allows grouping on categorical columns using range-partitioning implementation. The main challenge with this was to support proper behavior of the default value of [`groupby(observed=False)`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) parameter. `observed=False` as a default value for groupby is deprecated, however it will only be [replaced in pandas 3.0](https://github.com/pandas-dev/pandas/issues/55261), so we should have an implementation for that.
<b> What's `observed=False`? </b>
This parameter includes missing categories into the result index, the missing values are then filled with the default value for this particular aggregation. Consider this example for more details:
<details><summary>An example of how `observed=False` works</summary> …
> FEAT-#5925: Enable grouping on categoricals with range-partitioning impl 

- modin/pandas/base.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/utils.py
> FIX-#2405: Make sure named aggregation work for Series objects

- modin/pandas/test/test_groupby.py
CI on master started to fail after #6862 was merged (https://github.com/modin-project/modin/actions/runs/7701338108/job/20995335180). The tests are failing because the order of rows doesn't match between modin and pandas. The test fails even if I won't cast the data to categoricals, so I'm blaming #6875 for the failures. The failure isn't stable (fails not always), that's why it wasn't caught before merging #6862.
My current plan is:
1. Merge this hack in order to unblock CI
2. Make the investigation of #6875 my first priority
> FIX-#5925: Put a sorting-hack into groupby tests to hide #6875 bug

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/test/test_groupby.py
> FIX-#6899: Avoid sending lazy categorical proxies to workers

- modin/core/dataframe/algebra/groupby.py
- modin/core/storage_formats/pandas/parsers.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/error_message.py
- modin/pandas/groupby.py
- modin/pandas/test/utils.py
- modin/pandas/window.py
- modin/test/storage_formats/pandas/test_internals.py
Refactored code in response to issue #6293, addressing a typographical error. I corrected 'missmatch' to 'mismatch' across instances of  ```ErrorMessage.missmatch_with_pandas``` method as well as in some comments. 
> REFACTOR-#6293: Corrected 'missmatch' to 'mismatch' across instances of ErrorMessage.missmatch_with_pandas method 

- modin/core/dataframe/pandas/dataframe/dataframe.py
The actual issue was fixed by #6900, so we don't need this workaround anymore
> FIX-#6897: Revert unidist specific workaround for groupby

- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/test_general.py
> FIX-#6911: Remove unidist specific workaround in '.from_pandas()'

- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/test/storage_formats/pandas/test_internals.py
The original issue was caused by mixed non-MultiIndex and MultiIndex labels appearing in partial dtypes:
```python
>>> df.columns
MultiIndex([('a', ''),
('l1', 'l2')],
)
>>> df._dtypes_cache
{"a": int, ("l1", "l2"): int}
>>> df._materialize_dtypes() # error
```
The reason why partial dtypes was constructed that way - is unpredictability in how pandas merges non-MultiIndex and MultiIndex columns. 
<details><summary> Few examples of unpredictability</summary>
1. `.reset_index()` case:
```python
>>> df.index.names 
"a" <--- flat label
>>> df.columns
MultiIndex([('l1', 'l2')]) <--- MultiIndex columns
>>> df.reset_index().columns
MultiIndex([('a', ''),     <--- when merged, MultiIndex is preserved, missing levels
('l1', 'l2')],      are filled with an empty string
)
```
2. `pandas.concat()` …
> FIX-#6904: Align levels of partially known dtypes with MultiIndex labels

- modin/config/__init__.py
- modin/config/envvars.py
- modin/core/execution/dask/common/utils.py
> FEAT-#6914: Add a config for setting a number of threads per Dask worker

- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
**Depends on #6836.**
Multiple binary operations are faster to execute lazy, in a single batch. Here is an example:
```python
import ray
ray.init()
import time
df = pd.Series(range(100000))
start = time.time()
for i in range(100):
df = df + i
execute(df)
print(f"Time: {time.time() - start}")
```
Time: 2.4991016387939453
Time on master: 5.286777019500732
> FEAT-#6838: Prefer lazy execution for binary operations with scalar.

- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
> REFACTOR-#6918: Docstring and type hints fixes

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/dataframe/pandas/utils.py
- modin/core/storage_formats/pandas/query_compiler.py
> FIX-#6879: Convert the right DF to single partition before broadcasting in query_compiler.merge

- asv_bench/benchmarks/benchmarks.py
Same as in https://github.com/pandas-dev/pandas/pull/56155/files.
> TEST-#6932: don't use deprecated `pandas._testing.makeStringIndex`

- modin/core/storage_formats/pandas/query_compiler.py
You can find perf measurements and motivation in the issue: #6942
> FEAT-#6942: Enable range-partitioning impl for 'groupby().rolling()' by default

- .github/workflows/ci.yml
The `lint-black-isort` was moved to another file (#6945), so referencing it is no longer valid
> FIX-#6946: Remove 'needs: [lint-black-isort, ...]'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
Supporting this parameter is as simple as forwarding it to `groupby.apply()` call inside of the kernel
> FEAT-#6934: Support 'include_groups=False' parameter in 'groupby.apply()'

- modin/pandas/groupby.py
- modin/pandas/test/test_groupby.py
> FIX-#6948: Fix groupby when Modin dataframe has several column partitions

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/pandas/test/dataframe/test_join_sort.py
Fixing corner case when partitions are empty for merge.
> FIX-#6935: Fix Merge failed when right operand is an empty dataframe

- modin/experimental/pandas/__init__.py
> REFACTOR-#6958: Remove DataFrame.to_pickle_distributed in favour of DataFrame.modin.to_pickle_distributed

- modin/core/io/sql/sql_dispatcher.py
As outlined in the issue, these changes allow passing SQLAlchemy connection objects to `read_sql` by using the same workaround that is used for `to_sql`.
> FEAT-#6913: support sqlalchemy connectables in `read_sql` by getting connection url

- examples/tutorial/jupyter/execution/pandas_on_dask/cluster/exercise_5.ipynb
> DOCS-#6949: Create Modin on Dask cluster tutorial

- modin/test/test_docstring_urls.py
The PR starts using [`PANDAS_API_URL_TEMPLATE`](https://github.com/modin-project/modin/blob/271d98b260f03b345ae2384001f2df83b98322bf/modin/utils.py#L89) that always contains an actual pandas version instead of raw urls (if the pandas version in the url doesn't match with the installed one, the test fails)
> FIX-#6974: Always use actual pandas version in 'test_all_urls_exist'

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/test/storage_formats/pandas/test_internals.py
Check axes equality at the beginning of [`._copartition()`](https://github.com/modin-project/modin/blob/f601f8a9d602c70333548df3ef5e3c953df04f37/modin/core/dataframe/pandas/dataframe/dataframe.py#L3523) method using [`._check_if_axes_identical()`](https://github.com/modin-project/modin/blob/f601f8a9d602c70333548df3ef5e3c953df04f37/modin/core/dataframe/pandas/dataframe/dataframe.py#L3492), that supports computation-free comparison for sibling frames.
> PERF-#6979: Do not trigger '._copartition()' for identical indices on binary operations

- modin/core/dataframe/pandas/dataframe/dataframe.py
Changes in this PR prevent materialization for axes that were not specified in `._propagate_index_objs()`
> PERF-#6976: Do not trigger unnecessary computations on `._propagate_index_objs()`

- .github/workflows/ci.yml
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/utils.py
> FIX-#6984: Ensure the results of inplace operations materialize (for tests)

- examples/jupyter/Modin_Taxi.ipynb
- examples/jupyter/Pandas_Taxi.ipynb
> FIX-#6892: Updating data in notebooks from yellow taxi to green taxi dataset

- modin/logging/class_logger.py
- modin/logging/config.py
- modin/logging/logger_decorator.py
- modin/test/test_logging.py
> FEAT-#4622: Unify data type of log_level in logging module

- docs/ecosystem.rst
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/execution/ray/generic/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/io/io.py
- modin/pandas/dataframe.py
- modin/pandas/io.py
- modin/pandas/series.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_io.py
> FEAT-#6970: Implement to/from_ray_dataset functions

- modin/pandas/test/utils.py
> REFACTOR-#7002: get more information about exceptions from `eval_general` utility

- modin/config/__init__.py
- modin/config/envvars.py
- modin/config/test/docs_module/__init__.py
- modin/config/test/docs_module/classes.py
- modin/config/test/docs_module/functions.py
- modin/config/test/test_envvars.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/utils.py
Add support for custom documentation defined at runtime.
> FEAT-#6983: Add Pluggable Documentation Module Support

- README.md
- docs/flow/modin/experimental/pandas.rst
- docs/usage_guide/advanced_usage/index.rst
- modin/pandas/accessor.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/io.py
- modin/pandas/series.py
- modin/pandas/test/dataframe/test_indexing.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_io.py
- modin/pandas/test/test_series.py
- modin/utils.py
> REFACTOR-#7013: Move `to_pandas` and `to_ray_dataset` into modin namespace

- modin/core/execution/ray/common/__init__.py
- modin/core/execution/ray/common/deferred_execution.py
- modin/core/execution/ray/common/engine_wrapper.py
- modin/core/execution/ray/common/utils.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
> FEAT-#7001: Do not force materialization in MetaList.__getitem__()

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_api.py
> REFACTOR-#7017: Align `to_hdf` and `hist` signatures to pandas

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/utils.py
Part of https://github.com/modin-project/modin/pull/6954
> FIX-#7051: Update exception message for `astype` function

- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_default.py
> FIX-#7060: Fix `pivot` unexpected exception when index or columns are of Index type

- modin/pandas/test/test_io.py
- modin/pandas/test/utils.py
> TEST-#7066: Explicitly check for exceptions in `test_io.py`

- modin/pandas/test/test_groupby.py
- modin/pandas/test/utils.py
> TEST-#7064: Explicitly check for exceptions in `test_groupby.py`

- modin/pandas/__init__.py
- modin/pandas/arrays/__init__.py
- modin/pandas/test/test_api.py
- modin/pandas/test/test_series.py
This module is part of the public interface of Pandas.
> FEAT-#7070: Add `modin.pandas.arrays` module

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_reduce.py
- modin/pandas/test/dataframe/test_window.py
> FIX-#7088: Make sure `rank` raises `No axis named None...` exception

- modin/pandas/base.py
- modin/pandas/test/dataframe/test_reduce.py
> TEST-#7086: Explicitly check for exceptions in `test_reduce.py`

- modin/pandas/test/dataframe/test_map_metadata.py
> TEST-#7076: Explicitly check for exceptions in `test_map_metadata.py`

- asv_bench/benchmarks/utils/common.py
> REFACTOR-#3257: Move logging and caching to the gen_data function

- modin/core/execution/ray/common/engine_wrapper.py
- modin/test/storage_formats/pandas/test_internals.py
> FIX-#7072: Replace MaterializationHook with the materialized object on serialization.

- docs/ecosystem.rst
- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/io/io.py
- modin/pandas/accessor.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
- setup.py
> FEAT-#7021: Implement to/from_dask functions

- .github/actions/run-core-tests/group_3/action.yml
- docs/flow/modin/experimental/range_partitioning_groupby.rst
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_reduce.py
Adds range-partitioning implementation for `.nunique()` method. Unfortunately, range-partitioning in `.nunique()` can be used only for 1D data (`pd.Series` and 1-column DataFrames). The reason is that we need each column to be the 'key' in range-partitioning, which is not possible even if we use several columns to build bins:
```
initial df:        building bins for range-parts           splitting in range-parts           reduction phase
a  b       ---> bins: {                          ---->     a   b                           a 1                    
0  0  1                    0: [a<=0 and b<=10],            0  0   1    bin0.nunique()         b 2 
1  0  10                   1: [a<=0 and b>10]              1  0   10                  ---->   -----  sum(bin0, bin1)  ---->  a 2 (incorrect)
2 …
```
> FEAT-#7100: Add range-partitioning impl for 'nunique()'

- .github/actions/run-core-tests/group_2/action.yml
- .github/actions/run-core-tests/group_3/action.yml
- .github/workflows/ci.yml
- .github/workflows/push-to-master.yml
- docs/flow/modin/experimental/range_partitioning_groupby.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/test/dataframe/test_join_sort.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/test_general.py
- modin/pandas/test/test_series.py
- modin/pandas/test/utils.py
This PR merges implementations of `.unique()`/`.drop_duplicates()` into a single query compiler method called `unique()`. Some parts of `DataFrame.drop_duplicates()` implementation were moved to `BaseQueryCompiler.unique()`.
The performance highly depends on the number of duplicated values in the input data, so it's almost impossible to figure out a solid working heuristic:
<details><summary>perf for '.unique()'</summary>
MODIN_CPUS=16
MODIN_CPUS=44
<details><summary>script to measure</summary>
```python
import pandas
cfg.CpuCount.put(16)
def get_data(nrows, dtype):
if dtype == int:
return np.arange(nrows)
elif dtype == float:
return …
```
> FEAT-#7090: Add range-partitioning implementation for '.unique()' and '.drop_duplicates()'

- docs/ecosystem.rst
- docs/flow/modin/experimental/pandas.rst
- docs/usage_guide/advanced_usage/index.rst
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/execution/ray/generic/io/io.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/io/io.py
- modin/pandas/accessor.py
- modin/pandas/io.py
- modin/pandas/test/test_io.py
> REFACTOR-#7106: Rename from/to_ray_dataset to from/to_ray

- modin/config/envvars.py
> FEAT-#7102: Deprecate enable_api_only mode in modin logging

- .github/actions/mamba-env/action.yml
- docs/requirements-doc.txt
- environment-dev.yml
- examples/tutorial/jupyter/execution/pandas_on_ray/cluster/modin-cluster.yaml
- requirements-dev.txt
- setup.py
> TEST-#7125: Explicitly install modin in ci tests

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#7130: Preserve partition lengths in apply_full_axis with keep_partitioning=True

- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/base/interchange/dataframe_protocol/utils.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/core/storage_formats/pandas/aggregations.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/test/dataframe/test_map_metadata.py
- modin/pandas/test/dataframe/test_reduce.py
> FIX-#6793: use `pandas.api.types.pandas_dtype` instead of `np.dtype` for some more places

- modin/core/dataframe/pandas/dataframe/dataframe.py
> PERF-#7132: Preserve partition lengths in apply_full_axis with keep_partitioning=False

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/test_groupby.py
- modin/pandas/test/utils.py
Adds support for building range-partitioning based on an index level(s) and enables range-partitioning support for `df.groupby(level=...)` cases.
> FEAT-#7117: Support building range-partitioning from an index level

- modin/core/execution/utils.py
- modin/test/storage_formats/pandas/test_internals.py
- scripts/doc_checker.py
> FEAT-#7111: Implemented `@remote_function` decorator with cache

- docs/development/contributing.rst
> DOCS-#2434: Clarify the use of `--signoff` option

- modin/core/io/io.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/distributed/dataframe/pandas/partitions.py
- modin/experimental/core/storage_formats/hdk/query_compiler.py
- modin/pandas/accessor.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/general.py
- modin/pandas/groupby.py
- modin/pandas/indexing.py
- modin/pandas/iterator.py
- modin/pandas/resample.py
- modin/pandas/series.py
- modin/pandas/series_utils.py
- modin/pandas/window.py
To facilitate navigation, allows to automatically find places where functions and attributes are defined.
> FEAT-#7146: Use BaseQueryCompiler, BasePandasDataset, DataFrame or Series type hints at a high level

- .github/actions/run-core-tests/group_3/action.yml
- docs/flow/modin/experimental/range_partitioning_groupby.rst
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/dataframe/utils.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/test/dataframe/test_default.py
- modin/pandas/test/utils.py
Adds range-partitioning impl for `df.resample()`. The new implementation doesn't always work better, so enabling it only when the flag is specified.
<details><summary>script to measure</summary>
```python
import pandas
cfg.CpuCount.put(16)
nrows = [1_000_000, 5_000_000, 10_000_000]
ncols = [5, 33]
rules = [
"500ms", # doubles nrows
"30s", # decreases nrows in 30 times
"5min", # decreases nrows in 300
]
use_rparts = [True, False]
cols = pandas.MultiIndex.from_product([rules, ncols, use_rparts], names=["rule", "ncols", "USE RANGE PART"])
rres = pandas.DataFrame(index=nrows, columns=cols)
total_nits = len(nrows) * len(ncols) * len(rules) * …
```
> FEAT-#7118: Add range-partitioning impl for 'df.resample()'

- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/dataframe/pandas/utils.py
- modin/core/storage_formats/pandas/groupby.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
Keeping large objects (in our case, dataframes) in local variables when they are no longer needed is extremely memory-intensive. I propose to review all such places and try to free up memory as early as possible.
> PERF-#7150: Reduce peak memory consumption

- modin/core/dataframe/base/dataframe/utils.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/pandas/series.py
- modin/pandas/test/test_series.py
- modin/test/storage_formats/pandas/test_internals.py
> FEAT-#6929: Implement Series.case_when in a distributed way

- modin/core/dataframe/algebra/default2pandas/default.py
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/series.py
- modin/tests/pandas/test_series.py
> FIX-#7153: Fix `Series.corr` with `method != pearson`

- docs/usage_guide/advanced_usage/modin_logging.rst
> DOCS-#7144: Add information about logging from user defined function

- .github/actions/mamba-env/action.yml
- .github/actions/python-only/action.yml
- .github/actions/upload-coverage/action.yml
- .github/workflows/ci-notebooks.yml
- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/fuzzydata-test.yml
- .github/workflows/push-to-master.yml
> TEST-#7173: Update github actions

- .github/actions/run-core-tests/group_3/action.yml
- docs/flow/modin/experimental/range_partitioning_groupby.rst
- modin/config/__init__.py
- modin/config/envvars.py
- modin/core/storage_formats/pandas/groupby.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/tests/config/test_envvars.py
- modin/tests/core/storage_formats/pandas/test_internals.py
- modin/tests/pandas/test_groupby.py
- modin/tests/pandas/utils.py
Deprecate `cfg.RangePartitioningGroupby` in favor of `cfg.RangePartitioning`
> REFACTOR-#7105: Deprecate 'cfg.RangePartitioningGroupby'

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/tests/pandas/dataframe/test_window.py
> FIX-#7157: Make sure `quantile` function works with `numeric_only=True`

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/base/query_compiler.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/pandas/base.py
- modin/tests/pandas/test_series.py
Currently in master, In astype method if the datatype passed is a scalar, the scalar is converted to a dictionary with the keys as column names and values the scalar dtype value for all keys. This causes the exception message to be different in pandas vs modin as the function passed to remote function applies astype with the dictionary instead of scalar. 
This PR passes the scalar dtypes as is to QC layer and the scalar is used in remote function for astype.  This would also avoid unnecessarily iterating over  the column names if dtype is  a  scalar value.
> FIX-#7039: Pass scalar dtype as is to astype query compiler

- environment-dev.yml
- requirements/env_hdk.yml
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
This reverts commit 975b32ce16f076c449c0e22ad7236448da6ebc6b.
Should already be fixed in https://github.com/conda-forge/pytables-feedstock/issues/97
> Revert "TEST-#7166: Fix HDF tests in CI (#7167)"

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/axis_partition.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition_manager.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
- modin/core/io/column_stores/column_store_dispatcher.py
- modin/core/io/column_stores/parquet_dispatcher.py
- modin/core/io/text/text_file_dispatcher.py
- modin/core/storage_formats/cudf/parser.py
- modin/core/storage_formats/pandas/parsers.py
- modin/core/storage_formats/pandas/utils.py
- modin/tests/core/storage_formats/pandas/test_internals.py
- modin/tests/pandas/dataframe/test_map_metadata.py
- modin/tests/pandas/internals/test_repartition.py
The problem is that setting a new value for configuration variables is not automatically propagated to all Modin processes.
> FIX-#7170: Don't use `MinPartitionSize` configuration variable in remote context

- modin/pandas/dataframe.py
> FEAT-#7178: Add type hints for DataFrame

- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/pandas/dataframe/test_reduce.py
- modin/tests/pandas/utils.py
> FIX-#7093: Make sure `idxmax` and `idxmin` can work with string columns

- modin/pandas/series.py
- modin/tests/pandas/test_series.py
Need also for https://github.com/modin-project/modin/pull/7199
> FEAT-#6808: Implement `__arrow_array__` for Series

- modin/pandas/dataframe.py
- modin/tests/pandas/dataframe/test_default.py
FIX-#7206: df.melt cannot does not handle duplicate value_vars correctly
> FIX-#7206: df.melt cannot does not handle duplicate value_vars correctly

- modin/core/dataframe/algebra/binary.py
- modin/tests/pandas/dataframe/test_map_metadata.py
- modin/tests/pandas/test_series.py
Fixing problematic test cases will be part of the work on https://github.com/modin-project/modin/issues/7203.
> TEST-#7049: Add some sanity tests with pyarrow-backed pandas dataframes

- .github/workflows/ci.yml
- docs/getting_started/installation.rst
- environment-dev.yml
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/test_dataframe_api_standard.py
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
- setup.py
> FEAT-#6890: Modin implementation of DataFrame API standard

- modin/pandas/series.py
- modin/tests/pandas/dataframe/test_default.py
- modin/tests/pandas/test_series.py
Fixes a bug where creating a DF from a Series with tuple name did not give the DF a MultiIndex object for its `columns` property. This PR sets the underlying query compiler's object to be a MultiIndex when the Series is created.
> FIX-#7143: Constructing a DataFrame from a Modin Series with tuple name should produce MultiIndex columns

- docs/flow/modin/core/dataframe/algebra.rst
> DOCS-#7217: Update docs as to when Modin operators work best

- environment-dev.yml
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#7219: Pin dataframe-api-compat>=0.2.7

- modin/core/storage_formats/pandas/merge.py
- modin/core/storage_formats/pandas/query_compiler.py
We should not call `combine` for cases where the calculations default to pandas, since the result of this function is not used.
> PERF-#7227: Call `modin_frame.combine()` for merge and join only when necessary

- modin/core/io/column_stores/parquet_dispatcher.py
This was originally added here: https://github.com/modin-project/modin/pull/3416/files, but the reason for it is not described.
> FIX-#7221: Don't use `use_legacy_dataset=False` for `ParquetDataset`

- modin/core/storage_formats/pandas/merge.py
- modin/tests/core/storage_formats/pandas/test_internals.py
`merge` preserves the row splitting, but sometimes it's better to repartition. One extremely bad case is when there is a sequence of heavyweight operations where inefficient partitioning persists from the first to the last. For example, sequence of `merge` operations, where the left operand of the very first operation in the chain has only one partition. For example:
```python
cfg.NPartitions.put(8)
pd.DataFrame(np.arange(cfg.NPartitions.get() * cfg.MinPartitionSize.get())).to_numpy()
for _ in range(3):
np.random.seed(42)
df1 = pd.DataFrame(np.random.randint(100, size=(32, 16)))
assert df1._query_compiler._modin_frame._partitions.shape == (1, 1)
df2 = …
```
> PERF-#7230: Don't preserve bad partition for `merge`

- modin/core/execution/dask/common/engine_wrapper.py
- modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/execution/ray/common/engine_wrapper.py
- modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
- modin/core/execution/unidist/common/engine_wrapper.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
- modin/core/io/io.py
- modin/pandas/io.py
- modin/tests/pandas/test_io.py
> FEAT-#6492: Add `from_map` feature to create dataframe

- modin/tests/pandas/extensions/test_api_reexport.py
This PR re-exports the submodules of `pandas.api` from within `modin/pandas/api/__init__.py` to ensure they are not overwritten when a user tries to import `modin.pandas.api.extensions`.
> FIX-#7224: Importing modin.pandas.api.extensions overwrites re-export of pandas.api submodules

- .github/workflows/ci-required.yml
- environment-dev.yml
- requirements/env_hdk.yml
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
- scripts/doc_checker.py
- scripts/test/test_doc_checker.py
PR also updates `numpydoc`: `1.1.0` -> `1.6.0`.
> FIX-#7240: Allow `doc_checker.py` works with `functools.cached_property`

- environment-dev.yml
- modin/core/io/column_stores/parquet_dispatcher.py
- requirements-dev.txt
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
- setup.py
> FIX-#7246: Pin pyarrow>=10.0.1 as pandas 2.2.* does

- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/algebra/fold.py
- modin/core/dataframe/algebra/groupby.py
- modin/core/dataframe/algebra/map.py
- modin/core/dataframe/algebra/operator.py
- modin/core/dataframe/algebra/reduce.py
- modin/core/dataframe/algebra/tree_reduce.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/distributed/dataframe/pandas/partitions.py
> REFACTOR-#7242: Add type hints for `modin/core/dataframe/algebra/`

- environment-dev.yml
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- requirements-dev.txt
- requirements/env_hdk.yml
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
> FEAT-#7252: Add type hints for `base.py`

- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/pandas/dataframe/test_reduce.py
> FIX-#7248: Make sure `_validate_dtypes_sum_prod_mean` works correctly with datetime types

- modin/core/storage_formats/pandas/merge.py
- modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
- modin/tests/pandas/dataframe/test_join_sort.py
- modin/tests/pandas/utils.py
> FIX-#7250: Revert "PERF-#6666: Avoid internal reset_index for left merge"

- modin/experimental/pandas/__init__.py
- modin/pandas/accessor.py
- modin/tests/experimental/test_io_exp.py
> FIX-#6967: Remove read_pickle_distributed/to_pickle_distributed functions as deprecated

- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/core/storage_formats/pandas/query_compiler.py
> REFACTOR-#7260: Use `extract_dtype` internal function in more places

- modin/tests/pandas/dataframe/test_join_sort.py
> FIX-#0000: Make merge tests more stable by sorting results

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/tests/core/storage_formats/pandas/test_internals.py
Apply approaches from [PR-7136](https://github.com/modin-project/modin/pull/7136) for TreeReduce and GroupByReduce operators
> FEAT-#5394: Reduce amount of remote calls for TreeReduce and GroupByReduce operators

- modin/core/dataframe/algebra/fold.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/tests/core/storage_formats/pandas/test_internals.py
> FEAT-#6498: Make Fold operator more flexible

- modin/core/dataframe/algebra/default2pandas/default.py
- modin/tests/core/storage_formats/pandas/test_internals.py
Fixes the retrieval of the __name__ field of `property` objects in `DefaultMethod.register`. It previously displayed a hex address for the property, and now instead displays the name of its `fget` method.
> FIX-#7233: Display property name in default_to_pandas error messages

- modin/core/dataframe/base/partitioning/axis_partition.py
- modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
- modin/core/execution/python/implementations/pandas_on_python/partitioning/virtual_partition.py
- modin/core/execution/ray/implementations/cudf_on_ray/partitioning/axis_partition.py
- modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
- modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
> REFACTOR-#7271: Remove `instance_type` attribute of axis partitions

- modin/core/execution/dispatching/factories/factories.py
- modin/pandas/accessor.py
- modin/pandas/io.py
- modin/pandas/utils.py
- modin/tests/interchange/dataframe_protocol/pandas/test_protocol.py
- modin/tests/pandas/test_concat.py
- modin/utils.py
> REFACTOR-#7273: Remove deprecated functions from utils.py, accessor.py and io.py

- modin/logging/logger_decorator.py
> FIX-#7278: Make sure `enable_logging` decorator preserve type hints

- docs/development/using_pandas_on_dask.rst
> DOCS-#7287: Update Modin on Dask documentation

- modin/core/dataframe/algebra/binary.py
- modin/core/dataframe/algebra/tree_reduce.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/aggregations.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/tests/core/storage_formats/pandas/test_internals.py
- modin/tests/pandas/dataframe/test_indexing.py
- modin/tests/pandas/dataframe/test_join_sort.py
- modin/tests/pandas/dataframe/test_map_metadata.py
- modin/tests/pandas/dataframe/test_udf.py
- modin/tests/pandas/test_groupby.py
> REFACTOR-#7294: Reduce access of methods _modin_frame methods from query compiler objects

- environment-dev.yml
- requirements-dev.txt
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
> FIX-#7295: Unpin numexpr to allow versions >= 2.8.4 to match pandas

- .github/workflows/publish-to-pypi.yml
> FEAT-#7265: Automatic publication of Modin wheel to PyPI

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/dataframe/pandas/utils.py
Perf gain: ~15% against main branch with Ray 8 cores.
```python
df1 = pd.DataFrame(np.random.randint(1_000_000, size=(10_000, 100)))
df2 = pd.DataFrame(np.random.randint(1_000_000, size=(1_000_000, 100)))
for _ in range(5):
start = time()
df2._query_compiler._modin_frame._deferred_index = True
res = df1.merge(df2, on=3)
execute(res)
print(f"merge time: {time()-start}")
```
> PERF-#7299: Avoid using `synchronize_labels` for `combine` function

- modin/config/envvars.py
- modin/tests/config/test_envvars.py
- modin/utils.py
Signed-off-by: sfc-gh-mvashishtha <mahesh.vashishtha@snowflake.com>
Stop reloading modules for custom docstrings. See #7138 for motivation.
> FIX-#7138: Stop reloading modules for custom docstrings.

- modin/core/dataframe/algebra/binary.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/aggregations.py
- modin/core/storage_formats/pandas/merge.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/tests/core/storage_formats/pandas/test_internals.py
> REFACTOR-#7294: Add similar methods as in 7294 for operating on columns

- modin/utils.py
> FEAT-#7249: Add `reload_modin` feature

- .github/actions/python-only/action.yml
- .github/workflows/ci-required.yml
- .github/workflows/ci.yml
- modin/tests/pandas/test_series.py
Python 3.11 has been tested separately in https://github.com/modin-project/modin/pull/7317. It works.
> TEST-#7316: Run a subset of CI tests with python 3.10 and 3.11 on a scheduled basis.

- .github/dependabot.yaml
Currently, deprecation warnings are being thrown due to actions using out-of-date Node versions ([recent example](https://github.com/modin-project/modin/actions/runs/9536912855)). Rather than submitting a PR to update them manually, this PR configures Dependabot to regularly submit PRs to update GitHub action versions as needed.
If this PR merges, you can expect Dependabot to immediately submit a PR to update actions to newer versions.
> FIX-#0000: Add a Dependabot config to auto-update GitHub action versions

- modin/core/io/text/text_file_dispatcher.py
- modin/tests/pandas/test_io.py
> FIX-#7321: Using 'C' engine instead of 'pyarrow' for getting metadata in `read_csv`

- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/pandas/dataframe/test_default.py
- modin/tests/pandas/test_series.py
When creating a DataFrame or Series, no longer display `UserWarning: Distributing <class 'NoneType'> object. This may take some time.` when the size of the DataFrame or Series is small.
> FEAT-#6574: UserWarning no longer displayed when Series/DataFrames are small

- docs/_static/custom.js
- docs/conf.py
Adds the [RunLLM](https://runllm.com) widget, customized to Modin, to the documentation page. RunLLM is a custom technical support assistant that helps developers unblock themselves by answering conceptual questions, generating code, and helping debug.
Here's an example response from RunLLM:
Just a note that I put the `custom.js` file in a new directory called `_static`, which seems to be the convention for Sphinx, and I updated `conf.py` accordingly. I didn't see any existing uses of `html_static_paths`, but please let me know if there's a different preferred organization.
- [N/A] …
> DOCS-#0000: Adds RunLLM widget to docs

- docs/usage_guide/examples/index.rst
Fix borken links in Modin Usage Examples page
> DOCS-#7335: Fix borken links in Modin Usage Examples page

- modin/pandas/base.py
Fix a type check warning reported by Pyre@Google, which was outdated after code modification.
update the parameter `axis` of function `_stat_operation` from `int | str` to `Optional[Union[int, str]]`, since it could be `None` after commit https://github.com/modin-project/modin/commit/d192e8778d4eed1862a7f90200970af54e43f6d1
> FIX-#0000: Fix type hint

- docs/_static/custom.js
This PR to updates the widget's script path. RunLLM has switched to a new deployment framework which resolved multiple package delivery issues caused by jscdn caching. This improvement ensures RunLLM's askAI widget is more consistently up-to-date.
> DOCS-#0000: Update RunLLM Ask AI widget path

- modin/tests/config/docs_module/__init__.py
- modin/tests/config/docs_module/classes.py
- modin/tests/config/test_envvars.py
- modin/utils.py
> FIX-#7134: Use a separate docstring class for BasePandasDataset.

- modin/tests/config/docs_module/classes.py
- modin/tests/config/docs_module_with_just_base/__init__.py
- modin/tests/config/docs_module_with_just_base/classes.py
- modin/tests/config/test_envvars.py
- modin/utils.py
> FIX-#7113: Fix docstring overrides for subclasses.

- modin/config/envvars.py
- modin/core/execution/dask/common/utils.py
- modin/core/execution/ray/common/utils.py
- modin/core/execution/unidist/common/utils.py
> FIX-#7355: Cpu count would be set incorrectly on a cluster

- modin/polars/dataframe.py
> FIX-#7357: Fix `NoAttributeError` on `DataFrame.copy`

- docs/usage_guide/optimization_notes/index.rst
- modin/config/__init__.py
- modin/config/envvars.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/tests/core/storage_formats/pandas/test_internals.py
The use of Dynamic-partitioning depends on various factors such as data size, number of CPUs, operations performed, 
and it is up to the user to determine whether Dynamic-partitioning will give a boost in his case or not.
Performance results for `abs`:
<details>
<summary>32 CPUS</summary>
</details>
<details>
<summary>112 CPUS</summary>
</details>
- [x passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
> FEAT-#7368: Add a new environment variable for using dynamic partitioning

- .github/workflows/ci.yml
- .github/workflows/push-to-main.yml
> FIX-#7373: Try a previous version of `motoserver/moto` service, pin to 5.0.13

- modin/core/dataframe/algebra/groupby.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/dataframe/pandas/partitioning/partition_manager.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/tests/pandas/test_groupby.py
Performance results were obtained by using Dataframe with shape (20000, 5000).
| Operation        | Modin main | This PR |
| ---------------- | ------------- | --------- |
| fillna(df_value) | 32.460861    | 1.79279 |
> FEAT-#7337: Using dynamic partitionning in broadcast_apply

- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/tests/pandas/dataframe/test_map_metadata.py
When a new value is inserted into a frame, we call `pandas.api.types.pandas_dtype(value)` to extract the dtype of an object like a pandas Series or numpy array. After #7261, when a scalar value is passed, this usually raises a TypeError, so we construct a local pandas Series from the object and extract the dtype from there.
When the passed value is a date-like string, pandas will instead raise a ValueError because it tries to parse it as a numpy structured dtype. After this fix, we now catch ValueError in addition to TypeError to handle this case.
> FIX-#7371: Fix inserting datelike values into a DataFrame

- .github/workflows/ci.yml
> FIX-#7387: Limit the number of pytest workers for tests with Ray engine on Windows

- modin/pandas/series.py
- modin/tests/pandas/test_series.py
Series.duplicated uses DataFrame.duplicated in implementation, but since this drops the original Series's name, we need to manually restore it after the computation.
> FIX-#7375: Fix Series.duplicated dropping name

- modin/core/storage_formats/base/doc_utils.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/series.py
- modin/tests/pandas/test_series.py
Many binary operators in the frontend Series class were not passing their `fillna` parameters to the query compiler (not sure why this wasn't caught in linting). For arithmetic functions, the fix is simply to propagate `fillna`, but for logical operators (`eq`/`ge` etc.), the equivalent DataFrame method does not take a `fillna` parameter, so we need to add a separate query compiler method to handle this case.
> FIX-#7381: Fix Series binary operators ignoring fill_value

- modin/pandas/dataframe.py
> REFACTOR-#7315: Refactor axis checks in squeeze

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
Calling `len(pd.DataFrame(...))` will currently materialize the frame's Index, and return the length of the `pd.Index` object. This PR adds a `get_axis_len` method to the query compiler to potentially avoid this materialization when determining the length of the columns or index.
This may not make a large difference for existing backends, as the underlying `PandasDataFrame` caches the index/column labels together with the length of that axis. However, other backends may choose to cache the shape separate from the actual labels, and this extra method lets us potentially avoid materializing those labels. As such, frontend methods that previously called `len(df.index)` should instead call the equivalent `len(df)` to avoid potentially triggering this materialization.
> **_NOTE:_**  If you …
> PERF-#7397: Avoid materializing index/columns in shape checks

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/tests/pandas/dataframe/test_default.py
The `sort` parameter of `DataFrame.stack` was exposed in pandas docs in 2.1.0, but we didn't link it from the frontend to the query compiler.
> FIX-#7327: Use sort parameter of DataFrame.stack

- .github/actions/mamba-env/action.yml
- .github/workflows/ci.yml
- modin/__init__.py
> TEST-#7419: Fix CI

- modin/conftest.py
- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/core/execution/dispatching/factories/dispatcher.py
- modin/core/execution/dispatching/factories/factories.py
- modin/core/io/io.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/native_query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/pandas/io.py
- modin/tests/interchange/dataframe_protocol/base/test_sanity.py
- modin/tests/test_executions_api.py
Rename internal `to_dataframe` methods to `to_interchange_dataframe`, and internal `from_dataframe` methods to `from_interchange_dataframe`.
> REFACTOR-#7418: Rename internal interchange protocol methods.

- modin/core/dataframe/pandas/metadata/dtypes.py
- modin/pandas/io.py
- modin/tests/pandas/test_io.py
> TEST-#7431: Fix formatting for isort 6 and black 25

- modin/core/dataframe/pandas/interchange/dataframe_protocol/column.py
- modin/tests/interchange/dataframe_protocol/pandas/test_protocol.py
Implements the mapping between datetime64 types and the interchange DATETIME type.
> FIX-#7404: Implement interchange protocol for datetime columns

- .github/workflows/ci.yml
> TEST-#7437: Check execution-filter outputs correctly in CI.

- modin/pandas/series.py
- modin/tests/pandas/test_series.py
`Series.argmax/argmin` currently directly call `idxmax/idxmin`, which will give the wrong result if the index is not the default positional one. Calling `reset_index(drop=True)` first resolves this.
> FIX-#7413: Always use positional index before computing argmin/argmax

- modin/pandas/series.py
- modin/tests/pandas/test_series.py
Implements `Series._set_axis_name` to remove an `AttributeError` raised from `Series.rename_axis`.
> FIX-#7465: Properly implement Series.rename_axis

- modin/pandas/base.py
- modin/tests/pandas/test_backend.py
Adds a progress bar when materializing data in `BasePandasDataset.set_backend`. It looks like `tqdm` relies on timing individual iterations to display an actual estimate + extending bar, so right now the bar only moves between the to_pandas and FactoryDispatcher calls and isn't really meaningful aside from signaling that a transfer is in progress.
Notebook example:
Standard Python REPL example:
```
>>> import modin.pandas as pd
>>> pd.DataFrame([[1] * 5] * 5).set_backend("dask")
2025-03-18 15:40:43,301	INFO worker.py:1781 -- Started a local Ray instance.
Transferring data from Ray to Dask ...: 100%|█████████████████████████████████| 2/2 [00:01<00:00,  1.24it/s]
0  1  2  3  4
0  1  1  1  1  1
1  1  1  1  1  1
2  1  1  1  1  1
3  1  1  1  1  1
4  1  1  1  1  1
```
IPython REPL example:
``` …
```
> FEAT-#7468: Add progress bar for engine switch

- .github/workflows/ci.yml
- modin/conftest.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/api/extensions/__init__.py
- modin/pandas/api/extensions/extensions.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/config/test_envvars.py
- modin/tests/pandas/extensions/conftest.py
- modin/tests/pandas/extensions/test_base_extensions.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
- modin/tests/pandas/extensions/test_pd_extensions.py
- modin/tests/pandas/extensions/test_series_extensions.py
- modin/utils.py
Associate each base, dataframe, and series extension with a particular backend. Also, add `register_base_extension()`.
Wrap each base, dataframe and series method in a dispatcher that checks the backend of its first argument and then dispatches to the corresponding backend's extension, if it exists. For non-method extensions, including properties and scalars (like ints), we have to extend `__getatribute__`, `__getattr__`, `__delattr__`, and `__setattr__` to implement the extension.
In the future, the dispatcher could choose an appropriate backend when it has inputs from multiple backends. It could then convert all arguments to the correct backend and then choose the extension matching that backend.
> **_NOTE:_**  If you edit the PR title to match this format, you need to add another …
> FEAT-#7472: Register dataframe and series accessors with a particular backend.

- docs/development/architecture.rst
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Implement max-cost interface for a query compiler to express the maximum allowed coercion cost accepted by its implementation.
> FEAT-#7480: Implement max_cost interface

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Allows for proper cost optimization in the face of asymmetric information.
Provides for a case when one query compiler just happens to know more about the world than the other query compilers, and can optionally provide costing information in that scenario. This should be a class function on the "omniscient" query compiler, and it should take an object query compiler that it may create itself /from/.
This potentially allows a single query compiler to direct casting optimizations if it happens to know enough to do so.
> FEAT-#7482: Add "from_qc" API to QueryCompiler and BackendCostCalculator to handle asymmetric information scenarios

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FIX-#7490: Exclude move_to and _update_inplace from casting.

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/tests/pandas/dataframe/test_map_metadata.py
- modin/tests/pandas/test_series.py
> FIX-#7486: Add support for `.astype(pandas.CategoricalDtype(…))`

- modin/conftest.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/__init__.py
- modin/pandas/api/extensions/extensions.py
- modin/pandas/dataframe.py
- modin/pandas/indexing.py
- modin/pandas/series.py
- modin/tests/pandas/extensions/conftest.py
- modin/tests/pandas/extensions/test_pd_extensions.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Prior to this commit, general extensions would apply to all backends. Now, we can register an extension that applies to just one backend.
> FEAT-#7474: Register general functions with a particular backend.

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/dataframe/test_binary.py
- modin/tests/pandas/dataframe/test_udf.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
- modin/tests/pandas/test_series.py
Prior to this commit, synonyms like `DataFrame.__pow__` and `DataFrame.pow` would use the same extension set, but would address it with different names. That would cause confusing behavior. Now we define separate wrappers for each alias, so that each alias has its own set of extensions and can draw from that set of extensions appropriately.
> FIX-#7495: Separate extensions for aliases.

- modin/tests/experimental/test_io_exp.py
- modin/tests/pandas/test_io.py
On Windows, skip tests requiring libxml while we wait for libxml 2.14.1  to appear in conda.
> TEST-#7497: Skip tests requiring lxml on windows.

- modin/pandas/general.py
- modin/pandas/io.py
- modin/tests/pandas/extensions/test_pd_extensions.py
Allow I/O function accessors to override modin's I/O functions. Also test that we can override all the modin.pandas.general functions, and fix a bug where synonym pairs like `isnull` and `isna` were using the same set of general accessors.
> FEAT-#7492: Allow I/O function accessors.

- modin/config/__init__.py
- modin/config/envvars.py
This PR adds the `AutoSwitchBackend` configuration variable. Backend that wish to dynamically switch to other backends should respect this variable before applying any heuristics.
> FEAT-#7509: Add AutoSwitchBackend configuration variable

- modin/conftest.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/api/extensions/extensions.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FEAT-#7505: Support post-operation automatic backend switch.

- docs/development/architecture.rst
- modin/config/envvars.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
We add the move_to_me_cost function as something to be consulted during automatic switching. This allows for the /other/ query compiler to have more of a say in a potential data migration. This also helps to formalize the questions being asked of each participating query compiler, specifically the move_to_cost can be precisely defined as just the transmission and serialization cost of data movement.
We also allow ourselves to disregard transmission cost, or the move_to_cost when the current engine is simply unable to execute the current workload.
We also modify the Backend environment variable to allow for setting and getting the choices in order to constrain the set of engines considered during automatic switching.
In a future commit we will implement a default function similar to what …
> FEAT-#7523: Improve formal definition of the automatic switching algorithm

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Add cost functions to the query compiler that use some constants thresholds and costs to calculate "move" and "stay" costs. Prior to this commit, those functions were only defined in the test suite for casting.
Also make some arguments required in move_to_me_cost and stay_cost, instead of defaulting to `None`.
> REFACTOR-#7527: Add more costing logic to the base query compiler.

- modin/config/envvars.py
This small PR displays the choices in error message of environment vars.
> FIX-#7532: Display choices in error message of environment vars

- docs/requirements-doc.txt
- environment-dev.yml
- examples/tutorial/jupyter/execution/pandas_on_ray/cluster/modin-cluster.yaml
- modin/utils.py
- requirements-dev.txt
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- setup.py
Newer versions of setuptools with older versions of ray may result in the following error:
ModuleNotFoundError: Make sure all required packages are installed: No module named 'pkg_resources._vendor'
Newer versions of setuptools have deprecated pkg_resources ( see: https://setuptools.pypa.io/en/latest/pkg_resources.html ) which versions of ray<2.09 still reference in ray.data.init. Ray has replaced imports of this package in 2.10
To fix this we update the ray dependency to ray 2.10+
> FIX-#7536: setuptools / ray version conflict in pkg_resources._vendor 

- modin/pandas/base.py
- modin/tests/pandas/test_backend.py
FIX-#7538: set_backend materializes to pandas even if it is the same backend
Add an else clause.
> FIX-#7538: set_backend should exit early if there is nothing to do

- modin/core/storage_formats/base/query_compiler.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Existing query compilers can call get_axis_len(axis=0) to get a row count, but this may be expensive on lazily evaluated systems. Instead we add a new function which can be overridden on a per-query compiler basis for the max row count, which can be sometimes calculated more cheaply.
The default implementation of this is to simply call get_axis_len but sub-classes may have cheaper ways of estimating the length of the dataset.
> REFACTOR-#7534: Provide internal, overridable method for max_shape

- modin/conftest.py
- modin/pandas/__init__.py
- modin/pandas/api/extensions/extensions.py
- modin/pandas/dataframe.py
- modin/tests/pandas/extensions/test_pd_extensions.py
- modin/tests/pandas/extensions/test_series_extensions.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
In this PR, the extensions system tracks objects that were re-exported from pandas, and either wraps them in `wrap_free_function_in_argument_caster` if it is a function, or removes them from the namespace and dispatches via `__getattr__` if it is a class. Technically the `__getattr__` approach can be used for all objects, but this remains more consistent with how we handle dispatch for top-level functions that modin itself defines.
> FIX-#7528: Dispatch module-level extensions to the correct backend

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
This is a follow-up to #7522, which accidentally broke extension dispatch when an object is pinned. In the previous PR, the default method was being used rather than an extension, while the result backend was correctly preserved.
> FIX-#7521: Fix wrong extension being used when backend is pinned

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
Previously, we would always use `Backend.get()`, or the pinned backend if one of the inputs was pinned.
Resolves #7555
> FIX-#7555: Get the correct extension when AutoSwitchBackend is False.

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/groupby.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Prior to this commit, calling groupby() while `AutoSwitchBackend` was off would raise `NotImplementedError`. Previously, we would try to pin the result of a QueryCompilerCaster operation whenever `AutoSwitchBackend` was off, whereas we only need to pin when one of the inputs is pinned.
Resolves #7553
> FIX-#7553: Fix groupby when AutoSwitchBackend is disabled.

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FIX-#7559: Create the dummy query compiler just once per backend.

- modin/config/__init__.py
- modin/config/envvars.py
- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/native_query_compiler.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Add the ability to change basic thresholds on the native query compiler
> FEAT-#7540: Ability to configure NativeQueryCompiler AutoSwitch Settings

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/base.py
- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/pandas/extensions/test_base_extensions.py
Stop falling back to `__getattr__` for missing extensions. The `_getattr__from_extension_impl` implementation didn't access properties correctly, but we don't need to fall back to `__getattr__` at all, and we can implement extension property access with just `__getattribute__`.
Resolves #7562
> FIX-#7562: Raise AttributeError for missing extension properties.

- docs/development/architecture.rst
- docs/usage_guide/optimization_notes/index.rst
Adds a short blurb mentioning pandas on Snowflake to the architecture document, and a segment on configuring automatic backend switching to the optimization notes.
> DOCS-#7566: Add pandas on snowflake + backend pinning to documentation page

- modin/tests/pandas/test_io.py
`"s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv"` looks to no longer be available. I couldn't find another link that reproduces the issue fixed in #4658, so for now I'm xfailing the test to unblock CI.
> TEST-#7571: xfail test_read_csv_s3_issue4658 due to missing s3 bucket

- modin/core/dataframe/pandas/dataframe/dataframe.py
- modin/tests/pandas/dataframe/test_default.py
Ensure empty Dataframes with pyarrow dtypes maintain the dtype metadata.
> FIX-#7569: Fix handling of pyarrow dtype and empty dataframes

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/native_query_compiler.py
- modin/pandas/base.py
- modin/tests/pandas/dataframe/test_default.py
- modin/tests/pandas/native_df_interoperability/test_default.py
When a numpy function like `np.sqrt` is called on an object with the `__array_ufunc__` method, it will call `__array_ufunc__` to determine the appropriate implementation. Modin currently defaults to pandas for all operations in this case, but ideally should provide the option for backends to provide distributed implementations.
This PR creates the `do_array_ufunc_implementation` query compiler method. This method is unusual in that it takes the original DataFrame/Series object as argument, but this is done for convenience to allow direct calls to pandas API methods without the need to re-wrap the query compiler in a DataFrame/Series object.
The default `BaseQueryCompiler` implementation defaults to pandas as before, but the `NativeQueryCompiler` implementation now directly calls the …
> FEAT-#7573: Dispatch __array_ufunc__ to query compilers

- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
- modin/tests/test_metrics.py
In both the caster and the calculator we emit some new metrics to track the switching behavior. This will be used by a metrics handler to implement debugging tools.
> FEAT-#7549: Emit metrics on auto-switch and casting behavior

- modin/pandas/api/extensions/extensions.py
- modin/pandas/groupby.py
- modin/tests/pandas/extensions/test_groupby_extensions.py
Fixes the linked issue by calling __set_name__ on extensions defined with the cached_property decorator, and loosens restrictions on methods that can be extended on `DataFrameGroupBy` and `SeriesGroupBy` objects.
> FIX-#7578: Change groupby extension allow list and fix cached_property extensions

- modin/pandas/base.py
- modin/pandas/series.py
- modin/tests/pandas/dataframe/test_default.py
- modin/tests/pandas/test_series.py
The new signature of `__array__` should be backwards-compatible with callers that do not pass the `copy` keyword argument at all.
I tested this change locally with python 3.10 and 3.12. In CI, we test python 3.10 and python 3.11 [periodically](https://github.com/modin-project/modin/blob/cc19143ba2abe7b18e0fbd6efd26c7dcad5e39d6/.github/workflows/ci.yml#L39-L44), as [here](https://github.com/modin-project/modin/actions/runs/15152514188/job/42601094103).
Fixes #7582 
---------------
Signed-off-by: sfc-gh-mvashishtha <mahesh.vashishtha@snowflake.com>
> FIX-#7582: Add copy parameter to __array__ methods.

- modin/conftest.py
- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/logging/__init__.py
- modin/logging/config.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FIX-#7595: Log backend switching information with the modin logger.

- modin/conftest.py
Our tests use older versions of xgboost that [log to the root logger](https://github.com/dmlc/xgboost/blob/36eb41c960483c8b52b44082663c99e6a0de440a/python-package/xgboost/tracker.py#L382).
Resolves #7598
This PR won't trigger the xgboost tests on github actions, so I checked that `pytest  modin/tests/experimental/xgboost/ -n 12` passed locally.
> TEST-#7598: Allow xgboost to log to root.

- modin/core/storage_formats/pandas/query_compiler.py
- modin/pandas/dataframe.py
- modin/tests/pandas/dataframe/test_indexing.py
- modin/tests/pandas/native_df_interoperability/test_indexing.py
Default to pandas when inserting a column in an empty frame.
Resolves #5961
> FIX-#5961: Preserve dtypes when inserting column to empty frame.

- modin/pandas/dataframe.py
- modin/pandas/groupby.py
- modin/pandas/series.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
> FEAT-#7607: Support pinning groupby objects in place.

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
- modin/tests/pandas/test_general.py
Implements `__array_function__` to prevent errors when a backend implements the function as an extension method. See linked issue for details.
> FIX-#7616: Implement __array_function__ stub

- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/pandas/groupby.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
- modin/tests/pandas/test_backend.py
Support automatic backend switch for groupby objects by implementing set_backend().
Resolves #7618
Resolves #7544
> FEAT-#7618: FEAT-#7544: Support set_backend() for groupby objects.

- modin/logging/logger_decorator.py
Fixes a mypy warning raised in the newest version.
> TEST-#7629: Update code for mypy 1.17

- modin/core/storage_formats/base/query_compiler.py
- modin/core/storage_formats/pandas/native_query_compiler.py
- modin/core/storage_formats/pandas/query_compiler.py
- modin/logging/logger_decorator.py
- modin/pandas/base.py
- modin/pandas/utils.py
Defines the `move_to()` and `move_from()` methods as an interface for moving data between query compilers. Changes `set_backend()` to initially try those methods before falling back to the original implementation.
> FEAT-#7627: Define move_to and move_from methods

- docs/usage_guide/optimization_notes/index.rst
- modin/config/envvars.py
- modin/core/storage_formats/pandas/query_compiler_caster.py
- modin/tests/pandas/extensions/test_dataframe_extensions.py
- modin/tests/pandas/extensions/test_groupby_extensions.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
- modin/tests/test_metrics.py
AutoSwitchBackend is a new feature that may hurt performance in some cases once we start adding rules for automatically switching backends. We should disable it by default.
Resolves #7636
> FEAT-#7636: Make AutoSwitchBackend False by default.

- environment-dev.yml
- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/__init__.py
- modin/pandas/series_utils.py
- modin/tests/pandas/test_api.py
- modin/tests/pandas/test_groupby.py
- requirements-dev.txt
- requirements/env_unidist_linux.yml
- requirements/env_unidist_win.yml
- requirements/requirements-no-engine.yml
- setup.py
Increases the range of supported pandas versions to >2.2, <2.4.
Changes:
- `Series.str.decode` now has a `dtype `argument
- The `na` parameter of many string methods now uses `lib.no_default` instead of None, but we still pass `None` internally.
- `include_groups=True` in `groupby.apply` is now deprecated in pandas 2.3. This change is very far-reaching, and since many other methods use apply under the hood, I found it too difficult to change `include_groups` for every single possible function call. The warning is filtered instead.
> FEAT-#7604: Support pandas 2.3

- modin/config/__init__.py
- modin/config/envvars.py
- modin/core/storage_formats/pandas/native_query_compiler.py
- modin/tests/pandas/dataframe/test_default.py
- modin/tests/pandas/dataframe/test_window.py
- modin/tests/pandas/native_df_interoperability/test_copy_on_write.py
- modin/tests/pandas/test_general.py
- modin/tests/pandas/test_groupby.py
- modin/tests/pandas/utils.py
Uses shallow copies by default in native pandas execution mode, significantly improving performance. This behavior can be changed by setting `NativePandasDeepCopy.enable()`.
Summary of mutation behavior, with and without pandas copy-on-write:
Unscientific sanity check benchmark:
```
from modin.config import Backend
Backend.put("Pandas")
from time import perf_counter
def bm(f):
start = perf_counter()
f() 
print(perf_counter() - start)
df = pd.DataFrame(np.random.randint(0,100,size=(2**22,2**8)))
bm(lambda: repr(df.sort_values(0)))
``` …
> PERF-#7435: Use shallow copies in native pandas mode

- modin/core/dataframe/base/dataframe/utils.py
- modin/tests/pandas/dataframe/test_udf.py
2 failures are fixed here: 
- `DataFrame.insert` apparently is now typed with `pandas-stubs==2.3`, but was not typed before. Since pandas 2.3 is compatible with Python 3.9 all CI runs should pick up this change, but if it continues to be an issue I'll look into a workaround for seeing if it's possible to conditionally add the `type: ignore` directive.
- `np.cumproduct` was [deprecated](https://numpy.org/doc/1.26/release/1.25.0-notes.html#deprecations) some time ago, and removed in numpy>2. We've supported numpy>2 for a while, so it's unclear why this issue only just triggered.
> TEST-#7643: Fix residual failures from pandas 2.3

- modin/core/storage_formats/base/query_compiler.py
- modin/pandas/base.py
- modin/pandas/general.py
- modin/pandas/io.py
- modin/tests/experimental/test_io_exp.py
- modin/tests/interchange/dataframe_protocol/pandas/test_protocol.py
- modin/tests/pandas/dataframe/test_iter.py
- modin/tests/pandas/dataframe/test_udf.py
- modin/tests/pandas/extensions/test_groupby_extensions.py
- modin/tests/pandas/native_df_interoperability/test_default_to_pandas_without_warnings.py
- modin/tests/pandas/test_general.py
- modin/tests/pandas/test_reshape.py
- modin/tests/test_utils.py
- modin/utils.py
IO and general module functions now all share a code path that checks whether the active backend's query compiler should warn on default to pandas. Methods that default to pandas directly in the base.py frontend layer (rather than at the query compiler level) also now use this code path.
> FIX-#7638: Suppress default to pandas warnings on native pandas backend

- modin/pandas/base.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
- modin/tests/pandas/test_backend.py
- Make it fixed width
- Format row/col estimates with general formatting and limit to 6 characters
- Trim the operation name if needed, prefer the method over the object
> FEAT-#7647: Shorten the hybrid progress bar text

- modin/pandas/dataframe.py
- modin/pandas/series.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
Currently, `DataFrame.T` is declared like so:
```python
def transpose(self, copy=False, *args) -> DataFrame:  # noqa: PR01, RT01, D200
"""
Transpose index and columns.
"""
return self.__constructor__(
query_compiler=self._query_compiler.transpose(*args)
)
T: DataFrame = property(transpose)
```
This breaks automatic backend switching in a very subtle way. Because we use the `QueryCompilerCaster` ABC to replace all methods with a wrapper that picks the correct backend, the `transpose` referenced in `property(transpose)` is actually the original, unwrapped method, and therefore never uses the switching code path. This PR replaces the definition of `T` with
```python
@property
def T(self):
return self.transpose()
```
which defers lookup of `transpose` to runtime, and therefore uses the caster …
> FIX-#7653: Respect `AutoSwitchBackend` for `DataFrame.T`/`Series.T~

- modin/core/computation/eval.py
- modin/tests/pandas/dataframe/test_udf.py
Prior to this commit, calling `DataFrame.eval(inplace=False, engine='python')` with an assignment would incorrectly update the input dataframe. The root cause was calling `copy(deep=None)` instead of `copy(deep=True)`. We need to insert new columns to a deep copy of the input dataframe. `deep=None` is not part of the `copy` API at all, so we don't need to fix `copy()` behavior. It happens that `deep=None` does a deep copy in pandas, which is where we got the `deep=None` code from.
Resolves #7669
> FIX-#7669: Respect eval(inplace=False).

- modin/pandas/dataframe.py
- modin/tests/pandas/dataframe/test_indexing.py
> FIX-#7667: Fix `axis=None` case for `DataFrame.rename`

- modin/tests/pandas/native_df_interoperability/utils.py
Missed a line in create_test_series_in_defined_mode where we want to get the default Backend instead of "Ray"
> TEST-#7681: Interop Tests should all use Backend.get instead of "Ray"

- modin/config/envvars.py
- modin/core/storage_formats/base/query_compiler_calculator.py
- modin/tests/pandas/native_df_interoperability/test_compiler_caster.py
The BackendCostCalculator was originally designed to return None when no suitable backend was available. It would do this when the max_cost of all backend were exceeded. In practice, and with changes related to considering multiple backends for pre-operation switches it was realized that this was too restrictive and it would throw a ValueError under certain workloads.
This change allows the calculator to first calculate a backend considering max_cost but, if one is not found, then calculate one disregarding max_cost. A backend should always be returned in this case.
> FIX-#7684: When we exceed max_cost for all available Backends an error may occur
